(rule
 (deps spec.txt)
 (targets
  omd-tyxml-spec-001.md omd-tyxml-spec-001.html
  omd-tyxml-spec-002.md omd-tyxml-spec-002.html
  omd-tyxml-spec-003.md omd-tyxml-spec-003.html
  omd-tyxml-spec-004.md omd-tyxml-spec-004.html
  omd-tyxml-spec-005.md omd-tyxml-spec-005.html
  omd-tyxml-spec-006.md omd-tyxml-spec-006.html
  omd-tyxml-spec-007.md omd-tyxml-spec-007.html
  omd-tyxml-spec-008.md omd-tyxml-spec-008.html
  omd-tyxml-spec-009.md omd-tyxml-spec-009.html
  omd-tyxml-spec-010.md omd-tyxml-spec-010.html
  omd-tyxml-spec-011.md omd-tyxml-spec-011.html
  omd-tyxml-spec-012.md omd-tyxml-spec-012.html
  omd-tyxml-spec-013.md omd-tyxml-spec-013.html
  omd-tyxml-spec-014.md omd-tyxml-spec-014.html
  omd-tyxml-spec-015.md omd-tyxml-spec-015.html
  omd-tyxml-spec-016.md omd-tyxml-spec-016.html
  omd-tyxml-spec-017.md omd-tyxml-spec-017.html
  omd-tyxml-spec-018.md omd-tyxml-spec-018.html
  omd-tyxml-spec-019.md omd-tyxml-spec-019.html
  omd-tyxml-spec-020.md omd-tyxml-spec-020.html
  omd-tyxml-spec-021.md omd-tyxml-spec-021.html
  omd-tyxml-spec-022.md omd-tyxml-spec-022.html
  omd-tyxml-spec-023.md omd-tyxml-spec-023.html
  omd-tyxml-spec-024.md omd-tyxml-spec-024.html
  omd-tyxml-spec-025.md omd-tyxml-spec-025.html
  omd-tyxml-spec-026.md omd-tyxml-spec-026.html
  omd-tyxml-spec-027.md omd-tyxml-spec-027.html
  omd-tyxml-spec-028.md omd-tyxml-spec-028.html
  omd-tyxml-spec-029.md omd-tyxml-spec-029.html
  omd-tyxml-spec-030.md omd-tyxml-spec-030.html
  omd-tyxml-spec-031.md omd-tyxml-spec-031.html
  omd-tyxml-spec-032.md omd-tyxml-spec-032.html
  omd-tyxml-spec-033.md omd-tyxml-spec-033.html
  omd-tyxml-spec-034.md omd-tyxml-spec-034.html
  omd-tyxml-spec-035.md omd-tyxml-spec-035.html
  omd-tyxml-spec-036.md omd-tyxml-spec-036.html
  omd-tyxml-spec-037.md omd-tyxml-spec-037.html
  omd-tyxml-spec-038.md omd-tyxml-spec-038.html
  omd-tyxml-spec-039.md omd-tyxml-spec-039.html
  omd-tyxml-spec-040.md omd-tyxml-spec-040.html
  omd-tyxml-spec-041.md omd-tyxml-spec-041.html
  omd-tyxml-spec-042.md omd-tyxml-spec-042.html
  omd-tyxml-spec-043.md omd-tyxml-spec-043.html
  omd-tyxml-spec-044.md omd-tyxml-spec-044.html
  omd-tyxml-spec-045.md omd-tyxml-spec-045.html
  omd-tyxml-spec-046.md omd-tyxml-spec-046.html
  omd-tyxml-spec-047.md omd-tyxml-spec-047.html
  omd-tyxml-spec-048.md omd-tyxml-spec-048.html
  omd-tyxml-spec-049.md omd-tyxml-spec-049.html
  omd-tyxml-spec-050.md omd-tyxml-spec-050.html
  omd-tyxml-spec-051.md omd-tyxml-spec-051.html
  omd-tyxml-spec-052.md omd-tyxml-spec-052.html
  omd-tyxml-spec-053.md omd-tyxml-spec-053.html
  omd-tyxml-spec-054.md omd-tyxml-spec-054.html
  omd-tyxml-spec-055.md omd-tyxml-spec-055.html
  omd-tyxml-spec-056.md omd-tyxml-spec-056.html
  omd-tyxml-spec-057.md omd-tyxml-spec-057.html
  omd-tyxml-spec-058.md omd-tyxml-spec-058.html
  omd-tyxml-spec-059.md omd-tyxml-spec-059.html
  omd-tyxml-spec-060.md omd-tyxml-spec-060.html
  omd-tyxml-spec-061.md omd-tyxml-spec-061.html
  omd-tyxml-spec-062.md omd-tyxml-spec-062.html
  omd-tyxml-spec-063.md omd-tyxml-spec-063.html
  omd-tyxml-spec-064.md omd-tyxml-spec-064.html
  omd-tyxml-spec-065.md omd-tyxml-spec-065.html
  omd-tyxml-spec-066.md omd-tyxml-spec-066.html
  omd-tyxml-spec-067.md omd-tyxml-spec-067.html
  omd-tyxml-spec-068.md omd-tyxml-spec-068.html
  omd-tyxml-spec-069.md omd-tyxml-spec-069.html
  omd-tyxml-spec-070.md omd-tyxml-spec-070.html
  omd-tyxml-spec-071.md omd-tyxml-spec-071.html
  omd-tyxml-spec-072.md omd-tyxml-spec-072.html
  omd-tyxml-spec-073.md omd-tyxml-spec-073.html
  omd-tyxml-spec-074.md omd-tyxml-spec-074.html
  omd-tyxml-spec-075.md omd-tyxml-spec-075.html
  omd-tyxml-spec-076.md omd-tyxml-spec-076.html
  omd-tyxml-spec-077.md omd-tyxml-spec-077.html
  omd-tyxml-spec-078.md omd-tyxml-spec-078.html
  omd-tyxml-spec-079.md omd-tyxml-spec-079.html
  omd-tyxml-spec-080.md omd-tyxml-spec-080.html
  omd-tyxml-spec-081.md omd-tyxml-spec-081.html
  omd-tyxml-spec-082.md omd-tyxml-spec-082.html
  omd-tyxml-spec-083.md omd-tyxml-spec-083.html
  omd-tyxml-spec-084.md omd-tyxml-spec-084.html
  omd-tyxml-spec-085.md omd-tyxml-spec-085.html
  omd-tyxml-spec-086.md omd-tyxml-spec-086.html
  omd-tyxml-spec-087.md omd-tyxml-spec-087.html
  omd-tyxml-spec-088.md omd-tyxml-spec-088.html
  omd-tyxml-spec-089.md omd-tyxml-spec-089.html
  omd-tyxml-spec-090.md omd-tyxml-spec-090.html
  omd-tyxml-spec-091.md omd-tyxml-spec-091.html
  omd-tyxml-spec-092.md omd-tyxml-spec-092.html
  omd-tyxml-spec-093.md omd-tyxml-spec-093.html
  omd-tyxml-spec-094.md omd-tyxml-spec-094.html
  omd-tyxml-spec-095.md omd-tyxml-spec-095.html
  omd-tyxml-spec-096.md omd-tyxml-spec-096.html
  omd-tyxml-spec-097.md omd-tyxml-spec-097.html
  omd-tyxml-spec-098.md omd-tyxml-spec-098.html
  omd-tyxml-spec-099.md omd-tyxml-spec-099.html
  omd-tyxml-spec-100.md omd-tyxml-spec-100.html
  omd-tyxml-spec-101.md omd-tyxml-spec-101.html
  omd-tyxml-spec-102.md omd-tyxml-spec-102.html
  omd-tyxml-spec-103.md omd-tyxml-spec-103.html
  omd-tyxml-spec-104.md omd-tyxml-spec-104.html
  omd-tyxml-spec-105.md omd-tyxml-spec-105.html
  omd-tyxml-spec-106.md omd-tyxml-spec-106.html
  omd-tyxml-spec-107.md omd-tyxml-spec-107.html
  omd-tyxml-spec-108.md omd-tyxml-spec-108.html
  omd-tyxml-spec-109.md omd-tyxml-spec-109.html
  omd-tyxml-spec-110.md omd-tyxml-spec-110.html
  omd-tyxml-spec-111.md omd-tyxml-spec-111.html
  omd-tyxml-spec-112.md omd-tyxml-spec-112.html
  omd-tyxml-spec-113.md omd-tyxml-spec-113.html
  omd-tyxml-spec-114.md omd-tyxml-spec-114.html
  omd-tyxml-spec-115.md omd-tyxml-spec-115.html
  omd-tyxml-spec-116.md omd-tyxml-spec-116.html
  omd-tyxml-spec-117.md omd-tyxml-spec-117.html
  omd-tyxml-spec-118.md omd-tyxml-spec-118.html
  omd-tyxml-spec-119.md omd-tyxml-spec-119.html
  omd-tyxml-spec-120.md omd-tyxml-spec-120.html
  omd-tyxml-spec-121.md omd-tyxml-spec-121.html
  omd-tyxml-spec-122.md omd-tyxml-spec-122.html
  omd-tyxml-spec-123.md omd-tyxml-spec-123.html
  omd-tyxml-spec-124.md omd-tyxml-spec-124.html
  omd-tyxml-spec-125.md omd-tyxml-spec-125.html
  omd-tyxml-spec-126.md omd-tyxml-spec-126.html
  omd-tyxml-spec-127.md omd-tyxml-spec-127.html
  omd-tyxml-spec-128.md omd-tyxml-spec-128.html
  omd-tyxml-spec-129.md omd-tyxml-spec-129.html
  omd-tyxml-spec-130.md omd-tyxml-spec-130.html
  omd-tyxml-spec-131.md omd-tyxml-spec-131.html
  omd-tyxml-spec-132.md omd-tyxml-spec-132.html
  omd-tyxml-spec-133.md omd-tyxml-spec-133.html
  omd-tyxml-spec-134.md omd-tyxml-spec-134.html
  omd-tyxml-spec-135.md omd-tyxml-spec-135.html
  omd-tyxml-spec-136.md omd-tyxml-spec-136.html
  omd-tyxml-spec-137.md omd-tyxml-spec-137.html
  omd-tyxml-spec-138.md omd-tyxml-spec-138.html
  omd-tyxml-spec-139.md omd-tyxml-spec-139.html
  omd-tyxml-spec-140.md omd-tyxml-spec-140.html
  omd-tyxml-spec-141.md omd-tyxml-spec-141.html
  omd-tyxml-spec-142.md omd-tyxml-spec-142.html
  omd-tyxml-spec-143.md omd-tyxml-spec-143.html
  omd-tyxml-spec-144.md omd-tyxml-spec-144.html
  omd-tyxml-spec-145.md omd-tyxml-spec-145.html
  omd-tyxml-spec-146.md omd-tyxml-spec-146.html
  omd-tyxml-spec-147.md omd-tyxml-spec-147.html
  omd-tyxml-spec-148.md omd-tyxml-spec-148.html
  omd-tyxml-spec-149.md omd-tyxml-spec-149.html
  omd-tyxml-spec-150.md omd-tyxml-spec-150.html
  omd-tyxml-spec-151.md omd-tyxml-spec-151.html
  omd-tyxml-spec-152.md omd-tyxml-spec-152.html
  omd-tyxml-spec-153.md omd-tyxml-spec-153.html
  omd-tyxml-spec-154.md omd-tyxml-spec-154.html
  omd-tyxml-spec-155.md omd-tyxml-spec-155.html
  omd-tyxml-spec-156.md omd-tyxml-spec-156.html
  omd-tyxml-spec-157.md omd-tyxml-spec-157.html
  omd-tyxml-spec-158.md omd-tyxml-spec-158.html
  omd-tyxml-spec-159.md omd-tyxml-spec-159.html
  omd-tyxml-spec-160.md omd-tyxml-spec-160.html
  omd-tyxml-spec-161.md omd-tyxml-spec-161.html
  omd-tyxml-spec-162.md omd-tyxml-spec-162.html
  omd-tyxml-spec-163.md omd-tyxml-spec-163.html
  omd-tyxml-spec-164.md omd-tyxml-spec-164.html
  omd-tyxml-spec-165.md omd-tyxml-spec-165.html
  omd-tyxml-spec-166.md omd-tyxml-spec-166.html
  omd-tyxml-spec-167.md omd-tyxml-spec-167.html
  omd-tyxml-spec-168.md omd-tyxml-spec-168.html
  omd-tyxml-spec-169.md omd-tyxml-spec-169.html
  omd-tyxml-spec-170.md omd-tyxml-spec-170.html
  omd-tyxml-spec-171.md omd-tyxml-spec-171.html
  omd-tyxml-spec-172.md omd-tyxml-spec-172.html
  omd-tyxml-spec-173.md omd-tyxml-spec-173.html
  omd-tyxml-spec-174.md omd-tyxml-spec-174.html
  omd-tyxml-spec-175.md omd-tyxml-spec-175.html
  omd-tyxml-spec-176.md omd-tyxml-spec-176.html
  omd-tyxml-spec-177.md omd-tyxml-spec-177.html
  omd-tyxml-spec-178.md omd-tyxml-spec-178.html
  omd-tyxml-spec-179.md omd-tyxml-spec-179.html
  omd-tyxml-spec-180.md omd-tyxml-spec-180.html
  omd-tyxml-spec-181.md omd-tyxml-spec-181.html
  omd-tyxml-spec-182.md omd-tyxml-spec-182.html
  omd-tyxml-spec-183.md omd-tyxml-spec-183.html
  omd-tyxml-spec-184.md omd-tyxml-spec-184.html
  omd-tyxml-spec-185.md omd-tyxml-spec-185.html
  omd-tyxml-spec-186.md omd-tyxml-spec-186.html
  omd-tyxml-spec-187.md omd-tyxml-spec-187.html
  omd-tyxml-spec-188.md omd-tyxml-spec-188.html
  omd-tyxml-spec-189.md omd-tyxml-spec-189.html
  omd-tyxml-spec-190.md omd-tyxml-spec-190.html
  omd-tyxml-spec-191.md omd-tyxml-spec-191.html
  omd-tyxml-spec-192.md omd-tyxml-spec-192.html
  omd-tyxml-spec-193.md omd-tyxml-spec-193.html
  omd-tyxml-spec-194.md omd-tyxml-spec-194.html
  omd-tyxml-spec-195.md omd-tyxml-spec-195.html
  omd-tyxml-spec-196.md omd-tyxml-spec-196.html
  omd-tyxml-spec-197.md omd-tyxml-spec-197.html
  omd-tyxml-spec-198.md omd-tyxml-spec-198.html
  omd-tyxml-spec-199.md omd-tyxml-spec-199.html
  omd-tyxml-spec-200.md omd-tyxml-spec-200.html
  omd-tyxml-spec-201.md omd-tyxml-spec-201.html
  omd-tyxml-spec-202.md omd-tyxml-spec-202.html
  omd-tyxml-spec-203.md omd-tyxml-spec-203.html
  omd-tyxml-spec-204.md omd-tyxml-spec-204.html
  omd-tyxml-spec-205.md omd-tyxml-spec-205.html
  omd-tyxml-spec-206.md omd-tyxml-spec-206.html
  omd-tyxml-spec-207.md omd-tyxml-spec-207.html
  omd-tyxml-spec-208.md omd-tyxml-spec-208.html
  omd-tyxml-spec-209.md omd-tyxml-spec-209.html
  omd-tyxml-spec-210.md omd-tyxml-spec-210.html
  omd-tyxml-spec-211.md omd-tyxml-spec-211.html
  omd-tyxml-spec-212.md omd-tyxml-spec-212.html
  omd-tyxml-spec-213.md omd-tyxml-spec-213.html
  omd-tyxml-spec-214.md omd-tyxml-spec-214.html
  omd-tyxml-spec-215.md omd-tyxml-spec-215.html
  omd-tyxml-spec-216.md omd-tyxml-spec-216.html
  omd-tyxml-spec-217.md omd-tyxml-spec-217.html
  omd-tyxml-spec-218.md omd-tyxml-spec-218.html
  omd-tyxml-spec-219.md omd-tyxml-spec-219.html
  omd-tyxml-spec-220.md omd-tyxml-spec-220.html
  omd-tyxml-spec-221.md omd-tyxml-spec-221.html
  omd-tyxml-spec-222.md omd-tyxml-spec-222.html
  omd-tyxml-spec-223.md omd-tyxml-spec-223.html
  omd-tyxml-spec-224.md omd-tyxml-spec-224.html
  omd-tyxml-spec-225.md omd-tyxml-spec-225.html
  omd-tyxml-spec-226.md omd-tyxml-spec-226.html
  omd-tyxml-spec-227.md omd-tyxml-spec-227.html
  omd-tyxml-spec-228.md omd-tyxml-spec-228.html
  omd-tyxml-spec-229.md omd-tyxml-spec-229.html
  omd-tyxml-spec-230.md omd-tyxml-spec-230.html
  omd-tyxml-spec-231.md omd-tyxml-spec-231.html
  omd-tyxml-spec-232.md omd-tyxml-spec-232.html
  omd-tyxml-spec-233.md omd-tyxml-spec-233.html
  omd-tyxml-spec-234.md omd-tyxml-spec-234.html
  omd-tyxml-spec-235.md omd-tyxml-spec-235.html
  omd-tyxml-spec-236.md omd-tyxml-spec-236.html
  omd-tyxml-spec-237.md omd-tyxml-spec-237.html
  omd-tyxml-spec-238.md omd-tyxml-spec-238.html
  omd-tyxml-spec-239.md omd-tyxml-spec-239.html
  omd-tyxml-spec-240.md omd-tyxml-spec-240.html
  omd-tyxml-spec-241.md omd-tyxml-spec-241.html
  omd-tyxml-spec-242.md omd-tyxml-spec-242.html
  omd-tyxml-spec-243.md omd-tyxml-spec-243.html
  omd-tyxml-spec-244.md omd-tyxml-spec-244.html
  omd-tyxml-spec-245.md omd-tyxml-spec-245.html
  omd-tyxml-spec-246.md omd-tyxml-spec-246.html
  omd-tyxml-spec-247.md omd-tyxml-spec-247.html
  omd-tyxml-spec-248.md omd-tyxml-spec-248.html
  omd-tyxml-spec-249.md omd-tyxml-spec-249.html
  omd-tyxml-spec-250.md omd-tyxml-spec-250.html
  omd-tyxml-spec-251.md omd-tyxml-spec-251.html
  omd-tyxml-spec-252.md omd-tyxml-spec-252.html
  omd-tyxml-spec-253.md omd-tyxml-spec-253.html
  omd-tyxml-spec-254.md omd-tyxml-spec-254.html
  omd-tyxml-spec-255.md omd-tyxml-spec-255.html
  omd-tyxml-spec-256.md omd-tyxml-spec-256.html
  omd-tyxml-spec-257.md omd-tyxml-spec-257.html
  omd-tyxml-spec-258.md omd-tyxml-spec-258.html
  omd-tyxml-spec-259.md omd-tyxml-spec-259.html
  omd-tyxml-spec-260.md omd-tyxml-spec-260.html
  omd-tyxml-spec-261.md omd-tyxml-spec-261.html
  omd-tyxml-spec-262.md omd-tyxml-spec-262.html
  omd-tyxml-spec-263.md omd-tyxml-spec-263.html
  omd-tyxml-spec-264.md omd-tyxml-spec-264.html
  omd-tyxml-spec-265.md omd-tyxml-spec-265.html
  omd-tyxml-spec-266.md omd-tyxml-spec-266.html
  omd-tyxml-spec-267.md omd-tyxml-spec-267.html
  omd-tyxml-spec-268.md omd-tyxml-spec-268.html
  omd-tyxml-spec-269.md omd-tyxml-spec-269.html
  omd-tyxml-spec-270.md omd-tyxml-spec-270.html
  omd-tyxml-spec-271.md omd-tyxml-spec-271.html
  omd-tyxml-spec-272.md omd-tyxml-spec-272.html
  omd-tyxml-spec-273.md omd-tyxml-spec-273.html
  omd-tyxml-spec-274.md omd-tyxml-spec-274.html
  omd-tyxml-spec-275.md omd-tyxml-spec-275.html
  omd-tyxml-spec-276.md omd-tyxml-spec-276.html
  omd-tyxml-spec-277.md omd-tyxml-spec-277.html
  omd-tyxml-spec-278.md omd-tyxml-spec-278.html
  omd-tyxml-spec-279.md omd-tyxml-spec-279.html
  omd-tyxml-spec-280.md omd-tyxml-spec-280.html
  omd-tyxml-spec-281.md omd-tyxml-spec-281.html
  omd-tyxml-spec-282.md omd-tyxml-spec-282.html
  omd-tyxml-spec-283.md omd-tyxml-spec-283.html
  omd-tyxml-spec-284.md omd-tyxml-spec-284.html
  omd-tyxml-spec-285.md omd-tyxml-spec-285.html
  omd-tyxml-spec-286.md omd-tyxml-spec-286.html
  omd-tyxml-spec-287.md omd-tyxml-spec-287.html
  omd-tyxml-spec-288.md omd-tyxml-spec-288.html
  omd-tyxml-spec-289.md omd-tyxml-spec-289.html
  omd-tyxml-spec-290.md omd-tyxml-spec-290.html
  omd-tyxml-spec-291.md omd-tyxml-spec-291.html
  omd-tyxml-spec-292.md omd-tyxml-spec-292.html
  omd-tyxml-spec-293.md omd-tyxml-spec-293.html
  omd-tyxml-spec-294.md omd-tyxml-spec-294.html
  omd-tyxml-spec-295.md omd-tyxml-spec-295.html
  omd-tyxml-spec-296.md omd-tyxml-spec-296.html
  omd-tyxml-spec-297.md omd-tyxml-spec-297.html
  omd-tyxml-spec-298.md omd-tyxml-spec-298.html
  omd-tyxml-spec-299.md omd-tyxml-spec-299.html
  omd-tyxml-spec-300.md omd-tyxml-spec-300.html
  omd-tyxml-spec-301.md omd-tyxml-spec-301.html
  omd-tyxml-spec-302.md omd-tyxml-spec-302.html
  omd-tyxml-spec-303.md omd-tyxml-spec-303.html
  omd-tyxml-spec-304.md omd-tyxml-spec-304.html
  omd-tyxml-spec-305.md omd-tyxml-spec-305.html
  omd-tyxml-spec-306.md omd-tyxml-spec-306.html
  omd-tyxml-spec-307.md omd-tyxml-spec-307.html
  omd-tyxml-spec-308.md omd-tyxml-spec-308.html
  omd-tyxml-spec-309.md omd-tyxml-spec-309.html
  omd-tyxml-spec-310.md omd-tyxml-spec-310.html
  omd-tyxml-spec-311.md omd-tyxml-spec-311.html
  omd-tyxml-spec-312.md omd-tyxml-spec-312.html
  omd-tyxml-spec-313.md omd-tyxml-spec-313.html
  omd-tyxml-spec-314.md omd-tyxml-spec-314.html
  omd-tyxml-spec-315.md omd-tyxml-spec-315.html
  omd-tyxml-spec-316.md omd-tyxml-spec-316.html
  omd-tyxml-spec-317.md omd-tyxml-spec-317.html
  omd-tyxml-spec-318.md omd-tyxml-spec-318.html
  omd-tyxml-spec-319.md omd-tyxml-spec-319.html
  omd-tyxml-spec-320.md omd-tyxml-spec-320.html
  omd-tyxml-spec-321.md omd-tyxml-spec-321.html
  omd-tyxml-spec-322.md omd-tyxml-spec-322.html
  omd-tyxml-spec-323.md omd-tyxml-spec-323.html
  omd-tyxml-spec-324.md omd-tyxml-spec-324.html
  omd-tyxml-spec-325.md omd-tyxml-spec-325.html
  omd-tyxml-spec-326.md omd-tyxml-spec-326.html
  omd-tyxml-spec-327.md omd-tyxml-spec-327.html
  omd-tyxml-spec-328.md omd-tyxml-spec-328.html
  omd-tyxml-spec-329.md omd-tyxml-spec-329.html
  omd-tyxml-spec-330.md omd-tyxml-spec-330.html
  omd-tyxml-spec-331.md omd-tyxml-spec-331.html
  omd-tyxml-spec-332.md omd-tyxml-spec-332.html
  omd-tyxml-spec-333.md omd-tyxml-spec-333.html
  omd-tyxml-spec-334.md omd-tyxml-spec-334.html
  omd-tyxml-spec-335.md omd-tyxml-spec-335.html
  omd-tyxml-spec-336.md omd-tyxml-spec-336.html
  omd-tyxml-spec-337.md omd-tyxml-spec-337.html
  omd-tyxml-spec-338.md omd-tyxml-spec-338.html
  omd-tyxml-spec-339.md omd-tyxml-spec-339.html
  omd-tyxml-spec-340.md omd-tyxml-spec-340.html
  omd-tyxml-spec-341.md omd-tyxml-spec-341.html
  omd-tyxml-spec-342.md omd-tyxml-spec-342.html
  omd-tyxml-spec-343.md omd-tyxml-spec-343.html
  omd-tyxml-spec-344.md omd-tyxml-spec-344.html
  omd-tyxml-spec-345.md omd-tyxml-spec-345.html
  omd-tyxml-spec-346.md omd-tyxml-spec-346.html
  omd-tyxml-spec-347.md omd-tyxml-spec-347.html
  omd-tyxml-spec-348.md omd-tyxml-spec-348.html
  omd-tyxml-spec-349.md omd-tyxml-spec-349.html
  omd-tyxml-spec-350.md omd-tyxml-spec-350.html
  omd-tyxml-spec-351.md omd-tyxml-spec-351.html
  omd-tyxml-spec-352.md omd-tyxml-spec-352.html
  omd-tyxml-spec-353.md omd-tyxml-spec-353.html
  omd-tyxml-spec-354.md omd-tyxml-spec-354.html
  omd-tyxml-spec-355.md omd-tyxml-spec-355.html
  omd-tyxml-spec-356.md omd-tyxml-spec-356.html
  omd-tyxml-spec-357.md omd-tyxml-spec-357.html
  omd-tyxml-spec-358.md omd-tyxml-spec-358.html
  omd-tyxml-spec-359.md omd-tyxml-spec-359.html
  omd-tyxml-spec-360.md omd-tyxml-spec-360.html
  omd-tyxml-spec-361.md omd-tyxml-spec-361.html
  omd-tyxml-spec-362.md omd-tyxml-spec-362.html
  omd-tyxml-spec-363.md omd-tyxml-spec-363.html
  omd-tyxml-spec-364.md omd-tyxml-spec-364.html
  omd-tyxml-spec-365.md omd-tyxml-spec-365.html
  omd-tyxml-spec-366.md omd-tyxml-spec-366.html
  omd-tyxml-spec-367.md omd-tyxml-spec-367.html
  omd-tyxml-spec-368.md omd-tyxml-spec-368.html
  omd-tyxml-spec-369.md omd-tyxml-spec-369.html
  omd-tyxml-spec-370.md omd-tyxml-spec-370.html
  omd-tyxml-spec-371.md omd-tyxml-spec-371.html
  omd-tyxml-spec-372.md omd-tyxml-spec-372.html
  omd-tyxml-spec-373.md omd-tyxml-spec-373.html
  omd-tyxml-spec-374.md omd-tyxml-spec-374.html
  omd-tyxml-spec-375.md omd-tyxml-spec-375.html
  omd-tyxml-spec-376.md omd-tyxml-spec-376.html
  omd-tyxml-spec-377.md omd-tyxml-spec-377.html
  omd-tyxml-spec-378.md omd-tyxml-spec-378.html
  omd-tyxml-spec-379.md omd-tyxml-spec-379.html
  omd-tyxml-spec-380.md omd-tyxml-spec-380.html
  omd-tyxml-spec-381.md omd-tyxml-spec-381.html
  omd-tyxml-spec-382.md omd-tyxml-spec-382.html
  omd-tyxml-spec-383.md omd-tyxml-spec-383.html
  omd-tyxml-spec-384.md omd-tyxml-spec-384.html
  omd-tyxml-spec-385.md omd-tyxml-spec-385.html
  omd-tyxml-spec-386.md omd-tyxml-spec-386.html
  omd-tyxml-spec-387.md omd-tyxml-spec-387.html
  omd-tyxml-spec-388.md omd-tyxml-spec-388.html
  omd-tyxml-spec-389.md omd-tyxml-spec-389.html
  omd-tyxml-spec-390.md omd-tyxml-spec-390.html
  omd-tyxml-spec-391.md omd-tyxml-spec-391.html
  omd-tyxml-spec-392.md omd-tyxml-spec-392.html
  omd-tyxml-spec-393.md omd-tyxml-spec-393.html
  omd-tyxml-spec-394.md omd-tyxml-spec-394.html
  omd-tyxml-spec-395.md omd-tyxml-spec-395.html
  omd-tyxml-spec-396.md omd-tyxml-spec-396.html
  omd-tyxml-spec-397.md omd-tyxml-spec-397.html
  omd-tyxml-spec-398.md omd-tyxml-spec-398.html
  omd-tyxml-spec-399.md omd-tyxml-spec-399.html
  omd-tyxml-spec-400.md omd-tyxml-spec-400.html
  omd-tyxml-spec-401.md omd-tyxml-spec-401.html
  omd-tyxml-spec-402.md omd-tyxml-spec-402.html
  omd-tyxml-spec-403.md omd-tyxml-spec-403.html
  omd-tyxml-spec-404.md omd-tyxml-spec-404.html
  omd-tyxml-spec-405.md omd-tyxml-spec-405.html
  omd-tyxml-spec-406.md omd-tyxml-spec-406.html
  omd-tyxml-spec-407.md omd-tyxml-spec-407.html
  omd-tyxml-spec-408.md omd-tyxml-spec-408.html
  omd-tyxml-spec-409.md omd-tyxml-spec-409.html
  omd-tyxml-spec-410.md omd-tyxml-spec-410.html
  omd-tyxml-spec-411.md omd-tyxml-spec-411.html
  omd-tyxml-spec-412.md omd-tyxml-spec-412.html
  omd-tyxml-spec-413.md omd-tyxml-spec-413.html
  omd-tyxml-spec-414.md omd-tyxml-spec-414.html
  omd-tyxml-spec-415.md omd-tyxml-spec-415.html
  omd-tyxml-spec-416.md omd-tyxml-spec-416.html
  omd-tyxml-spec-417.md omd-tyxml-spec-417.html
  omd-tyxml-spec-418.md omd-tyxml-spec-418.html
  omd-tyxml-spec-419.md omd-tyxml-spec-419.html
  omd-tyxml-spec-420.md omd-tyxml-spec-420.html
  omd-tyxml-spec-421.md omd-tyxml-spec-421.html
  omd-tyxml-spec-422.md omd-tyxml-spec-422.html
  omd-tyxml-spec-423.md omd-tyxml-spec-423.html
  omd-tyxml-spec-424.md omd-tyxml-spec-424.html
  omd-tyxml-spec-425.md omd-tyxml-spec-425.html
  omd-tyxml-spec-426.md omd-tyxml-spec-426.html
  omd-tyxml-spec-427.md omd-tyxml-spec-427.html
  omd-tyxml-spec-428.md omd-tyxml-spec-428.html
  omd-tyxml-spec-429.md omd-tyxml-spec-429.html
  omd-tyxml-spec-430.md omd-tyxml-spec-430.html
  omd-tyxml-spec-431.md omd-tyxml-spec-431.html
  omd-tyxml-spec-432.md omd-tyxml-spec-432.html
  omd-tyxml-spec-433.md omd-tyxml-spec-433.html
  omd-tyxml-spec-434.md omd-tyxml-spec-434.html
  omd-tyxml-spec-435.md omd-tyxml-spec-435.html
  omd-tyxml-spec-436.md omd-tyxml-spec-436.html
  omd-tyxml-spec-437.md omd-tyxml-spec-437.html
  omd-tyxml-spec-438.md omd-tyxml-spec-438.html
  omd-tyxml-spec-439.md omd-tyxml-spec-439.html
  omd-tyxml-spec-440.md omd-tyxml-spec-440.html
  omd-tyxml-spec-441.md omd-tyxml-spec-441.html
  omd-tyxml-spec-442.md omd-tyxml-spec-442.html
  omd-tyxml-spec-443.md omd-tyxml-spec-443.html
  omd-tyxml-spec-444.md omd-tyxml-spec-444.html
  omd-tyxml-spec-445.md omd-tyxml-spec-445.html
  omd-tyxml-spec-446.md omd-tyxml-spec-446.html
  omd-tyxml-spec-447.md omd-tyxml-spec-447.html
  omd-tyxml-spec-448.md omd-tyxml-spec-448.html
  omd-tyxml-spec-449.md omd-tyxml-spec-449.html
  omd-tyxml-spec-450.md omd-tyxml-spec-450.html
  omd-tyxml-spec-451.md omd-tyxml-spec-451.html
  omd-tyxml-spec-452.md omd-tyxml-spec-452.html
  omd-tyxml-spec-453.md omd-tyxml-spec-453.html
  omd-tyxml-spec-454.md omd-tyxml-spec-454.html
  omd-tyxml-spec-455.md omd-tyxml-spec-455.html
  omd-tyxml-spec-456.md omd-tyxml-spec-456.html
  omd-tyxml-spec-457.md omd-tyxml-spec-457.html
  omd-tyxml-spec-458.md omd-tyxml-spec-458.html
  omd-tyxml-spec-459.md omd-tyxml-spec-459.html
  omd-tyxml-spec-460.md omd-tyxml-spec-460.html
  omd-tyxml-spec-461.md omd-tyxml-spec-461.html
  omd-tyxml-spec-462.md omd-tyxml-spec-462.html
  omd-tyxml-spec-463.md omd-tyxml-spec-463.html
  omd-tyxml-spec-464.md omd-tyxml-spec-464.html
  omd-tyxml-spec-465.md omd-tyxml-spec-465.html
  omd-tyxml-spec-466.md omd-tyxml-spec-466.html
  omd-tyxml-spec-467.md omd-tyxml-spec-467.html
  omd-tyxml-spec-468.md omd-tyxml-spec-468.html
  omd-tyxml-spec-469.md omd-tyxml-spec-469.html
  omd-tyxml-spec-470.md omd-tyxml-spec-470.html
  omd-tyxml-spec-471.md omd-tyxml-spec-471.html
  omd-tyxml-spec-472.md omd-tyxml-spec-472.html
  omd-tyxml-spec-473.md omd-tyxml-spec-473.html
  omd-tyxml-spec-474.md omd-tyxml-spec-474.html
  omd-tyxml-spec-475.md omd-tyxml-spec-475.html
  omd-tyxml-spec-476.md omd-tyxml-spec-476.html
  omd-tyxml-spec-477.md omd-tyxml-spec-477.html
  omd-tyxml-spec-478.md omd-tyxml-spec-478.html
  omd-tyxml-spec-479.md omd-tyxml-spec-479.html
  omd-tyxml-spec-480.md omd-tyxml-spec-480.html
  omd-tyxml-spec-481.md omd-tyxml-spec-481.html
  omd-tyxml-spec-482.md omd-tyxml-spec-482.html
  omd-tyxml-spec-483.md omd-tyxml-spec-483.html
  omd-tyxml-spec-484.md omd-tyxml-spec-484.html
  omd-tyxml-spec-485.md omd-tyxml-spec-485.html
  omd-tyxml-spec-486.md omd-tyxml-spec-486.html
  omd-tyxml-spec-487.md omd-tyxml-spec-487.html
  omd-tyxml-spec-488.md omd-tyxml-spec-488.html
  omd-tyxml-spec-489.md omd-tyxml-spec-489.html
  omd-tyxml-spec-490.md omd-tyxml-spec-490.html
  omd-tyxml-spec-491.md omd-tyxml-spec-491.html
  omd-tyxml-spec-492.md omd-tyxml-spec-492.html
  omd-tyxml-spec-493.md omd-tyxml-spec-493.html
  omd-tyxml-spec-494.md omd-tyxml-spec-494.html
  omd-tyxml-spec-495.md omd-tyxml-spec-495.html
  omd-tyxml-spec-496.md omd-tyxml-spec-496.html
  omd-tyxml-spec-497.md omd-tyxml-spec-497.html
  omd-tyxml-spec-498.md omd-tyxml-spec-498.html
  omd-tyxml-spec-499.md omd-tyxml-spec-499.html
  omd-tyxml-spec-500.md omd-tyxml-spec-500.html
  omd-tyxml-spec-501.md omd-tyxml-spec-501.html
  omd-tyxml-spec-502.md omd-tyxml-spec-502.html
  omd-tyxml-spec-503.md omd-tyxml-spec-503.html
  omd-tyxml-spec-504.md omd-tyxml-spec-504.html
  omd-tyxml-spec-505.md omd-tyxml-spec-505.html
  omd-tyxml-spec-506.md omd-tyxml-spec-506.html
  omd-tyxml-spec-507.md omd-tyxml-spec-507.html
  omd-tyxml-spec-508.md omd-tyxml-spec-508.html
  omd-tyxml-spec-509.md omd-tyxml-spec-509.html
  omd-tyxml-spec-510.md omd-tyxml-spec-510.html
  omd-tyxml-spec-511.md omd-tyxml-spec-511.html
  omd-tyxml-spec-512.md omd-tyxml-spec-512.html
  omd-tyxml-spec-513.md omd-tyxml-spec-513.html
  omd-tyxml-spec-514.md omd-tyxml-spec-514.html
  omd-tyxml-spec-515.md omd-tyxml-spec-515.html
  omd-tyxml-spec-516.md omd-tyxml-spec-516.html
  omd-tyxml-spec-517.md omd-tyxml-spec-517.html
  omd-tyxml-spec-518.md omd-tyxml-spec-518.html
  omd-tyxml-spec-519.md omd-tyxml-spec-519.html
  omd-tyxml-spec-520.md omd-tyxml-spec-520.html
  omd-tyxml-spec-521.md omd-tyxml-spec-521.html
  omd-tyxml-spec-522.md omd-tyxml-spec-522.html
  omd-tyxml-spec-523.md omd-tyxml-spec-523.html
  omd-tyxml-spec-524.md omd-tyxml-spec-524.html
  omd-tyxml-spec-525.md omd-tyxml-spec-525.html
  omd-tyxml-spec-526.md omd-tyxml-spec-526.html
  omd-tyxml-spec-527.md omd-tyxml-spec-527.html
  omd-tyxml-spec-528.md omd-tyxml-spec-528.html
  omd-tyxml-spec-529.md omd-tyxml-spec-529.html
  omd-tyxml-spec-530.md omd-tyxml-spec-530.html
  omd-tyxml-spec-531.md omd-tyxml-spec-531.html
  omd-tyxml-spec-532.md omd-tyxml-spec-532.html
  omd-tyxml-spec-533.md omd-tyxml-spec-533.html
  omd-tyxml-spec-534.md omd-tyxml-spec-534.html
  omd-tyxml-spec-535.md omd-tyxml-spec-535.html
  omd-tyxml-spec-536.md omd-tyxml-spec-536.html
  omd-tyxml-spec-537.md omd-tyxml-spec-537.html
  omd-tyxml-spec-538.md omd-tyxml-spec-538.html
  omd-tyxml-spec-539.md omd-tyxml-spec-539.html
  omd-tyxml-spec-540.md omd-tyxml-spec-540.html
  omd-tyxml-spec-541.md omd-tyxml-spec-541.html
  omd-tyxml-spec-542.md omd-tyxml-spec-542.html
  omd-tyxml-spec-543.md omd-tyxml-spec-543.html
  omd-tyxml-spec-544.md omd-tyxml-spec-544.html
  omd-tyxml-spec-545.md omd-tyxml-spec-545.html
  omd-tyxml-spec-546.md omd-tyxml-spec-546.html
  omd-tyxml-spec-547.md omd-tyxml-spec-547.html
  omd-tyxml-spec-548.md omd-tyxml-spec-548.html
  omd-tyxml-spec-549.md omd-tyxml-spec-549.html
  omd-tyxml-spec-550.md omd-tyxml-spec-550.html
  omd-tyxml-spec-551.md omd-tyxml-spec-551.html
  omd-tyxml-spec-552.md omd-tyxml-spec-552.html
  omd-tyxml-spec-553.md omd-tyxml-spec-553.html
  omd-tyxml-spec-554.md omd-tyxml-spec-554.html
  omd-tyxml-spec-555.md omd-tyxml-spec-555.html
  omd-tyxml-spec-556.md omd-tyxml-spec-556.html
  omd-tyxml-spec-557.md omd-tyxml-spec-557.html
  omd-tyxml-spec-558.md omd-tyxml-spec-558.html
  omd-tyxml-spec-559.md omd-tyxml-spec-559.html
  omd-tyxml-spec-560.md omd-tyxml-spec-560.html
  omd-tyxml-spec-561.md omd-tyxml-spec-561.html
  omd-tyxml-spec-562.md omd-tyxml-spec-562.html
  omd-tyxml-spec-563.md omd-tyxml-spec-563.html
  omd-tyxml-spec-564.md omd-tyxml-spec-564.html
  omd-tyxml-spec-565.md omd-tyxml-spec-565.html
  omd-tyxml-spec-566.md omd-tyxml-spec-566.html
  omd-tyxml-spec-567.md omd-tyxml-spec-567.html
  omd-tyxml-spec-568.md omd-tyxml-spec-568.html
  omd-tyxml-spec-569.md omd-tyxml-spec-569.html
  omd-tyxml-spec-570.md omd-tyxml-spec-570.html
  omd-tyxml-spec-571.md omd-tyxml-spec-571.html
  omd-tyxml-spec-572.md omd-tyxml-spec-572.html
  omd-tyxml-spec-573.md omd-tyxml-spec-573.html
  omd-tyxml-spec-574.md omd-tyxml-spec-574.html
  omd-tyxml-spec-575.md omd-tyxml-spec-575.html
  omd-tyxml-spec-576.md omd-tyxml-spec-576.html
  omd-tyxml-spec-577.md omd-tyxml-spec-577.html
  omd-tyxml-spec-578.md omd-tyxml-spec-578.html
  omd-tyxml-spec-579.md omd-tyxml-spec-579.html
  omd-tyxml-spec-580.md omd-tyxml-spec-580.html
  omd-tyxml-spec-581.md omd-tyxml-spec-581.html
  omd-tyxml-spec-582.md omd-tyxml-spec-582.html
  omd-tyxml-spec-583.md omd-tyxml-spec-583.html
  omd-tyxml-spec-584.md omd-tyxml-spec-584.html
  omd-tyxml-spec-585.md omd-tyxml-spec-585.html
  omd-tyxml-spec-586.md omd-tyxml-spec-586.html
  omd-tyxml-spec-587.md omd-tyxml-spec-587.html
  omd-tyxml-spec-588.md omd-tyxml-spec-588.html
  omd-tyxml-spec-589.md omd-tyxml-spec-589.html
  omd-tyxml-spec-590.md omd-tyxml-spec-590.html
  omd-tyxml-spec-591.md omd-tyxml-spec-591.html
  omd-tyxml-spec-592.md omd-tyxml-spec-592.html
  omd-tyxml-spec-593.md omd-tyxml-spec-593.html
  omd-tyxml-spec-594.md omd-tyxml-spec-594.html
  omd-tyxml-spec-595.md omd-tyxml-spec-595.html
  omd-tyxml-spec-596.md omd-tyxml-spec-596.html
  omd-tyxml-spec-597.md omd-tyxml-spec-597.html
  omd-tyxml-spec-598.md omd-tyxml-spec-598.html
  omd-tyxml-spec-599.md omd-tyxml-spec-599.html
  omd-tyxml-spec-600.md omd-tyxml-spec-600.html
  omd-tyxml-spec-601.md omd-tyxml-spec-601.html
  omd-tyxml-spec-602.md omd-tyxml-spec-602.html
  omd-tyxml-spec-603.md omd-tyxml-spec-603.html
  omd-tyxml-spec-604.md omd-tyxml-spec-604.html
  omd-tyxml-spec-605.md omd-tyxml-spec-605.html
  omd-tyxml-spec-606.md omd-tyxml-spec-606.html
  omd-tyxml-spec-607.md omd-tyxml-spec-607.html
  omd-tyxml-spec-608.md omd-tyxml-spec-608.html
  omd-tyxml-spec-609.md omd-tyxml-spec-609.html
  omd-tyxml-spec-610.md omd-tyxml-spec-610.html
  omd-tyxml-spec-611.md omd-tyxml-spec-611.html
  omd-tyxml-spec-612.md omd-tyxml-spec-612.html
  omd-tyxml-spec-613.md omd-tyxml-spec-613.html
  omd-tyxml-spec-614.md omd-tyxml-spec-614.html
  omd-tyxml-spec-615.md omd-tyxml-spec-615.html
  omd-tyxml-spec-616.md omd-tyxml-spec-616.html
  omd-tyxml-spec-617.md omd-tyxml-spec-617.html
  omd-tyxml-spec-618.md omd-tyxml-spec-618.html
  omd-tyxml-spec-619.md omd-tyxml-spec-619.html
  omd-tyxml-spec-620.md omd-tyxml-spec-620.html
  omd-tyxml-spec-621.md omd-tyxml-spec-621.html
  omd-tyxml-spec-622.md omd-tyxml-spec-622.html
  omd-tyxml-spec-623.md omd-tyxml-spec-623.html
  omd-tyxml-spec-624.md omd-tyxml-spec-624.html
  omd-tyxml-spec-625.md omd-tyxml-spec-625.html
  omd-tyxml-spec-626.md omd-tyxml-spec-626.html
  omd-tyxml-spec-627.md omd-tyxml-spec-627.html
  omd-tyxml-spec-628.md omd-tyxml-spec-628.html
  omd-tyxml-spec-629.md omd-tyxml-spec-629.html
  omd-tyxml-spec-630.md omd-tyxml-spec-630.html
  omd-tyxml-spec-631.md omd-tyxml-spec-631.html
  omd-tyxml-spec-632.md omd-tyxml-spec-632.html
  omd-tyxml-spec-633.md omd-tyxml-spec-633.html
  omd-tyxml-spec-634.md omd-tyxml-spec-634.html
  omd-tyxml-spec-635.md omd-tyxml-spec-635.html
  omd-tyxml-spec-636.md omd-tyxml-spec-636.html
  omd-tyxml-spec-637.md omd-tyxml-spec-637.html
  omd-tyxml-spec-638.md omd-tyxml-spec-638.html
  omd-tyxml-spec-639.md omd-tyxml-spec-639.html
  omd-tyxml-spec-640.md omd-tyxml-spec-640.html
  omd-tyxml-spec-641.md omd-tyxml-spec-641.html
  omd-tyxml-spec-642.md omd-tyxml-spec-642.html
  omd-tyxml-spec-643.md omd-tyxml-spec-643.html
  omd-tyxml-spec-644.md omd-tyxml-spec-644.html
  omd-tyxml-spec-645.md omd-tyxml-spec-645.html
  omd-tyxml-spec-646.md omd-tyxml-spec-646.html
  omd-tyxml-spec-647.md omd-tyxml-spec-647.html
  omd-tyxml-spec-648.md omd-tyxml-spec-648.html
  omd-tyxml-spec-649.md omd-tyxml-spec-649.html)
 (action (run ./extract_tests.exe -generate-test-files-omd-tyxml-spec)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-001.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-001.md}))))
(rule
 (alias omd-tyxml-spec-001)
 (action (diff omd-tyxml-spec-001.html omd-tyxml-spec-001.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-002.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-002.md}))))
(rule
 (alias omd-tyxml-spec-002)
 (action (diff omd-tyxml-spec-002.html omd-tyxml-spec-002.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-003.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-003.md}))))
(rule
 (alias omd-tyxml-spec-003)
 (action (diff omd-tyxml-spec-003.html omd-tyxml-spec-003.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-004.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-004.md}))))
(rule
 (alias omd-tyxml-spec-004)
 (action (diff omd-tyxml-spec-004.html omd-tyxml-spec-004.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-005.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-005.md}))))
(rule
 (alias omd-tyxml-spec-005)
 (action (diff omd-tyxml-spec-005.html omd-tyxml-spec-005.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-006.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-006.md}))))
(rule
 (alias omd-tyxml-spec-006)
 (action (diff omd-tyxml-spec-006.html omd-tyxml-spec-006.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-007.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-007.md}))))
(rule
 (alias omd-tyxml-spec-007)
 (action (diff omd-tyxml-spec-007.html omd-tyxml-spec-007.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-008.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-008.md}))))
(rule
 (alias omd-tyxml-spec-008)
 (action (diff omd-tyxml-spec-008.html omd-tyxml-spec-008.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-009.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-009.md}))))
(rule
 (alias omd-tyxml-spec-009)
 (action (diff omd-tyxml-spec-009.html omd-tyxml-spec-009.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-010.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-010.md}))))
(rule
 (alias omd-tyxml-spec-010)
 (action (diff omd-tyxml-spec-010.html omd-tyxml-spec-010.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-011.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-011.md}))))
(rule
 (alias omd-tyxml-spec-011)
 (action (diff omd-tyxml-spec-011.html omd-tyxml-spec-011.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-012.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-012.md}))))
(rule
 (alias omd-tyxml-spec-012)
 (action (diff omd-tyxml-spec-012.html omd-tyxml-spec-012.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-013.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-013.md}))))
(rule
 (alias omd-tyxml-spec-013)
 (action (diff omd-tyxml-spec-013.html omd-tyxml-spec-013.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-014.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-014.md}))))
(rule
 (alias omd-tyxml-spec-014)
 (action (diff omd-tyxml-spec-014.html omd-tyxml-spec-014.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-015.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-015.md}))))
(rule
 (alias omd-tyxml-spec-015)
 (action (diff omd-tyxml-spec-015.html omd-tyxml-spec-015.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-016.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-016.md}))))
(rule
 (alias omd-tyxml-spec-016)
 (action (diff omd-tyxml-spec-016.html omd-tyxml-spec-016.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-017.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-017.md}))))
(rule
 (alias omd-tyxml-spec-017)
 (action (diff omd-tyxml-spec-017.html omd-tyxml-spec-017.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-018.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-018.md}))))
(rule
 (alias omd-tyxml-spec-018)
 (action (diff omd-tyxml-spec-018.html omd-tyxml-spec-018.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-019.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-019.md}))))
(rule
 (alias omd-tyxml-spec-019)
 (action (diff omd-tyxml-spec-019.html omd-tyxml-spec-019.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-020.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-020.md}))))
(rule
 (alias omd-tyxml-spec-020)
 (action (diff omd-tyxml-spec-020.html omd-tyxml-spec-020.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-021.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-021.md}))))
(rule
 (alias omd-tyxml-spec-021)
 (action (diff omd-tyxml-spec-021.html omd-tyxml-spec-021.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-022.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-022.md}))))
(rule
 (alias omd-tyxml-spec-022)
 (action (diff omd-tyxml-spec-022.html omd-tyxml-spec-022.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-023.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-023.md}))))
(rule
 (alias omd-tyxml-spec-023)
 (action (diff omd-tyxml-spec-023.html omd-tyxml-spec-023.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-024.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-024.md}))))
(rule
 (alias omd-tyxml-spec-024)
 (action (diff omd-tyxml-spec-024.html omd-tyxml-spec-024.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-025.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-025.md}))))
(rule
 (alias omd-tyxml-spec-025)
 (action (diff omd-tyxml-spec-025.html omd-tyxml-spec-025.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-026.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-026.md}))))
(rule
 (alias omd-tyxml-spec-026)
 (action (diff omd-tyxml-spec-026.html omd-tyxml-spec-026.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-027.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-027.md}))))
(rule
 (alias omd-tyxml-spec-027)
 (action (diff omd-tyxml-spec-027.html omd-tyxml-spec-027.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-028.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-028.md}))))
(rule
 (alias omd-tyxml-spec-028)
 (action (diff omd-tyxml-spec-028.html omd-tyxml-spec-028.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-029.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-029.md}))))
(rule
 (alias omd-tyxml-spec-029)
 (action (diff omd-tyxml-spec-029.html omd-tyxml-spec-029.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-030.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-030.md}))))
(rule
 (alias omd-tyxml-spec-030)
 (action (diff omd-tyxml-spec-030.html omd-tyxml-spec-030.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-031.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-031.md}))))
(rule
 (alias omd-tyxml-spec-031)
 (action (diff omd-tyxml-spec-031.html omd-tyxml-spec-031.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-032.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-032.md}))))
(rule
 (alias omd-tyxml-spec-032)
 (action (diff omd-tyxml-spec-032.html omd-tyxml-spec-032.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-033.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-033.md}))))
(rule
 (alias omd-tyxml-spec-033)
 (action (diff omd-tyxml-spec-033.html omd-tyxml-spec-033.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-034.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-034.md}))))
(rule
 (alias omd-tyxml-spec-034)
 (action (diff omd-tyxml-spec-034.html omd-tyxml-spec-034.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-035.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-035.md}))))
(rule
 (alias omd-tyxml-spec-035)
 (action (diff omd-tyxml-spec-035.html omd-tyxml-spec-035.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-036.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-036.md}))))
(rule
 (alias omd-tyxml-spec-036)
 (action (diff omd-tyxml-spec-036.html omd-tyxml-spec-036.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-037.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-037.md}))))
(rule
 (alias omd-tyxml-spec-037)
 (action (diff omd-tyxml-spec-037.html omd-tyxml-spec-037.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-038.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-038.md}))))
(rule
 (alias omd-tyxml-spec-038)
 (action (diff omd-tyxml-spec-038.html omd-tyxml-spec-038.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-039.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-039.md}))))
(rule
 (alias omd-tyxml-spec-039)
 (action (diff omd-tyxml-spec-039.html omd-tyxml-spec-039.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-040.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-040.md}))))
(rule
 (alias omd-tyxml-spec-040)
 (action (diff omd-tyxml-spec-040.html omd-tyxml-spec-040.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-041.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-041.md}))))
(rule
 (alias omd-tyxml-spec-041)
 (action (diff omd-tyxml-spec-041.html omd-tyxml-spec-041.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-042.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-042.md}))))
(rule
 (alias omd-tyxml-spec-042)
 (action (diff omd-tyxml-spec-042.html omd-tyxml-spec-042.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-043.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-043.md}))))
(rule
 (alias omd-tyxml-spec-043)
 (action (diff omd-tyxml-spec-043.html omd-tyxml-spec-043.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-044.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-044.md}))))
(rule
 (alias omd-tyxml-spec-044)
 (action (diff omd-tyxml-spec-044.html omd-tyxml-spec-044.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-045.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-045.md}))))
(rule
 (alias omd-tyxml-spec-045)
 (action (diff omd-tyxml-spec-045.html omd-tyxml-spec-045.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-046.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-046.md}))))
(rule
 (alias omd-tyxml-spec-046)
 (action (diff omd-tyxml-spec-046.html omd-tyxml-spec-046.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-047.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-047.md}))))
(rule
 (alias omd-tyxml-spec-047)
 (action (diff omd-tyxml-spec-047.html omd-tyxml-spec-047.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-048.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-048.md}))))
(rule
 (alias omd-tyxml-spec-048)
 (action (diff omd-tyxml-spec-048.html omd-tyxml-spec-048.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-049.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-049.md}))))
(rule
 (alias omd-tyxml-spec-049)
 (action (diff omd-tyxml-spec-049.html omd-tyxml-spec-049.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-050.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-050.md}))))
(rule
 (alias omd-tyxml-spec-050)
 (action (diff omd-tyxml-spec-050.html omd-tyxml-spec-050.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-051.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-051.md}))))
(rule
 (alias omd-tyxml-spec-051)
 (action (diff omd-tyxml-spec-051.html omd-tyxml-spec-051.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-052.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-052.md}))))
(rule
 (alias omd-tyxml-spec-052)
 (action (diff omd-tyxml-spec-052.html omd-tyxml-spec-052.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-053.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-053.md}))))
(rule
 (alias omd-tyxml-spec-053)
 (action (diff omd-tyxml-spec-053.html omd-tyxml-spec-053.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-054.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-054.md}))))
(rule
 (alias omd-tyxml-spec-054)
 (action (diff omd-tyxml-spec-054.html omd-tyxml-spec-054.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-055.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-055.md}))))
(rule
 (alias omd-tyxml-spec-055)
 (action (diff omd-tyxml-spec-055.html omd-tyxml-spec-055.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-056.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-056.md}))))
(rule
 (alias omd-tyxml-spec-056)
 (action (diff omd-tyxml-spec-056.html omd-tyxml-spec-056.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-057.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-057.md}))))
(rule
 (alias omd-tyxml-spec-057)
 (action (diff omd-tyxml-spec-057.html omd-tyxml-spec-057.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-058.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-058.md}))))
(rule
 (alias omd-tyxml-spec-058)
 (action (diff omd-tyxml-spec-058.html omd-tyxml-spec-058.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-059.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-059.md}))))
(rule
 (alias omd-tyxml-spec-059)
 (action (diff omd-tyxml-spec-059.html omd-tyxml-spec-059.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-060.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-060.md}))))
(rule
 (alias omd-tyxml-spec-060)
 (action (diff omd-tyxml-spec-060.html omd-tyxml-spec-060.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-061.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-061.md}))))
(rule
 (alias omd-tyxml-spec-061)
 (action (diff omd-tyxml-spec-061.html omd-tyxml-spec-061.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-062.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-062.md}))))
(rule
 (alias omd-tyxml-spec-062)
 (action (diff omd-tyxml-spec-062.html omd-tyxml-spec-062.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-063.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-063.md}))))
(rule
 (alias omd-tyxml-spec-063)
 (action (diff omd-tyxml-spec-063.html omd-tyxml-spec-063.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-064.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-064.md}))))
(rule
 (alias omd-tyxml-spec-064)
 (action (diff omd-tyxml-spec-064.html omd-tyxml-spec-064.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-065.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-065.md}))))
(rule
 (alias omd-tyxml-spec-065)
 (action (diff omd-tyxml-spec-065.html omd-tyxml-spec-065.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-066.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-066.md}))))
(rule
 (alias omd-tyxml-spec-066)
 (action (diff omd-tyxml-spec-066.html omd-tyxml-spec-066.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-067.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-067.md}))))
(rule
 (alias omd-tyxml-spec-067)
 (action (diff omd-tyxml-spec-067.html omd-tyxml-spec-067.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-068.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-068.md}))))
(rule
 (alias omd-tyxml-spec-068)
 (action (diff omd-tyxml-spec-068.html omd-tyxml-spec-068.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-069.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-069.md}))))
(rule
 (alias omd-tyxml-spec-069)
 (action (diff omd-tyxml-spec-069.html omd-tyxml-spec-069.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-070.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-070.md}))))
(rule
 (alias omd-tyxml-spec-070)
 (action (diff omd-tyxml-spec-070.html omd-tyxml-spec-070.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-071.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-071.md}))))
(rule
 (alias omd-tyxml-spec-071)
 (action (diff omd-tyxml-spec-071.html omd-tyxml-spec-071.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-072.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-072.md}))))
(rule
 (alias omd-tyxml-spec-072)
 (action (diff omd-tyxml-spec-072.html omd-tyxml-spec-072.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-073.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-073.md}))))
(rule
 (alias omd-tyxml-spec-073)
 (action (diff omd-tyxml-spec-073.html omd-tyxml-spec-073.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-074.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-074.md}))))
(rule
 (alias omd-tyxml-spec-074)
 (action (diff omd-tyxml-spec-074.html omd-tyxml-spec-074.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-075.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-075.md}))))
(rule
 (alias omd-tyxml-spec-075)
 (action (diff omd-tyxml-spec-075.html omd-tyxml-spec-075.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-076.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-076.md}))))
(rule
 (alias omd-tyxml-spec-076)
 (action (diff omd-tyxml-spec-076.html omd-tyxml-spec-076.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-077.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-077.md}))))
(rule
 (alias omd-tyxml-spec-077)
 (action (diff omd-tyxml-spec-077.html omd-tyxml-spec-077.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-078.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-078.md}))))
(rule
 (alias omd-tyxml-spec-078)
 (action (diff omd-tyxml-spec-078.html omd-tyxml-spec-078.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-079.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-079.md}))))
(rule
 (alias omd-tyxml-spec-079)
 (action (diff omd-tyxml-spec-079.html omd-tyxml-spec-079.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-080.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-080.md}))))
(rule
 (alias omd-tyxml-spec-080)
 (action (diff omd-tyxml-spec-080.html omd-tyxml-spec-080.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-081.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-081.md}))))
(rule
 (alias omd-tyxml-spec-081)
 (action (diff omd-tyxml-spec-081.html omd-tyxml-spec-081.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-082.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-082.md}))))
(rule
 (alias omd-tyxml-spec-082)
 (action (diff omd-tyxml-spec-082.html omd-tyxml-spec-082.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-083.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-083.md}))))
(rule
 (alias omd-tyxml-spec-083)
 (action (diff omd-tyxml-spec-083.html omd-tyxml-spec-083.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-084.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-084.md}))))
(rule
 (alias omd-tyxml-spec-084)
 (action (diff omd-tyxml-spec-084.html omd-tyxml-spec-084.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-085.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-085.md}))))
(rule
 (alias omd-tyxml-spec-085)
 (action (diff omd-tyxml-spec-085.html omd-tyxml-spec-085.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-086.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-086.md}))))
(rule
 (alias omd-tyxml-spec-086)
 (action (diff omd-tyxml-spec-086.html omd-tyxml-spec-086.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-087.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-087.md}))))
(rule
 (alias omd-tyxml-spec-087)
 (action (diff omd-tyxml-spec-087.html omd-tyxml-spec-087.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-088.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-088.md}))))
(rule
 (alias omd-tyxml-spec-088)
 (action (diff omd-tyxml-spec-088.html omd-tyxml-spec-088.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-089.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-089.md}))))
(rule
 (alias omd-tyxml-spec-089)
 (action (diff omd-tyxml-spec-089.html omd-tyxml-spec-089.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-090.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-090.md}))))
(rule
 (alias omd-tyxml-spec-090)
 (action (diff omd-tyxml-spec-090.html omd-tyxml-spec-090.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-091.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-091.md}))))
(rule
 (alias omd-tyxml-spec-091)
 (action (diff omd-tyxml-spec-091.html omd-tyxml-spec-091.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-092.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-092.md}))))
(rule
 (alias omd-tyxml-spec-092)
 (action (diff omd-tyxml-spec-092.html omd-tyxml-spec-092.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-093.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-093.md}))))
(rule
 (alias omd-tyxml-spec-093)
 (action (diff omd-tyxml-spec-093.html omd-tyxml-spec-093.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-094.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-094.md}))))
(rule
 (alias omd-tyxml-spec-094)
 (action (diff omd-tyxml-spec-094.html omd-tyxml-spec-094.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-095.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-095.md}))))
(rule
 (alias omd-tyxml-spec-095)
 (action (diff omd-tyxml-spec-095.html omd-tyxml-spec-095.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-096.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-096.md}))))
(rule
 (alias omd-tyxml-spec-096)
 (action (diff omd-tyxml-spec-096.html omd-tyxml-spec-096.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-097.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-097.md}))))
(rule
 (alias omd-tyxml-spec-097)
 (action (diff omd-tyxml-spec-097.html omd-tyxml-spec-097.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-098.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-098.md}))))
(rule
 (alias omd-tyxml-spec-098)
 (action (diff omd-tyxml-spec-098.html omd-tyxml-spec-098.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-099.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-099.md}))))
(rule
 (alias omd-tyxml-spec-099)
 (action (diff omd-tyxml-spec-099.html omd-tyxml-spec-099.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-100.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-100.md}))))
(rule
 (alias omd-tyxml-spec-100)
 (action (diff omd-tyxml-spec-100.html omd-tyxml-spec-100.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-101.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-101.md}))))
(rule
 (alias omd-tyxml-spec-101)
 (action (diff omd-tyxml-spec-101.html omd-tyxml-spec-101.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-102.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-102.md}))))
(rule
 (alias omd-tyxml-spec-102)
 (action (diff omd-tyxml-spec-102.html omd-tyxml-spec-102.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-103.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-103.md}))))
(rule
 (alias omd-tyxml-spec-103)
 (action (diff omd-tyxml-spec-103.html omd-tyxml-spec-103.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-104.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-104.md}))))
(rule
 (alias omd-tyxml-spec-104)
 (action (diff omd-tyxml-spec-104.html omd-tyxml-spec-104.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-105.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-105.md}))))
(rule
 (alias omd-tyxml-spec-105)
 (action (diff omd-tyxml-spec-105.html omd-tyxml-spec-105.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-106.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-106.md}))))
(rule
 (alias omd-tyxml-spec-106)
 (action (diff omd-tyxml-spec-106.html omd-tyxml-spec-106.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-107.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-107.md}))))
(rule
 (alias omd-tyxml-spec-107)
 (action (diff omd-tyxml-spec-107.html omd-tyxml-spec-107.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-108.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-108.md}))))
(rule
 (alias omd-tyxml-spec-108)
 (action (diff omd-tyxml-spec-108.html omd-tyxml-spec-108.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-109.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-109.md}))))
(rule
 (alias omd-tyxml-spec-109)
 (action (diff omd-tyxml-spec-109.html omd-tyxml-spec-109.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-110.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-110.md}))))
(rule
 (alias omd-tyxml-spec-110)
 (action (diff omd-tyxml-spec-110.html omd-tyxml-spec-110.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-111.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-111.md}))))
(rule
 (alias omd-tyxml-spec-111)
 (action (diff omd-tyxml-spec-111.html omd-tyxml-spec-111.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-112.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-112.md}))))
(rule
 (alias omd-tyxml-spec-112)
 (action (diff omd-tyxml-spec-112.html omd-tyxml-spec-112.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-113.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-113.md}))))
(rule
 (alias omd-tyxml-spec-113)
 (action (diff omd-tyxml-spec-113.html omd-tyxml-spec-113.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-114.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-114.md}))))
(rule
 (alias omd-tyxml-spec-114)
 (action (diff omd-tyxml-spec-114.html omd-tyxml-spec-114.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-115.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-115.md}))))
(rule
 (alias omd-tyxml-spec-115)
 (action (diff omd-tyxml-spec-115.html omd-tyxml-spec-115.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-116.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-116.md}))))
(rule
 (alias omd-tyxml-spec-116)
 (action (diff omd-tyxml-spec-116.html omd-tyxml-spec-116.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-117.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-117.md}))))
(rule
 (alias omd-tyxml-spec-117)
 (action (diff omd-tyxml-spec-117.html omd-tyxml-spec-117.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-118.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-118.md}))))
(rule
 (alias omd-tyxml-spec-118)
 (action (diff omd-tyxml-spec-118.html omd-tyxml-spec-118.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-119.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-119.md}))))
(rule
 (alias omd-tyxml-spec-119)
 (action (diff omd-tyxml-spec-119.html omd-tyxml-spec-119.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-120.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-120.md}))))
(rule
 (alias omd-tyxml-spec-120)
 (action (diff omd-tyxml-spec-120.html omd-tyxml-spec-120.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-121.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-121.md}))))
(rule
 (alias omd-tyxml-spec-121)
 (action (diff omd-tyxml-spec-121.html omd-tyxml-spec-121.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-122.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-122.md}))))
(rule
 (alias omd-tyxml-spec-122)
 (action (diff omd-tyxml-spec-122.html omd-tyxml-spec-122.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-123.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-123.md}))))
(rule
 (alias omd-tyxml-spec-123)
 (action (diff omd-tyxml-spec-123.html omd-tyxml-spec-123.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-124.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-124.md}))))
(rule
 (alias omd-tyxml-spec-124)
 (action (diff omd-tyxml-spec-124.html omd-tyxml-spec-124.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-125.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-125.md}))))
(rule
 (alias omd-tyxml-spec-125)
 (action (diff omd-tyxml-spec-125.html omd-tyxml-spec-125.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-126.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-126.md}))))
(rule
 (alias omd-tyxml-spec-126)
 (action (diff omd-tyxml-spec-126.html omd-tyxml-spec-126.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-127.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-127.md}))))
(rule
 (alias omd-tyxml-spec-127)
 (action (diff omd-tyxml-spec-127.html omd-tyxml-spec-127.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-128.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-128.md}))))
(rule
 (alias omd-tyxml-spec-128)
 (action (diff omd-tyxml-spec-128.html omd-tyxml-spec-128.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-129.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-129.md}))))
(rule
 (alias omd-tyxml-spec-129)
 (action (diff omd-tyxml-spec-129.html omd-tyxml-spec-129.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-130.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-130.md}))))
(rule
 (alias omd-tyxml-spec-130)
 (action (diff omd-tyxml-spec-130.html omd-tyxml-spec-130.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-131.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-131.md}))))
(rule
 (alias omd-tyxml-spec-131)
 (action (diff omd-tyxml-spec-131.html omd-tyxml-spec-131.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-132.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-132.md}))))
(rule
 (alias omd-tyxml-spec-132)
 (action (diff omd-tyxml-spec-132.html omd-tyxml-spec-132.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-133.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-133.md}))))
(rule
 (alias omd-tyxml-spec-133)
 (action (diff omd-tyxml-spec-133.html omd-tyxml-spec-133.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-134.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-134.md}))))
(rule
 (alias omd-tyxml-spec-134)
 (action (diff omd-tyxml-spec-134.html omd-tyxml-spec-134.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-135.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-135.md}))))
(rule
 (alias omd-tyxml-spec-135)
 (action (diff omd-tyxml-spec-135.html omd-tyxml-spec-135.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-136.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-136.md}))))
(rule
 (alias omd-tyxml-spec-136)
 (action (diff omd-tyxml-spec-136.html omd-tyxml-spec-136.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-137.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-137.md}))))
(rule
 (alias omd-tyxml-spec-137)
 (action (diff omd-tyxml-spec-137.html omd-tyxml-spec-137.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-138.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-138.md}))))
(rule
 (alias omd-tyxml-spec-138)
 (action (diff omd-tyxml-spec-138.html omd-tyxml-spec-138.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-139.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-139.md}))))
(rule
 (alias omd-tyxml-spec-139)
 (action (diff omd-tyxml-spec-139.html omd-tyxml-spec-139.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-140.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-140.md}))))
(rule
 (alias omd-tyxml-spec-140)
 (action (diff omd-tyxml-spec-140.html omd-tyxml-spec-140.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-141.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-141.md}))))
(rule
 (alias omd-tyxml-spec-141)
 (action (diff omd-tyxml-spec-141.html omd-tyxml-spec-141.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-142.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-142.md}))))
(rule
 (alias omd-tyxml-spec-142)
 (action (diff omd-tyxml-spec-142.html omd-tyxml-spec-142.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-143.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-143.md}))))
(rule
 (alias omd-tyxml-spec-143)
 (action (diff omd-tyxml-spec-143.html omd-tyxml-spec-143.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-144.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-144.md}))))
(rule
 (alias omd-tyxml-spec-144)
 (action (diff omd-tyxml-spec-144.html omd-tyxml-spec-144.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-145.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-145.md}))))
(rule
 (alias omd-tyxml-spec-145)
 (action (diff omd-tyxml-spec-145.html omd-tyxml-spec-145.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-146.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-146.md}))))
(rule
 (alias omd-tyxml-spec-146)
 (action (diff omd-tyxml-spec-146.html omd-tyxml-spec-146.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-147.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-147.md}))))
(rule
 (alias omd-tyxml-spec-147)
 (action (diff omd-tyxml-spec-147.html omd-tyxml-spec-147.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-148.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-148.md}))))
(rule
 (alias omd-tyxml-spec-148)
 (action (diff omd-tyxml-spec-148.html omd-tyxml-spec-148.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-149.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-149.md}))))
(rule
 (alias omd-tyxml-spec-149)
 (action (diff omd-tyxml-spec-149.html omd-tyxml-spec-149.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-150.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-150.md}))))
(rule
 (alias omd-tyxml-spec-150)
 (action (diff omd-tyxml-spec-150.html omd-tyxml-spec-150.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-151.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-151.md}))))
(rule
 (alias omd-tyxml-spec-151)
 (action (diff omd-tyxml-spec-151.html omd-tyxml-spec-151.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-152.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-152.md}))))
(rule
 (alias omd-tyxml-spec-152)
 (action (diff omd-tyxml-spec-152.html omd-tyxml-spec-152.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-153.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-153.md}))))
(rule
 (alias omd-tyxml-spec-153)
 (action (diff omd-tyxml-spec-153.html omd-tyxml-spec-153.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-154.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-154.md}))))
(rule
 (alias omd-tyxml-spec-154)
 (action (diff omd-tyxml-spec-154.html omd-tyxml-spec-154.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-155.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-155.md}))))
(rule
 (alias omd-tyxml-spec-155)
 (action (diff omd-tyxml-spec-155.html omd-tyxml-spec-155.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-156.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-156.md}))))
(rule
 (alias omd-tyxml-spec-156)
 (action (diff omd-tyxml-spec-156.html omd-tyxml-spec-156.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-157.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-157.md}))))
(rule
 (alias omd-tyxml-spec-157)
 (action (diff omd-tyxml-spec-157.html omd-tyxml-spec-157.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-158.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-158.md}))))
(rule
 (alias omd-tyxml-spec-158)
 (action (diff omd-tyxml-spec-158.html omd-tyxml-spec-158.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-159.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-159.md}))))
(rule
 (alias omd-tyxml-spec-159)
 (action (diff omd-tyxml-spec-159.html omd-tyxml-spec-159.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-160.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-160.md}))))
(rule
 (alias omd-tyxml-spec-160)
 (action (diff omd-tyxml-spec-160.html omd-tyxml-spec-160.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-161.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-161.md}))))
(rule
 (alias omd-tyxml-spec-161)
 (action (diff omd-tyxml-spec-161.html omd-tyxml-spec-161.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-162.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-162.md}))))
(rule
 (alias omd-tyxml-spec-162)
 (action (diff omd-tyxml-spec-162.html omd-tyxml-spec-162.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-163.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-163.md}))))
(rule
 (alias omd-tyxml-spec-163)
 (action (diff omd-tyxml-spec-163.html omd-tyxml-spec-163.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-164.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-164.md}))))
(rule
 (alias omd-tyxml-spec-164)
 (action (diff omd-tyxml-spec-164.html omd-tyxml-spec-164.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-165.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-165.md}))))
(rule
 (alias omd-tyxml-spec-165)
 (action (diff omd-tyxml-spec-165.html omd-tyxml-spec-165.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-166.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-166.md}))))
(rule
 (alias omd-tyxml-spec-166)
 (action (diff omd-tyxml-spec-166.html omd-tyxml-spec-166.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-167.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-167.md}))))
(rule
 (alias omd-tyxml-spec-167)
 (action (diff omd-tyxml-spec-167.html omd-tyxml-spec-167.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-168.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-168.md}))))
(rule
 (alias omd-tyxml-spec-168)
 (action (diff omd-tyxml-spec-168.html omd-tyxml-spec-168.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-169.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-169.md}))))
(rule
 (alias omd-tyxml-spec-169)
 (action (diff omd-tyxml-spec-169.html omd-tyxml-spec-169.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-170.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-170.md}))))
(rule
 (alias omd-tyxml-spec-170)
 (action (diff omd-tyxml-spec-170.html omd-tyxml-spec-170.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-171.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-171.md}))))
(rule
 (alias omd-tyxml-spec-171)
 (action (diff omd-tyxml-spec-171.html omd-tyxml-spec-171.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-172.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-172.md}))))
(rule
 (alias omd-tyxml-spec-172)
 (action (diff omd-tyxml-spec-172.html omd-tyxml-spec-172.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-173.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-173.md}))))
(rule
 (alias omd-tyxml-spec-173)
 (action (diff omd-tyxml-spec-173.html omd-tyxml-spec-173.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-174.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-174.md}))))
(rule
 (alias omd-tyxml-spec-174)
 (action (diff omd-tyxml-spec-174.html omd-tyxml-spec-174.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-175.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-175.md}))))
(rule
 (alias omd-tyxml-spec-175)
 (action (diff omd-tyxml-spec-175.html omd-tyxml-spec-175.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-176.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-176.md}))))
(rule
 (alias omd-tyxml-spec-176)
 (action (diff omd-tyxml-spec-176.html omd-tyxml-spec-176.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-177.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-177.md}))))
(rule
 (alias omd-tyxml-spec-177)
 (action (diff omd-tyxml-spec-177.html omd-tyxml-spec-177.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-178.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-178.md}))))
(rule
 (alias omd-tyxml-spec-178)
 (action (diff omd-tyxml-spec-178.html omd-tyxml-spec-178.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-179.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-179.md}))))
(rule
 (alias omd-tyxml-spec-179)
 (action (diff omd-tyxml-spec-179.html omd-tyxml-spec-179.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-180.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-180.md}))))
(rule
 (alias omd-tyxml-spec-180)
 (action (diff omd-tyxml-spec-180.html omd-tyxml-spec-180.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-181.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-181.md}))))
(rule
 (alias omd-tyxml-spec-181)
 (action (diff omd-tyxml-spec-181.html omd-tyxml-spec-181.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-182.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-182.md}))))
(rule
 (alias omd-tyxml-spec-182)
 (action (diff omd-tyxml-spec-182.html omd-tyxml-spec-182.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-183.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-183.md}))))
(rule
 (alias omd-tyxml-spec-183)
 (action (diff omd-tyxml-spec-183.html omd-tyxml-spec-183.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-184.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-184.md}))))
(rule
 (alias omd-tyxml-spec-184)
 (action (diff omd-tyxml-spec-184.html omd-tyxml-spec-184.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-185.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-185.md}))))
(rule
 (alias omd-tyxml-spec-185)
 (action (diff omd-tyxml-spec-185.html omd-tyxml-spec-185.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-186.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-186.md}))))
(rule
 (alias omd-tyxml-spec-186)
 (action (diff omd-tyxml-spec-186.html omd-tyxml-spec-186.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-187.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-187.md}))))
(rule
 (alias omd-tyxml-spec-187)
 (action (diff omd-tyxml-spec-187.html omd-tyxml-spec-187.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-188.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-188.md}))))
(rule
 (alias omd-tyxml-spec-188)
 (action (diff omd-tyxml-spec-188.html omd-tyxml-spec-188.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-189.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-189.md}))))
(rule
 (alias omd-tyxml-spec-189)
 (action (diff omd-tyxml-spec-189.html omd-tyxml-spec-189.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-190.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-190.md}))))
(rule
 (alias omd-tyxml-spec-190)
 (action (diff omd-tyxml-spec-190.html omd-tyxml-spec-190.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-191.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-191.md}))))
(rule
 (alias omd-tyxml-spec-191)
 (action (diff omd-tyxml-spec-191.html omd-tyxml-spec-191.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-192.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-192.md}))))
(rule
 (alias omd-tyxml-spec-192)
 (action (diff omd-tyxml-spec-192.html omd-tyxml-spec-192.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-193.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-193.md}))))
(rule
 (alias omd-tyxml-spec-193)
 (action (diff omd-tyxml-spec-193.html omd-tyxml-spec-193.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-194.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-194.md}))))
(rule
 (alias omd-tyxml-spec-194)
 (action (diff omd-tyxml-spec-194.html omd-tyxml-spec-194.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-195.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-195.md}))))
(rule
 (alias omd-tyxml-spec-195)
 (action (diff omd-tyxml-spec-195.html omd-tyxml-spec-195.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-196.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-196.md}))))
(rule
 (alias omd-tyxml-spec-196)
 (action (diff omd-tyxml-spec-196.html omd-tyxml-spec-196.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-197.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-197.md}))))
(rule
 (alias omd-tyxml-spec-197)
 (action (diff omd-tyxml-spec-197.html omd-tyxml-spec-197.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-198.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-198.md}))))
(rule
 (alias omd-tyxml-spec-198)
 (action (diff omd-tyxml-spec-198.html omd-tyxml-spec-198.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-199.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-199.md}))))
(rule
 (alias omd-tyxml-spec-199)
 (action (diff omd-tyxml-spec-199.html omd-tyxml-spec-199.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-200.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-200.md}))))
(rule
 (alias omd-tyxml-spec-200)
 (action (diff omd-tyxml-spec-200.html omd-tyxml-spec-200.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-201.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-201.md}))))
(rule
 (alias omd-tyxml-spec-201)
 (action (diff omd-tyxml-spec-201.html omd-tyxml-spec-201.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-202.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-202.md}))))
(rule
 (alias omd-tyxml-spec-202)
 (action (diff omd-tyxml-spec-202.html omd-tyxml-spec-202.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-203.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-203.md}))))
(rule
 (alias omd-tyxml-spec-203)
 (action (diff omd-tyxml-spec-203.html omd-tyxml-spec-203.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-204.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-204.md}))))
(rule
 (alias omd-tyxml-spec-204)
 (action (diff omd-tyxml-spec-204.html omd-tyxml-spec-204.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-205.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-205.md}))))
(rule
 (alias omd-tyxml-spec-205)
 (action (diff omd-tyxml-spec-205.html omd-tyxml-spec-205.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-206.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-206.md}))))
(rule
 (alias omd-tyxml-spec-206)
 (action (diff omd-tyxml-spec-206.html omd-tyxml-spec-206.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-207.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-207.md}))))
(rule
 (alias omd-tyxml-spec-207)
 (action (diff omd-tyxml-spec-207.html omd-tyxml-spec-207.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-208.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-208.md}))))
(rule
 (alias omd-tyxml-spec-208)
 (action (diff omd-tyxml-spec-208.html omd-tyxml-spec-208.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-209.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-209.md}))))
(rule
 (alias omd-tyxml-spec-209)
 (action (diff omd-tyxml-spec-209.html omd-tyxml-spec-209.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-210.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-210.md}))))
(rule
 (alias omd-tyxml-spec-210)
 (action (diff omd-tyxml-spec-210.html omd-tyxml-spec-210.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-211.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-211.md}))))
(rule
 (alias omd-tyxml-spec-211)
 (action (diff omd-tyxml-spec-211.html omd-tyxml-spec-211.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-212.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-212.md}))))
(rule
 (alias omd-tyxml-spec-212)
 (action (diff omd-tyxml-spec-212.html omd-tyxml-spec-212.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-213.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-213.md}))))
(rule
 (alias omd-tyxml-spec-213)
 (action (diff omd-tyxml-spec-213.html omd-tyxml-spec-213.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-214.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-214.md}))))
(rule
 (alias omd-tyxml-spec-214)
 (action (diff omd-tyxml-spec-214.html omd-tyxml-spec-214.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-215.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-215.md}))))
(rule
 (alias omd-tyxml-spec-215)
 (action (diff omd-tyxml-spec-215.html omd-tyxml-spec-215.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-216.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-216.md}))))
(rule
 (alias omd-tyxml-spec-216)
 (action (diff omd-tyxml-spec-216.html omd-tyxml-spec-216.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-217.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-217.md}))))
(rule
 (alias omd-tyxml-spec-217)
 (action (diff omd-tyxml-spec-217.html omd-tyxml-spec-217.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-218.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-218.md}))))
(rule
 (alias omd-tyxml-spec-218)
 (action (diff omd-tyxml-spec-218.html omd-tyxml-spec-218.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-219.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-219.md}))))
(rule
 (alias omd-tyxml-spec-219)
 (action (diff omd-tyxml-spec-219.html omd-tyxml-spec-219.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-220.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-220.md}))))
(rule
 (alias omd-tyxml-spec-220)
 (action (diff omd-tyxml-spec-220.html omd-tyxml-spec-220.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-221.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-221.md}))))
(rule
 (alias omd-tyxml-spec-221)
 (action (diff omd-tyxml-spec-221.html omd-tyxml-spec-221.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-222.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-222.md}))))
(rule
 (alias omd-tyxml-spec-222)
 (action (diff omd-tyxml-spec-222.html omd-tyxml-spec-222.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-223.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-223.md}))))
(rule
 (alias omd-tyxml-spec-223)
 (action (diff omd-tyxml-spec-223.html omd-tyxml-spec-223.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-224.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-224.md}))))
(rule
 (alias omd-tyxml-spec-224)
 (action (diff omd-tyxml-spec-224.html omd-tyxml-spec-224.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-225.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-225.md}))))
(rule
 (alias omd-tyxml-spec-225)
 (action (diff omd-tyxml-spec-225.html omd-tyxml-spec-225.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-226.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-226.md}))))
(rule
 (alias omd-tyxml-spec-226)
 (action (diff omd-tyxml-spec-226.html omd-tyxml-spec-226.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-227.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-227.md}))))
(rule
 (alias omd-tyxml-spec-227)
 (action (diff omd-tyxml-spec-227.html omd-tyxml-spec-227.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-228.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-228.md}))))
(rule
 (alias omd-tyxml-spec-228)
 (action (diff omd-tyxml-spec-228.html omd-tyxml-spec-228.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-229.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-229.md}))))
(rule
 (alias omd-tyxml-spec-229)
 (action (diff omd-tyxml-spec-229.html omd-tyxml-spec-229.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-230.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-230.md}))))
(rule
 (alias omd-tyxml-spec-230)
 (action (diff omd-tyxml-spec-230.html omd-tyxml-spec-230.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-231.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-231.md}))))
(rule
 (alias omd-tyxml-spec-231)
 (action (diff omd-tyxml-spec-231.html omd-tyxml-spec-231.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-232.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-232.md}))))
(rule
 (alias omd-tyxml-spec-232)
 (action (diff omd-tyxml-spec-232.html omd-tyxml-spec-232.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-233.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-233.md}))))
(rule
 (alias omd-tyxml-spec-233)
 (action (diff omd-tyxml-spec-233.html omd-tyxml-spec-233.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-234.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-234.md}))))
(rule
 (alias omd-tyxml-spec-234)
 (action (diff omd-tyxml-spec-234.html omd-tyxml-spec-234.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-235.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-235.md}))))
(rule
 (alias omd-tyxml-spec-235)
 (action (diff omd-tyxml-spec-235.html omd-tyxml-spec-235.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-236.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-236.md}))))
(rule
 (alias omd-tyxml-spec-236)
 (action (diff omd-tyxml-spec-236.html omd-tyxml-spec-236.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-237.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-237.md}))))
(rule
 (alias omd-tyxml-spec-237)
 (action (diff omd-tyxml-spec-237.html omd-tyxml-spec-237.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-238.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-238.md}))))
(rule
 (alias omd-tyxml-spec-238)
 (action (diff omd-tyxml-spec-238.html omd-tyxml-spec-238.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-239.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-239.md}))))
(rule
 (alias omd-tyxml-spec-239)
 (action (diff omd-tyxml-spec-239.html omd-tyxml-spec-239.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-240.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-240.md}))))
(rule
 (alias omd-tyxml-spec-240)
 (action (diff omd-tyxml-spec-240.html omd-tyxml-spec-240.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-241.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-241.md}))))
(rule
 (alias omd-tyxml-spec-241)
 (action (diff omd-tyxml-spec-241.html omd-tyxml-spec-241.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-242.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-242.md}))))
(rule
 (alias omd-tyxml-spec-242)
 (action (diff omd-tyxml-spec-242.html omd-tyxml-spec-242.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-243.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-243.md}))))
(rule
 (alias omd-tyxml-spec-243)
 (action (diff omd-tyxml-spec-243.html omd-tyxml-spec-243.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-244.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-244.md}))))
(rule
 (alias omd-tyxml-spec-244)
 (action (diff omd-tyxml-spec-244.html omd-tyxml-spec-244.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-245.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-245.md}))))
(rule
 (alias omd-tyxml-spec-245)
 (action (diff omd-tyxml-spec-245.html omd-tyxml-spec-245.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-246.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-246.md}))))
(rule
 (alias omd-tyxml-spec-246)
 (action (diff omd-tyxml-spec-246.html omd-tyxml-spec-246.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-247.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-247.md}))))
(rule
 (alias omd-tyxml-spec-247)
 (action (diff omd-tyxml-spec-247.html omd-tyxml-spec-247.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-248.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-248.md}))))
(rule
 (alias omd-tyxml-spec-248)
 (action (diff omd-tyxml-spec-248.html omd-tyxml-spec-248.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-249.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-249.md}))))
(rule
 (alias omd-tyxml-spec-249)
 (action (diff omd-tyxml-spec-249.html omd-tyxml-spec-249.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-250.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-250.md}))))
(rule
 (alias omd-tyxml-spec-250)
 (action (diff omd-tyxml-spec-250.html omd-tyxml-spec-250.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-251.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-251.md}))))
(rule
 (alias omd-tyxml-spec-251)
 (action (diff omd-tyxml-spec-251.html omd-tyxml-spec-251.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-252.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-252.md}))))
(rule
 (alias omd-tyxml-spec-252)
 (action (diff omd-tyxml-spec-252.html omd-tyxml-spec-252.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-253.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-253.md}))))
(rule
 (alias omd-tyxml-spec-253)
 (action (diff omd-tyxml-spec-253.html omd-tyxml-spec-253.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-254.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-254.md}))))
(rule
 (alias omd-tyxml-spec-254)
 (action (diff omd-tyxml-spec-254.html omd-tyxml-spec-254.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-255.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-255.md}))))
(rule
 (alias omd-tyxml-spec-255)
 (action (diff omd-tyxml-spec-255.html omd-tyxml-spec-255.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-256.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-256.md}))))
(rule
 (alias omd-tyxml-spec-256)
 (action (diff omd-tyxml-spec-256.html omd-tyxml-spec-256.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-257.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-257.md}))))
(rule
 (alias omd-tyxml-spec-257)
 (action (diff omd-tyxml-spec-257.html omd-tyxml-spec-257.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-258.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-258.md}))))
(rule
 (alias omd-tyxml-spec-258)
 (action (diff omd-tyxml-spec-258.html omd-tyxml-spec-258.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-259.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-259.md}))))
(rule
 (alias omd-tyxml-spec-259)
 (action (diff omd-tyxml-spec-259.html omd-tyxml-spec-259.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-260.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-260.md}))))
(rule
 (alias omd-tyxml-spec-260)
 (action (diff omd-tyxml-spec-260.html omd-tyxml-spec-260.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-261.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-261.md}))))
(rule
 (alias omd-tyxml-spec-261)
 (action (diff omd-tyxml-spec-261.html omd-tyxml-spec-261.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-262.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-262.md}))))
(rule
 (alias omd-tyxml-spec-262)
 (action (diff omd-tyxml-spec-262.html omd-tyxml-spec-262.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-263.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-263.md}))))
(rule
 (alias omd-tyxml-spec-263)
 (action (diff omd-tyxml-spec-263.html omd-tyxml-spec-263.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-264.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-264.md}))))
(rule
 (alias omd-tyxml-spec-264)
 (action (diff omd-tyxml-spec-264.html omd-tyxml-spec-264.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-265.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-265.md}))))
(rule
 (alias omd-tyxml-spec-265)
 (action (diff omd-tyxml-spec-265.html omd-tyxml-spec-265.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-266.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-266.md}))))
(rule
 (alias omd-tyxml-spec-266)
 (action (diff omd-tyxml-spec-266.html omd-tyxml-spec-266.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-267.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-267.md}))))
(rule
 (alias omd-tyxml-spec-267)
 (action (diff omd-tyxml-spec-267.html omd-tyxml-spec-267.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-268.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-268.md}))))
(rule
 (alias omd-tyxml-spec-268)
 (action (diff omd-tyxml-spec-268.html omd-tyxml-spec-268.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-269.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-269.md}))))
(rule
 (alias omd-tyxml-spec-269)
 (action (diff omd-tyxml-spec-269.html omd-tyxml-spec-269.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-270.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-270.md}))))
(rule
 (alias omd-tyxml-spec-270)
 (action (diff omd-tyxml-spec-270.html omd-tyxml-spec-270.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-271.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-271.md}))))
(rule
 (alias omd-tyxml-spec-271)
 (action (diff omd-tyxml-spec-271.html omd-tyxml-spec-271.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-272.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-272.md}))))
(rule
 (alias omd-tyxml-spec-272)
 (action (diff omd-tyxml-spec-272.html omd-tyxml-spec-272.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-273.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-273.md}))))
(rule
 (alias omd-tyxml-spec-273)
 (action (diff omd-tyxml-spec-273.html omd-tyxml-spec-273.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-274.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-274.md}))))
(rule
 (alias omd-tyxml-spec-274)
 (action (diff omd-tyxml-spec-274.html omd-tyxml-spec-274.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-275.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-275.md}))))
(rule
 (alias omd-tyxml-spec-275)
 (action (diff omd-tyxml-spec-275.html omd-tyxml-spec-275.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-276.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-276.md}))))
(rule
 (alias omd-tyxml-spec-276)
 (action (diff omd-tyxml-spec-276.html omd-tyxml-spec-276.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-277.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-277.md}))))
(rule
 (alias omd-tyxml-spec-277)
 (action (diff omd-tyxml-spec-277.html omd-tyxml-spec-277.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-278.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-278.md}))))
(rule
 (alias omd-tyxml-spec-278)
 (action (diff omd-tyxml-spec-278.html omd-tyxml-spec-278.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-279.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-279.md}))))
(rule
 (alias omd-tyxml-spec-279)
 (action (diff omd-tyxml-spec-279.html omd-tyxml-spec-279.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-280.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-280.md}))))
(rule
 (alias omd-tyxml-spec-280)
 (action (diff omd-tyxml-spec-280.html omd-tyxml-spec-280.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-281.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-281.md}))))
(rule
 (alias omd-tyxml-spec-281)
 (action (diff omd-tyxml-spec-281.html omd-tyxml-spec-281.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-282.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-282.md}))))
(rule
 (alias omd-tyxml-spec-282)
 (action (diff omd-tyxml-spec-282.html omd-tyxml-spec-282.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-283.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-283.md}))))
(rule
 (alias omd-tyxml-spec-283)
 (action (diff omd-tyxml-spec-283.html omd-tyxml-spec-283.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-284.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-284.md}))))
(rule
 (alias omd-tyxml-spec-284)
 (action (diff omd-tyxml-spec-284.html omd-tyxml-spec-284.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-285.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-285.md}))))
(rule
 (alias omd-tyxml-spec-285)
 (action (diff omd-tyxml-spec-285.html omd-tyxml-spec-285.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-286.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-286.md}))))
(rule
 (alias omd-tyxml-spec-286)
 (action (diff omd-tyxml-spec-286.html omd-tyxml-spec-286.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-287.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-287.md}))))
(rule
 (alias omd-tyxml-spec-287)
 (action (diff omd-tyxml-spec-287.html omd-tyxml-spec-287.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-288.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-288.md}))))
(rule
 (alias omd-tyxml-spec-288)
 (action (diff omd-tyxml-spec-288.html omd-tyxml-spec-288.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-289.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-289.md}))))
(rule
 (alias omd-tyxml-spec-289)
 (action (diff omd-tyxml-spec-289.html omd-tyxml-spec-289.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-290.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-290.md}))))
(rule
 (alias omd-tyxml-spec-290)
 (action (diff omd-tyxml-spec-290.html omd-tyxml-spec-290.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-291.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-291.md}))))
(rule
 (alias omd-tyxml-spec-291)
 (action (diff omd-tyxml-spec-291.html omd-tyxml-spec-291.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-292.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-292.md}))))
(rule
 (alias omd-tyxml-spec-292)
 (action (diff omd-tyxml-spec-292.html omd-tyxml-spec-292.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-293.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-293.md}))))
(rule
 (alias omd-tyxml-spec-293)
 (action (diff omd-tyxml-spec-293.html omd-tyxml-spec-293.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-294.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-294.md}))))
(rule
 (alias omd-tyxml-spec-294)
 (action (diff omd-tyxml-spec-294.html omd-tyxml-spec-294.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-295.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-295.md}))))
(rule
 (alias omd-tyxml-spec-295)
 (action (diff omd-tyxml-spec-295.html omd-tyxml-spec-295.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-296.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-296.md}))))
(rule
 (alias omd-tyxml-spec-296)
 (action (diff omd-tyxml-spec-296.html omd-tyxml-spec-296.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-297.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-297.md}))))
(rule
 (alias omd-tyxml-spec-297)
 (action (diff omd-tyxml-spec-297.html omd-tyxml-spec-297.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-298.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-298.md}))))
(rule
 (alias omd-tyxml-spec-298)
 (action (diff omd-tyxml-spec-298.html omd-tyxml-spec-298.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-299.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-299.md}))))
(rule
 (alias omd-tyxml-spec-299)
 (action (diff omd-tyxml-spec-299.html omd-tyxml-spec-299.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-300.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-300.md}))))
(rule
 (alias omd-tyxml-spec-300)
 (action (diff omd-tyxml-spec-300.html omd-tyxml-spec-300.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-301.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-301.md}))))
(rule
 (alias omd-tyxml-spec-301)
 (action (diff omd-tyxml-spec-301.html omd-tyxml-spec-301.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-302.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-302.md}))))
(rule
 (alias omd-tyxml-spec-302)
 (action (diff omd-tyxml-spec-302.html omd-tyxml-spec-302.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-303.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-303.md}))))
(rule
 (alias omd-tyxml-spec-303)
 (action (diff omd-tyxml-spec-303.html omd-tyxml-spec-303.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-304.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-304.md}))))
(rule
 (alias omd-tyxml-spec-304)
 (action (diff omd-tyxml-spec-304.html omd-tyxml-spec-304.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-305.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-305.md}))))
(rule
 (alias omd-tyxml-spec-305)
 (action (diff omd-tyxml-spec-305.html omd-tyxml-spec-305.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-306.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-306.md}))))
(rule
 (alias omd-tyxml-spec-306)
 (action (diff omd-tyxml-spec-306.html omd-tyxml-spec-306.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-307.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-307.md}))))
(rule
 (alias omd-tyxml-spec-307)
 (action (diff omd-tyxml-spec-307.html omd-tyxml-spec-307.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-308.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-308.md}))))
(rule
 (alias omd-tyxml-spec-308)
 (action (diff omd-tyxml-spec-308.html omd-tyxml-spec-308.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-309.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-309.md}))))
(rule
 (alias omd-tyxml-spec-309)
 (action (diff omd-tyxml-spec-309.html omd-tyxml-spec-309.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-310.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-310.md}))))
(rule
 (alias omd-tyxml-spec-310)
 (action (diff omd-tyxml-spec-310.html omd-tyxml-spec-310.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-311.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-311.md}))))
(rule
 (alias omd-tyxml-spec-311)
 (action (diff omd-tyxml-spec-311.html omd-tyxml-spec-311.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-312.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-312.md}))))
(rule
 (alias omd-tyxml-spec-312)
 (action (diff omd-tyxml-spec-312.html omd-tyxml-spec-312.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-313.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-313.md}))))
(rule
 (alias omd-tyxml-spec-313)
 (action (diff omd-tyxml-spec-313.html omd-tyxml-spec-313.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-314.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-314.md}))))
(rule
 (alias omd-tyxml-spec-314)
 (action (diff omd-tyxml-spec-314.html omd-tyxml-spec-314.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-315.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-315.md}))))
(rule
 (alias omd-tyxml-spec-315)
 (action (diff omd-tyxml-spec-315.html omd-tyxml-spec-315.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-316.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-316.md}))))
(rule
 (alias omd-tyxml-spec-316)
 (action (diff omd-tyxml-spec-316.html omd-tyxml-spec-316.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-317.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-317.md}))))
(rule
 (alias omd-tyxml-spec-317)
 (action (diff omd-tyxml-spec-317.html omd-tyxml-spec-317.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-318.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-318.md}))))
(rule
 (alias omd-tyxml-spec-318)
 (action (diff omd-tyxml-spec-318.html omd-tyxml-spec-318.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-319.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-319.md}))))
(rule
 (alias omd-tyxml-spec-319)
 (action (diff omd-tyxml-spec-319.html omd-tyxml-spec-319.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-320.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-320.md}))))
(rule
 (alias omd-tyxml-spec-320)
 (action (diff omd-tyxml-spec-320.html omd-tyxml-spec-320.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-321.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-321.md}))))
(rule
 (alias omd-tyxml-spec-321)
 (action (diff omd-tyxml-spec-321.html omd-tyxml-spec-321.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-322.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-322.md}))))
(rule
 (alias omd-tyxml-spec-322)
 (action (diff omd-tyxml-spec-322.html omd-tyxml-spec-322.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-323.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-323.md}))))
(rule
 (alias omd-tyxml-spec-323)
 (action (diff omd-tyxml-spec-323.html omd-tyxml-spec-323.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-324.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-324.md}))))
(rule
 (alias omd-tyxml-spec-324)
 (action (diff omd-tyxml-spec-324.html omd-tyxml-spec-324.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-325.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-325.md}))))
(rule
 (alias omd-tyxml-spec-325)
 (action (diff omd-tyxml-spec-325.html omd-tyxml-spec-325.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-326.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-326.md}))))
(rule
 (alias omd-tyxml-spec-326)
 (action (diff omd-tyxml-spec-326.html omd-tyxml-spec-326.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-327.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-327.md}))))
(rule
 (alias omd-tyxml-spec-327)
 (action (diff omd-tyxml-spec-327.html omd-tyxml-spec-327.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-328.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-328.md}))))
(rule
 (alias omd-tyxml-spec-328)
 (action (diff omd-tyxml-spec-328.html omd-tyxml-spec-328.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-329.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-329.md}))))
(rule
 (alias omd-tyxml-spec-329)
 (action (diff omd-tyxml-spec-329.html omd-tyxml-spec-329.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-330.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-330.md}))))
(rule
 (alias omd-tyxml-spec-330)
 (action (diff omd-tyxml-spec-330.html omd-tyxml-spec-330.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-331.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-331.md}))))
(rule
 (alias omd-tyxml-spec-331)
 (action (diff omd-tyxml-spec-331.html omd-tyxml-spec-331.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-332.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-332.md}))))
(rule
 (alias omd-tyxml-spec-332)
 (action (diff omd-tyxml-spec-332.html omd-tyxml-spec-332.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-333.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-333.md}))))
(rule
 (alias omd-tyxml-spec-333)
 (action (diff omd-tyxml-spec-333.html omd-tyxml-spec-333.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-334.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-334.md}))))
(rule
 (alias omd-tyxml-spec-334)
 (action (diff omd-tyxml-spec-334.html omd-tyxml-spec-334.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-335.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-335.md}))))
(rule
 (alias omd-tyxml-spec-335)
 (action (diff omd-tyxml-spec-335.html omd-tyxml-spec-335.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-336.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-336.md}))))
(rule
 (alias omd-tyxml-spec-336)
 (action (diff omd-tyxml-spec-336.html omd-tyxml-spec-336.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-337.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-337.md}))))
(rule
 (alias omd-tyxml-spec-337)
 (action (diff omd-tyxml-spec-337.html omd-tyxml-spec-337.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-338.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-338.md}))))
(rule
 (alias omd-tyxml-spec-338)
 (action (diff omd-tyxml-spec-338.html omd-tyxml-spec-338.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-339.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-339.md}))))
(rule
 (alias omd-tyxml-spec-339)
 (action (diff omd-tyxml-spec-339.html omd-tyxml-spec-339.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-340.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-340.md}))))
(rule
 (alias omd-tyxml-spec-340)
 (action (diff omd-tyxml-spec-340.html omd-tyxml-spec-340.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-341.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-341.md}))))
(rule
 (alias omd-tyxml-spec-341)
 (action (diff omd-tyxml-spec-341.html omd-tyxml-spec-341.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-342.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-342.md}))))
(rule
 (alias omd-tyxml-spec-342)
 (action (diff omd-tyxml-spec-342.html omd-tyxml-spec-342.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-343.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-343.md}))))
(rule
 (alias omd-tyxml-spec-343)
 (action (diff omd-tyxml-spec-343.html omd-tyxml-spec-343.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-344.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-344.md}))))
(rule
 (alias omd-tyxml-spec-344)
 (action (diff omd-tyxml-spec-344.html omd-tyxml-spec-344.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-345.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-345.md}))))
(rule
 (alias omd-tyxml-spec-345)
 (action (diff omd-tyxml-spec-345.html omd-tyxml-spec-345.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-346.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-346.md}))))
(rule
 (alias omd-tyxml-spec-346)
 (action (diff omd-tyxml-spec-346.html omd-tyxml-spec-346.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-347.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-347.md}))))
(rule
 (alias omd-tyxml-spec-347)
 (action (diff omd-tyxml-spec-347.html omd-tyxml-spec-347.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-348.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-348.md}))))
(rule
 (alias omd-tyxml-spec-348)
 (action (diff omd-tyxml-spec-348.html omd-tyxml-spec-348.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-349.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-349.md}))))
(rule
 (alias omd-tyxml-spec-349)
 (action (diff omd-tyxml-spec-349.html omd-tyxml-spec-349.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-350.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-350.md}))))
(rule
 (alias omd-tyxml-spec-350)
 (action (diff omd-tyxml-spec-350.html omd-tyxml-spec-350.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-351.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-351.md}))))
(rule
 (alias omd-tyxml-spec-351)
 (action (diff omd-tyxml-spec-351.html omd-tyxml-spec-351.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-352.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-352.md}))))
(rule
 (alias omd-tyxml-spec-352)
 (action (diff omd-tyxml-spec-352.html omd-tyxml-spec-352.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-353.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-353.md}))))
(rule
 (alias omd-tyxml-spec-353)
 (action (diff omd-tyxml-spec-353.html omd-tyxml-spec-353.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-354.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-354.md}))))
(rule
 (alias omd-tyxml-spec-354)
 (action (diff omd-tyxml-spec-354.html omd-tyxml-spec-354.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-355.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-355.md}))))
(rule
 (alias omd-tyxml-spec-355)
 (action (diff omd-tyxml-spec-355.html omd-tyxml-spec-355.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-356.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-356.md}))))
(rule
 (alias omd-tyxml-spec-356)
 (action (diff omd-tyxml-spec-356.html omd-tyxml-spec-356.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-357.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-357.md}))))
(rule
 (alias omd-tyxml-spec-357)
 (action (diff omd-tyxml-spec-357.html omd-tyxml-spec-357.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-358.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-358.md}))))
(rule
 (alias omd-tyxml-spec-358)
 (action (diff omd-tyxml-spec-358.html omd-tyxml-spec-358.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-359.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-359.md}))))
(rule
 (alias omd-tyxml-spec-359)
 (action (diff omd-tyxml-spec-359.html omd-tyxml-spec-359.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-360.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-360.md}))))
(rule
 (alias omd-tyxml-spec-360)
 (action (diff omd-tyxml-spec-360.html omd-tyxml-spec-360.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-361.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-361.md}))))
(rule
 (alias omd-tyxml-spec-361)
 (action (diff omd-tyxml-spec-361.html omd-tyxml-spec-361.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-362.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-362.md}))))
(rule
 (alias omd-tyxml-spec-362)
 (action (diff omd-tyxml-spec-362.html omd-tyxml-spec-362.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-363.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-363.md}))))
(rule
 (alias omd-tyxml-spec-363)
 (action (diff omd-tyxml-spec-363.html omd-tyxml-spec-363.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-364.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-364.md}))))
(rule
 (alias omd-tyxml-spec-364)
 (action (diff omd-tyxml-spec-364.html omd-tyxml-spec-364.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-365.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-365.md}))))
(rule
 (alias omd-tyxml-spec-365)
 (action (diff omd-tyxml-spec-365.html omd-tyxml-spec-365.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-366.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-366.md}))))
(rule
 (alias omd-tyxml-spec-366)
 (action (diff omd-tyxml-spec-366.html omd-tyxml-spec-366.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-367.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-367.md}))))
(rule
 (alias omd-tyxml-spec-367)
 (action (diff omd-tyxml-spec-367.html omd-tyxml-spec-367.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-368.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-368.md}))))
(rule
 (alias omd-tyxml-spec-368)
 (action (diff omd-tyxml-spec-368.html omd-tyxml-spec-368.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-369.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-369.md}))))
(rule
 (alias omd-tyxml-spec-369)
 (action (diff omd-tyxml-spec-369.html omd-tyxml-spec-369.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-370.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-370.md}))))
(rule
 (alias omd-tyxml-spec-370)
 (action (diff omd-tyxml-spec-370.html omd-tyxml-spec-370.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-371.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-371.md}))))
(rule
 (alias omd-tyxml-spec-371)
 (action (diff omd-tyxml-spec-371.html omd-tyxml-spec-371.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-372.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-372.md}))))
(rule
 (alias omd-tyxml-spec-372)
 (action (diff omd-tyxml-spec-372.html omd-tyxml-spec-372.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-373.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-373.md}))))
(rule
 (alias omd-tyxml-spec-373)
 (action (diff omd-tyxml-spec-373.html omd-tyxml-spec-373.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-374.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-374.md}))))
(rule
 (alias omd-tyxml-spec-374)
 (action (diff omd-tyxml-spec-374.html omd-tyxml-spec-374.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-375.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-375.md}))))
(rule
 (alias omd-tyxml-spec-375)
 (action (diff omd-tyxml-spec-375.html omd-tyxml-spec-375.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-376.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-376.md}))))
(rule
 (alias omd-tyxml-spec-376)
 (action (diff omd-tyxml-spec-376.html omd-tyxml-spec-376.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-377.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-377.md}))))
(rule
 (alias omd-tyxml-spec-377)
 (action (diff omd-tyxml-spec-377.html omd-tyxml-spec-377.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-378.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-378.md}))))
(rule
 (alias omd-tyxml-spec-378)
 (action (diff omd-tyxml-spec-378.html omd-tyxml-spec-378.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-379.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-379.md}))))
(rule
 (alias omd-tyxml-spec-379)
 (action (diff omd-tyxml-spec-379.html omd-tyxml-spec-379.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-380.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-380.md}))))
(rule
 (alias omd-tyxml-spec-380)
 (action (diff omd-tyxml-spec-380.html omd-tyxml-spec-380.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-381.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-381.md}))))
(rule
 (alias omd-tyxml-spec-381)
 (action (diff omd-tyxml-spec-381.html omd-tyxml-spec-381.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-382.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-382.md}))))
(rule
 (alias omd-tyxml-spec-382)
 (action (diff omd-tyxml-spec-382.html omd-tyxml-spec-382.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-383.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-383.md}))))
(rule
 (alias omd-tyxml-spec-383)
 (action (diff omd-tyxml-spec-383.html omd-tyxml-spec-383.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-384.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-384.md}))))
(rule
 (alias omd-tyxml-spec-384)
 (action (diff omd-tyxml-spec-384.html omd-tyxml-spec-384.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-385.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-385.md}))))
(rule
 (alias omd-tyxml-spec-385)
 (action (diff omd-tyxml-spec-385.html omd-tyxml-spec-385.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-386.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-386.md}))))
(rule
 (alias omd-tyxml-spec-386)
 (action (diff omd-tyxml-spec-386.html omd-tyxml-spec-386.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-387.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-387.md}))))
(rule
 (alias omd-tyxml-spec-387)
 (action (diff omd-tyxml-spec-387.html omd-tyxml-spec-387.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-388.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-388.md}))))
(rule
 (alias omd-tyxml-spec-388)
 (action (diff omd-tyxml-spec-388.html omd-tyxml-spec-388.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-389.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-389.md}))))
(rule
 (alias omd-tyxml-spec-389)
 (action (diff omd-tyxml-spec-389.html omd-tyxml-spec-389.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-390.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-390.md}))))
(rule
 (alias omd-tyxml-spec-390)
 (action (diff omd-tyxml-spec-390.html omd-tyxml-spec-390.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-391.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-391.md}))))
(rule
 (alias omd-tyxml-spec-391)
 (action (diff omd-tyxml-spec-391.html omd-tyxml-spec-391.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-392.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-392.md}))))
(rule
 (alias omd-tyxml-spec-392)
 (action (diff omd-tyxml-spec-392.html omd-tyxml-spec-392.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-393.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-393.md}))))
(rule
 (alias omd-tyxml-spec-393)
 (action (diff omd-tyxml-spec-393.html omd-tyxml-spec-393.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-394.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-394.md}))))
(rule
 (alias omd-tyxml-spec-394)
 (action (diff omd-tyxml-spec-394.html omd-tyxml-spec-394.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-395.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-395.md}))))
(rule
 (alias omd-tyxml-spec-395)
 (action (diff omd-tyxml-spec-395.html omd-tyxml-spec-395.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-396.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-396.md}))))
(rule
 (alias omd-tyxml-spec-396)
 (action (diff omd-tyxml-spec-396.html omd-tyxml-spec-396.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-397.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-397.md}))))
(rule
 (alias omd-tyxml-spec-397)
 (action (diff omd-tyxml-spec-397.html omd-tyxml-spec-397.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-398.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-398.md}))))
(rule
 (alias omd-tyxml-spec-398)
 (action (diff omd-tyxml-spec-398.html omd-tyxml-spec-398.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-399.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-399.md}))))
(rule
 (alias omd-tyxml-spec-399)
 (action (diff omd-tyxml-spec-399.html omd-tyxml-spec-399.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-400.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-400.md}))))
(rule
 (alias omd-tyxml-spec-400)
 (action (diff omd-tyxml-spec-400.html omd-tyxml-spec-400.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-401.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-401.md}))))
(rule
 (alias omd-tyxml-spec-401)
 (action (diff omd-tyxml-spec-401.html omd-tyxml-spec-401.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-402.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-402.md}))))
(rule
 (alias omd-tyxml-spec-402)
 (action (diff omd-tyxml-spec-402.html omd-tyxml-spec-402.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-403.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-403.md}))))
(rule
 (alias omd-tyxml-spec-403)
 (action (diff omd-tyxml-spec-403.html omd-tyxml-spec-403.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-404.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-404.md}))))
(rule
 (alias omd-tyxml-spec-404)
 (action (diff omd-tyxml-spec-404.html omd-tyxml-spec-404.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-405.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-405.md}))))
(rule
 (alias omd-tyxml-spec-405)
 (action (diff omd-tyxml-spec-405.html omd-tyxml-spec-405.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-406.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-406.md}))))
(rule
 (alias omd-tyxml-spec-406)
 (action (diff omd-tyxml-spec-406.html omd-tyxml-spec-406.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-407.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-407.md}))))
(rule
 (alias omd-tyxml-spec-407)
 (action (diff omd-tyxml-spec-407.html omd-tyxml-spec-407.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-408.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-408.md}))))
(rule
 (alias omd-tyxml-spec-408)
 (action (diff omd-tyxml-spec-408.html omd-tyxml-spec-408.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-409.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-409.md}))))
(rule
 (alias omd-tyxml-spec-409)
 (action (diff omd-tyxml-spec-409.html omd-tyxml-spec-409.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-410.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-410.md}))))
(rule
 (alias omd-tyxml-spec-410)
 (action (diff omd-tyxml-spec-410.html omd-tyxml-spec-410.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-411.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-411.md}))))
(rule
 (alias omd-tyxml-spec-411)
 (action (diff omd-tyxml-spec-411.html omd-tyxml-spec-411.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-412.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-412.md}))))
(rule
 (alias omd-tyxml-spec-412)
 (action (diff omd-tyxml-spec-412.html omd-tyxml-spec-412.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-413.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-413.md}))))
(rule
 (alias omd-tyxml-spec-413)
 (action (diff omd-tyxml-spec-413.html omd-tyxml-spec-413.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-414.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-414.md}))))
(rule
 (alias omd-tyxml-spec-414)
 (action (diff omd-tyxml-spec-414.html omd-tyxml-spec-414.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-415.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-415.md}))))
(rule
 (alias omd-tyxml-spec-415)
 (action (diff omd-tyxml-spec-415.html omd-tyxml-spec-415.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-416.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-416.md}))))
(rule
 (alias omd-tyxml-spec-416)
 (action (diff omd-tyxml-spec-416.html omd-tyxml-spec-416.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-417.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-417.md}))))
(rule
 (alias omd-tyxml-spec-417)
 (action (diff omd-tyxml-spec-417.html omd-tyxml-spec-417.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-418.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-418.md}))))
(rule
 (alias omd-tyxml-spec-418)
 (action (diff omd-tyxml-spec-418.html omd-tyxml-spec-418.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-419.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-419.md}))))
(rule
 (alias omd-tyxml-spec-419)
 (action (diff omd-tyxml-spec-419.html omd-tyxml-spec-419.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-420.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-420.md}))))
(rule
 (alias omd-tyxml-spec-420)
 (action (diff omd-tyxml-spec-420.html omd-tyxml-spec-420.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-421.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-421.md}))))
(rule
 (alias omd-tyxml-spec-421)
 (action (diff omd-tyxml-spec-421.html omd-tyxml-spec-421.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-422.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-422.md}))))
(rule
 (alias omd-tyxml-spec-422)
 (action (diff omd-tyxml-spec-422.html omd-tyxml-spec-422.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-423.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-423.md}))))
(rule
 (alias omd-tyxml-spec-423)
 (action (diff omd-tyxml-spec-423.html omd-tyxml-spec-423.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-424.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-424.md}))))
(rule
 (alias omd-tyxml-spec-424)
 (action (diff omd-tyxml-spec-424.html omd-tyxml-spec-424.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-425.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-425.md}))))
(rule
 (alias omd-tyxml-spec-425)
 (action (diff omd-tyxml-spec-425.html omd-tyxml-spec-425.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-426.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-426.md}))))
(rule
 (alias omd-tyxml-spec-426)
 (action (diff omd-tyxml-spec-426.html omd-tyxml-spec-426.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-427.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-427.md}))))
(rule
 (alias omd-tyxml-spec-427)
 (action (diff omd-tyxml-spec-427.html omd-tyxml-spec-427.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-428.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-428.md}))))
(rule
 (alias omd-tyxml-spec-428)
 (action (diff omd-tyxml-spec-428.html omd-tyxml-spec-428.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-429.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-429.md}))))
(rule
 (alias omd-tyxml-spec-429)
 (action (diff omd-tyxml-spec-429.html omd-tyxml-spec-429.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-430.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-430.md}))))
(rule
 (alias omd-tyxml-spec-430)
 (action (diff omd-tyxml-spec-430.html omd-tyxml-spec-430.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-431.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-431.md}))))
(rule
 (alias omd-tyxml-spec-431)
 (action (diff omd-tyxml-spec-431.html omd-tyxml-spec-431.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-432.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-432.md}))))
(rule
 (alias omd-tyxml-spec-432)
 (action (diff omd-tyxml-spec-432.html omd-tyxml-spec-432.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-433.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-433.md}))))
(rule
 (alias omd-tyxml-spec-433)
 (action (diff omd-tyxml-spec-433.html omd-tyxml-spec-433.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-434.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-434.md}))))
(rule
 (alias omd-tyxml-spec-434)
 (action (diff omd-tyxml-spec-434.html omd-tyxml-spec-434.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-435.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-435.md}))))
(rule
 (alias omd-tyxml-spec-435)
 (action (diff omd-tyxml-spec-435.html omd-tyxml-spec-435.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-436.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-436.md}))))
(rule
 (alias omd-tyxml-spec-436)
 (action (diff omd-tyxml-spec-436.html omd-tyxml-spec-436.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-437.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-437.md}))))
(rule
 (alias omd-tyxml-spec-437)
 (action (diff omd-tyxml-spec-437.html omd-tyxml-spec-437.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-438.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-438.md}))))
(rule
 (alias omd-tyxml-spec-438)
 (action (diff omd-tyxml-spec-438.html omd-tyxml-spec-438.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-439.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-439.md}))))
(rule
 (alias omd-tyxml-spec-439)
 (action (diff omd-tyxml-spec-439.html omd-tyxml-spec-439.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-440.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-440.md}))))
(rule
 (alias omd-tyxml-spec-440)
 (action (diff omd-tyxml-spec-440.html omd-tyxml-spec-440.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-441.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-441.md}))))
(rule
 (alias omd-tyxml-spec-441)
 (action (diff omd-tyxml-spec-441.html omd-tyxml-spec-441.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-442.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-442.md}))))
(rule
 (alias omd-tyxml-spec-442)
 (action (diff omd-tyxml-spec-442.html omd-tyxml-spec-442.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-443.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-443.md}))))
(rule
 (alias omd-tyxml-spec-443)
 (action (diff omd-tyxml-spec-443.html omd-tyxml-spec-443.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-444.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-444.md}))))
(rule
 (alias omd-tyxml-spec-444)
 (action (diff omd-tyxml-spec-444.html omd-tyxml-spec-444.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-445.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-445.md}))))
(rule
 (alias omd-tyxml-spec-445)
 (action (diff omd-tyxml-spec-445.html omd-tyxml-spec-445.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-446.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-446.md}))))
(rule
 (alias omd-tyxml-spec-446)
 (action (diff omd-tyxml-spec-446.html omd-tyxml-spec-446.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-447.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-447.md}))))
(rule
 (alias omd-tyxml-spec-447)
 (action (diff omd-tyxml-spec-447.html omd-tyxml-spec-447.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-448.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-448.md}))))
(rule
 (alias omd-tyxml-spec-448)
 (action (diff omd-tyxml-spec-448.html omd-tyxml-spec-448.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-449.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-449.md}))))
(rule
 (alias omd-tyxml-spec-449)
 (action (diff omd-tyxml-spec-449.html omd-tyxml-spec-449.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-450.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-450.md}))))
(rule
 (alias omd-tyxml-spec-450)
 (action (diff omd-tyxml-spec-450.html omd-tyxml-spec-450.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-451.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-451.md}))))
(rule
 (alias omd-tyxml-spec-451)
 (action (diff omd-tyxml-spec-451.html omd-tyxml-spec-451.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-452.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-452.md}))))
(rule
 (alias omd-tyxml-spec-452)
 (action (diff omd-tyxml-spec-452.html omd-tyxml-spec-452.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-453.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-453.md}))))
(rule
 (alias omd-tyxml-spec-453)
 (action (diff omd-tyxml-spec-453.html omd-tyxml-spec-453.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-454.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-454.md}))))
(rule
 (alias omd-tyxml-spec-454)
 (action (diff omd-tyxml-spec-454.html omd-tyxml-spec-454.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-455.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-455.md}))))
(rule
 (alias omd-tyxml-spec-455)
 (action (diff omd-tyxml-spec-455.html omd-tyxml-spec-455.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-456.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-456.md}))))
(rule
 (alias omd-tyxml-spec-456)
 (action (diff omd-tyxml-spec-456.html omd-tyxml-spec-456.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-457.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-457.md}))))
(rule
 (alias omd-tyxml-spec-457)
 (action (diff omd-tyxml-spec-457.html omd-tyxml-spec-457.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-458.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-458.md}))))
(rule
 (alias omd-tyxml-spec-458)
 (action (diff omd-tyxml-spec-458.html omd-tyxml-spec-458.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-459.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-459.md}))))
(rule
 (alias omd-tyxml-spec-459)
 (action (diff omd-tyxml-spec-459.html omd-tyxml-spec-459.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-460.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-460.md}))))
(rule
 (alias omd-tyxml-spec-460)
 (action (diff omd-tyxml-spec-460.html omd-tyxml-spec-460.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-461.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-461.md}))))
(rule
 (alias omd-tyxml-spec-461)
 (action (diff omd-tyxml-spec-461.html omd-tyxml-spec-461.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-462.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-462.md}))))
(rule
 (alias omd-tyxml-spec-462)
 (action (diff omd-tyxml-spec-462.html omd-tyxml-spec-462.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-463.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-463.md}))))
(rule
 (alias omd-tyxml-spec-463)
 (action (diff omd-tyxml-spec-463.html omd-tyxml-spec-463.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-464.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-464.md}))))
(rule
 (alias omd-tyxml-spec-464)
 (action (diff omd-tyxml-spec-464.html omd-tyxml-spec-464.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-465.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-465.md}))))
(rule
 (alias omd-tyxml-spec-465)
 (action (diff omd-tyxml-spec-465.html omd-tyxml-spec-465.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-466.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-466.md}))))
(rule
 (alias omd-tyxml-spec-466)
 (action (diff omd-tyxml-spec-466.html omd-tyxml-spec-466.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-467.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-467.md}))))
(rule
 (alias omd-tyxml-spec-467)
 (action (diff omd-tyxml-spec-467.html omd-tyxml-spec-467.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-468.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-468.md}))))
(rule
 (alias omd-tyxml-spec-468)
 (action (diff omd-tyxml-spec-468.html omd-tyxml-spec-468.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-469.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-469.md}))))
(rule
 (alias omd-tyxml-spec-469)
 (action (diff omd-tyxml-spec-469.html omd-tyxml-spec-469.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-470.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-470.md}))))
(rule
 (alias omd-tyxml-spec-470)
 (action (diff omd-tyxml-spec-470.html omd-tyxml-spec-470.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-471.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-471.md}))))
(rule
 (alias omd-tyxml-spec-471)
 (action (diff omd-tyxml-spec-471.html omd-tyxml-spec-471.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-472.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-472.md}))))
(rule
 (alias omd-tyxml-spec-472)
 (action (diff omd-tyxml-spec-472.html omd-tyxml-spec-472.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-473.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-473.md}))))
(rule
 (alias omd-tyxml-spec-473)
 (action (diff omd-tyxml-spec-473.html omd-tyxml-spec-473.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-474.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-474.md}))))
(rule
 (alias omd-tyxml-spec-474)
 (action (diff omd-tyxml-spec-474.html omd-tyxml-spec-474.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-475.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-475.md}))))
(rule
 (alias omd-tyxml-spec-475)
 (action (diff omd-tyxml-spec-475.html omd-tyxml-spec-475.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-476.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-476.md}))))
(rule
 (alias omd-tyxml-spec-476)
 (action (diff omd-tyxml-spec-476.html omd-tyxml-spec-476.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-477.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-477.md}))))
(rule
 (alias omd-tyxml-spec-477)
 (action (diff omd-tyxml-spec-477.html omd-tyxml-spec-477.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-478.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-478.md}))))
(rule
 (alias omd-tyxml-spec-478)
 (action (diff omd-tyxml-spec-478.html omd-tyxml-spec-478.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-479.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-479.md}))))
(rule
 (alias omd-tyxml-spec-479)
 (action (diff omd-tyxml-spec-479.html omd-tyxml-spec-479.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-480.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-480.md}))))
(rule
 (alias omd-tyxml-spec-480)
 (action (diff omd-tyxml-spec-480.html omd-tyxml-spec-480.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-481.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-481.md}))))
(rule
 (alias omd-tyxml-spec-481)
 (action (diff omd-tyxml-spec-481.html omd-tyxml-spec-481.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-482.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-482.md}))))
(rule
 (alias omd-tyxml-spec-482)
 (action (diff omd-tyxml-spec-482.html omd-tyxml-spec-482.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-483.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-483.md}))))
(rule
 (alias omd-tyxml-spec-483)
 (action (diff omd-tyxml-spec-483.html omd-tyxml-spec-483.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-484.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-484.md}))))
(rule
 (alias omd-tyxml-spec-484)
 (action (diff omd-tyxml-spec-484.html omd-tyxml-spec-484.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-485.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-485.md}))))
(rule
 (alias omd-tyxml-spec-485)
 (action (diff omd-tyxml-spec-485.html omd-tyxml-spec-485.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-486.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-486.md}))))
(rule
 (alias omd-tyxml-spec-486)
 (action (diff omd-tyxml-spec-486.html omd-tyxml-spec-486.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-487.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-487.md}))))
(rule
 (alias omd-tyxml-spec-487)
 (action (diff omd-tyxml-spec-487.html omd-tyxml-spec-487.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-488.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-488.md}))))
(rule
 (alias omd-tyxml-spec-488)
 (action (diff omd-tyxml-spec-488.html omd-tyxml-spec-488.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-489.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-489.md}))))
(rule
 (alias omd-tyxml-spec-489)
 (action (diff omd-tyxml-spec-489.html omd-tyxml-spec-489.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-490.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-490.md}))))
(rule
 (alias omd-tyxml-spec-490)
 (action (diff omd-tyxml-spec-490.html omd-tyxml-spec-490.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-491.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-491.md}))))
(rule
 (alias omd-tyxml-spec-491)
 (action (diff omd-tyxml-spec-491.html omd-tyxml-spec-491.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-492.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-492.md}))))
(rule
 (alias omd-tyxml-spec-492)
 (action (diff omd-tyxml-spec-492.html omd-tyxml-spec-492.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-493.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-493.md}))))
(rule
 (alias omd-tyxml-spec-493)
 (action (diff omd-tyxml-spec-493.html omd-tyxml-spec-493.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-494.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-494.md}))))
(rule
 (alias omd-tyxml-spec-494)
 (action (diff omd-tyxml-spec-494.html omd-tyxml-spec-494.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-495.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-495.md}))))
(rule
 (alias omd-tyxml-spec-495)
 (action (diff omd-tyxml-spec-495.html omd-tyxml-spec-495.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-496.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-496.md}))))
(rule
 (alias omd-tyxml-spec-496)
 (action (diff omd-tyxml-spec-496.html omd-tyxml-spec-496.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-497.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-497.md}))))
(rule
 (alias omd-tyxml-spec-497)
 (action (diff omd-tyxml-spec-497.html omd-tyxml-spec-497.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-498.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-498.md}))))
(rule
 (alias omd-tyxml-spec-498)
 (action (diff omd-tyxml-spec-498.html omd-tyxml-spec-498.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-499.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-499.md}))))
(rule
 (alias omd-tyxml-spec-499)
 (action (diff omd-tyxml-spec-499.html omd-tyxml-spec-499.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-500.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-500.md}))))
(rule
 (alias omd-tyxml-spec-500)
 (action (diff omd-tyxml-spec-500.html omd-tyxml-spec-500.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-501.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-501.md}))))
(rule
 (alias omd-tyxml-spec-501)
 (action (diff omd-tyxml-spec-501.html omd-tyxml-spec-501.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-502.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-502.md}))))
(rule
 (alias omd-tyxml-spec-502)
 (action (diff omd-tyxml-spec-502.html omd-tyxml-spec-502.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-503.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-503.md}))))
(rule
 (alias omd-tyxml-spec-503)
 (action (diff omd-tyxml-spec-503.html omd-tyxml-spec-503.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-504.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-504.md}))))
(rule
 (alias omd-tyxml-spec-504)
 (action (diff omd-tyxml-spec-504.html omd-tyxml-spec-504.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-505.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-505.md}))))
(rule
 (alias omd-tyxml-spec-505)
 (action (diff omd-tyxml-spec-505.html omd-tyxml-spec-505.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-506.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-506.md}))))
(rule
 (alias omd-tyxml-spec-506)
 (action (diff omd-tyxml-spec-506.html omd-tyxml-spec-506.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-507.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-507.md}))))
(rule
 (alias omd-tyxml-spec-507)
 (action (diff omd-tyxml-spec-507.html omd-tyxml-spec-507.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-508.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-508.md}))))
(rule
 (alias omd-tyxml-spec-508)
 (action (diff omd-tyxml-spec-508.html omd-tyxml-spec-508.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-509.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-509.md}))))
(rule
 (alias omd-tyxml-spec-509)
 (action (diff omd-tyxml-spec-509.html omd-tyxml-spec-509.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-510.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-510.md}))))
(rule
 (alias omd-tyxml-spec-510)
 (action (diff omd-tyxml-spec-510.html omd-tyxml-spec-510.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-511.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-511.md}))))
(rule
 (alias omd-tyxml-spec-511)
 (action (diff omd-tyxml-spec-511.html omd-tyxml-spec-511.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-512.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-512.md}))))
(rule
 (alias omd-tyxml-spec-512)
 (action (diff omd-tyxml-spec-512.html omd-tyxml-spec-512.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-513.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-513.md}))))
(rule
 (alias omd-tyxml-spec-513)
 (action (diff omd-tyxml-spec-513.html omd-tyxml-spec-513.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-514.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-514.md}))))
(rule
 (alias omd-tyxml-spec-514)
 (action (diff omd-tyxml-spec-514.html omd-tyxml-spec-514.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-515.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-515.md}))))
(rule
 (alias omd-tyxml-spec-515)
 (action (diff omd-tyxml-spec-515.html omd-tyxml-spec-515.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-516.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-516.md}))))
(rule
 (alias omd-tyxml-spec-516)
 (action (diff omd-tyxml-spec-516.html omd-tyxml-spec-516.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-517.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-517.md}))))
(rule
 (alias omd-tyxml-spec-517)
 (action (diff omd-tyxml-spec-517.html omd-tyxml-spec-517.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-518.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-518.md}))))
(rule
 (alias omd-tyxml-spec-518)
 (action (diff omd-tyxml-spec-518.html omd-tyxml-spec-518.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-519.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-519.md}))))
(rule
 (alias omd-tyxml-spec-519)
 (action (diff omd-tyxml-spec-519.html omd-tyxml-spec-519.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-520.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-520.md}))))
(rule
 (alias omd-tyxml-spec-520)
 (action (diff omd-tyxml-spec-520.html omd-tyxml-spec-520.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-521.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-521.md}))))
(rule
 (alias omd-tyxml-spec-521)
 (action (diff omd-tyxml-spec-521.html omd-tyxml-spec-521.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-522.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-522.md}))))
(rule
 (alias omd-tyxml-spec-522)
 (action (diff omd-tyxml-spec-522.html omd-tyxml-spec-522.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-523.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-523.md}))))
(rule
 (alias omd-tyxml-spec-523)
 (action (diff omd-tyxml-spec-523.html omd-tyxml-spec-523.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-524.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-524.md}))))
(rule
 (alias omd-tyxml-spec-524)
 (action (diff omd-tyxml-spec-524.html omd-tyxml-spec-524.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-525.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-525.md}))))
(rule
 (alias omd-tyxml-spec-525)
 (action (diff omd-tyxml-spec-525.html omd-tyxml-spec-525.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-526.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-526.md}))))
(rule
 (alias omd-tyxml-spec-526)
 (action (diff omd-tyxml-spec-526.html omd-tyxml-spec-526.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-527.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-527.md}))))
(rule
 (alias omd-tyxml-spec-527)
 (action (diff omd-tyxml-spec-527.html omd-tyxml-spec-527.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-528.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-528.md}))))
(rule
 (alias omd-tyxml-spec-528)
 (action (diff omd-tyxml-spec-528.html omd-tyxml-spec-528.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-529.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-529.md}))))
(rule
 (alias omd-tyxml-spec-529)
 (action (diff omd-tyxml-spec-529.html omd-tyxml-spec-529.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-530.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-530.md}))))
(rule
 (alias omd-tyxml-spec-530)
 (action (diff omd-tyxml-spec-530.html omd-tyxml-spec-530.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-531.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-531.md}))))
(rule
 (alias omd-tyxml-spec-531)
 (action (diff omd-tyxml-spec-531.html omd-tyxml-spec-531.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-532.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-532.md}))))
(rule
 (alias omd-tyxml-spec-532)
 (action (diff omd-tyxml-spec-532.html omd-tyxml-spec-532.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-533.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-533.md}))))
(rule
 (alias omd-tyxml-spec-533)
 (action (diff omd-tyxml-spec-533.html omd-tyxml-spec-533.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-534.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-534.md}))))
(rule
 (alias omd-tyxml-spec-534)
 (action (diff omd-tyxml-spec-534.html omd-tyxml-spec-534.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-535.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-535.md}))))
(rule
 (alias omd-tyxml-spec-535)
 (action (diff omd-tyxml-spec-535.html omd-tyxml-spec-535.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-536.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-536.md}))))
(rule
 (alias omd-tyxml-spec-536)
 (action (diff omd-tyxml-spec-536.html omd-tyxml-spec-536.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-537.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-537.md}))))
(rule
 (alias omd-tyxml-spec-537)
 (action (diff omd-tyxml-spec-537.html omd-tyxml-spec-537.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-538.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-538.md}))))
(rule
 (alias omd-tyxml-spec-538)
 (action (diff omd-tyxml-spec-538.html omd-tyxml-spec-538.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-539.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-539.md}))))
(rule
 (alias omd-tyxml-spec-539)
 (action (diff omd-tyxml-spec-539.html omd-tyxml-spec-539.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-540.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-540.md}))))
(rule
 (alias omd-tyxml-spec-540)
 (action (diff omd-tyxml-spec-540.html omd-tyxml-spec-540.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-541.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-541.md}))))
(rule
 (alias omd-tyxml-spec-541)
 (action (diff omd-tyxml-spec-541.html omd-tyxml-spec-541.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-542.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-542.md}))))
(rule
 (alias omd-tyxml-spec-542)
 (action (diff omd-tyxml-spec-542.html omd-tyxml-spec-542.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-543.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-543.md}))))
(rule
 (alias omd-tyxml-spec-543)
 (action (diff omd-tyxml-spec-543.html omd-tyxml-spec-543.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-544.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-544.md}))))
(rule
 (alias omd-tyxml-spec-544)
 (action (diff omd-tyxml-spec-544.html omd-tyxml-spec-544.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-545.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-545.md}))))
(rule
 (alias omd-tyxml-spec-545)
 (action (diff omd-tyxml-spec-545.html omd-tyxml-spec-545.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-546.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-546.md}))))
(rule
 (alias omd-tyxml-spec-546)
 (action (diff omd-tyxml-spec-546.html omd-tyxml-spec-546.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-547.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-547.md}))))
(rule
 (alias omd-tyxml-spec-547)
 (action (diff omd-tyxml-spec-547.html omd-tyxml-spec-547.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-548.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-548.md}))))
(rule
 (alias omd-tyxml-spec-548)
 (action (diff omd-tyxml-spec-548.html omd-tyxml-spec-548.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-549.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-549.md}))))
(rule
 (alias omd-tyxml-spec-549)
 (action (diff omd-tyxml-spec-549.html omd-tyxml-spec-549.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-550.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-550.md}))))
(rule
 (alias omd-tyxml-spec-550)
 (action (diff omd-tyxml-spec-550.html omd-tyxml-spec-550.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-551.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-551.md}))))
(rule
 (alias omd-tyxml-spec-551)
 (action (diff omd-tyxml-spec-551.html omd-tyxml-spec-551.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-552.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-552.md}))))
(rule
 (alias omd-tyxml-spec-552)
 (action (diff omd-tyxml-spec-552.html omd-tyxml-spec-552.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-553.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-553.md}))))
(rule
 (alias omd-tyxml-spec-553)
 (action (diff omd-tyxml-spec-553.html omd-tyxml-spec-553.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-554.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-554.md}))))
(rule
 (alias omd-tyxml-spec-554)
 (action (diff omd-tyxml-spec-554.html omd-tyxml-spec-554.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-555.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-555.md}))))
(rule
 (alias omd-tyxml-spec-555)
 (action (diff omd-tyxml-spec-555.html omd-tyxml-spec-555.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-556.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-556.md}))))
(rule
 (alias omd-tyxml-spec-556)
 (action (diff omd-tyxml-spec-556.html omd-tyxml-spec-556.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-557.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-557.md}))))
(rule
 (alias omd-tyxml-spec-557)
 (action (diff omd-tyxml-spec-557.html omd-tyxml-spec-557.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-558.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-558.md}))))
(rule
 (alias omd-tyxml-spec-558)
 (action (diff omd-tyxml-spec-558.html omd-tyxml-spec-558.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-559.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-559.md}))))
(rule
 (alias omd-tyxml-spec-559)
 (action (diff omd-tyxml-spec-559.html omd-tyxml-spec-559.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-560.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-560.md}))))
(rule
 (alias omd-tyxml-spec-560)
 (action (diff omd-tyxml-spec-560.html omd-tyxml-spec-560.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-561.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-561.md}))))
(rule
 (alias omd-tyxml-spec-561)
 (action (diff omd-tyxml-spec-561.html omd-tyxml-spec-561.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-562.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-562.md}))))
(rule
 (alias omd-tyxml-spec-562)
 (action (diff omd-tyxml-spec-562.html omd-tyxml-spec-562.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-563.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-563.md}))))
(rule
 (alias omd-tyxml-spec-563)
 (action (diff omd-tyxml-spec-563.html omd-tyxml-spec-563.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-564.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-564.md}))))
(rule
 (alias omd-tyxml-spec-564)
 (action (diff omd-tyxml-spec-564.html omd-tyxml-spec-564.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-565.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-565.md}))))
(rule
 (alias omd-tyxml-spec-565)
 (action (diff omd-tyxml-spec-565.html omd-tyxml-spec-565.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-566.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-566.md}))))
(rule
 (alias omd-tyxml-spec-566)
 (action (diff omd-tyxml-spec-566.html omd-tyxml-spec-566.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-567.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-567.md}))))
(rule
 (alias omd-tyxml-spec-567)
 (action (diff omd-tyxml-spec-567.html omd-tyxml-spec-567.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-568.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-568.md}))))
(rule
 (alias omd-tyxml-spec-568)
 (action (diff omd-tyxml-spec-568.html omd-tyxml-spec-568.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-569.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-569.md}))))
(rule
 (alias omd-tyxml-spec-569)
 (action (diff omd-tyxml-spec-569.html omd-tyxml-spec-569.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-570.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-570.md}))))
(rule
 (alias omd-tyxml-spec-570)
 (action (diff omd-tyxml-spec-570.html omd-tyxml-spec-570.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-571.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-571.md}))))
(rule
 (alias omd-tyxml-spec-571)
 (action (diff omd-tyxml-spec-571.html omd-tyxml-spec-571.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-572.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-572.md}))))
(rule
 (alias omd-tyxml-spec-572)
 (action (diff omd-tyxml-spec-572.html omd-tyxml-spec-572.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-573.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-573.md}))))
(rule
 (alias omd-tyxml-spec-573)
 (action (diff omd-tyxml-spec-573.html omd-tyxml-spec-573.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-574.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-574.md}))))
(rule
 (alias omd-tyxml-spec-574)
 (action (diff omd-tyxml-spec-574.html omd-tyxml-spec-574.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-575.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-575.md}))))
(rule
 (alias omd-tyxml-spec-575)
 (action (diff omd-tyxml-spec-575.html omd-tyxml-spec-575.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-576.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-576.md}))))
(rule
 (alias omd-tyxml-spec-576)
 (action (diff omd-tyxml-spec-576.html omd-tyxml-spec-576.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-577.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-577.md}))))
(rule
 (alias omd-tyxml-spec-577)
 (action (diff omd-tyxml-spec-577.html omd-tyxml-spec-577.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-578.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-578.md}))))
(rule
 (alias omd-tyxml-spec-578)
 (action (diff omd-tyxml-spec-578.html omd-tyxml-spec-578.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-579.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-579.md}))))
(rule
 (alias omd-tyxml-spec-579)
 (action (diff omd-tyxml-spec-579.html omd-tyxml-spec-579.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-580.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-580.md}))))
(rule
 (alias omd-tyxml-spec-580)
 (action (diff omd-tyxml-spec-580.html omd-tyxml-spec-580.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-581.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-581.md}))))
(rule
 (alias omd-tyxml-spec-581)
 (action (diff omd-tyxml-spec-581.html omd-tyxml-spec-581.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-582.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-582.md}))))
(rule
 (alias omd-tyxml-spec-582)
 (action (diff omd-tyxml-spec-582.html omd-tyxml-spec-582.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-583.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-583.md}))))
(rule
 (alias omd-tyxml-spec-583)
 (action (diff omd-tyxml-spec-583.html omd-tyxml-spec-583.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-584.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-584.md}))))
(rule
 (alias omd-tyxml-spec-584)
 (action (diff omd-tyxml-spec-584.html omd-tyxml-spec-584.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-585.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-585.md}))))
(rule
 (alias omd-tyxml-spec-585)
 (action (diff omd-tyxml-spec-585.html omd-tyxml-spec-585.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-586.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-586.md}))))
(rule
 (alias omd-tyxml-spec-586)
 (action (diff omd-tyxml-spec-586.html omd-tyxml-spec-586.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-587.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-587.md}))))
(rule
 (alias omd-tyxml-spec-587)
 (action (diff omd-tyxml-spec-587.html omd-tyxml-spec-587.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-588.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-588.md}))))
(rule
 (alias omd-tyxml-spec-588)
 (action (diff omd-tyxml-spec-588.html omd-tyxml-spec-588.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-589.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-589.md}))))
(rule
 (alias omd-tyxml-spec-589)
 (action (diff omd-tyxml-spec-589.html omd-tyxml-spec-589.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-590.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-590.md}))))
(rule
 (alias omd-tyxml-spec-590)
 (action (diff omd-tyxml-spec-590.html omd-tyxml-spec-590.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-591.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-591.md}))))
(rule
 (alias omd-tyxml-spec-591)
 (action (diff omd-tyxml-spec-591.html omd-tyxml-spec-591.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-592.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-592.md}))))
(rule
 (alias omd-tyxml-spec-592)
 (action (diff omd-tyxml-spec-592.html omd-tyxml-spec-592.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-593.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-593.md}))))
(rule
 (alias omd-tyxml-spec-593)
 (action (diff omd-tyxml-spec-593.html omd-tyxml-spec-593.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-594.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-594.md}))))
(rule
 (alias omd-tyxml-spec-594)
 (action (diff omd-tyxml-spec-594.html omd-tyxml-spec-594.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-595.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-595.md}))))
(rule
 (alias omd-tyxml-spec-595)
 (action (diff omd-tyxml-spec-595.html omd-tyxml-spec-595.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-596.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-596.md}))))
(rule
 (alias omd-tyxml-spec-596)
 (action (diff omd-tyxml-spec-596.html omd-tyxml-spec-596.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-597.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-597.md}))))
(rule
 (alias omd-tyxml-spec-597)
 (action (diff omd-tyxml-spec-597.html omd-tyxml-spec-597.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-598.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-598.md}))))
(rule
 (alias omd-tyxml-spec-598)
 (action (diff omd-tyxml-spec-598.html omd-tyxml-spec-598.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-599.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-599.md}))))
(rule
 (alias omd-tyxml-spec-599)
 (action (diff omd-tyxml-spec-599.html omd-tyxml-spec-599.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-600.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-600.md}))))
(rule
 (alias omd-tyxml-spec-600)
 (action (diff omd-tyxml-spec-600.html omd-tyxml-spec-600.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-601.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-601.md}))))
(rule
 (alias omd-tyxml-spec-601)
 (action (diff omd-tyxml-spec-601.html omd-tyxml-spec-601.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-602.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-602.md}))))
(rule
 (alias omd-tyxml-spec-602)
 (action (diff omd-tyxml-spec-602.html omd-tyxml-spec-602.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-603.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-603.md}))))
(rule
 (alias omd-tyxml-spec-603)
 (action (diff omd-tyxml-spec-603.html omd-tyxml-spec-603.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-604.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-604.md}))))
(rule
 (alias omd-tyxml-spec-604)
 (action (diff omd-tyxml-spec-604.html omd-tyxml-spec-604.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-605.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-605.md}))))
(rule
 (alias omd-tyxml-spec-605)
 (action (diff omd-tyxml-spec-605.html omd-tyxml-spec-605.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-606.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-606.md}))))
(rule
 (alias omd-tyxml-spec-606)
 (action (diff omd-tyxml-spec-606.html omd-tyxml-spec-606.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-607.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-607.md}))))
(rule
 (alias omd-tyxml-spec-607)
 (action (diff omd-tyxml-spec-607.html omd-tyxml-spec-607.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-608.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-608.md}))))
(rule
 (alias omd-tyxml-spec-608)
 (action (diff omd-tyxml-spec-608.html omd-tyxml-spec-608.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-609.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-609.md}))))
(rule
 (alias omd-tyxml-spec-609)
 (action (diff omd-tyxml-spec-609.html omd-tyxml-spec-609.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-610.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-610.md}))))
(rule
 (alias omd-tyxml-spec-610)
 (action (diff omd-tyxml-spec-610.html omd-tyxml-spec-610.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-611.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-611.md}))))
(rule
 (alias omd-tyxml-spec-611)
 (action (diff omd-tyxml-spec-611.html omd-tyxml-spec-611.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-612.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-612.md}))))
(rule
 (alias omd-tyxml-spec-612)
 (action (diff omd-tyxml-spec-612.html omd-tyxml-spec-612.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-613.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-613.md}))))
(rule
 (alias omd-tyxml-spec-613)
 (action (diff omd-tyxml-spec-613.html omd-tyxml-spec-613.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-614.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-614.md}))))
(rule
 (alias omd-tyxml-spec-614)
 (action (diff omd-tyxml-spec-614.html omd-tyxml-spec-614.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-615.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-615.md}))))
(rule
 (alias omd-tyxml-spec-615)
 (action (diff omd-tyxml-spec-615.html omd-tyxml-spec-615.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-616.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-616.md}))))
(rule
 (alias omd-tyxml-spec-616)
 (action (diff omd-tyxml-spec-616.html omd-tyxml-spec-616.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-617.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-617.md}))))
(rule
 (alias omd-tyxml-spec-617)
 (action (diff omd-tyxml-spec-617.html omd-tyxml-spec-617.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-618.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-618.md}))))
(rule
 (alias omd-tyxml-spec-618)
 (action (diff omd-tyxml-spec-618.html omd-tyxml-spec-618.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-619.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-619.md}))))
(rule
 (alias omd-tyxml-spec-619)
 (action (diff omd-tyxml-spec-619.html omd-tyxml-spec-619.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-620.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-620.md}))))
(rule
 (alias omd-tyxml-spec-620)
 (action (diff omd-tyxml-spec-620.html omd-tyxml-spec-620.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-621.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-621.md}))))
(rule
 (alias omd-tyxml-spec-621)
 (action (diff omd-tyxml-spec-621.html omd-tyxml-spec-621.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-622.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-622.md}))))
(rule
 (alias omd-tyxml-spec-622)
 (action (diff omd-tyxml-spec-622.html omd-tyxml-spec-622.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-623.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-623.md}))))
(rule
 (alias omd-tyxml-spec-623)
 (action (diff omd-tyxml-spec-623.html omd-tyxml-spec-623.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-624.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-624.md}))))
(rule
 (alias omd-tyxml-spec-624)
 (action (diff omd-tyxml-spec-624.html omd-tyxml-spec-624.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-625.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-625.md}))))
(rule
 (alias omd-tyxml-spec-625)
 (action (diff omd-tyxml-spec-625.html omd-tyxml-spec-625.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-626.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-626.md}))))
(rule
 (alias omd-tyxml-spec-626)
 (action (diff omd-tyxml-spec-626.html omd-tyxml-spec-626.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-627.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-627.md}))))
(rule
 (alias omd-tyxml-spec-627)
 (action (diff omd-tyxml-spec-627.html omd-tyxml-spec-627.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-628.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-628.md}))))
(rule
 (alias omd-tyxml-spec-628)
 (action (diff omd-tyxml-spec-628.html omd-tyxml-spec-628.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-629.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-629.md}))))
(rule
 (alias omd-tyxml-spec-629)
 (action (diff omd-tyxml-spec-629.html omd-tyxml-spec-629.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-630.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-630.md}))))
(rule
 (alias omd-tyxml-spec-630)
 (action (diff omd-tyxml-spec-630.html omd-tyxml-spec-630.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-631.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-631.md}))))
(rule
 (alias omd-tyxml-spec-631)
 (action (diff omd-tyxml-spec-631.html omd-tyxml-spec-631.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-632.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-632.md}))))
(rule
 (alias omd-tyxml-spec-632)
 (action (diff omd-tyxml-spec-632.html omd-tyxml-spec-632.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-633.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-633.md}))))
(rule
 (alias omd-tyxml-spec-633)
 (action (diff omd-tyxml-spec-633.html omd-tyxml-spec-633.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-634.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-634.md}))))
(rule
 (alias omd-tyxml-spec-634)
 (action (diff omd-tyxml-spec-634.html omd-tyxml-spec-634.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-635.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-635.md}))))
(rule
 (alias omd-tyxml-spec-635)
 (action (diff omd-tyxml-spec-635.html omd-tyxml-spec-635.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-636.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-636.md}))))
(rule
 (alias omd-tyxml-spec-636)
 (action (diff omd-tyxml-spec-636.html omd-tyxml-spec-636.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-637.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-637.md}))))
(rule
 (alias omd-tyxml-spec-637)
 (action (diff omd-tyxml-spec-637.html omd-tyxml-spec-637.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-638.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-638.md}))))
(rule
 (alias omd-tyxml-spec-638)
 (action (diff omd-tyxml-spec-638.html omd-tyxml-spec-638.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-639.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-639.md}))))
(rule
 (alias omd-tyxml-spec-639)
 (action (diff omd-tyxml-spec-639.html omd-tyxml-spec-639.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-640.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-640.md}))))
(rule
 (alias omd-tyxml-spec-640)
 (action (diff omd-tyxml-spec-640.html omd-tyxml-spec-640.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-641.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-641.md}))))
(rule
 (alias omd-tyxml-spec-641)
 (action (diff omd-tyxml-spec-641.html omd-tyxml-spec-641.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-642.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-642.md}))))
(rule
 (alias omd-tyxml-spec-642)
 (action (diff omd-tyxml-spec-642.html omd-tyxml-spec-642.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-643.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-643.md}))))
(rule
 (alias omd-tyxml-spec-643)
 (action (diff omd-tyxml-spec-643.html omd-tyxml-spec-643.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-644.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-644.md}))))
(rule
 (alias omd-tyxml-spec-644)
 (action (diff omd-tyxml-spec-644.html omd-tyxml-spec-644.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-645.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-645.md}))))
(rule
 (alias omd-tyxml-spec-645)
 (action (diff omd-tyxml-spec-645.html omd-tyxml-spec-645.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-646.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-646.md}))))
(rule
 (alias omd-tyxml-spec-646)
 (action (diff omd-tyxml-spec-646.html omd-tyxml-spec-646.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-647.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-647.md}))))
(rule
 (alias omd-tyxml-spec-647)
 (action (diff omd-tyxml-spec-647.html omd-tyxml-spec-647.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-648.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-648.md}))))
(rule
 (alias omd-tyxml-spec-648)
 (action (diff omd-tyxml-spec-648.html omd-tyxml-spec-648.html.new)))
(rule
 (action
  (with-stdout-to omd-tyxml-spec-649.html.new
   (run ./omd_tyxml.exe %{dep:omd-tyxml-spec-649.md}))))
(rule
 (alias omd-tyxml-spec-649)
 (action (diff omd-tyxml-spec-649.html omd-tyxml-spec-649.html.new)))
(alias
 (name runtest)
 (deps
  (alias omd-tyxml-spec-001)
  (alias omd-tyxml-spec-002)
  (alias omd-tyxml-spec-003)
  (alias omd-tyxml-spec-004)
  (alias omd-tyxml-spec-005)
  (alias omd-tyxml-spec-006)
  (alias omd-tyxml-spec-007)
  (alias omd-tyxml-spec-008)
  (alias omd-tyxml-spec-009)
  (alias omd-tyxml-spec-010)
  (alias omd-tyxml-spec-011)
  (alias omd-tyxml-spec-012)
  (alias omd-tyxml-spec-013)
  (alias omd-tyxml-spec-014)
  (alias omd-tyxml-spec-015)
  (alias omd-tyxml-spec-016)
  (alias omd-tyxml-spec-017)
  (alias omd-tyxml-spec-018)
  (alias omd-tyxml-spec-019)
  (alias omd-tyxml-spec-020)
  (alias omd-tyxml-spec-021)
  (alias omd-tyxml-spec-022)
  (alias omd-tyxml-spec-023)
  (alias omd-tyxml-spec-024)
  (alias omd-tyxml-spec-025)
  (alias omd-tyxml-spec-026)
  (alias omd-tyxml-spec-027)
  (alias omd-tyxml-spec-028)
  (alias omd-tyxml-spec-029)
  (alias omd-tyxml-spec-030)
  (alias omd-tyxml-spec-031)
  (alias omd-tyxml-spec-032)
  (alias omd-tyxml-spec-033)
  (alias omd-tyxml-spec-034)
  (alias omd-tyxml-spec-035)
  (alias omd-tyxml-spec-036)
  (alias omd-tyxml-spec-037)
  (alias omd-tyxml-spec-038)
  (alias omd-tyxml-spec-039)
  (alias omd-tyxml-spec-040)
  (alias omd-tyxml-spec-041)
  (alias omd-tyxml-spec-042)
  (alias omd-tyxml-spec-043)
  (alias omd-tyxml-spec-044)
  (alias omd-tyxml-spec-045)
  (alias omd-tyxml-spec-046)
  (alias omd-tyxml-spec-047)
  (alias omd-tyxml-spec-048)
  (alias omd-tyxml-spec-049)
  (alias omd-tyxml-spec-050)
  (alias omd-tyxml-spec-051)
  (alias omd-tyxml-spec-052)
  (alias omd-tyxml-spec-053)
  (alias omd-tyxml-spec-054)
  (alias omd-tyxml-spec-055)
  (alias omd-tyxml-spec-056)
  (alias omd-tyxml-spec-057)
  (alias omd-tyxml-spec-058)
  (alias omd-tyxml-spec-059)
  (alias omd-tyxml-spec-060)
  (alias omd-tyxml-spec-061)
  (alias omd-tyxml-spec-062)
  (alias omd-tyxml-spec-063)
  (alias omd-tyxml-spec-064)
  (alias omd-tyxml-spec-065)
  (alias omd-tyxml-spec-066)
  (alias omd-tyxml-spec-067)
  (alias omd-tyxml-spec-068)
  (alias omd-tyxml-spec-069)
  (alias omd-tyxml-spec-070)
  (alias omd-tyxml-spec-071)
  (alias omd-tyxml-spec-072)
  (alias omd-tyxml-spec-073)
  (alias omd-tyxml-spec-074)
  (alias omd-tyxml-spec-075)
  (alias omd-tyxml-spec-076)
  (alias omd-tyxml-spec-077)
  (alias omd-tyxml-spec-078)
  (alias omd-tyxml-spec-079)
  (alias omd-tyxml-spec-080)
  (alias omd-tyxml-spec-081)
  (alias omd-tyxml-spec-082)
  (alias omd-tyxml-spec-083)
  (alias omd-tyxml-spec-084)
  (alias omd-tyxml-spec-085)
  (alias omd-tyxml-spec-086)
  (alias omd-tyxml-spec-087)
  (alias omd-tyxml-spec-088)
  (alias omd-tyxml-spec-089)
  (alias omd-tyxml-spec-090)
  (alias omd-tyxml-spec-091)
  (alias omd-tyxml-spec-092)
  (alias omd-tyxml-spec-093)
  (alias omd-tyxml-spec-094)
  (alias omd-tyxml-spec-095)
  (alias omd-tyxml-spec-096)
  (alias omd-tyxml-spec-097)
  (alias omd-tyxml-spec-098)
  (alias omd-tyxml-spec-099)
  (alias omd-tyxml-spec-100)
  (alias omd-tyxml-spec-101)
  (alias omd-tyxml-spec-102)
  (alias omd-tyxml-spec-103)
  (alias omd-tyxml-spec-104)
  (alias omd-tyxml-spec-105)
  (alias omd-tyxml-spec-106)
  (alias omd-tyxml-spec-107)
  (alias omd-tyxml-spec-108)
  (alias omd-tyxml-spec-109)
  (alias omd-tyxml-spec-110)
  (alias omd-tyxml-spec-111)
  (alias omd-tyxml-spec-112)
  (alias omd-tyxml-spec-113)
  (alias omd-tyxml-spec-114)
  (alias omd-tyxml-spec-115)
  (alias omd-tyxml-spec-116)
  (alias omd-tyxml-spec-117)
  (alias omd-tyxml-spec-118)
  (alias omd-tyxml-spec-119)
  (alias omd-tyxml-spec-120)
  (alias omd-tyxml-spec-121)
  (alias omd-tyxml-spec-122)
  (alias omd-tyxml-spec-123)
  (alias omd-tyxml-spec-124)
  (alias omd-tyxml-spec-125)
  (alias omd-tyxml-spec-126)
  (alias omd-tyxml-spec-127)
  (alias omd-tyxml-spec-128)
  (alias omd-tyxml-spec-129)
  (alias omd-tyxml-spec-130)
  (alias omd-tyxml-spec-131)
  (alias omd-tyxml-spec-132)
  (alias omd-tyxml-spec-133)
  (alias omd-tyxml-spec-134)
  (alias omd-tyxml-spec-135)
  (alias omd-tyxml-spec-136)
  (alias omd-tyxml-spec-137)
  (alias omd-tyxml-spec-138)
  (alias omd-tyxml-spec-139)
  (alias omd-tyxml-spec-140)
  (alias omd-tyxml-spec-141)
  (alias omd-tyxml-spec-142)
  (alias omd-tyxml-spec-143)
  (alias omd-tyxml-spec-144)
  (alias omd-tyxml-spec-145)
  (alias omd-tyxml-spec-146)
  (alias omd-tyxml-spec-147)
  (alias omd-tyxml-spec-148)
  (alias omd-tyxml-spec-149)
  (alias omd-tyxml-spec-150)
  (alias omd-tyxml-spec-151)
  (alias omd-tyxml-spec-152)
  (alias omd-tyxml-spec-153)
  (alias omd-tyxml-spec-154)
  (alias omd-tyxml-spec-155)
  (alias omd-tyxml-spec-156)
  (alias omd-tyxml-spec-157)
  (alias omd-tyxml-spec-158)
  (alias omd-tyxml-spec-159)
  (alias omd-tyxml-spec-160)
  (alias omd-tyxml-spec-161)
  (alias omd-tyxml-spec-162)
  (alias omd-tyxml-spec-163)
  (alias omd-tyxml-spec-165)
  (alias omd-tyxml-spec-166)
  (alias omd-tyxml-spec-167)
  (alias omd-tyxml-spec-168)
  (alias omd-tyxml-spec-169)
  (alias omd-tyxml-spec-170)
  (alias omd-tyxml-spec-171)
  (alias omd-tyxml-spec-172)
  (alias omd-tyxml-spec-173)
  (alias omd-tyxml-spec-174)
  (alias omd-tyxml-spec-176)
  (alias omd-tyxml-spec-177)
  (alias omd-tyxml-spec-178)
  (alias omd-tyxml-spec-179)
  (alias omd-tyxml-spec-180)
  (alias omd-tyxml-spec-181)
  (alias omd-tyxml-spec-182)
  (alias omd-tyxml-spec-183)
  (alias omd-tyxml-spec-186)
  (alias omd-tyxml-spec-187)
  (alias omd-tyxml-spec-188)
  (alias omd-tyxml-spec-189)
  (alias omd-tyxml-spec-190)
  (alias omd-tyxml-spec-191)
  (alias omd-tyxml-spec-192)
  (alias omd-tyxml-spec-193)
  (alias omd-tyxml-spec-194)
  (alias omd-tyxml-spec-195)
  (alias omd-tyxml-spec-196)
  (alias omd-tyxml-spec-197)
  (alias omd-tyxml-spec-198)
  (alias omd-tyxml-spec-199)
  (alias omd-tyxml-spec-200)
  (alias omd-tyxml-spec-201)
  (alias omd-tyxml-spec-202)
  (alias omd-tyxml-spec-203)
  (alias omd-tyxml-spec-204)
  (alias omd-tyxml-spec-205)
  (alias omd-tyxml-spec-206)
  (alias omd-tyxml-spec-207)
  (alias omd-tyxml-spec-208)
  (alias omd-tyxml-spec-209)
  (alias omd-tyxml-spec-210)
  (alias omd-tyxml-spec-211)
  (alias omd-tyxml-spec-212)
  (alias omd-tyxml-spec-213)
  (alias omd-tyxml-spec-214)
  (alias omd-tyxml-spec-215)
  (alias omd-tyxml-spec-216)
  (alias omd-tyxml-spec-217)
  (alias omd-tyxml-spec-218)
  (alias omd-tyxml-spec-219)
  (alias omd-tyxml-spec-220)
  (alias omd-tyxml-spec-221)
  (alias omd-tyxml-spec-222)
  (alias omd-tyxml-spec-223)
  (alias omd-tyxml-spec-224)
  (alias omd-tyxml-spec-225)
  (alias omd-tyxml-spec-226)
  (alias omd-tyxml-spec-227)
  (alias omd-tyxml-spec-228)
  (alias omd-tyxml-spec-229)
  (alias omd-tyxml-spec-230)
  (alias omd-tyxml-spec-231)
  (alias omd-tyxml-spec-232)
  (alias omd-tyxml-spec-233)
  (alias omd-tyxml-spec-234)
  (alias omd-tyxml-spec-235)
  (alias omd-tyxml-spec-236)
  (alias omd-tyxml-spec-237)
  (alias omd-tyxml-spec-238)
  (alias omd-tyxml-spec-239)
  (alias omd-tyxml-spec-240)
  (alias omd-tyxml-spec-241)
  (alias omd-tyxml-spec-242)
  (alias omd-tyxml-spec-243)
  (alias omd-tyxml-spec-244)
  (alias omd-tyxml-spec-245)
  (alias omd-tyxml-spec-246)
  (alias omd-tyxml-spec-247)
  (alias omd-tyxml-spec-248)
  (alias omd-tyxml-spec-249)
  (alias omd-tyxml-spec-250)
  (alias omd-tyxml-spec-251)
  (alias omd-tyxml-spec-252)
  (alias omd-tyxml-spec-253)
  (alias omd-tyxml-spec-254)
  (alias omd-tyxml-spec-255)
  (alias omd-tyxml-spec-256)
  (alias omd-tyxml-spec-257)
  (alias omd-tyxml-spec-258)
  (alias omd-tyxml-spec-259)
  (alias omd-tyxml-spec-260)
  (alias omd-tyxml-spec-261)
  (alias omd-tyxml-spec-262)
  (alias omd-tyxml-spec-263)
  (alias omd-tyxml-spec-264)
  (alias omd-tyxml-spec-265)
  (alias omd-tyxml-spec-266)
  (alias omd-tyxml-spec-267)
  (alias omd-tyxml-spec-268)
  (alias omd-tyxml-spec-269)
  (alias omd-tyxml-spec-270)
  (alias omd-tyxml-spec-271)
  (alias omd-tyxml-spec-272)
  (alias omd-tyxml-spec-273)
  (alias omd-tyxml-spec-274)
  (alias omd-tyxml-spec-275)
  (alias omd-tyxml-spec-276)
  (alias omd-tyxml-spec-277)
  (alias omd-tyxml-spec-278)
  (alias omd-tyxml-spec-279)
  (alias omd-tyxml-spec-280)
  (alias omd-tyxml-spec-281)
  (alias omd-tyxml-spec-282)
  (alias omd-tyxml-spec-283)
  (alias omd-tyxml-spec-284)
  (alias omd-tyxml-spec-285)
  (alias omd-tyxml-spec-286)
  (alias omd-tyxml-spec-287)
  (alias omd-tyxml-spec-288)
  (alias omd-tyxml-spec-289)
  (alias omd-tyxml-spec-290)
  (alias omd-tyxml-spec-291)
  (alias omd-tyxml-spec-292)
  (alias omd-tyxml-spec-293)
  (alias omd-tyxml-spec-294)
  (alias omd-tyxml-spec-295)
  (alias omd-tyxml-spec-296)
  (alias omd-tyxml-spec-297)
  (alias omd-tyxml-spec-298)
  (alias omd-tyxml-spec-299)
  (alias omd-tyxml-spec-300)
  (alias omd-tyxml-spec-301)
  (alias omd-tyxml-spec-302)
  (alias omd-tyxml-spec-303)
  (alias omd-tyxml-spec-304)
  (alias omd-tyxml-spec-305)
  (alias omd-tyxml-spec-306)
  (alias omd-tyxml-spec-307)
  (alias omd-tyxml-spec-308)
  (alias omd-tyxml-spec-309)
  (alias omd-tyxml-spec-310)
  (alias omd-tyxml-spec-311)
  (alias omd-tyxml-spec-312)
  (alias omd-tyxml-spec-313)
  (alias omd-tyxml-spec-314)
  (alias omd-tyxml-spec-315)
  (alias omd-tyxml-spec-316)
  (alias omd-tyxml-spec-317)
  (alias omd-tyxml-spec-318)
  (alias omd-tyxml-spec-319)
  (alias omd-tyxml-spec-320)
  (alias omd-tyxml-spec-321)
  (alias omd-tyxml-spec-322)
  (alias omd-tyxml-spec-323)
  (alias omd-tyxml-spec-324)
  (alias omd-tyxml-spec-325)
  (alias omd-tyxml-spec-326)
  (alias omd-tyxml-spec-327)
  (alias omd-tyxml-spec-328)
  (alias omd-tyxml-spec-329)
  (alias omd-tyxml-spec-330)
  (alias omd-tyxml-spec-331)
  (alias omd-tyxml-spec-332)
  (alias omd-tyxml-spec-333)
  (alias omd-tyxml-spec-335)
  (alias omd-tyxml-spec-336)
  (alias omd-tyxml-spec-337)
  (alias omd-tyxml-spec-338)
  (alias omd-tyxml-spec-339)
  (alias omd-tyxml-spec-340)
  (alias omd-tyxml-spec-341)
  (alias omd-tyxml-spec-342)
  (alias omd-tyxml-spec-343)
  (alias omd-tyxml-spec-344)
  (alias omd-tyxml-spec-345)
  (alias omd-tyxml-spec-346)
  (alias omd-tyxml-spec-347)
  (alias omd-tyxml-spec-348)
  (alias omd-tyxml-spec-349)
  (alias omd-tyxml-spec-350)
  (alias omd-tyxml-spec-351)
  (alias omd-tyxml-spec-352)
  (alias omd-tyxml-spec-354)
  (alias omd-tyxml-spec-355)
  (alias omd-tyxml-spec-356)
  (alias omd-tyxml-spec-357)
  (alias omd-tyxml-spec-358)
  (alias omd-tyxml-spec-359)
  (alias omd-tyxml-spec-360)
  (alias omd-tyxml-spec-361)
  (alias omd-tyxml-spec-362)
  (alias omd-tyxml-spec-363)
  (alias omd-tyxml-spec-364)
  (alias omd-tyxml-spec-365)
  (alias omd-tyxml-spec-366)
  (alias omd-tyxml-spec-367)
  (alias omd-tyxml-spec-368)
  (alias omd-tyxml-spec-369)
  (alias omd-tyxml-spec-370)
  (alias omd-tyxml-spec-371)
  (alias omd-tyxml-spec-372)
  (alias omd-tyxml-spec-373)
  (alias omd-tyxml-spec-374)
  (alias omd-tyxml-spec-375)
  (alias omd-tyxml-spec-376)
  (alias omd-tyxml-spec-377)
  (alias omd-tyxml-spec-378)
  (alias omd-tyxml-spec-379)
  (alias omd-tyxml-spec-380)
  (alias omd-tyxml-spec-381)
  (alias omd-tyxml-spec-382)
  (alias omd-tyxml-spec-383)
  (alias omd-tyxml-spec-384)
  (alias omd-tyxml-spec-385)
  (alias omd-tyxml-spec-386)
  (alias omd-tyxml-spec-387)
  (alias omd-tyxml-spec-388)
  (alias omd-tyxml-spec-389)
  (alias omd-tyxml-spec-390)
  (alias omd-tyxml-spec-391)
  (alias omd-tyxml-spec-392)
  (alias omd-tyxml-spec-393)
  (alias omd-tyxml-spec-394)
  (alias omd-tyxml-spec-395)
  (alias omd-tyxml-spec-396)
  (alias omd-tyxml-spec-397)
  (alias omd-tyxml-spec-398)
  (alias omd-tyxml-spec-399)
  (alias omd-tyxml-spec-400)
  (alias omd-tyxml-spec-401)
  (alias omd-tyxml-spec-402)
  (alias omd-tyxml-spec-403)
  (alias omd-tyxml-spec-404)
  (alias omd-tyxml-spec-405)
  (alias omd-tyxml-spec-406)
  (alias omd-tyxml-spec-407)
  (alias omd-tyxml-spec-408)
  (alias omd-tyxml-spec-409)
  (alias omd-tyxml-spec-412)
  (alias omd-tyxml-spec-413)
  (alias omd-tyxml-spec-417)
  (alias omd-tyxml-spec-418)
  (alias omd-tyxml-spec-419)
  (alias omd-tyxml-spec-420)
  (alias omd-tyxml-spec-421)
  (alias omd-tyxml-spec-422)
  (alias omd-tyxml-spec-423)
  (alias omd-tyxml-spec-424)
  (alias omd-tyxml-spec-425)
  (alias omd-tyxml-spec-426)
  (alias omd-tyxml-spec-427)
  (alias omd-tyxml-spec-429)
  (alias omd-tyxml-spec-430)
  (alias omd-tyxml-spec-431)
  (alias omd-tyxml-spec-432)
  (alias omd-tyxml-spec-433)
  (alias omd-tyxml-spec-434)
  (alias omd-tyxml-spec-435)
  (alias omd-tyxml-spec-436)
  (alias omd-tyxml-spec-437)
  (alias omd-tyxml-spec-438)
  (alias omd-tyxml-spec-439)
  (alias omd-tyxml-spec-440)
  (alias omd-tyxml-spec-441)
  (alias omd-tyxml-spec-442)
  (alias omd-tyxml-spec-443)
  (alias omd-tyxml-spec-444)
  (alias omd-tyxml-spec-445)
  (alias omd-tyxml-spec-446)
  (alias omd-tyxml-spec-447)
  (alias omd-tyxml-spec-448)
  (alias omd-tyxml-spec-449)
  (alias omd-tyxml-spec-450)
  (alias omd-tyxml-spec-451)
  (alias omd-tyxml-spec-452)
  (alias omd-tyxml-spec-453)
  (alias omd-tyxml-spec-454)
  (alias omd-tyxml-spec-455)
  (alias omd-tyxml-spec-456)
  (alias omd-tyxml-spec-457)
  (alias omd-tyxml-spec-458)
  (alias omd-tyxml-spec-459)
  (alias omd-tyxml-spec-460)
  (alias omd-tyxml-spec-461)
  (alias omd-tyxml-spec-462)
  (alias omd-tyxml-spec-463)
  (alias omd-tyxml-spec-464)
  (alias omd-tyxml-spec-465)
  (alias omd-tyxml-spec-466)
  (alias omd-tyxml-spec-467)
  (alias omd-tyxml-spec-470)
  (alias omd-tyxml-spec-471)
  (alias omd-tyxml-spec-472)
  (alias omd-tyxml-spec-473)
  (alias omd-tyxml-spec-474)
  (alias omd-tyxml-spec-475)
  (alias omd-tyxml-spec-476)
  (alias omd-tyxml-spec-477)
  (alias omd-tyxml-spec-478)
  (alias omd-tyxml-spec-479)
  (alias omd-tyxml-spec-480)
  (alias omd-tyxml-spec-481)
  (alias omd-tyxml-spec-482)
  (alias omd-tyxml-spec-483)
  (alias omd-tyxml-spec-484)
  (alias omd-tyxml-spec-485)
  (alias omd-tyxml-spec-487)
  (alias omd-tyxml-spec-488)
  (alias omd-tyxml-spec-489)
  (alias omd-tyxml-spec-490)
  (alias omd-tyxml-spec-491)
  (alias omd-tyxml-spec-492)
  (alias omd-tyxml-spec-493)
  (alias omd-tyxml-spec-494)
  (alias omd-tyxml-spec-495)
  (alias omd-tyxml-spec-496)
  (alias omd-tyxml-spec-497)
  (alias omd-tyxml-spec-498)
  (alias omd-tyxml-spec-499)
  (alias omd-tyxml-spec-500)
  (alias omd-tyxml-spec-501)
  (alias omd-tyxml-spec-502)
  (alias omd-tyxml-spec-503)
  (alias omd-tyxml-spec-504)
  (alias omd-tyxml-spec-505)
  (alias omd-tyxml-spec-506)
  (alias omd-tyxml-spec-507)
  (alias omd-tyxml-spec-508)
  (alias omd-tyxml-spec-509)
  (alias omd-tyxml-spec-510)
  (alias omd-tyxml-spec-511)
  (alias omd-tyxml-spec-512)
  (alias omd-tyxml-spec-513)
  (alias omd-tyxml-spec-514)
  (alias omd-tyxml-spec-515)
  (alias omd-tyxml-spec-517)
  (alias omd-tyxml-spec-518)
  (alias omd-tyxml-spec-520)
  (alias omd-tyxml-spec-521)
  (alias omd-tyxml-spec-522)
  (alias omd-tyxml-spec-523)
  (alias omd-tyxml-spec-524)
  (alias omd-tyxml-spec-525)
  (alias omd-tyxml-spec-526)
  (alias omd-tyxml-spec-527)
  (alias omd-tyxml-spec-528)
  (alias omd-tyxml-spec-529)
  (alias omd-tyxml-spec-530)
  (alias omd-tyxml-spec-531)
  (alias omd-tyxml-spec-532)
  (alias omd-tyxml-spec-533)
  (alias omd-tyxml-spec-534)
  (alias omd-tyxml-spec-535)
  (alias omd-tyxml-spec-537)
  (alias omd-tyxml-spec-538)
  (alias omd-tyxml-spec-539)
  (alias omd-tyxml-spec-540)
  (alias omd-tyxml-spec-541)
  (alias omd-tyxml-spec-542)
  (alias omd-tyxml-spec-543)
  (alias omd-tyxml-spec-544)
  (alias omd-tyxml-spec-545)
  (alias omd-tyxml-spec-546)
  (alias omd-tyxml-spec-547)
  (alias omd-tyxml-spec-548)
  (alias omd-tyxml-spec-549)
  (alias omd-tyxml-spec-550)
  (alias omd-tyxml-spec-551)
  (alias omd-tyxml-spec-552)
  (alias omd-tyxml-spec-553)
  (alias omd-tyxml-spec-554)
  (alias omd-tyxml-spec-555)
  (alias omd-tyxml-spec-556)
  (alias omd-tyxml-spec-557)
  (alias omd-tyxml-spec-558)
  (alias omd-tyxml-spec-559)
  (alias omd-tyxml-spec-560)
  (alias omd-tyxml-spec-561)
  (alias omd-tyxml-spec-562)
  (alias omd-tyxml-spec-563)
  (alias omd-tyxml-spec-564)
  (alias omd-tyxml-spec-565)
  (alias omd-tyxml-spec-566)
  (alias omd-tyxml-spec-567)
  (alias omd-tyxml-spec-568)
  (alias omd-tyxml-spec-569)
  (alias omd-tyxml-spec-571)
  (alias omd-tyxml-spec-572)
  (alias omd-tyxml-spec-573)
  (alias omd-tyxml-spec-574)
  (alias omd-tyxml-spec-575)
  (alias omd-tyxml-spec-576)
  (alias omd-tyxml-spec-577)
  (alias omd-tyxml-spec-578)
  (alias omd-tyxml-spec-579)
  (alias omd-tyxml-spec-580)
  (alias omd-tyxml-spec-581)
  (alias omd-tyxml-spec-582)
  (alias omd-tyxml-spec-583)
  (alias omd-tyxml-spec-584)
  (alias omd-tyxml-spec-585)
  (alias omd-tyxml-spec-586)
  (alias omd-tyxml-spec-587)
  (alias omd-tyxml-spec-588)
  (alias omd-tyxml-spec-589)
  (alias omd-tyxml-spec-590)
  (alias omd-tyxml-spec-592)
  (alias omd-tyxml-spec-593)
  (alias omd-tyxml-spec-594)
  (alias omd-tyxml-spec-595)
  (alias omd-tyxml-spec-596)
  (alias omd-tyxml-spec-597)
  (alias omd-tyxml-spec-598)
  (alias omd-tyxml-spec-599)
  (alias omd-tyxml-spec-600)
  (alias omd-tyxml-spec-601)
  (alias omd-tyxml-spec-602)
  (alias omd-tyxml-spec-603)
  (alias omd-tyxml-spec-604)
  (alias omd-tyxml-spec-605)
  (alias omd-tyxml-spec-606)
  (alias omd-tyxml-spec-607)
  (alias omd-tyxml-spec-608)
  (alias omd-tyxml-spec-609)
  (alias omd-tyxml-spec-610)
  (alias omd-tyxml-spec-611)
  (alias omd-tyxml-spec-612)
  (alias omd-tyxml-spec-613)
  (alias omd-tyxml-spec-614)
  (alias omd-tyxml-spec-615)
  (alias omd-tyxml-spec-616)
  (alias omd-tyxml-spec-617)
  (alias omd-tyxml-spec-618)
  (alias omd-tyxml-spec-619)
  (alias omd-tyxml-spec-620)
  (alias omd-tyxml-spec-621)
  (alias omd-tyxml-spec-622)
  (alias omd-tyxml-spec-623)
  (alias omd-tyxml-spec-624)
  (alias omd-tyxml-spec-625)
  (alias omd-tyxml-spec-626)
  (alias omd-tyxml-spec-627)
  (alias omd-tyxml-spec-628)
  (alias omd-tyxml-spec-629)
  (alias omd-tyxml-spec-630)
  (alias omd-tyxml-spec-631)
  (alias omd-tyxml-spec-632)
  (alias omd-tyxml-spec-633)
  (alias omd-tyxml-spec-634)
  (alias omd-tyxml-spec-635)
  (alias omd-tyxml-spec-636)
  (alias omd-tyxml-spec-637)
  (alias omd-tyxml-spec-638)
  (alias omd-tyxml-spec-639)
  (alias omd-tyxml-spec-640)
  (alias omd-tyxml-spec-641)
  (alias omd-tyxml-spec-642)
  (alias omd-tyxml-spec-643)
  (alias omd-tyxml-spec-644)
  (alias omd-tyxml-spec-645)
  (alias omd-tyxml-spec-646)
  (alias omd-tyxml-spec-647)
  (alias omd-tyxml-spec-648)
  (alias omd-tyxml-spec-649)))
