(rule
 (deps spec.txt attributes.md def_list.md)
 (targets
  spec-001.md spec-001.html
  spec-002.md spec-002.html
  spec-003.md spec-003.html
  spec-004.md spec-004.html
  spec-005.md spec-005.html
  spec-006.md spec-006.html
  spec-007.md spec-007.html
  spec-008.md spec-008.html
  spec-009.md spec-009.html
  spec-010.md spec-010.html
  spec-011.md spec-011.html
  spec-012.md spec-012.html
  spec-013.md spec-013.html
  spec-014.md spec-014.html
  spec-015.md spec-015.html
  spec-016.md spec-016.html
  spec-017.md spec-017.html
  spec-018.md spec-018.html
  spec-019.md spec-019.html
  spec-020.md spec-020.html
  spec-021.md spec-021.html
  spec-022.md spec-022.html
  spec-023.md spec-023.html
  spec-024.md spec-024.html
  spec-025.md spec-025.html
  spec-026.md spec-026.html
  spec-027.md spec-027.html
  spec-028.md spec-028.html
  spec-029.md spec-029.html
  spec-030.md spec-030.html
  spec-031.md spec-031.html
  spec-032.md spec-032.html
  spec-033.md spec-033.html
  spec-034.md spec-034.html
  spec-035.md spec-035.html
  spec-036.md spec-036.html
  spec-037.md spec-037.html
  spec-038.md spec-038.html
  spec-039.md spec-039.html
  spec-040.md spec-040.html
  spec-041.md spec-041.html
  spec-042.md spec-042.html
  spec-043.md spec-043.html
  spec-044.md spec-044.html
  spec-045.md spec-045.html
  spec-046.md spec-046.html
  spec-047.md spec-047.html
  spec-048.md spec-048.html
  spec-049.md spec-049.html
  spec-050.md spec-050.html
  spec-051.md spec-051.html
  spec-052.md spec-052.html
  spec-053.md spec-053.html
  spec-054.md spec-054.html
  spec-055.md spec-055.html
  spec-056.md spec-056.html
  spec-057.md spec-057.html
  spec-058.md spec-058.html
  spec-059.md spec-059.html
  spec-060.md spec-060.html
  spec-061.md spec-061.html
  spec-062.md spec-062.html
  spec-063.md spec-063.html
  spec-064.md spec-064.html
  spec-065.md spec-065.html
  spec-066.md spec-066.html
  spec-067.md spec-067.html
  spec-068.md spec-068.html
  spec-069.md spec-069.html
  spec-070.md spec-070.html
  spec-071.md spec-071.html
  spec-072.md spec-072.html
  spec-073.md spec-073.html
  spec-074.md spec-074.html
  spec-075.md spec-075.html
  spec-076.md spec-076.html
  spec-077.md spec-077.html
  spec-078.md spec-078.html
  spec-079.md spec-079.html
  spec-080.md spec-080.html
  spec-081.md spec-081.html
  spec-082.md spec-082.html
  spec-083.md spec-083.html
  spec-084.md spec-084.html
  spec-085.md spec-085.html
  spec-086.md spec-086.html
  spec-087.md spec-087.html
  spec-088.md spec-088.html
  spec-089.md spec-089.html
  spec-090.md spec-090.html
  spec-091.md spec-091.html
  spec-092.md spec-092.html
  spec-093.md spec-093.html
  spec-094.md spec-094.html
  spec-095.md spec-095.html
  spec-096.md spec-096.html
  spec-097.md spec-097.html
  spec-098.md spec-098.html
  spec-099.md spec-099.html
  spec-100.md spec-100.html
  spec-101.md spec-101.html
  spec-102.md spec-102.html
  spec-103.md spec-103.html
  spec-104.md spec-104.html
  spec-105.md spec-105.html
  spec-106.md spec-106.html
  spec-107.md spec-107.html
  spec-108.md spec-108.html
  spec-109.md spec-109.html
  spec-110.md spec-110.html
  spec-111.md spec-111.html
  spec-112.md spec-112.html
  spec-113.md spec-113.html
  spec-114.md spec-114.html
  spec-115.md spec-115.html
  spec-116.md spec-116.html
  spec-117.md spec-117.html
  spec-118.md spec-118.html
  spec-119.md spec-119.html
  spec-120.md spec-120.html
  spec-121.md spec-121.html
  spec-122.md spec-122.html
  spec-123.md spec-123.html
  spec-124.md spec-124.html
  spec-125.md spec-125.html
  spec-126.md spec-126.html
  spec-127.md spec-127.html
  spec-128.md spec-128.html
  spec-129.md spec-129.html
  spec-130.md spec-130.html
  spec-131.md spec-131.html
  spec-132.md spec-132.html
  spec-133.md spec-133.html
  spec-134.md spec-134.html
  spec-135.md spec-135.html
  spec-136.md spec-136.html
  spec-137.md spec-137.html
  spec-138.md spec-138.html
  spec-139.md spec-139.html
  spec-140.md spec-140.html
  spec-141.md spec-141.html
  spec-142.md spec-142.html
  spec-143.md spec-143.html
  spec-144.md spec-144.html
  spec-145.md spec-145.html
  spec-146.md spec-146.html
  spec-147.md spec-147.html
  spec-148.md spec-148.html
  spec-149.md spec-149.html
  spec-150.md spec-150.html
  spec-151.md spec-151.html
  spec-152.md spec-152.html
  spec-153.md spec-153.html
  spec-154.md spec-154.html
  spec-155.md spec-155.html
  spec-156.md spec-156.html
  spec-157.md spec-157.html
  spec-158.md spec-158.html
  spec-159.md spec-159.html
  spec-160.md spec-160.html
  spec-161.md spec-161.html
  spec-162.md spec-162.html
  spec-163.md spec-163.html
  spec-164.md spec-164.html
  spec-165.md spec-165.html
  spec-166.md spec-166.html
  spec-167.md spec-167.html
  spec-168.md spec-168.html
  spec-169.md spec-169.html
  spec-170.md spec-170.html
  spec-171.md spec-171.html
  spec-172.md spec-172.html
  spec-173.md spec-173.html
  spec-174.md spec-174.html
  spec-175.md spec-175.html
  spec-176.md spec-176.html
  spec-177.md spec-177.html
  spec-178.md spec-178.html
  spec-179.md spec-179.html
  spec-180.md spec-180.html
  spec-181.md spec-181.html
  spec-182.md spec-182.html
  spec-183.md spec-183.html
  spec-184.md spec-184.html
  spec-185.md spec-185.html
  spec-186.md spec-186.html
  spec-187.md spec-187.html
  spec-188.md spec-188.html
  spec-189.md spec-189.html
  spec-190.md spec-190.html
  spec-191.md spec-191.html
  spec-192.md spec-192.html
  spec-193.md spec-193.html
  spec-194.md spec-194.html
  spec-195.md spec-195.html
  spec-196.md spec-196.html
  spec-197.md spec-197.html
  spec-198.md spec-198.html
  spec-199.md spec-199.html
  spec-200.md spec-200.html
  spec-201.md spec-201.html
  spec-202.md spec-202.html
  spec-203.md spec-203.html
  spec-204.md spec-204.html
  spec-205.md spec-205.html
  spec-206.md spec-206.html
  spec-207.md spec-207.html
  spec-208.md spec-208.html
  spec-209.md spec-209.html
  spec-210.md spec-210.html
  spec-211.md spec-211.html
  spec-212.md spec-212.html
  spec-213.md spec-213.html
  spec-214.md spec-214.html
  spec-215.md spec-215.html
  spec-216.md spec-216.html
  spec-217.md spec-217.html
  spec-218.md spec-218.html
  spec-219.md spec-219.html
  spec-220.md spec-220.html
  spec-221.md spec-221.html
  spec-222.md spec-222.html
  spec-223.md spec-223.html
  spec-224.md spec-224.html
  spec-225.md spec-225.html
  spec-226.md spec-226.html
  spec-227.md spec-227.html
  spec-228.md spec-228.html
  spec-229.md spec-229.html
  spec-230.md spec-230.html
  spec-231.md spec-231.html
  spec-232.md spec-232.html
  spec-233.md spec-233.html
  spec-234.md spec-234.html
  spec-235.md spec-235.html
  spec-236.md spec-236.html
  spec-237.md spec-237.html
  spec-238.md spec-238.html
  spec-239.md spec-239.html
  spec-240.md spec-240.html
  spec-241.md spec-241.html
  spec-242.md spec-242.html
  spec-243.md spec-243.html
  spec-244.md spec-244.html
  spec-245.md spec-245.html
  spec-246.md spec-246.html
  spec-247.md spec-247.html
  spec-248.md spec-248.html
  spec-249.md spec-249.html
  spec-250.md spec-250.html
  spec-251.md spec-251.html
  spec-252.md spec-252.html
  spec-253.md spec-253.html
  spec-254.md spec-254.html
  spec-255.md spec-255.html
  spec-256.md spec-256.html
  spec-257.md spec-257.html
  spec-258.md spec-258.html
  spec-259.md spec-259.html
  spec-260.md spec-260.html
  spec-261.md spec-261.html
  spec-262.md spec-262.html
  spec-263.md spec-263.html
  spec-264.md spec-264.html
  spec-265.md spec-265.html
  spec-266.md spec-266.html
  spec-267.md spec-267.html
  spec-268.md spec-268.html
  spec-269.md spec-269.html
  spec-270.md spec-270.html
  spec-271.md spec-271.html
  spec-272.md spec-272.html
  spec-273.md spec-273.html
  spec-274.md spec-274.html
  spec-275.md spec-275.html
  spec-276.md spec-276.html
  spec-277.md spec-277.html
  spec-278.md spec-278.html
  spec-279.md spec-279.html
  spec-280.md spec-280.html
  spec-281.md spec-281.html
  spec-282.md spec-282.html
  spec-283.md spec-283.html
  spec-284.md spec-284.html
  spec-285.md spec-285.html
  spec-286.md spec-286.html
  spec-287.md spec-287.html
  spec-288.md spec-288.html
  spec-289.md spec-289.html
  spec-290.md spec-290.html
  spec-291.md spec-291.html
  spec-292.md spec-292.html
  spec-293.md spec-293.html
  spec-294.md spec-294.html
  spec-295.md spec-295.html
  spec-296.md spec-296.html
  spec-297.md spec-297.html
  spec-298.md spec-298.html
  spec-299.md spec-299.html
  spec-300.md spec-300.html
  spec-301.md spec-301.html
  spec-302.md spec-302.html
  spec-303.md spec-303.html
  spec-304.md spec-304.html
  spec-305.md spec-305.html
  spec-306.md spec-306.html
  spec-307.md spec-307.html
  spec-308.md spec-308.html
  spec-309.md spec-309.html
  spec-310.md spec-310.html
  spec-311.md spec-311.html
  spec-312.md spec-312.html
  spec-313.md spec-313.html
  spec-314.md spec-314.html
  spec-315.md spec-315.html
  spec-316.md spec-316.html
  spec-317.md spec-317.html
  spec-318.md spec-318.html
  spec-319.md spec-319.html
  spec-320.md spec-320.html
  spec-321.md spec-321.html
  spec-322.md spec-322.html
  spec-323.md spec-323.html
  spec-324.md spec-324.html
  spec-325.md spec-325.html
  spec-326.md spec-326.html
  spec-327.md spec-327.html
  spec-328.md spec-328.html
  spec-329.md spec-329.html
  spec-330.md spec-330.html
  spec-331.md spec-331.html
  spec-332.md spec-332.html
  spec-333.md spec-333.html
  spec-334.md spec-334.html
  spec-335.md spec-335.html
  spec-336.md spec-336.html
  spec-337.md spec-337.html
  spec-338.md spec-338.html
  spec-339.md spec-339.html
  spec-340.md spec-340.html
  spec-341.md spec-341.html
  spec-342.md spec-342.html
  spec-343.md spec-343.html
  spec-344.md spec-344.html
  spec-345.md spec-345.html
  spec-346.md spec-346.html
  spec-347.md spec-347.html
  spec-348.md spec-348.html
  spec-349.md spec-349.html
  spec-350.md spec-350.html
  spec-351.md spec-351.html
  spec-352.md spec-352.html
  spec-353.md spec-353.html
  spec-354.md spec-354.html
  spec-355.md spec-355.html
  spec-356.md spec-356.html
  spec-357.md spec-357.html
  spec-358.md spec-358.html
  spec-359.md spec-359.html
  spec-360.md spec-360.html
  spec-361.md spec-361.html
  spec-362.md spec-362.html
  spec-363.md spec-363.html
  spec-364.md spec-364.html
  spec-365.md spec-365.html
  spec-366.md spec-366.html
  spec-367.md spec-367.html
  spec-368.md spec-368.html
  spec-369.md spec-369.html
  spec-370.md spec-370.html
  spec-371.md spec-371.html
  spec-372.md spec-372.html
  spec-373.md spec-373.html
  spec-374.md spec-374.html
  spec-375.md spec-375.html
  spec-376.md spec-376.html
  spec-377.md spec-377.html
  spec-378.md spec-378.html
  spec-379.md spec-379.html
  spec-380.md spec-380.html
  spec-381.md spec-381.html
  spec-382.md spec-382.html
  spec-383.md spec-383.html
  spec-384.md spec-384.html
  spec-385.md spec-385.html
  spec-386.md spec-386.html
  spec-387.md spec-387.html
  spec-388.md spec-388.html
  spec-389.md spec-389.html
  spec-390.md spec-390.html
  spec-391.md spec-391.html
  spec-392.md spec-392.html
  spec-393.md spec-393.html
  spec-394.md spec-394.html
  spec-395.md spec-395.html
  spec-396.md spec-396.html
  spec-397.md spec-397.html
  spec-398.md spec-398.html
  spec-399.md spec-399.html
  spec-400.md spec-400.html
  spec-401.md spec-401.html
  spec-402.md spec-402.html
  spec-403.md spec-403.html
  spec-404.md spec-404.html
  spec-405.md spec-405.html
  spec-406.md spec-406.html
  spec-407.md spec-407.html
  spec-408.md spec-408.html
  spec-409.md spec-409.html
  spec-410.md spec-410.html
  spec-411.md spec-411.html
  spec-412.md spec-412.html
  spec-413.md spec-413.html
  spec-414.md spec-414.html
  spec-415.md spec-415.html
  spec-416.md spec-416.html
  spec-417.md spec-417.html
  spec-418.md spec-418.html
  spec-419.md spec-419.html
  spec-420.md spec-420.html
  spec-421.md spec-421.html
  spec-422.md spec-422.html
  spec-423.md spec-423.html
  spec-424.md spec-424.html
  spec-425.md spec-425.html
  spec-426.md spec-426.html
  spec-427.md spec-427.html
  spec-428.md spec-428.html
  spec-429.md spec-429.html
  spec-430.md spec-430.html
  spec-431.md spec-431.html
  spec-432.md spec-432.html
  spec-433.md spec-433.html
  spec-434.md spec-434.html
  spec-435.md spec-435.html
  spec-436.md spec-436.html
  spec-437.md spec-437.html
  spec-438.md spec-438.html
  spec-439.md spec-439.html
  spec-440.md spec-440.html
  spec-441.md spec-441.html
  spec-442.md spec-442.html
  spec-443.md spec-443.html
  spec-444.md spec-444.html
  spec-445.md spec-445.html
  spec-446.md spec-446.html
  spec-447.md spec-447.html
  spec-448.md spec-448.html
  spec-449.md spec-449.html
  spec-450.md spec-450.html
  spec-451.md spec-451.html
  spec-452.md spec-452.html
  spec-453.md spec-453.html
  spec-454.md spec-454.html
  spec-455.md spec-455.html
  spec-456.md spec-456.html
  spec-457.md spec-457.html
  spec-458.md spec-458.html
  spec-459.md spec-459.html
  spec-460.md spec-460.html
  spec-461.md spec-461.html
  spec-462.md spec-462.html
  spec-463.md spec-463.html
  spec-464.md spec-464.html
  spec-465.md spec-465.html
  spec-466.md spec-466.html
  spec-467.md spec-467.html
  spec-468.md spec-468.html
  spec-469.md spec-469.html
  spec-470.md spec-470.html
  spec-471.md spec-471.html
  spec-472.md spec-472.html
  spec-473.md spec-473.html
  spec-474.md spec-474.html
  spec-475.md spec-475.html
  spec-476.md spec-476.html
  spec-477.md spec-477.html
  spec-478.md spec-478.html
  spec-479.md spec-479.html
  spec-480.md spec-480.html
  spec-481.md spec-481.html
  spec-482.md spec-482.html
  spec-483.md spec-483.html
  spec-484.md spec-484.html
  spec-485.md spec-485.html
  spec-486.md spec-486.html
  spec-487.md spec-487.html
  spec-488.md spec-488.html
  spec-489.md spec-489.html
  spec-490.md spec-490.html
  spec-491.md spec-491.html
  spec-492.md spec-492.html
  spec-493.md spec-493.html
  spec-494.md spec-494.html
  spec-495.md spec-495.html
  spec-496.md spec-496.html
  spec-497.md spec-497.html
  spec-498.md spec-498.html
  spec-499.md spec-499.html
  spec-500.md spec-500.html
  spec-501.md spec-501.html
  spec-502.md spec-502.html
  spec-503.md spec-503.html
  spec-504.md spec-504.html
  spec-505.md spec-505.html
  spec-506.md spec-506.html
  spec-507.md spec-507.html
  spec-508.md spec-508.html
  spec-509.md spec-509.html
  spec-510.md spec-510.html
  spec-511.md spec-511.html
  spec-512.md spec-512.html
  spec-513.md spec-513.html
  spec-514.md spec-514.html
  spec-515.md spec-515.html
  spec-516.md spec-516.html
  spec-517.md spec-517.html
  spec-518.md spec-518.html
  spec-519.md spec-519.html
  spec-520.md spec-520.html
  spec-521.md spec-521.html
  spec-522.md spec-522.html
  spec-523.md spec-523.html
  spec-524.md spec-524.html
  spec-525.md spec-525.html
  spec-526.md spec-526.html
  spec-527.md spec-527.html
  spec-528.md spec-528.html
  spec-529.md spec-529.html
  spec-530.md spec-530.html
  spec-531.md spec-531.html
  spec-532.md spec-532.html
  spec-533.md spec-533.html
  spec-534.md spec-534.html
  spec-535.md spec-535.html
  spec-536.md spec-536.html
  spec-537.md spec-537.html
  spec-538.md spec-538.html
  spec-539.md spec-539.html
  spec-540.md spec-540.html
  spec-541.md spec-541.html
  spec-542.md spec-542.html
  spec-543.md spec-543.html
  spec-544.md spec-544.html
  spec-545.md spec-545.html
  spec-546.md spec-546.html
  spec-547.md spec-547.html
  spec-548.md spec-548.html
  spec-549.md spec-549.html
  spec-550.md spec-550.html
  spec-551.md spec-551.html
  spec-552.md spec-552.html
  spec-553.md spec-553.html
  spec-554.md spec-554.html
  spec-555.md spec-555.html
  spec-556.md spec-556.html
  spec-557.md spec-557.html
  spec-558.md spec-558.html
  spec-559.md spec-559.html
  spec-560.md spec-560.html
  spec-561.md spec-561.html
  spec-562.md spec-562.html
  spec-563.md spec-563.html
  spec-564.md spec-564.html
  spec-565.md spec-565.html
  spec-566.md spec-566.html
  spec-567.md spec-567.html
  spec-568.md spec-568.html
  spec-569.md spec-569.html
  spec-570.md spec-570.html
  spec-571.md spec-571.html
  spec-572.md spec-572.html
  spec-573.md spec-573.html
  spec-574.md spec-574.html
  spec-575.md spec-575.html
  spec-576.md spec-576.html
  spec-577.md spec-577.html
  spec-578.md spec-578.html
  spec-579.md spec-579.html
  spec-580.md spec-580.html
  spec-581.md spec-581.html
  spec-582.md spec-582.html
  spec-583.md spec-583.html
  spec-584.md spec-584.html
  spec-585.md spec-585.html
  spec-586.md spec-586.html
  spec-587.md spec-587.html
  spec-588.md spec-588.html
  spec-589.md spec-589.html
  spec-590.md spec-590.html
  spec-591.md spec-591.html
  spec-592.md spec-592.html
  spec-593.md spec-593.html
  spec-594.md spec-594.html
  spec-595.md spec-595.html
  spec-596.md spec-596.html
  spec-597.md spec-597.html
  spec-598.md spec-598.html
  spec-599.md spec-599.html
  spec-600.md spec-600.html
  spec-601.md spec-601.html
  spec-602.md spec-602.html
  spec-603.md spec-603.html
  spec-604.md spec-604.html
  spec-605.md spec-605.html
  spec-606.md spec-606.html
  spec-607.md spec-607.html
  spec-608.md spec-608.html
  spec-609.md spec-609.html
  spec-610.md spec-610.html
  spec-611.md spec-611.html
  spec-612.md spec-612.html
  spec-613.md spec-613.html
  spec-614.md spec-614.html
  spec-615.md spec-615.html
  spec-616.md spec-616.html
  spec-617.md spec-617.html
  spec-618.md spec-618.html
  spec-619.md spec-619.html
  spec-620.md spec-620.html
  spec-621.md spec-621.html
  spec-622.md spec-622.html
  spec-623.md spec-623.html
  spec-624.md spec-624.html
  spec-625.md spec-625.html
  spec-626.md spec-626.html
  spec-627.md spec-627.html
  spec-628.md spec-628.html
  spec-629.md spec-629.html
  spec-630.md spec-630.html
  spec-631.md spec-631.html
  spec-632.md spec-632.html
  spec-633.md spec-633.html
  spec-634.md spec-634.html
  spec-635.md spec-635.html
  spec-636.md spec-636.html
  spec-637.md spec-637.html
  spec-638.md spec-638.html
  spec-639.md spec-639.html
  spec-640.md spec-640.html
  spec-641.md spec-641.html
  spec-642.md spec-642.html
  spec-643.md spec-643.html
  spec-644.md spec-644.html
  spec-645.md spec-645.html
  spec-646.md spec-646.html
  spec-647.md spec-647.html
  spec-648.md spec-648.html
  spec-649.md spec-649.html
  spec-650.md spec-650.html
  spec-651.md spec-651.html
  spec-652.md spec-652.html
  attributes-001.md attributes-001.html
  attributes-002.md attributes-002.html
  attributes-003.md attributes-003.html
  attributes-004.md attributes-004.html
  attributes-005.md attributes-005.html
  attributes-006.md attributes-006.html
  attributes-007.md attributes-007.html
  attributes-008.md attributes-008.html
  attributes-009.md attributes-009.html
  attributes-010.md attributes-010.html
  attributes-011.md attributes-011.html
  attributes-012.md attributes-012.html
  attributes-013.md attributes-013.html
  attributes-014.md attributes-014.html
  attributes-015.md attributes-015.html
  def_list-001.md def_list-001.html)
 (action (run ./extract_tests.exe -generate-test-files %{deps})))
(rule
 (action
  (with-stdout-to spec-001.html.new (run ./omd.exe %{dep:spec-001.md}))))
(rule
 (alias spec-001)
 (action (diff spec-001.html spec-001.html.new)))
(rule
 (action
  (with-stdout-to spec-002.html.new (run ./omd.exe %{dep:spec-002.md}))))
(rule
 (alias spec-002)
 (action (diff spec-002.html spec-002.html.new)))
(rule
 (action
  (with-stdout-to spec-003.html.new (run ./omd.exe %{dep:spec-003.md}))))
(rule
 (alias spec-003)
 (action (diff spec-003.html spec-003.html.new)))
(rule
 (action
  (with-stdout-to spec-004.html.new (run ./omd.exe %{dep:spec-004.md}))))
(rule
 (alias spec-004)
 (action (diff spec-004.html spec-004.html.new)))
(rule
 (action
  (with-stdout-to spec-005.html.new (run ./omd.exe %{dep:spec-005.md}))))
(rule
 (alias spec-005)
 (action (diff spec-005.html spec-005.html.new)))
(rule
 (action
  (with-stdout-to spec-006.html.new (run ./omd.exe %{dep:spec-006.md}))))
(rule
 (alias spec-006)
 (action (diff spec-006.html spec-006.html.new)))
(rule
 (action
  (with-stdout-to spec-007.html.new (run ./omd.exe %{dep:spec-007.md}))))
(rule
 (alias spec-007)
 (action (diff spec-007.html spec-007.html.new)))
(rule
 (action
  (with-stdout-to spec-008.html.new (run ./omd.exe %{dep:spec-008.md}))))
(rule
 (alias spec-008)
 (action (diff spec-008.html spec-008.html.new)))
(rule
 (action
  (with-stdout-to spec-009.html.new (run ./omd.exe %{dep:spec-009.md}))))
(rule
 (alias spec-009)
 (action (diff spec-009.html spec-009.html.new)))
(rule
 (action
  (with-stdout-to spec-010.html.new (run ./omd.exe %{dep:spec-010.md}))))
(rule
 (alias spec-010)
 (action (diff spec-010.html spec-010.html.new)))
(rule
 (action
  (with-stdout-to spec-011.html.new (run ./omd.exe %{dep:spec-011.md}))))
(rule
 (alias spec-011)
 (action (diff spec-011.html spec-011.html.new)))
(rule
 (action
  (with-stdout-to spec-012.html.new (run ./omd.exe %{dep:spec-012.md}))))
(rule
 (alias spec-012)
 (action (diff spec-012.html spec-012.html.new)))
(rule
 (action
  (with-stdout-to spec-013.html.new (run ./omd.exe %{dep:spec-013.md}))))
(rule
 (alias spec-013)
 (action (diff spec-013.html spec-013.html.new)))
(rule
 (action
  (with-stdout-to spec-014.html.new (run ./omd.exe %{dep:spec-014.md}))))
(rule
 (alias spec-014)
 (action (diff spec-014.html spec-014.html.new)))
(rule
 (action
  (with-stdout-to spec-015.html.new (run ./omd.exe %{dep:spec-015.md}))))
(rule
 (alias spec-015)
 (action (diff spec-015.html spec-015.html.new)))
(rule
 (action
  (with-stdout-to spec-016.html.new (run ./omd.exe %{dep:spec-016.md}))))
(rule
 (alias spec-016)
 (action (diff spec-016.html spec-016.html.new)))
(rule
 (action
  (with-stdout-to spec-017.html.new (run ./omd.exe %{dep:spec-017.md}))))
(rule
 (alias spec-017)
 (action (diff spec-017.html spec-017.html.new)))
(rule
 (action
  (with-stdout-to spec-018.html.new (run ./omd.exe %{dep:spec-018.md}))))
(rule
 (alias spec-018)
 (action (diff spec-018.html spec-018.html.new)))
(rule
 (action
  (with-stdout-to spec-019.html.new (run ./omd.exe %{dep:spec-019.md}))))
(rule
 (alias spec-019)
 (action (diff spec-019.html spec-019.html.new)))
(rule
 (action
  (with-stdout-to spec-020.html.new (run ./omd.exe %{dep:spec-020.md}))))
(rule
 (alias spec-020)
 (action (diff spec-020.html spec-020.html.new)))
(rule
 (action
  (with-stdout-to spec-021.html.new (run ./omd.exe %{dep:spec-021.md}))))
(rule
 (alias spec-021)
 (action (diff spec-021.html spec-021.html.new)))
(rule
 (action
  (with-stdout-to spec-022.html.new (run ./omd.exe %{dep:spec-022.md}))))
(rule
 (alias spec-022)
 (action (diff spec-022.html spec-022.html.new)))
(rule
 (action
  (with-stdout-to spec-023.html.new (run ./omd.exe %{dep:spec-023.md}))))
(rule
 (alias spec-023)
 (action (diff spec-023.html spec-023.html.new)))
(rule
 (action
  (with-stdout-to spec-024.html.new (run ./omd.exe %{dep:spec-024.md}))))
(rule
 (alias spec-024)
 (action (diff spec-024.html spec-024.html.new)))
(rule
 (action
  (with-stdout-to spec-025.html.new (run ./omd.exe %{dep:spec-025.md}))))
(rule
 (alias spec-025)
 (action (diff spec-025.html spec-025.html.new)))
(rule
 (action
  (with-stdout-to spec-026.html.new (run ./omd.exe %{dep:spec-026.md}))))
(rule
 (alias spec-026)
 (action (diff spec-026.html spec-026.html.new)))
(rule
 (action
  (with-stdout-to spec-027.html.new (run ./omd.exe %{dep:spec-027.md}))))
(rule
 (alias spec-027)
 (action (diff spec-027.html spec-027.html.new)))
(rule
 (action
  (with-stdout-to spec-028.html.new (run ./omd.exe %{dep:spec-028.md}))))
(rule
 (alias spec-028)
 (action (diff spec-028.html spec-028.html.new)))
(rule
 (action
  (with-stdout-to spec-029.html.new (run ./omd.exe %{dep:spec-029.md}))))
(rule
 (alias spec-029)
 (action (diff spec-029.html spec-029.html.new)))
(rule
 (action
  (with-stdout-to spec-030.html.new (run ./omd.exe %{dep:spec-030.md}))))
(rule
 (alias spec-030)
 (action (diff spec-030.html spec-030.html.new)))
(rule
 (action
  (with-stdout-to spec-031.html.new (run ./omd.exe %{dep:spec-031.md}))))
(rule
 (alias spec-031)
 (action (diff spec-031.html spec-031.html.new)))
(rule
 (action
  (with-stdout-to spec-032.html.new (run ./omd.exe %{dep:spec-032.md}))))
(rule
 (alias spec-032)
 (action (diff spec-032.html spec-032.html.new)))
(rule
 (action
  (with-stdout-to spec-033.html.new (run ./omd.exe %{dep:spec-033.md}))))
(rule
 (alias spec-033)
 (action (diff spec-033.html spec-033.html.new)))
(rule
 (action
  (with-stdout-to spec-034.html.new (run ./omd.exe %{dep:spec-034.md}))))
(rule
 (alias spec-034)
 (action (diff spec-034.html spec-034.html.new)))
(rule
 (action
  (with-stdout-to spec-035.html.new (run ./omd.exe %{dep:spec-035.md}))))
(rule
 (alias spec-035)
 (action (diff spec-035.html spec-035.html.new)))
(rule
 (action
  (with-stdout-to spec-036.html.new (run ./omd.exe %{dep:spec-036.md}))))
(rule
 (alias spec-036)
 (action (diff spec-036.html spec-036.html.new)))
(rule
 (action
  (with-stdout-to spec-037.html.new (run ./omd.exe %{dep:spec-037.md}))))
(rule
 (alias spec-037)
 (action (diff spec-037.html spec-037.html.new)))
(rule
 (action
  (with-stdout-to spec-038.html.new (run ./omd.exe %{dep:spec-038.md}))))
(rule
 (alias spec-038)
 (action (diff spec-038.html spec-038.html.new)))
(rule
 (action
  (with-stdout-to spec-039.html.new (run ./omd.exe %{dep:spec-039.md}))))
(rule
 (alias spec-039)
 (action (diff spec-039.html spec-039.html.new)))
(rule
 (action
  (with-stdout-to spec-040.html.new (run ./omd.exe %{dep:spec-040.md}))))
(rule
 (alias spec-040)
 (action (diff spec-040.html spec-040.html.new)))
(rule
 (action
  (with-stdout-to spec-041.html.new (run ./omd.exe %{dep:spec-041.md}))))
(rule
 (alias spec-041)
 (action (diff spec-041.html spec-041.html.new)))
(rule
 (action
  (with-stdout-to spec-042.html.new (run ./omd.exe %{dep:spec-042.md}))))
(rule
 (alias spec-042)
 (action (diff spec-042.html spec-042.html.new)))
(rule
 (action
  (with-stdout-to spec-043.html.new (run ./omd.exe %{dep:spec-043.md}))))
(rule
 (alias spec-043)
 (action (diff spec-043.html spec-043.html.new)))
(rule
 (action
  (with-stdout-to spec-044.html.new (run ./omd.exe %{dep:spec-044.md}))))
(rule
 (alias spec-044)
 (action (diff spec-044.html spec-044.html.new)))
(rule
 (action
  (with-stdout-to spec-045.html.new (run ./omd.exe %{dep:spec-045.md}))))
(rule
 (alias spec-045)
 (action (diff spec-045.html spec-045.html.new)))
(rule
 (action
  (with-stdout-to spec-046.html.new (run ./omd.exe %{dep:spec-046.md}))))
(rule
 (alias spec-046)
 (action (diff spec-046.html spec-046.html.new)))
(rule
 (action
  (with-stdout-to spec-047.html.new (run ./omd.exe %{dep:spec-047.md}))))
(rule
 (alias spec-047)
 (action (diff spec-047.html spec-047.html.new)))
(rule
 (action
  (with-stdout-to spec-048.html.new (run ./omd.exe %{dep:spec-048.md}))))
(rule
 (alias spec-048)
 (action (diff spec-048.html spec-048.html.new)))
(rule
 (action
  (with-stdout-to spec-049.html.new (run ./omd.exe %{dep:spec-049.md}))))
(rule
 (alias spec-049)
 (action (diff spec-049.html spec-049.html.new)))
(rule
 (action
  (with-stdout-to spec-050.html.new (run ./omd.exe %{dep:spec-050.md}))))
(rule
 (alias spec-050)
 (action (diff spec-050.html spec-050.html.new)))
(rule
 (action
  (with-stdout-to spec-051.html.new (run ./omd.exe %{dep:spec-051.md}))))
(rule
 (alias spec-051)
 (action (diff spec-051.html spec-051.html.new)))
(rule
 (action
  (with-stdout-to spec-052.html.new (run ./omd.exe %{dep:spec-052.md}))))
(rule
 (alias spec-052)
 (action (diff spec-052.html spec-052.html.new)))
(rule
 (action
  (with-stdout-to spec-053.html.new (run ./omd.exe %{dep:spec-053.md}))))
(rule
 (alias spec-053)
 (action (diff spec-053.html spec-053.html.new)))
(rule
 (action
  (with-stdout-to spec-054.html.new (run ./omd.exe %{dep:spec-054.md}))))
(rule
 (alias spec-054)
 (action (diff spec-054.html spec-054.html.new)))
(rule
 (action
  (with-stdout-to spec-055.html.new (run ./omd.exe %{dep:spec-055.md}))))
(rule
 (alias spec-055)
 (action (diff spec-055.html spec-055.html.new)))
(rule
 (action
  (with-stdout-to spec-056.html.new (run ./omd.exe %{dep:spec-056.md}))))
(rule
 (alias spec-056)
 (action (diff spec-056.html spec-056.html.new)))
(rule
 (action
  (with-stdout-to spec-057.html.new (run ./omd.exe %{dep:spec-057.md}))))
(rule
 (alias spec-057)
 (action (diff spec-057.html spec-057.html.new)))
(rule
 (action
  (with-stdout-to spec-058.html.new (run ./omd.exe %{dep:spec-058.md}))))
(rule
 (alias spec-058)
 (action (diff spec-058.html spec-058.html.new)))
(rule
 (action
  (with-stdout-to spec-059.html.new (run ./omd.exe %{dep:spec-059.md}))))
(rule
 (alias spec-059)
 (action (diff spec-059.html spec-059.html.new)))
(rule
 (action
  (with-stdout-to spec-060.html.new (run ./omd.exe %{dep:spec-060.md}))))
(rule
 (alias spec-060)
 (action (diff spec-060.html spec-060.html.new)))
(rule
 (action
  (with-stdout-to spec-061.html.new (run ./omd.exe %{dep:spec-061.md}))))
(rule
 (alias spec-061)
 (action (diff spec-061.html spec-061.html.new)))
(rule
 (action
  (with-stdout-to spec-062.html.new (run ./omd.exe %{dep:spec-062.md}))))
(rule
 (alias spec-062)
 (action (diff spec-062.html spec-062.html.new)))
(rule
 (action
  (with-stdout-to spec-063.html.new (run ./omd.exe %{dep:spec-063.md}))))
(rule
 (alias spec-063)
 (action (diff spec-063.html spec-063.html.new)))
(rule
 (action
  (with-stdout-to spec-064.html.new (run ./omd.exe %{dep:spec-064.md}))))
(rule
 (alias spec-064)
 (action (diff spec-064.html spec-064.html.new)))
(rule
 (action
  (with-stdout-to spec-065.html.new (run ./omd.exe %{dep:spec-065.md}))))
(rule
 (alias spec-065)
 (action (diff spec-065.html spec-065.html.new)))
(rule
 (action
  (with-stdout-to spec-066.html.new (run ./omd.exe %{dep:spec-066.md}))))
(rule
 (alias spec-066)
 (action (diff spec-066.html spec-066.html.new)))
(rule
 (action
  (with-stdout-to spec-067.html.new (run ./omd.exe %{dep:spec-067.md}))))
(rule
 (alias spec-067)
 (action (diff spec-067.html spec-067.html.new)))
(rule
 (action
  (with-stdout-to spec-068.html.new (run ./omd.exe %{dep:spec-068.md}))))
(rule
 (alias spec-068)
 (action (diff spec-068.html spec-068.html.new)))
(rule
 (action
  (with-stdout-to spec-069.html.new (run ./omd.exe %{dep:spec-069.md}))))
(rule
 (alias spec-069)
 (action (diff spec-069.html spec-069.html.new)))
(rule
 (action
  (with-stdout-to spec-070.html.new (run ./omd.exe %{dep:spec-070.md}))))
(rule
 (alias spec-070)
 (action (diff spec-070.html spec-070.html.new)))
(rule
 (action
  (with-stdout-to spec-071.html.new (run ./omd.exe %{dep:spec-071.md}))))
(rule
 (alias spec-071)
 (action (diff spec-071.html spec-071.html.new)))
(rule
 (action
  (with-stdout-to spec-072.html.new (run ./omd.exe %{dep:spec-072.md}))))
(rule
 (alias spec-072)
 (action (diff spec-072.html spec-072.html.new)))
(rule
 (action
  (with-stdout-to spec-073.html.new (run ./omd.exe %{dep:spec-073.md}))))
(rule
 (alias spec-073)
 (action (diff spec-073.html spec-073.html.new)))
(rule
 (action
  (with-stdout-to spec-074.html.new (run ./omd.exe %{dep:spec-074.md}))))
(rule
 (alias spec-074)
 (action (diff spec-074.html spec-074.html.new)))
(rule
 (action
  (with-stdout-to spec-075.html.new (run ./omd.exe %{dep:spec-075.md}))))
(rule
 (alias spec-075)
 (action (diff spec-075.html spec-075.html.new)))
(rule
 (action
  (with-stdout-to spec-076.html.new (run ./omd.exe %{dep:spec-076.md}))))
(rule
 (alias spec-076)
 (action (diff spec-076.html spec-076.html.new)))
(rule
 (action
  (with-stdout-to spec-077.html.new (run ./omd.exe %{dep:spec-077.md}))))
(rule
 (alias spec-077)
 (action (diff spec-077.html spec-077.html.new)))
(rule
 (action
  (with-stdout-to spec-078.html.new (run ./omd.exe %{dep:spec-078.md}))))
(rule
 (alias spec-078)
 (action (diff spec-078.html spec-078.html.new)))
(rule
 (action
  (with-stdout-to spec-079.html.new (run ./omd.exe %{dep:spec-079.md}))))
(rule
 (alias spec-079)
 (action (diff spec-079.html spec-079.html.new)))
(rule
 (action
  (with-stdout-to spec-080.html.new (run ./omd.exe %{dep:spec-080.md}))))
(rule
 (alias spec-080)
 (action (diff spec-080.html spec-080.html.new)))
(rule
 (action
  (with-stdout-to spec-081.html.new (run ./omd.exe %{dep:spec-081.md}))))
(rule
 (alias spec-081)
 (action (diff spec-081.html spec-081.html.new)))
(rule
 (action
  (with-stdout-to spec-082.html.new (run ./omd.exe %{dep:spec-082.md}))))
(rule
 (alias spec-082)
 (action (diff spec-082.html spec-082.html.new)))
(rule
 (action
  (with-stdout-to spec-083.html.new (run ./omd.exe %{dep:spec-083.md}))))
(rule
 (alias spec-083)
 (action (diff spec-083.html spec-083.html.new)))
(rule
 (action
  (with-stdout-to spec-084.html.new (run ./omd.exe %{dep:spec-084.md}))))
(rule
 (alias spec-084)
 (action (diff spec-084.html spec-084.html.new)))
(rule
 (action
  (with-stdout-to spec-085.html.new (run ./omd.exe %{dep:spec-085.md}))))
(rule
 (alias spec-085)
 (action (diff spec-085.html spec-085.html.new)))
(rule
 (action
  (with-stdout-to spec-086.html.new (run ./omd.exe %{dep:spec-086.md}))))
(rule
 (alias spec-086)
 (action (diff spec-086.html spec-086.html.new)))
(rule
 (action
  (with-stdout-to spec-087.html.new (run ./omd.exe %{dep:spec-087.md}))))
(rule
 (alias spec-087)
 (action (diff spec-087.html spec-087.html.new)))
(rule
 (action
  (with-stdout-to spec-088.html.new (run ./omd.exe %{dep:spec-088.md}))))
(rule
 (alias spec-088)
 (action (diff spec-088.html spec-088.html.new)))
(rule
 (action
  (with-stdout-to spec-089.html.new (run ./omd.exe %{dep:spec-089.md}))))
(rule
 (alias spec-089)
 (action (diff spec-089.html spec-089.html.new)))
(rule
 (action
  (with-stdout-to spec-090.html.new (run ./omd.exe %{dep:spec-090.md}))))
(rule
 (alias spec-090)
 (action (diff spec-090.html spec-090.html.new)))
(rule
 (action
  (with-stdout-to spec-091.html.new (run ./omd.exe %{dep:spec-091.md}))))
(rule
 (alias spec-091)
 (action (diff spec-091.html spec-091.html.new)))
(rule
 (action
  (with-stdout-to spec-092.html.new (run ./omd.exe %{dep:spec-092.md}))))
(rule
 (alias spec-092)
 (action (diff spec-092.html spec-092.html.new)))
(rule
 (action
  (with-stdout-to spec-093.html.new (run ./omd.exe %{dep:spec-093.md}))))
(rule
 (alias spec-093)
 (action (diff spec-093.html spec-093.html.new)))
(rule
 (action
  (with-stdout-to spec-094.html.new (run ./omd.exe %{dep:spec-094.md}))))
(rule
 (alias spec-094)
 (action (diff spec-094.html spec-094.html.new)))
(rule
 (action
  (with-stdout-to spec-095.html.new (run ./omd.exe %{dep:spec-095.md}))))
(rule
 (alias spec-095)
 (action (diff spec-095.html spec-095.html.new)))
(rule
 (action
  (with-stdout-to spec-096.html.new (run ./omd.exe %{dep:spec-096.md}))))
(rule
 (alias spec-096)
 (action (diff spec-096.html spec-096.html.new)))
(rule
 (action
  (with-stdout-to spec-097.html.new (run ./omd.exe %{dep:spec-097.md}))))
(rule
 (alias spec-097)
 (action (diff spec-097.html spec-097.html.new)))
(rule
 (action
  (with-stdout-to spec-098.html.new (run ./omd.exe %{dep:spec-098.md}))))
(rule
 (alias spec-098)
 (action (diff spec-098.html spec-098.html.new)))
(rule
 (action
  (with-stdout-to spec-099.html.new (run ./omd.exe %{dep:spec-099.md}))))
(rule
 (alias spec-099)
 (action (diff spec-099.html spec-099.html.new)))
(rule
 (action
  (with-stdout-to spec-100.html.new (run ./omd.exe %{dep:spec-100.md}))))
(rule
 (alias spec-100)
 (action (diff spec-100.html spec-100.html.new)))
(rule
 (action
  (with-stdout-to spec-101.html.new (run ./omd.exe %{dep:spec-101.md}))))
(rule
 (alias spec-101)
 (action (diff spec-101.html spec-101.html.new)))
(rule
 (action
  (with-stdout-to spec-102.html.new (run ./omd.exe %{dep:spec-102.md}))))
(rule
 (alias spec-102)
 (action (diff spec-102.html spec-102.html.new)))
(rule
 (action
  (with-stdout-to spec-103.html.new (run ./omd.exe %{dep:spec-103.md}))))
(rule
 (alias spec-103)
 (action (diff spec-103.html spec-103.html.new)))
(rule
 (action
  (with-stdout-to spec-104.html.new (run ./omd.exe %{dep:spec-104.md}))))
(rule
 (alias spec-104)
 (action (diff spec-104.html spec-104.html.new)))
(rule
 (action
  (with-stdout-to spec-105.html.new (run ./omd.exe %{dep:spec-105.md}))))
(rule
 (alias spec-105)
 (action (diff spec-105.html spec-105.html.new)))
(rule
 (action
  (with-stdout-to spec-106.html.new (run ./omd.exe %{dep:spec-106.md}))))
(rule
 (alias spec-106)
 (action (diff spec-106.html spec-106.html.new)))
(rule
 (action
  (with-stdout-to spec-107.html.new (run ./omd.exe %{dep:spec-107.md}))))
(rule
 (alias spec-107)
 (action (diff spec-107.html spec-107.html.new)))
(rule
 (action
  (with-stdout-to spec-108.html.new (run ./omd.exe %{dep:spec-108.md}))))
(rule
 (alias spec-108)
 (action (diff spec-108.html spec-108.html.new)))
(rule
 (action
  (with-stdout-to spec-109.html.new (run ./omd.exe %{dep:spec-109.md}))))
(rule
 (alias spec-109)
 (action (diff spec-109.html spec-109.html.new)))
(rule
 (action
  (with-stdout-to spec-110.html.new (run ./omd.exe %{dep:spec-110.md}))))
(rule
 (alias spec-110)
 (action (diff spec-110.html spec-110.html.new)))
(rule
 (action
  (with-stdout-to spec-111.html.new (run ./omd.exe %{dep:spec-111.md}))))
(rule
 (alias spec-111)
 (action (diff spec-111.html spec-111.html.new)))
(rule
 (action
  (with-stdout-to spec-112.html.new (run ./omd.exe %{dep:spec-112.md}))))
(rule
 (alias spec-112)
 (action (diff spec-112.html spec-112.html.new)))
(rule
 (action
  (with-stdout-to spec-113.html.new (run ./omd.exe %{dep:spec-113.md}))))
(rule
 (alias spec-113)
 (action (diff spec-113.html spec-113.html.new)))
(rule
 (action
  (with-stdout-to spec-114.html.new (run ./omd.exe %{dep:spec-114.md}))))
(rule
 (alias spec-114)
 (action (diff spec-114.html spec-114.html.new)))
(rule
 (action
  (with-stdout-to spec-115.html.new (run ./omd.exe %{dep:spec-115.md}))))
(rule
 (alias spec-115)
 (action (diff spec-115.html spec-115.html.new)))
(rule
 (action
  (with-stdout-to spec-116.html.new (run ./omd.exe %{dep:spec-116.md}))))
(rule
 (alias spec-116)
 (action (diff spec-116.html spec-116.html.new)))
(rule
 (action
  (with-stdout-to spec-117.html.new (run ./omd.exe %{dep:spec-117.md}))))
(rule
 (alias spec-117)
 (action (diff spec-117.html spec-117.html.new)))
(rule
 (action
  (with-stdout-to spec-118.html.new (run ./omd.exe %{dep:spec-118.md}))))
(rule
 (alias spec-118)
 (action (diff spec-118.html spec-118.html.new)))
(rule
 (action
  (with-stdout-to spec-119.html.new (run ./omd.exe %{dep:spec-119.md}))))
(rule
 (alias spec-119)
 (action (diff spec-119.html spec-119.html.new)))
(rule
 (action
  (with-stdout-to spec-120.html.new (run ./omd.exe %{dep:spec-120.md}))))
(rule
 (alias spec-120)
 (action (diff spec-120.html spec-120.html.new)))
(rule
 (action
  (with-stdout-to spec-121.html.new (run ./omd.exe %{dep:spec-121.md}))))
(rule
 (alias spec-121)
 (action (diff spec-121.html spec-121.html.new)))
(rule
 (action
  (with-stdout-to spec-122.html.new (run ./omd.exe %{dep:spec-122.md}))))
(rule
 (alias spec-122)
 (action (diff spec-122.html spec-122.html.new)))
(rule
 (action
  (with-stdout-to spec-123.html.new (run ./omd.exe %{dep:spec-123.md}))))
(rule
 (alias spec-123)
 (action (diff spec-123.html spec-123.html.new)))
(rule
 (action
  (with-stdout-to spec-124.html.new (run ./omd.exe %{dep:spec-124.md}))))
(rule
 (alias spec-124)
 (action (diff spec-124.html spec-124.html.new)))
(rule
 (action
  (with-stdout-to spec-125.html.new (run ./omd.exe %{dep:spec-125.md}))))
(rule
 (alias spec-125)
 (action (diff spec-125.html spec-125.html.new)))
(rule
 (action
  (with-stdout-to spec-126.html.new (run ./omd.exe %{dep:spec-126.md}))))
(rule
 (alias spec-126)
 (action (diff spec-126.html spec-126.html.new)))
(rule
 (action
  (with-stdout-to spec-127.html.new (run ./omd.exe %{dep:spec-127.md}))))
(rule
 (alias spec-127)
 (action (diff spec-127.html spec-127.html.new)))
(rule
 (action
  (with-stdout-to spec-128.html.new (run ./omd.exe %{dep:spec-128.md}))))
(rule
 (alias spec-128)
 (action (diff spec-128.html spec-128.html.new)))
(rule
 (action
  (with-stdout-to spec-129.html.new (run ./omd.exe %{dep:spec-129.md}))))
(rule
 (alias spec-129)
 (action (diff spec-129.html spec-129.html.new)))
(rule
 (action
  (with-stdout-to spec-130.html.new (run ./omd.exe %{dep:spec-130.md}))))
(rule
 (alias spec-130)
 (action (diff spec-130.html spec-130.html.new)))
(rule
 (action
  (with-stdout-to spec-131.html.new (run ./omd.exe %{dep:spec-131.md}))))
(rule
 (alias spec-131)
 (action (diff spec-131.html spec-131.html.new)))
(rule
 (action
  (with-stdout-to spec-132.html.new (run ./omd.exe %{dep:spec-132.md}))))
(rule
 (alias spec-132)
 (action (diff spec-132.html spec-132.html.new)))
(rule
 (action
  (with-stdout-to spec-133.html.new (run ./omd.exe %{dep:spec-133.md}))))
(rule
 (alias spec-133)
 (action (diff spec-133.html spec-133.html.new)))
(rule
 (action
  (with-stdout-to spec-134.html.new (run ./omd.exe %{dep:spec-134.md}))))
(rule
 (alias spec-134)
 (action (diff spec-134.html spec-134.html.new)))
(rule
 (action
  (with-stdout-to spec-135.html.new (run ./omd.exe %{dep:spec-135.md}))))
(rule
 (alias spec-135)
 (action (diff spec-135.html spec-135.html.new)))
(rule
 (action
  (with-stdout-to spec-136.html.new (run ./omd.exe %{dep:spec-136.md}))))
(rule
 (alias spec-136)
 (action (diff spec-136.html spec-136.html.new)))
(rule
 (action
  (with-stdout-to spec-137.html.new (run ./omd.exe %{dep:spec-137.md}))))
(rule
 (alias spec-137)
 (action (diff spec-137.html spec-137.html.new)))
(rule
 (action
  (with-stdout-to spec-138.html.new (run ./omd.exe %{dep:spec-138.md}))))
(rule
 (alias spec-138)
 (action (diff spec-138.html spec-138.html.new)))
(rule
 (action
  (with-stdout-to spec-139.html.new (run ./omd.exe %{dep:spec-139.md}))))
(rule
 (alias spec-139)
 (action (diff spec-139.html spec-139.html.new)))
(rule
 (action
  (with-stdout-to spec-140.html.new (run ./omd.exe %{dep:spec-140.md}))))
(rule
 (alias spec-140)
 (action (diff spec-140.html spec-140.html.new)))
(rule
 (action
  (with-stdout-to spec-141.html.new (run ./omd.exe %{dep:spec-141.md}))))
(rule
 (alias spec-141)
 (action (diff spec-141.html spec-141.html.new)))
(rule
 (action
  (with-stdout-to spec-142.html.new (run ./omd.exe %{dep:spec-142.md}))))
(rule
 (alias spec-142)
 (action (diff spec-142.html spec-142.html.new)))
(rule
 (action
  (with-stdout-to spec-143.html.new (run ./omd.exe %{dep:spec-143.md}))))
(rule
 (alias spec-143)
 (action (diff spec-143.html spec-143.html.new)))
(rule
 (action
  (with-stdout-to spec-144.html.new (run ./omd.exe %{dep:spec-144.md}))))
(rule
 (alias spec-144)
 (action (diff spec-144.html spec-144.html.new)))
(rule
 (action
  (with-stdout-to spec-145.html.new (run ./omd.exe %{dep:spec-145.md}))))
(rule
 (alias spec-145)
 (action (diff spec-145.html spec-145.html.new)))
(rule
 (action
  (with-stdout-to spec-146.html.new (run ./omd.exe %{dep:spec-146.md}))))
(rule
 (alias spec-146)
 (action (diff spec-146.html spec-146.html.new)))
(rule
 (action
  (with-stdout-to spec-147.html.new (run ./omd.exe %{dep:spec-147.md}))))
(rule
 (alias spec-147)
 (action (diff spec-147.html spec-147.html.new)))
(rule
 (action
  (with-stdout-to spec-148.html.new (run ./omd.exe %{dep:spec-148.md}))))
(rule
 (alias spec-148)
 (action (diff spec-148.html spec-148.html.new)))
(rule
 (action
  (with-stdout-to spec-149.html.new (run ./omd.exe %{dep:spec-149.md}))))
(rule
 (alias spec-149)
 (action (diff spec-149.html spec-149.html.new)))
(rule
 (action
  (with-stdout-to spec-150.html.new (run ./omd.exe %{dep:spec-150.md}))))
(rule
 (alias spec-150)
 (action (diff spec-150.html spec-150.html.new)))
(rule
 (action
  (with-stdout-to spec-151.html.new (run ./omd.exe %{dep:spec-151.md}))))
(rule
 (alias spec-151)
 (action (diff spec-151.html spec-151.html.new)))
(rule
 (action
  (with-stdout-to spec-152.html.new (run ./omd.exe %{dep:spec-152.md}))))
(rule
 (alias spec-152)
 (action (diff spec-152.html spec-152.html.new)))
(rule
 (action
  (with-stdout-to spec-153.html.new (run ./omd.exe %{dep:spec-153.md}))))
(rule
 (alias spec-153)
 (action (diff spec-153.html spec-153.html.new)))
(rule
 (action
  (with-stdout-to spec-154.html.new (run ./omd.exe %{dep:spec-154.md}))))
(rule
 (alias spec-154)
 (action (diff spec-154.html spec-154.html.new)))
(rule
 (action
  (with-stdout-to spec-155.html.new (run ./omd.exe %{dep:spec-155.md}))))
(rule
 (alias spec-155)
 (action (diff spec-155.html spec-155.html.new)))
(rule
 (action
  (with-stdout-to spec-156.html.new (run ./omd.exe %{dep:spec-156.md}))))
(rule
 (alias spec-156)
 (action (diff spec-156.html spec-156.html.new)))
(rule
 (action
  (with-stdout-to spec-157.html.new (run ./omd.exe %{dep:spec-157.md}))))
(rule
 (alias spec-157)
 (action (diff spec-157.html spec-157.html.new)))
(rule
 (action
  (with-stdout-to spec-158.html.new (run ./omd.exe %{dep:spec-158.md}))))
(rule
 (alias spec-158)
 (action (diff spec-158.html spec-158.html.new)))
(rule
 (action
  (with-stdout-to spec-159.html.new (run ./omd.exe %{dep:spec-159.md}))))
(rule
 (alias spec-159)
 (action (diff spec-159.html spec-159.html.new)))
(rule
 (action
  (with-stdout-to spec-160.html.new (run ./omd.exe %{dep:spec-160.md}))))
(rule
 (alias spec-160)
 (action (diff spec-160.html spec-160.html.new)))
(rule
 (action
  (with-stdout-to spec-161.html.new (run ./omd.exe %{dep:spec-161.md}))))
(rule
 (alias spec-161)
 (action (diff spec-161.html spec-161.html.new)))
(rule
 (action
  (with-stdout-to spec-162.html.new (run ./omd.exe %{dep:spec-162.md}))))
(rule
 (alias spec-162)
 (action (diff spec-162.html spec-162.html.new)))
(rule
 (action
  (with-stdout-to spec-163.html.new (run ./omd.exe %{dep:spec-163.md}))))
(rule
 (alias spec-163)
 (action (diff spec-163.html spec-163.html.new)))
(rule
 (action
  (with-stdout-to spec-164.html.new (run ./omd.exe %{dep:spec-164.md}))))
(rule
 (alias spec-164)
 (action (diff spec-164.html spec-164.html.new)))
(rule
 (action
  (with-stdout-to spec-165.html.new (run ./omd.exe %{dep:spec-165.md}))))
(rule
 (alias spec-165)
 (action (diff spec-165.html spec-165.html.new)))
(rule
 (action
  (with-stdout-to spec-166.html.new (run ./omd.exe %{dep:spec-166.md}))))
(rule
 (alias spec-166)
 (action (diff spec-166.html spec-166.html.new)))
(rule
 (action
  (with-stdout-to spec-167.html.new (run ./omd.exe %{dep:spec-167.md}))))
(rule
 (alias spec-167)
 (action (diff spec-167.html spec-167.html.new)))
(rule
 (action
  (with-stdout-to spec-168.html.new (run ./omd.exe %{dep:spec-168.md}))))
(rule
 (alias spec-168)
 (action (diff spec-168.html spec-168.html.new)))
(rule
 (action
  (with-stdout-to spec-169.html.new (run ./omd.exe %{dep:spec-169.md}))))
(rule
 (alias spec-169)
 (action (diff spec-169.html spec-169.html.new)))
(rule
 (action
  (with-stdout-to spec-170.html.new (run ./omd.exe %{dep:spec-170.md}))))
(rule
 (alias spec-170)
 (action (diff spec-170.html spec-170.html.new)))
(rule
 (action
  (with-stdout-to spec-171.html.new (run ./omd.exe %{dep:spec-171.md}))))
(rule
 (alias spec-171)
 (action (diff spec-171.html spec-171.html.new)))
(rule
 (action
  (with-stdout-to spec-172.html.new (run ./omd.exe %{dep:spec-172.md}))))
(rule
 (alias spec-172)
 (action (diff spec-172.html spec-172.html.new)))
(rule
 (action
  (with-stdout-to spec-173.html.new (run ./omd.exe %{dep:spec-173.md}))))
(rule
 (alias spec-173)
 (action (diff spec-173.html spec-173.html.new)))
(rule
 (action
  (with-stdout-to spec-174.html.new (run ./omd.exe %{dep:spec-174.md}))))
(rule
 (alias spec-174)
 (action (diff spec-174.html spec-174.html.new)))
(rule
 (action
  (with-stdout-to spec-175.html.new (run ./omd.exe %{dep:spec-175.md}))))
(rule
 (alias spec-175)
 (action (diff spec-175.html spec-175.html.new)))
(rule
 (action
  (with-stdout-to spec-176.html.new (run ./omd.exe %{dep:spec-176.md}))))
(rule
 (alias spec-176)
 (action (diff spec-176.html spec-176.html.new)))
(rule
 (action
  (with-stdout-to spec-177.html.new (run ./omd.exe %{dep:spec-177.md}))))
(rule
 (alias spec-177)
 (action (diff spec-177.html spec-177.html.new)))
(rule
 (action
  (with-stdout-to spec-178.html.new (run ./omd.exe %{dep:spec-178.md}))))
(rule
 (alias spec-178)
 (action (diff spec-178.html spec-178.html.new)))
(rule
 (action
  (with-stdout-to spec-179.html.new (run ./omd.exe %{dep:spec-179.md}))))
(rule
 (alias spec-179)
 (action (diff spec-179.html spec-179.html.new)))
(rule
 (action
  (with-stdout-to spec-180.html.new (run ./omd.exe %{dep:spec-180.md}))))
(rule
 (alias spec-180)
 (action (diff spec-180.html spec-180.html.new)))
(rule
 (action
  (with-stdout-to spec-181.html.new (run ./omd.exe %{dep:spec-181.md}))))
(rule
 (alias spec-181)
 (action (diff spec-181.html spec-181.html.new)))
(rule
 (action
  (with-stdout-to spec-182.html.new (run ./omd.exe %{dep:spec-182.md}))))
(rule
 (alias spec-182)
 (action (diff spec-182.html spec-182.html.new)))
(rule
 (action
  (with-stdout-to spec-183.html.new (run ./omd.exe %{dep:spec-183.md}))))
(rule
 (alias spec-183)
 (action (diff spec-183.html spec-183.html.new)))
(rule
 (action
  (with-stdout-to spec-184.html.new (run ./omd.exe %{dep:spec-184.md}))))
(rule
 (alias spec-184)
 (action (diff spec-184.html spec-184.html.new)))
(rule
 (action
  (with-stdout-to spec-185.html.new (run ./omd.exe %{dep:spec-185.md}))))
(rule
 (alias spec-185)
 (action (diff spec-185.html spec-185.html.new)))
(rule
 (action
  (with-stdout-to spec-186.html.new (run ./omd.exe %{dep:spec-186.md}))))
(rule
 (alias spec-186)
 (action (diff spec-186.html spec-186.html.new)))
(rule
 (action
  (with-stdout-to spec-187.html.new (run ./omd.exe %{dep:spec-187.md}))))
(rule
 (alias spec-187)
 (action (diff spec-187.html spec-187.html.new)))
(rule
 (action
  (with-stdout-to spec-188.html.new (run ./omd.exe %{dep:spec-188.md}))))
(rule
 (alias spec-188)
 (action (diff spec-188.html spec-188.html.new)))
(rule
 (action
  (with-stdout-to spec-189.html.new (run ./omd.exe %{dep:spec-189.md}))))
(rule
 (alias spec-189)
 (action (diff spec-189.html spec-189.html.new)))
(rule
 (action
  (with-stdout-to spec-190.html.new (run ./omd.exe %{dep:spec-190.md}))))
(rule
 (alias spec-190)
 (action (diff spec-190.html spec-190.html.new)))
(rule
 (action
  (with-stdout-to spec-191.html.new (run ./omd.exe %{dep:spec-191.md}))))
(rule
 (alias spec-191)
 (action (diff spec-191.html spec-191.html.new)))
(rule
 (action
  (with-stdout-to spec-192.html.new (run ./omd.exe %{dep:spec-192.md}))))
(rule
 (alias spec-192)
 (action (diff spec-192.html spec-192.html.new)))
(rule
 (action
  (with-stdout-to spec-193.html.new (run ./omd.exe %{dep:spec-193.md}))))
(rule
 (alias spec-193)
 (action (diff spec-193.html spec-193.html.new)))
(rule
 (action
  (with-stdout-to spec-194.html.new (run ./omd.exe %{dep:spec-194.md}))))
(rule
 (alias spec-194)
 (action (diff spec-194.html spec-194.html.new)))
(rule
 (action
  (with-stdout-to spec-195.html.new (run ./omd.exe %{dep:spec-195.md}))))
(rule
 (alias spec-195)
 (action (diff spec-195.html spec-195.html.new)))
(rule
 (action
  (with-stdout-to spec-196.html.new (run ./omd.exe %{dep:spec-196.md}))))
(rule
 (alias spec-196)
 (action (diff spec-196.html spec-196.html.new)))
(rule
 (action
  (with-stdout-to spec-197.html.new (run ./omd.exe %{dep:spec-197.md}))))
(rule
 (alias spec-197)
 (action (diff spec-197.html spec-197.html.new)))
(rule
 (action
  (with-stdout-to spec-198.html.new (run ./omd.exe %{dep:spec-198.md}))))
(rule
 (alias spec-198)
 (action (diff spec-198.html spec-198.html.new)))
(rule
 (action
  (with-stdout-to spec-199.html.new (run ./omd.exe %{dep:spec-199.md}))))
(rule
 (alias spec-199)
 (action (diff spec-199.html spec-199.html.new)))
(rule
 (action
  (with-stdout-to spec-200.html.new (run ./omd.exe %{dep:spec-200.md}))))
(rule
 (alias spec-200)
 (action (diff spec-200.html spec-200.html.new)))
(rule
 (action
  (with-stdout-to spec-201.html.new (run ./omd.exe %{dep:spec-201.md}))))
(rule
 (alias spec-201)
 (action (diff spec-201.html spec-201.html.new)))
(rule
 (action
  (with-stdout-to spec-202.html.new (run ./omd.exe %{dep:spec-202.md}))))
(rule
 (alias spec-202)
 (action (diff spec-202.html spec-202.html.new)))
(rule
 (action
  (with-stdout-to spec-203.html.new (run ./omd.exe %{dep:spec-203.md}))))
(rule
 (alias spec-203)
 (action (diff spec-203.html spec-203.html.new)))
(rule
 (action
  (with-stdout-to spec-204.html.new (run ./omd.exe %{dep:spec-204.md}))))
(rule
 (alias spec-204)
 (action (diff spec-204.html spec-204.html.new)))
(rule
 (action
  (with-stdout-to spec-205.html.new (run ./omd.exe %{dep:spec-205.md}))))
(rule
 (alias spec-205)
 (action (diff spec-205.html spec-205.html.new)))
(rule
 (action
  (with-stdout-to spec-206.html.new (run ./omd.exe %{dep:spec-206.md}))))
(rule
 (alias spec-206)
 (action (diff spec-206.html spec-206.html.new)))
(rule
 (action
  (with-stdout-to spec-207.html.new (run ./omd.exe %{dep:spec-207.md}))))
(rule
 (alias spec-207)
 (action (diff spec-207.html spec-207.html.new)))
(rule
 (action
  (with-stdout-to spec-208.html.new (run ./omd.exe %{dep:spec-208.md}))))
(rule
 (alias spec-208)
 (action (diff spec-208.html spec-208.html.new)))
(rule
 (action
  (with-stdout-to spec-209.html.new (run ./omd.exe %{dep:spec-209.md}))))
(rule
 (alias spec-209)
 (action (diff spec-209.html spec-209.html.new)))
(rule
 (action
  (with-stdout-to spec-210.html.new (run ./omd.exe %{dep:spec-210.md}))))
(rule
 (alias spec-210)
 (action (diff spec-210.html spec-210.html.new)))
(rule
 (action
  (with-stdout-to spec-211.html.new (run ./omd.exe %{dep:spec-211.md}))))
(rule
 (alias spec-211)
 (action (diff spec-211.html spec-211.html.new)))
(rule
 (action
  (with-stdout-to spec-212.html.new (run ./omd.exe %{dep:spec-212.md}))))
(rule
 (alias spec-212)
 (action (diff spec-212.html spec-212.html.new)))
(rule
 (action
  (with-stdout-to spec-213.html.new (run ./omd.exe %{dep:spec-213.md}))))
(rule
 (alias spec-213)
 (action (diff spec-213.html spec-213.html.new)))
(rule
 (action
  (with-stdout-to spec-214.html.new (run ./omd.exe %{dep:spec-214.md}))))
(rule
 (alias spec-214)
 (action (diff spec-214.html spec-214.html.new)))
(rule
 (action
  (with-stdout-to spec-215.html.new (run ./omd.exe %{dep:spec-215.md}))))
(rule
 (alias spec-215)
 (action (diff spec-215.html spec-215.html.new)))
(rule
 (action
  (with-stdout-to spec-216.html.new (run ./omd.exe %{dep:spec-216.md}))))
(rule
 (alias spec-216)
 (action (diff spec-216.html spec-216.html.new)))
(rule
 (action
  (with-stdout-to spec-217.html.new (run ./omd.exe %{dep:spec-217.md}))))
(rule
 (alias spec-217)
 (action (diff spec-217.html spec-217.html.new)))
(rule
 (action
  (with-stdout-to spec-218.html.new (run ./omd.exe %{dep:spec-218.md}))))
(rule
 (alias spec-218)
 (action (diff spec-218.html spec-218.html.new)))
(rule
 (action
  (with-stdout-to spec-219.html.new (run ./omd.exe %{dep:spec-219.md}))))
(rule
 (alias spec-219)
 (action (diff spec-219.html spec-219.html.new)))
(rule
 (action
  (with-stdout-to spec-220.html.new (run ./omd.exe %{dep:spec-220.md}))))
(rule
 (alias spec-220)
 (action (diff spec-220.html spec-220.html.new)))
(rule
 (action
  (with-stdout-to spec-221.html.new (run ./omd.exe %{dep:spec-221.md}))))
(rule
 (alias spec-221)
 (action (diff spec-221.html spec-221.html.new)))
(rule
 (action
  (with-stdout-to spec-222.html.new (run ./omd.exe %{dep:spec-222.md}))))
(rule
 (alias spec-222)
 (action (diff spec-222.html spec-222.html.new)))
(rule
 (action
  (with-stdout-to spec-223.html.new (run ./omd.exe %{dep:spec-223.md}))))
(rule
 (alias spec-223)
 (action (diff spec-223.html spec-223.html.new)))
(rule
 (action
  (with-stdout-to spec-224.html.new (run ./omd.exe %{dep:spec-224.md}))))
(rule
 (alias spec-224)
 (action (diff spec-224.html spec-224.html.new)))
(rule
 (action
  (with-stdout-to spec-225.html.new (run ./omd.exe %{dep:spec-225.md}))))
(rule
 (alias spec-225)
 (action (diff spec-225.html spec-225.html.new)))
(rule
 (action
  (with-stdout-to spec-226.html.new (run ./omd.exe %{dep:spec-226.md}))))
(rule
 (alias spec-226)
 (action (diff spec-226.html spec-226.html.new)))
(rule
 (action
  (with-stdout-to spec-227.html.new (run ./omd.exe %{dep:spec-227.md}))))
(rule
 (alias spec-227)
 (action (diff spec-227.html spec-227.html.new)))
(rule
 (action
  (with-stdout-to spec-228.html.new (run ./omd.exe %{dep:spec-228.md}))))
(rule
 (alias spec-228)
 (action (diff spec-228.html spec-228.html.new)))
(rule
 (action
  (with-stdout-to spec-229.html.new (run ./omd.exe %{dep:spec-229.md}))))
(rule
 (alias spec-229)
 (action (diff spec-229.html spec-229.html.new)))
(rule
 (action
  (with-stdout-to spec-230.html.new (run ./omd.exe %{dep:spec-230.md}))))
(rule
 (alias spec-230)
 (action (diff spec-230.html spec-230.html.new)))
(rule
 (action
  (with-stdout-to spec-231.html.new (run ./omd.exe %{dep:spec-231.md}))))
(rule
 (alias spec-231)
 (action (diff spec-231.html spec-231.html.new)))
(rule
 (action
  (with-stdout-to spec-232.html.new (run ./omd.exe %{dep:spec-232.md}))))
(rule
 (alias spec-232)
 (action (diff spec-232.html spec-232.html.new)))
(rule
 (action
  (with-stdout-to spec-233.html.new (run ./omd.exe %{dep:spec-233.md}))))
(rule
 (alias spec-233)
 (action (diff spec-233.html spec-233.html.new)))
(rule
 (action
  (with-stdout-to spec-234.html.new (run ./omd.exe %{dep:spec-234.md}))))
(rule
 (alias spec-234)
 (action (diff spec-234.html spec-234.html.new)))
(rule
 (action
  (with-stdout-to spec-235.html.new (run ./omd.exe %{dep:spec-235.md}))))
(rule
 (alias spec-235)
 (action (diff spec-235.html spec-235.html.new)))
(rule
 (action
  (with-stdout-to spec-236.html.new (run ./omd.exe %{dep:spec-236.md}))))
(rule
 (alias spec-236)
 (action (diff spec-236.html spec-236.html.new)))
(rule
 (action
  (with-stdout-to spec-237.html.new (run ./omd.exe %{dep:spec-237.md}))))
(rule
 (alias spec-237)
 (action (diff spec-237.html spec-237.html.new)))
(rule
 (action
  (with-stdout-to spec-238.html.new (run ./omd.exe %{dep:spec-238.md}))))
(rule
 (alias spec-238)
 (action (diff spec-238.html spec-238.html.new)))
(rule
 (action
  (with-stdout-to spec-239.html.new (run ./omd.exe %{dep:spec-239.md}))))
(rule
 (alias spec-239)
 (action (diff spec-239.html spec-239.html.new)))
(rule
 (action
  (with-stdout-to spec-240.html.new (run ./omd.exe %{dep:spec-240.md}))))
(rule
 (alias spec-240)
 (action (diff spec-240.html spec-240.html.new)))
(rule
 (action
  (with-stdout-to spec-241.html.new (run ./omd.exe %{dep:spec-241.md}))))
(rule
 (alias spec-241)
 (action (diff spec-241.html spec-241.html.new)))
(rule
 (action
  (with-stdout-to spec-242.html.new (run ./omd.exe %{dep:spec-242.md}))))
(rule
 (alias spec-242)
 (action (diff spec-242.html spec-242.html.new)))
(rule
 (action
  (with-stdout-to spec-243.html.new (run ./omd.exe %{dep:spec-243.md}))))
(rule
 (alias spec-243)
 (action (diff spec-243.html spec-243.html.new)))
(rule
 (action
  (with-stdout-to spec-244.html.new (run ./omd.exe %{dep:spec-244.md}))))
(rule
 (alias spec-244)
 (action (diff spec-244.html spec-244.html.new)))
(rule
 (action
  (with-stdout-to spec-245.html.new (run ./omd.exe %{dep:spec-245.md}))))
(rule
 (alias spec-245)
 (action (diff spec-245.html spec-245.html.new)))
(rule
 (action
  (with-stdout-to spec-246.html.new (run ./omd.exe %{dep:spec-246.md}))))
(rule
 (alias spec-246)
 (action (diff spec-246.html spec-246.html.new)))
(rule
 (action
  (with-stdout-to spec-247.html.new (run ./omd.exe %{dep:spec-247.md}))))
(rule
 (alias spec-247)
 (action (diff spec-247.html spec-247.html.new)))
(rule
 (action
  (with-stdout-to spec-248.html.new (run ./omd.exe %{dep:spec-248.md}))))
(rule
 (alias spec-248)
 (action (diff spec-248.html spec-248.html.new)))
(rule
 (action
  (with-stdout-to spec-249.html.new (run ./omd.exe %{dep:spec-249.md}))))
(rule
 (alias spec-249)
 (action (diff spec-249.html spec-249.html.new)))
(rule
 (action
  (with-stdout-to spec-250.html.new (run ./omd.exe %{dep:spec-250.md}))))
(rule
 (alias spec-250)
 (action (diff spec-250.html spec-250.html.new)))
(rule
 (action
  (with-stdout-to spec-251.html.new (run ./omd.exe %{dep:spec-251.md}))))
(rule
 (alias spec-251)
 (action (diff spec-251.html spec-251.html.new)))
(rule
 (action
  (with-stdout-to spec-252.html.new (run ./omd.exe %{dep:spec-252.md}))))
(rule
 (alias spec-252)
 (action (diff spec-252.html spec-252.html.new)))
(rule
 (action
  (with-stdout-to spec-253.html.new (run ./omd.exe %{dep:spec-253.md}))))
(rule
 (alias spec-253)
 (action (diff spec-253.html spec-253.html.new)))
(rule
 (action
  (with-stdout-to spec-254.html.new (run ./omd.exe %{dep:spec-254.md}))))
(rule
 (alias spec-254)
 (action (diff spec-254.html spec-254.html.new)))
(rule
 (action
  (with-stdout-to spec-255.html.new (run ./omd.exe %{dep:spec-255.md}))))
(rule
 (alias spec-255)
 (action (diff spec-255.html spec-255.html.new)))
(rule
 (action
  (with-stdout-to spec-256.html.new (run ./omd.exe %{dep:spec-256.md}))))
(rule
 (alias spec-256)
 (action (diff spec-256.html spec-256.html.new)))
(rule
 (action
  (with-stdout-to spec-257.html.new (run ./omd.exe %{dep:spec-257.md}))))
(rule
 (alias spec-257)
 (action (diff spec-257.html spec-257.html.new)))
(rule
 (action
  (with-stdout-to spec-258.html.new (run ./omd.exe %{dep:spec-258.md}))))
(rule
 (alias spec-258)
 (action (diff spec-258.html spec-258.html.new)))
(rule
 (action
  (with-stdout-to spec-259.html.new (run ./omd.exe %{dep:spec-259.md}))))
(rule
 (alias spec-259)
 (action (diff spec-259.html spec-259.html.new)))
(rule
 (action
  (with-stdout-to spec-260.html.new (run ./omd.exe %{dep:spec-260.md}))))
(rule
 (alias spec-260)
 (action (diff spec-260.html spec-260.html.new)))
(rule
 (action
  (with-stdout-to spec-261.html.new (run ./omd.exe %{dep:spec-261.md}))))
(rule
 (alias spec-261)
 (action (diff spec-261.html spec-261.html.new)))
(rule
 (action
  (with-stdout-to spec-262.html.new (run ./omd.exe %{dep:spec-262.md}))))
(rule
 (alias spec-262)
 (action (diff spec-262.html spec-262.html.new)))
(rule
 (action
  (with-stdout-to spec-263.html.new (run ./omd.exe %{dep:spec-263.md}))))
(rule
 (alias spec-263)
 (action (diff spec-263.html spec-263.html.new)))
(rule
 (action
  (with-stdout-to spec-264.html.new (run ./omd.exe %{dep:spec-264.md}))))
(rule
 (alias spec-264)
 (action (diff spec-264.html spec-264.html.new)))
(rule
 (action
  (with-stdout-to spec-265.html.new (run ./omd.exe %{dep:spec-265.md}))))
(rule
 (alias spec-265)
 (action (diff spec-265.html spec-265.html.new)))
(rule
 (action
  (with-stdout-to spec-266.html.new (run ./omd.exe %{dep:spec-266.md}))))
(rule
 (alias spec-266)
 (action (diff spec-266.html spec-266.html.new)))
(rule
 (action
  (with-stdout-to spec-267.html.new (run ./omd.exe %{dep:spec-267.md}))))
(rule
 (alias spec-267)
 (action (diff spec-267.html spec-267.html.new)))
(rule
 (action
  (with-stdout-to spec-268.html.new (run ./omd.exe %{dep:spec-268.md}))))
(rule
 (alias spec-268)
 (action (diff spec-268.html spec-268.html.new)))
(rule
 (action
  (with-stdout-to spec-269.html.new (run ./omd.exe %{dep:spec-269.md}))))
(rule
 (alias spec-269)
 (action (diff spec-269.html spec-269.html.new)))
(rule
 (action
  (with-stdout-to spec-270.html.new (run ./omd.exe %{dep:spec-270.md}))))
(rule
 (alias spec-270)
 (action (diff spec-270.html spec-270.html.new)))
(rule
 (action
  (with-stdout-to spec-271.html.new (run ./omd.exe %{dep:spec-271.md}))))
(rule
 (alias spec-271)
 (action (diff spec-271.html spec-271.html.new)))
(rule
 (action
  (with-stdout-to spec-272.html.new (run ./omd.exe %{dep:spec-272.md}))))
(rule
 (alias spec-272)
 (action (diff spec-272.html spec-272.html.new)))
(rule
 (action
  (with-stdout-to spec-273.html.new (run ./omd.exe %{dep:spec-273.md}))))
(rule
 (alias spec-273)
 (action (diff spec-273.html spec-273.html.new)))
(rule
 (action
  (with-stdout-to spec-274.html.new (run ./omd.exe %{dep:spec-274.md}))))
(rule
 (alias spec-274)
 (action (diff spec-274.html spec-274.html.new)))
(rule
 (action
  (with-stdout-to spec-275.html.new (run ./omd.exe %{dep:spec-275.md}))))
(rule
 (alias spec-275)
 (action (diff spec-275.html spec-275.html.new)))
(rule
 (action
  (with-stdout-to spec-276.html.new (run ./omd.exe %{dep:spec-276.md}))))
(rule
 (alias spec-276)
 (action (diff spec-276.html spec-276.html.new)))
(rule
 (action
  (with-stdout-to spec-277.html.new (run ./omd.exe %{dep:spec-277.md}))))
(rule
 (alias spec-277)
 (action (diff spec-277.html spec-277.html.new)))
(rule
 (action
  (with-stdout-to spec-278.html.new (run ./omd.exe %{dep:spec-278.md}))))
(rule
 (alias spec-278)
 (action (diff spec-278.html spec-278.html.new)))
(rule
 (action
  (with-stdout-to spec-279.html.new (run ./omd.exe %{dep:spec-279.md}))))
(rule
 (alias spec-279)
 (action (diff spec-279.html spec-279.html.new)))
(rule
 (action
  (with-stdout-to spec-280.html.new (run ./omd.exe %{dep:spec-280.md}))))
(rule
 (alias spec-280)
 (action (diff spec-280.html spec-280.html.new)))
(rule
 (action
  (with-stdout-to spec-281.html.new (run ./omd.exe %{dep:spec-281.md}))))
(rule
 (alias spec-281)
 (action (diff spec-281.html spec-281.html.new)))
(rule
 (action
  (with-stdout-to spec-282.html.new (run ./omd.exe %{dep:spec-282.md}))))
(rule
 (alias spec-282)
 (action (diff spec-282.html spec-282.html.new)))
(rule
 (action
  (with-stdout-to spec-283.html.new (run ./omd.exe %{dep:spec-283.md}))))
(rule
 (alias spec-283)
 (action (diff spec-283.html spec-283.html.new)))
(rule
 (action
  (with-stdout-to spec-284.html.new (run ./omd.exe %{dep:spec-284.md}))))
(rule
 (alias spec-284)
 (action (diff spec-284.html spec-284.html.new)))
(rule
 (action
  (with-stdout-to spec-285.html.new (run ./omd.exe %{dep:spec-285.md}))))
(rule
 (alias spec-285)
 (action (diff spec-285.html spec-285.html.new)))
(rule
 (action
  (with-stdout-to spec-286.html.new (run ./omd.exe %{dep:spec-286.md}))))
(rule
 (alias spec-286)
 (action (diff spec-286.html spec-286.html.new)))
(rule
 (action
  (with-stdout-to spec-287.html.new (run ./omd.exe %{dep:spec-287.md}))))
(rule
 (alias spec-287)
 (action (diff spec-287.html spec-287.html.new)))
(rule
 (action
  (with-stdout-to spec-288.html.new (run ./omd.exe %{dep:spec-288.md}))))
(rule
 (alias spec-288)
 (action (diff spec-288.html spec-288.html.new)))
(rule
 (action
  (with-stdout-to spec-289.html.new (run ./omd.exe %{dep:spec-289.md}))))
(rule
 (alias spec-289)
 (action (diff spec-289.html spec-289.html.new)))
(rule
 (action
  (with-stdout-to spec-290.html.new (run ./omd.exe %{dep:spec-290.md}))))
(rule
 (alias spec-290)
 (action (diff spec-290.html spec-290.html.new)))
(rule
 (action
  (with-stdout-to spec-291.html.new (run ./omd.exe %{dep:spec-291.md}))))
(rule
 (alias spec-291)
 (action (diff spec-291.html spec-291.html.new)))
(rule
 (action
  (with-stdout-to spec-292.html.new (run ./omd.exe %{dep:spec-292.md}))))
(rule
 (alias spec-292)
 (action (diff spec-292.html spec-292.html.new)))
(rule
 (action
  (with-stdout-to spec-293.html.new (run ./omd.exe %{dep:spec-293.md}))))
(rule
 (alias spec-293)
 (action (diff spec-293.html spec-293.html.new)))
(rule
 (action
  (with-stdout-to spec-294.html.new (run ./omd.exe %{dep:spec-294.md}))))
(rule
 (alias spec-294)
 (action (diff spec-294.html spec-294.html.new)))
(rule
 (action
  (with-stdout-to spec-295.html.new (run ./omd.exe %{dep:spec-295.md}))))
(rule
 (alias spec-295)
 (action (diff spec-295.html spec-295.html.new)))
(rule
 (action
  (with-stdout-to spec-296.html.new (run ./omd.exe %{dep:spec-296.md}))))
(rule
 (alias spec-296)
 (action (diff spec-296.html spec-296.html.new)))
(rule
 (action
  (with-stdout-to spec-297.html.new (run ./omd.exe %{dep:spec-297.md}))))
(rule
 (alias spec-297)
 (action (diff spec-297.html spec-297.html.new)))
(rule
 (action
  (with-stdout-to spec-298.html.new (run ./omd.exe %{dep:spec-298.md}))))
(rule
 (alias spec-298)
 (action (diff spec-298.html spec-298.html.new)))
(rule
 (action
  (with-stdout-to spec-299.html.new (run ./omd.exe %{dep:spec-299.md}))))
(rule
 (alias spec-299)
 (action (diff spec-299.html spec-299.html.new)))
(rule
 (action
  (with-stdout-to spec-300.html.new (run ./omd.exe %{dep:spec-300.md}))))
(rule
 (alias spec-300)
 (action (diff spec-300.html spec-300.html.new)))
(rule
 (action
  (with-stdout-to spec-301.html.new (run ./omd.exe %{dep:spec-301.md}))))
(rule
 (alias spec-301)
 (action (diff spec-301.html spec-301.html.new)))
(rule
 (action
  (with-stdout-to spec-302.html.new (run ./omd.exe %{dep:spec-302.md}))))
(rule
 (alias spec-302)
 (action (diff spec-302.html spec-302.html.new)))
(rule
 (action
  (with-stdout-to spec-303.html.new (run ./omd.exe %{dep:spec-303.md}))))
(rule
 (alias spec-303)
 (action (diff spec-303.html spec-303.html.new)))
(rule
 (action
  (with-stdout-to spec-304.html.new (run ./omd.exe %{dep:spec-304.md}))))
(rule
 (alias spec-304)
 (action (diff spec-304.html spec-304.html.new)))
(rule
 (action
  (with-stdout-to spec-305.html.new (run ./omd.exe %{dep:spec-305.md}))))
(rule
 (alias spec-305)
 (action (diff spec-305.html spec-305.html.new)))
(rule
 (action
  (with-stdout-to spec-306.html.new (run ./omd.exe %{dep:spec-306.md}))))
(rule
 (alias spec-306)
 (action (diff spec-306.html spec-306.html.new)))
(rule
 (action
  (with-stdout-to spec-307.html.new (run ./omd.exe %{dep:spec-307.md}))))
(rule
 (alias spec-307)
 (action (diff spec-307.html spec-307.html.new)))
(rule
 (action
  (with-stdout-to spec-308.html.new (run ./omd.exe %{dep:spec-308.md}))))
(rule
 (alias spec-308)
 (action (diff spec-308.html spec-308.html.new)))
(rule
 (action
  (with-stdout-to spec-309.html.new (run ./omd.exe %{dep:spec-309.md}))))
(rule
 (alias spec-309)
 (action (diff spec-309.html spec-309.html.new)))
(rule
 (action
  (with-stdout-to spec-310.html.new (run ./omd.exe %{dep:spec-310.md}))))
(rule
 (alias spec-310)
 (action (diff spec-310.html spec-310.html.new)))
(rule
 (action
  (with-stdout-to spec-311.html.new (run ./omd.exe %{dep:spec-311.md}))))
(rule
 (alias spec-311)
 (action (diff spec-311.html spec-311.html.new)))
(rule
 (action
  (with-stdout-to spec-312.html.new (run ./omd.exe %{dep:spec-312.md}))))
(rule
 (alias spec-312)
 (action (diff spec-312.html spec-312.html.new)))
(rule
 (action
  (with-stdout-to spec-313.html.new (run ./omd.exe %{dep:spec-313.md}))))
(rule
 (alias spec-313)
 (action (diff spec-313.html spec-313.html.new)))
(rule
 (action
  (with-stdout-to spec-314.html.new (run ./omd.exe %{dep:spec-314.md}))))
(rule
 (alias spec-314)
 (action (diff spec-314.html spec-314.html.new)))
(rule
 (action
  (with-stdout-to spec-315.html.new (run ./omd.exe %{dep:spec-315.md}))))
(rule
 (alias spec-315)
 (action (diff spec-315.html spec-315.html.new)))
(rule
 (action
  (with-stdout-to spec-316.html.new (run ./omd.exe %{dep:spec-316.md}))))
(rule
 (alias spec-316)
 (action (diff spec-316.html spec-316.html.new)))
(rule
 (action
  (with-stdout-to spec-317.html.new (run ./omd.exe %{dep:spec-317.md}))))
(rule
 (alias spec-317)
 (action (diff spec-317.html spec-317.html.new)))
(rule
 (action
  (with-stdout-to spec-318.html.new (run ./omd.exe %{dep:spec-318.md}))))
(rule
 (alias spec-318)
 (action (diff spec-318.html spec-318.html.new)))
(rule
 (action
  (with-stdout-to spec-319.html.new (run ./omd.exe %{dep:spec-319.md}))))
(rule
 (alias spec-319)
 (action (diff spec-319.html spec-319.html.new)))
(rule
 (action
  (with-stdout-to spec-320.html.new (run ./omd.exe %{dep:spec-320.md}))))
(rule
 (alias spec-320)
 (action (diff spec-320.html spec-320.html.new)))
(rule
 (action
  (with-stdout-to spec-321.html.new (run ./omd.exe %{dep:spec-321.md}))))
(rule
 (alias spec-321)
 (action (diff spec-321.html spec-321.html.new)))
(rule
 (action
  (with-stdout-to spec-322.html.new (run ./omd.exe %{dep:spec-322.md}))))
(rule
 (alias spec-322)
 (action (diff spec-322.html spec-322.html.new)))
(rule
 (action
  (with-stdout-to spec-323.html.new (run ./omd.exe %{dep:spec-323.md}))))
(rule
 (alias spec-323)
 (action (diff spec-323.html spec-323.html.new)))
(rule
 (action
  (with-stdout-to spec-324.html.new (run ./omd.exe %{dep:spec-324.md}))))
(rule
 (alias spec-324)
 (action (diff spec-324.html spec-324.html.new)))
(rule
 (action
  (with-stdout-to spec-325.html.new (run ./omd.exe %{dep:spec-325.md}))))
(rule
 (alias spec-325)
 (action (diff spec-325.html spec-325.html.new)))
(rule
 (action
  (with-stdout-to spec-326.html.new (run ./omd.exe %{dep:spec-326.md}))))
(rule
 (alias spec-326)
 (action (diff spec-326.html spec-326.html.new)))
(rule
 (action
  (with-stdout-to spec-327.html.new (run ./omd.exe %{dep:spec-327.md}))))
(rule
 (alias spec-327)
 (action (diff spec-327.html spec-327.html.new)))
(rule
 (action
  (with-stdout-to spec-328.html.new (run ./omd.exe %{dep:spec-328.md}))))
(rule
 (alias spec-328)
 (action (diff spec-328.html spec-328.html.new)))
(rule
 (action
  (with-stdout-to spec-329.html.new (run ./omd.exe %{dep:spec-329.md}))))
(rule
 (alias spec-329)
 (action (diff spec-329.html spec-329.html.new)))
(rule
 (action
  (with-stdout-to spec-330.html.new (run ./omd.exe %{dep:spec-330.md}))))
(rule
 (alias spec-330)
 (action (diff spec-330.html spec-330.html.new)))
(rule
 (action
  (with-stdout-to spec-331.html.new (run ./omd.exe %{dep:spec-331.md}))))
(rule
 (alias spec-331)
 (action (diff spec-331.html spec-331.html.new)))
(rule
 (action
  (with-stdout-to spec-332.html.new (run ./omd.exe %{dep:spec-332.md}))))
(rule
 (alias spec-332)
 (action (diff spec-332.html spec-332.html.new)))
(rule
 (action
  (with-stdout-to spec-333.html.new (run ./omd.exe %{dep:spec-333.md}))))
(rule
 (alias spec-333)
 (action (diff spec-333.html spec-333.html.new)))
(rule
 (action
  (with-stdout-to spec-334.html.new (run ./omd.exe %{dep:spec-334.md}))))
(rule
 (alias spec-334)
 (action (diff spec-334.html spec-334.html.new)))
(rule
 (action
  (with-stdout-to spec-335.html.new (run ./omd.exe %{dep:spec-335.md}))))
(rule
 (alias spec-335)
 (action (diff spec-335.html spec-335.html.new)))
(rule
 (action
  (with-stdout-to spec-336.html.new (run ./omd.exe %{dep:spec-336.md}))))
(rule
 (alias spec-336)
 (action (diff spec-336.html spec-336.html.new)))
(rule
 (action
  (with-stdout-to spec-337.html.new (run ./omd.exe %{dep:spec-337.md}))))
(rule
 (alias spec-337)
 (action (diff spec-337.html spec-337.html.new)))
(rule
 (action
  (with-stdout-to spec-338.html.new (run ./omd.exe %{dep:spec-338.md}))))
(rule
 (alias spec-338)
 (action (diff spec-338.html spec-338.html.new)))
(rule
 (action
  (with-stdout-to spec-339.html.new (run ./omd.exe %{dep:spec-339.md}))))
(rule
 (alias spec-339)
 (action (diff spec-339.html spec-339.html.new)))
(rule
 (action
  (with-stdout-to spec-340.html.new (run ./omd.exe %{dep:spec-340.md}))))
(rule
 (alias spec-340)
 (action (diff spec-340.html spec-340.html.new)))
(rule
 (action
  (with-stdout-to spec-341.html.new (run ./omd.exe %{dep:spec-341.md}))))
(rule
 (alias spec-341)
 (action (diff spec-341.html spec-341.html.new)))
(rule
 (action
  (with-stdout-to spec-342.html.new (run ./omd.exe %{dep:spec-342.md}))))
(rule
 (alias spec-342)
 (action (diff spec-342.html spec-342.html.new)))
(rule
 (action
  (with-stdout-to spec-343.html.new (run ./omd.exe %{dep:spec-343.md}))))
(rule
 (alias spec-343)
 (action (diff spec-343.html spec-343.html.new)))
(rule
 (action
  (with-stdout-to spec-344.html.new (run ./omd.exe %{dep:spec-344.md}))))
(rule
 (alias spec-344)
 (action (diff spec-344.html spec-344.html.new)))
(rule
 (action
  (with-stdout-to spec-345.html.new (run ./omd.exe %{dep:spec-345.md}))))
(rule
 (alias spec-345)
 (action (diff spec-345.html spec-345.html.new)))
(rule
 (action
  (with-stdout-to spec-346.html.new (run ./omd.exe %{dep:spec-346.md}))))
(rule
 (alias spec-346)
 (action (diff spec-346.html spec-346.html.new)))
(rule
 (action
  (with-stdout-to spec-347.html.new (run ./omd.exe %{dep:spec-347.md}))))
(rule
 (alias spec-347)
 (action (diff spec-347.html spec-347.html.new)))
(rule
 (action
  (with-stdout-to spec-348.html.new (run ./omd.exe %{dep:spec-348.md}))))
(rule
 (alias spec-348)
 (action (diff spec-348.html spec-348.html.new)))
(rule
 (action
  (with-stdout-to spec-349.html.new (run ./omd.exe %{dep:spec-349.md}))))
(rule
 (alias spec-349)
 (action (diff spec-349.html spec-349.html.new)))
(rule
 (action
  (with-stdout-to spec-350.html.new (run ./omd.exe %{dep:spec-350.md}))))
(rule
 (alias spec-350)
 (action (diff spec-350.html spec-350.html.new)))
(rule
 (action
  (with-stdout-to spec-351.html.new (run ./omd.exe %{dep:spec-351.md}))))
(rule
 (alias spec-351)
 (action (diff spec-351.html spec-351.html.new)))
(rule
 (action
  (with-stdout-to spec-352.html.new (run ./omd.exe %{dep:spec-352.md}))))
(rule
 (alias spec-352)
 (action (diff spec-352.html spec-352.html.new)))
(rule
 (action
  (with-stdout-to spec-353.html.new (run ./omd.exe %{dep:spec-353.md}))))
(rule
 (alias spec-353)
 (action (diff spec-353.html spec-353.html.new)))
(rule
 (action
  (with-stdout-to spec-354.html.new (run ./omd.exe %{dep:spec-354.md}))))
(rule
 (alias spec-354)
 (action (diff spec-354.html spec-354.html.new)))
(rule
 (action
  (with-stdout-to spec-355.html.new (run ./omd.exe %{dep:spec-355.md}))))
(rule
 (alias spec-355)
 (action (diff spec-355.html spec-355.html.new)))
(rule
 (action
  (with-stdout-to spec-356.html.new (run ./omd.exe %{dep:spec-356.md}))))
(rule
 (alias spec-356)
 (action (diff spec-356.html spec-356.html.new)))
(rule
 (action
  (with-stdout-to spec-357.html.new (run ./omd.exe %{dep:spec-357.md}))))
(rule
 (alias spec-357)
 (action (diff spec-357.html spec-357.html.new)))
(rule
 (action
  (with-stdout-to spec-358.html.new (run ./omd.exe %{dep:spec-358.md}))))
(rule
 (alias spec-358)
 (action (diff spec-358.html spec-358.html.new)))
(rule
 (action
  (with-stdout-to spec-359.html.new (run ./omd.exe %{dep:spec-359.md}))))
(rule
 (alias spec-359)
 (action (diff spec-359.html spec-359.html.new)))
(rule
 (action
  (with-stdout-to spec-360.html.new (run ./omd.exe %{dep:spec-360.md}))))
(rule
 (alias spec-360)
 (action (diff spec-360.html spec-360.html.new)))
(rule
 (action
  (with-stdout-to spec-361.html.new (run ./omd.exe %{dep:spec-361.md}))))
(rule
 (alias spec-361)
 (action (diff spec-361.html spec-361.html.new)))
(rule
 (action
  (with-stdout-to spec-362.html.new (run ./omd.exe %{dep:spec-362.md}))))
(rule
 (alias spec-362)
 (action (diff spec-362.html spec-362.html.new)))
(rule
 (action
  (with-stdout-to spec-363.html.new (run ./omd.exe %{dep:spec-363.md}))))
(rule
 (alias spec-363)
 (action (diff spec-363.html spec-363.html.new)))
(rule
 (action
  (with-stdout-to spec-364.html.new (run ./omd.exe %{dep:spec-364.md}))))
(rule
 (alias spec-364)
 (action (diff spec-364.html spec-364.html.new)))
(rule
 (action
  (with-stdout-to spec-365.html.new (run ./omd.exe %{dep:spec-365.md}))))
(rule
 (alias spec-365)
 (action (diff spec-365.html spec-365.html.new)))
(rule
 (action
  (with-stdout-to spec-366.html.new (run ./omd.exe %{dep:spec-366.md}))))
(rule
 (alias spec-366)
 (action (diff spec-366.html spec-366.html.new)))
(rule
 (action
  (with-stdout-to spec-367.html.new (run ./omd.exe %{dep:spec-367.md}))))
(rule
 (alias spec-367)
 (action (diff spec-367.html spec-367.html.new)))
(rule
 (action
  (with-stdout-to spec-368.html.new (run ./omd.exe %{dep:spec-368.md}))))
(rule
 (alias spec-368)
 (action (diff spec-368.html spec-368.html.new)))
(rule
 (action
  (with-stdout-to spec-369.html.new (run ./omd.exe %{dep:spec-369.md}))))
(rule
 (alias spec-369)
 (action (diff spec-369.html spec-369.html.new)))
(rule
 (action
  (with-stdout-to spec-370.html.new (run ./omd.exe %{dep:spec-370.md}))))
(rule
 (alias spec-370)
 (action (diff spec-370.html spec-370.html.new)))
(rule
 (action
  (with-stdout-to spec-371.html.new (run ./omd.exe %{dep:spec-371.md}))))
(rule
 (alias spec-371)
 (action (diff spec-371.html spec-371.html.new)))
(rule
 (action
  (with-stdout-to spec-372.html.new (run ./omd.exe %{dep:spec-372.md}))))
(rule
 (alias spec-372)
 (action (diff spec-372.html spec-372.html.new)))
(rule
 (action
  (with-stdout-to spec-373.html.new (run ./omd.exe %{dep:spec-373.md}))))
(rule
 (alias spec-373)
 (action (diff spec-373.html spec-373.html.new)))
(rule
 (action
  (with-stdout-to spec-374.html.new (run ./omd.exe %{dep:spec-374.md}))))
(rule
 (alias spec-374)
 (action (diff spec-374.html spec-374.html.new)))
(rule
 (action
  (with-stdout-to spec-375.html.new (run ./omd.exe %{dep:spec-375.md}))))
(rule
 (alias spec-375)
 (action (diff spec-375.html spec-375.html.new)))
(rule
 (action
  (with-stdout-to spec-376.html.new (run ./omd.exe %{dep:spec-376.md}))))
(rule
 (alias spec-376)
 (action (diff spec-376.html spec-376.html.new)))
(rule
 (action
  (with-stdout-to spec-377.html.new (run ./omd.exe %{dep:spec-377.md}))))
(rule
 (alias spec-377)
 (action (diff spec-377.html spec-377.html.new)))
(rule
 (action
  (with-stdout-to spec-378.html.new (run ./omd.exe %{dep:spec-378.md}))))
(rule
 (alias spec-378)
 (action (diff spec-378.html spec-378.html.new)))
(rule
 (action
  (with-stdout-to spec-379.html.new (run ./omd.exe %{dep:spec-379.md}))))
(rule
 (alias spec-379)
 (action (diff spec-379.html spec-379.html.new)))
(rule
 (action
  (with-stdout-to spec-380.html.new (run ./omd.exe %{dep:spec-380.md}))))
(rule
 (alias spec-380)
 (action (diff spec-380.html spec-380.html.new)))
(rule
 (action
  (with-stdout-to spec-381.html.new (run ./omd.exe %{dep:spec-381.md}))))
(rule
 (alias spec-381)
 (action (diff spec-381.html spec-381.html.new)))
(rule
 (action
  (with-stdout-to spec-382.html.new (run ./omd.exe %{dep:spec-382.md}))))
(rule
 (alias spec-382)
 (action (diff spec-382.html spec-382.html.new)))
(rule
 (action
  (with-stdout-to spec-383.html.new (run ./omd.exe %{dep:spec-383.md}))))
(rule
 (alias spec-383)
 (action (diff spec-383.html spec-383.html.new)))
(rule
 (action
  (with-stdout-to spec-384.html.new (run ./omd.exe %{dep:spec-384.md}))))
(rule
 (alias spec-384)
 (action (diff spec-384.html spec-384.html.new)))
(rule
 (action
  (with-stdout-to spec-385.html.new (run ./omd.exe %{dep:spec-385.md}))))
(rule
 (alias spec-385)
 (action (diff spec-385.html spec-385.html.new)))
(rule
 (action
  (with-stdout-to spec-386.html.new (run ./omd.exe %{dep:spec-386.md}))))
(rule
 (alias spec-386)
 (action (diff spec-386.html spec-386.html.new)))
(rule
 (action
  (with-stdout-to spec-387.html.new (run ./omd.exe %{dep:spec-387.md}))))
(rule
 (alias spec-387)
 (action (diff spec-387.html spec-387.html.new)))
(rule
 (action
  (with-stdout-to spec-388.html.new (run ./omd.exe %{dep:spec-388.md}))))
(rule
 (alias spec-388)
 (action (diff spec-388.html spec-388.html.new)))
(rule
 (action
  (with-stdout-to spec-389.html.new (run ./omd.exe %{dep:spec-389.md}))))
(rule
 (alias spec-389)
 (action (diff spec-389.html spec-389.html.new)))
(rule
 (action
  (with-stdout-to spec-390.html.new (run ./omd.exe %{dep:spec-390.md}))))
(rule
 (alias spec-390)
 (action (diff spec-390.html spec-390.html.new)))
(rule
 (action
  (with-stdout-to spec-391.html.new (run ./omd.exe %{dep:spec-391.md}))))
(rule
 (alias spec-391)
 (action (diff spec-391.html spec-391.html.new)))
(rule
 (action
  (with-stdout-to spec-392.html.new (run ./omd.exe %{dep:spec-392.md}))))
(rule
 (alias spec-392)
 (action (diff spec-392.html spec-392.html.new)))
(rule
 (action
  (with-stdout-to spec-393.html.new (run ./omd.exe %{dep:spec-393.md}))))
(rule
 (alias spec-393)
 (action (diff spec-393.html spec-393.html.new)))
(rule
 (action
  (with-stdout-to spec-394.html.new (run ./omd.exe %{dep:spec-394.md}))))
(rule
 (alias spec-394)
 (action (diff spec-394.html spec-394.html.new)))
(rule
 (action
  (with-stdout-to spec-395.html.new (run ./omd.exe %{dep:spec-395.md}))))
(rule
 (alias spec-395)
 (action (diff spec-395.html spec-395.html.new)))
(rule
 (action
  (with-stdout-to spec-396.html.new (run ./omd.exe %{dep:spec-396.md}))))
(rule
 (alias spec-396)
 (action (diff spec-396.html spec-396.html.new)))
(rule
 (action
  (with-stdout-to spec-397.html.new (run ./omd.exe %{dep:spec-397.md}))))
(rule
 (alias spec-397)
 (action (diff spec-397.html spec-397.html.new)))
(rule
 (action
  (with-stdout-to spec-398.html.new (run ./omd.exe %{dep:spec-398.md}))))
(rule
 (alias spec-398)
 (action (diff spec-398.html spec-398.html.new)))
(rule
 (action
  (with-stdout-to spec-399.html.new (run ./omd.exe %{dep:spec-399.md}))))
(rule
 (alias spec-399)
 (action (diff spec-399.html spec-399.html.new)))
(rule
 (action
  (with-stdout-to spec-400.html.new (run ./omd.exe %{dep:spec-400.md}))))
(rule
 (alias spec-400)
 (action (diff spec-400.html spec-400.html.new)))
(rule
 (action
  (with-stdout-to spec-401.html.new (run ./omd.exe %{dep:spec-401.md}))))
(rule
 (alias spec-401)
 (action (diff spec-401.html spec-401.html.new)))
(rule
 (action
  (with-stdout-to spec-402.html.new (run ./omd.exe %{dep:spec-402.md}))))
(rule
 (alias spec-402)
 (action (diff spec-402.html spec-402.html.new)))
(rule
 (action
  (with-stdout-to spec-403.html.new (run ./omd.exe %{dep:spec-403.md}))))
(rule
 (alias spec-403)
 (action (diff spec-403.html spec-403.html.new)))
(rule
 (action
  (with-stdout-to spec-404.html.new (run ./omd.exe %{dep:spec-404.md}))))
(rule
 (alias spec-404)
 (action (diff spec-404.html spec-404.html.new)))
(rule
 (action
  (with-stdout-to spec-405.html.new (run ./omd.exe %{dep:spec-405.md}))))
(rule
 (alias spec-405)
 (action (diff spec-405.html spec-405.html.new)))
(rule
 (action
  (with-stdout-to spec-406.html.new (run ./omd.exe %{dep:spec-406.md}))))
(rule
 (alias spec-406)
 (action (diff spec-406.html spec-406.html.new)))
(rule
 (action
  (with-stdout-to spec-407.html.new (run ./omd.exe %{dep:spec-407.md}))))
(rule
 (alias spec-407)
 (action (diff spec-407.html spec-407.html.new)))
(rule
 (action
  (with-stdout-to spec-408.html.new (run ./omd.exe %{dep:spec-408.md}))))
(rule
 (alias spec-408)
 (action (diff spec-408.html spec-408.html.new)))
(rule
 (action
  (with-stdout-to spec-409.html.new (run ./omd.exe %{dep:spec-409.md}))))
(rule
 (alias spec-409)
 (action (diff spec-409.html spec-409.html.new)))
(rule
 (action
  (with-stdout-to spec-410.html.new (run ./omd.exe %{dep:spec-410.md}))))
(rule
 (alias spec-410)
 (action (diff spec-410.html spec-410.html.new)))
(rule
 (action
  (with-stdout-to spec-411.html.new (run ./omd.exe %{dep:spec-411.md}))))
(rule
 (alias spec-411)
 (action (diff spec-411.html spec-411.html.new)))
(rule
 (action
  (with-stdout-to spec-412.html.new (run ./omd.exe %{dep:spec-412.md}))))
(rule
 (alias spec-412)
 (action (diff spec-412.html spec-412.html.new)))
(rule
 (action
  (with-stdout-to spec-413.html.new (run ./omd.exe %{dep:spec-413.md}))))
(rule
 (alias spec-413)
 (action (diff spec-413.html spec-413.html.new)))
(rule
 (action
  (with-stdout-to spec-414.html.new (run ./omd.exe %{dep:spec-414.md}))))
(rule
 (alias spec-414)
 (action (diff spec-414.html spec-414.html.new)))
(rule
 (action
  (with-stdout-to spec-415.html.new (run ./omd.exe %{dep:spec-415.md}))))
(rule
 (alias spec-415)
 (action (diff spec-415.html spec-415.html.new)))
(rule
 (action
  (with-stdout-to spec-416.html.new (run ./omd.exe %{dep:spec-416.md}))))
(rule
 (alias spec-416)
 (action (diff spec-416.html spec-416.html.new)))
(rule
 (action
  (with-stdout-to spec-417.html.new (run ./omd.exe %{dep:spec-417.md}))))
(rule
 (alias spec-417)
 (action (diff spec-417.html spec-417.html.new)))
(rule
 (action
  (with-stdout-to spec-418.html.new (run ./omd.exe %{dep:spec-418.md}))))
(rule
 (alias spec-418)
 (action (diff spec-418.html spec-418.html.new)))
(rule
 (action
  (with-stdout-to spec-419.html.new (run ./omd.exe %{dep:spec-419.md}))))
(rule
 (alias spec-419)
 (action (diff spec-419.html spec-419.html.new)))
(rule
 (action
  (with-stdout-to spec-420.html.new (run ./omd.exe %{dep:spec-420.md}))))
(rule
 (alias spec-420)
 (action (diff spec-420.html spec-420.html.new)))
(rule
 (action
  (with-stdout-to spec-421.html.new (run ./omd.exe %{dep:spec-421.md}))))
(rule
 (alias spec-421)
 (action (diff spec-421.html spec-421.html.new)))
(rule
 (action
  (with-stdout-to spec-422.html.new (run ./omd.exe %{dep:spec-422.md}))))
(rule
 (alias spec-422)
 (action (diff spec-422.html spec-422.html.new)))
(rule
 (action
  (with-stdout-to spec-423.html.new (run ./omd.exe %{dep:spec-423.md}))))
(rule
 (alias spec-423)
 (action (diff spec-423.html spec-423.html.new)))
(rule
 (action
  (with-stdout-to spec-424.html.new (run ./omd.exe %{dep:spec-424.md}))))
(rule
 (alias spec-424)
 (action (diff spec-424.html spec-424.html.new)))
(rule
 (action
  (with-stdout-to spec-425.html.new (run ./omd.exe %{dep:spec-425.md}))))
(rule
 (alias spec-425)
 (action (diff spec-425.html spec-425.html.new)))
(rule
 (action
  (with-stdout-to spec-426.html.new (run ./omd.exe %{dep:spec-426.md}))))
(rule
 (alias spec-426)
 (action (diff spec-426.html spec-426.html.new)))
(rule
 (action
  (with-stdout-to spec-427.html.new (run ./omd.exe %{dep:spec-427.md}))))
(rule
 (alias spec-427)
 (action (diff spec-427.html spec-427.html.new)))
(rule
 (action
  (with-stdout-to spec-428.html.new (run ./omd.exe %{dep:spec-428.md}))))
(rule
 (alias spec-428)
 (action (diff spec-428.html spec-428.html.new)))
(rule
 (action
  (with-stdout-to spec-429.html.new (run ./omd.exe %{dep:spec-429.md}))))
(rule
 (alias spec-429)
 (action (diff spec-429.html spec-429.html.new)))
(rule
 (action
  (with-stdout-to spec-430.html.new (run ./omd.exe %{dep:spec-430.md}))))
(rule
 (alias spec-430)
 (action (diff spec-430.html spec-430.html.new)))
(rule
 (action
  (with-stdout-to spec-431.html.new (run ./omd.exe %{dep:spec-431.md}))))
(rule
 (alias spec-431)
 (action (diff spec-431.html spec-431.html.new)))
(rule
 (action
  (with-stdout-to spec-432.html.new (run ./omd.exe %{dep:spec-432.md}))))
(rule
 (alias spec-432)
 (action (diff spec-432.html spec-432.html.new)))
(rule
 (action
  (with-stdout-to spec-433.html.new (run ./omd.exe %{dep:spec-433.md}))))
(rule
 (alias spec-433)
 (action (diff spec-433.html spec-433.html.new)))
(rule
 (action
  (with-stdout-to spec-434.html.new (run ./omd.exe %{dep:spec-434.md}))))
(rule
 (alias spec-434)
 (action (diff spec-434.html spec-434.html.new)))
(rule
 (action
  (with-stdout-to spec-435.html.new (run ./omd.exe %{dep:spec-435.md}))))
(rule
 (alias spec-435)
 (action (diff spec-435.html spec-435.html.new)))
(rule
 (action
  (with-stdout-to spec-436.html.new (run ./omd.exe %{dep:spec-436.md}))))
(rule
 (alias spec-436)
 (action (diff spec-436.html spec-436.html.new)))
(rule
 (action
  (with-stdout-to spec-437.html.new (run ./omd.exe %{dep:spec-437.md}))))
(rule
 (alias spec-437)
 (action (diff spec-437.html spec-437.html.new)))
(rule
 (action
  (with-stdout-to spec-438.html.new (run ./omd.exe %{dep:spec-438.md}))))
(rule
 (alias spec-438)
 (action (diff spec-438.html spec-438.html.new)))
(rule
 (action
  (with-stdout-to spec-439.html.new (run ./omd.exe %{dep:spec-439.md}))))
(rule
 (alias spec-439)
 (action (diff spec-439.html spec-439.html.new)))
(rule
 (action
  (with-stdout-to spec-440.html.new (run ./omd.exe %{dep:spec-440.md}))))
(rule
 (alias spec-440)
 (action (diff spec-440.html spec-440.html.new)))
(rule
 (action
  (with-stdout-to spec-441.html.new (run ./omd.exe %{dep:spec-441.md}))))
(rule
 (alias spec-441)
 (action (diff spec-441.html spec-441.html.new)))
(rule
 (action
  (with-stdout-to spec-442.html.new (run ./omd.exe %{dep:spec-442.md}))))
(rule
 (alias spec-442)
 (action (diff spec-442.html spec-442.html.new)))
(rule
 (action
  (with-stdout-to spec-443.html.new (run ./omd.exe %{dep:spec-443.md}))))
(rule
 (alias spec-443)
 (action (diff spec-443.html spec-443.html.new)))
(rule
 (action
  (with-stdout-to spec-444.html.new (run ./omd.exe %{dep:spec-444.md}))))
(rule
 (alias spec-444)
 (action (diff spec-444.html spec-444.html.new)))
(rule
 (action
  (with-stdout-to spec-445.html.new (run ./omd.exe %{dep:spec-445.md}))))
(rule
 (alias spec-445)
 (action (diff spec-445.html spec-445.html.new)))
(rule
 (action
  (with-stdout-to spec-446.html.new (run ./omd.exe %{dep:spec-446.md}))))
(rule
 (alias spec-446)
 (action (diff spec-446.html spec-446.html.new)))
(rule
 (action
  (with-stdout-to spec-447.html.new (run ./omd.exe %{dep:spec-447.md}))))
(rule
 (alias spec-447)
 (action (diff spec-447.html spec-447.html.new)))
(rule
 (action
  (with-stdout-to spec-448.html.new (run ./omd.exe %{dep:spec-448.md}))))
(rule
 (alias spec-448)
 (action (diff spec-448.html spec-448.html.new)))
(rule
 (action
  (with-stdout-to spec-449.html.new (run ./omd.exe %{dep:spec-449.md}))))
(rule
 (alias spec-449)
 (action (diff spec-449.html spec-449.html.new)))
(rule
 (action
  (with-stdout-to spec-450.html.new (run ./omd.exe %{dep:spec-450.md}))))
(rule
 (alias spec-450)
 (action (diff spec-450.html spec-450.html.new)))
(rule
 (action
  (with-stdout-to spec-451.html.new (run ./omd.exe %{dep:spec-451.md}))))
(rule
 (alias spec-451)
 (action (diff spec-451.html spec-451.html.new)))
(rule
 (action
  (with-stdout-to spec-452.html.new (run ./omd.exe %{dep:spec-452.md}))))
(rule
 (alias spec-452)
 (action (diff spec-452.html spec-452.html.new)))
(rule
 (action
  (with-stdout-to spec-453.html.new (run ./omd.exe %{dep:spec-453.md}))))
(rule
 (alias spec-453)
 (action (diff spec-453.html spec-453.html.new)))
(rule
 (action
  (with-stdout-to spec-454.html.new (run ./omd.exe %{dep:spec-454.md}))))
(rule
 (alias spec-454)
 (action (diff spec-454.html spec-454.html.new)))
(rule
 (action
  (with-stdout-to spec-455.html.new (run ./omd.exe %{dep:spec-455.md}))))
(rule
 (alias spec-455)
 (action (diff spec-455.html spec-455.html.new)))
(rule
 (action
  (with-stdout-to spec-456.html.new (run ./omd.exe %{dep:spec-456.md}))))
(rule
 (alias spec-456)
 (action (diff spec-456.html spec-456.html.new)))
(rule
 (action
  (with-stdout-to spec-457.html.new (run ./omd.exe %{dep:spec-457.md}))))
(rule
 (alias spec-457)
 (action (diff spec-457.html spec-457.html.new)))
(rule
 (action
  (with-stdout-to spec-458.html.new (run ./omd.exe %{dep:spec-458.md}))))
(rule
 (alias spec-458)
 (action (diff spec-458.html spec-458.html.new)))
(rule
 (action
  (with-stdout-to spec-459.html.new (run ./omd.exe %{dep:spec-459.md}))))
(rule
 (alias spec-459)
 (action (diff spec-459.html spec-459.html.new)))
(rule
 (action
  (with-stdout-to spec-460.html.new (run ./omd.exe %{dep:spec-460.md}))))
(rule
 (alias spec-460)
 (action (diff spec-460.html spec-460.html.new)))
(rule
 (action
  (with-stdout-to spec-461.html.new (run ./omd.exe %{dep:spec-461.md}))))
(rule
 (alias spec-461)
 (action (diff spec-461.html spec-461.html.new)))
(rule
 (action
  (with-stdout-to spec-462.html.new (run ./omd.exe %{dep:spec-462.md}))))
(rule
 (alias spec-462)
 (action (diff spec-462.html spec-462.html.new)))
(rule
 (action
  (with-stdout-to spec-463.html.new (run ./omd.exe %{dep:spec-463.md}))))
(rule
 (alias spec-463)
 (action (diff spec-463.html spec-463.html.new)))
(rule
 (action
  (with-stdout-to spec-464.html.new (run ./omd.exe %{dep:spec-464.md}))))
(rule
 (alias spec-464)
 (action (diff spec-464.html spec-464.html.new)))
(rule
 (action
  (with-stdout-to spec-465.html.new (run ./omd.exe %{dep:spec-465.md}))))
(rule
 (alias spec-465)
 (action (diff spec-465.html spec-465.html.new)))
(rule
 (action
  (with-stdout-to spec-466.html.new (run ./omd.exe %{dep:spec-466.md}))))
(rule
 (alias spec-466)
 (action (diff spec-466.html spec-466.html.new)))
(rule
 (action
  (with-stdout-to spec-467.html.new (run ./omd.exe %{dep:spec-467.md}))))
(rule
 (alias spec-467)
 (action (diff spec-467.html spec-467.html.new)))
(rule
 (action
  (with-stdout-to spec-468.html.new (run ./omd.exe %{dep:spec-468.md}))))
(rule
 (alias spec-468)
 (action (diff spec-468.html spec-468.html.new)))
(rule
 (action
  (with-stdout-to spec-469.html.new (run ./omd.exe %{dep:spec-469.md}))))
(rule
 (alias spec-469)
 (action (diff spec-469.html spec-469.html.new)))
(rule
 (action
  (with-stdout-to spec-470.html.new (run ./omd.exe %{dep:spec-470.md}))))
(rule
 (alias spec-470)
 (action (diff spec-470.html spec-470.html.new)))
(rule
 (action
  (with-stdout-to spec-471.html.new (run ./omd.exe %{dep:spec-471.md}))))
(rule
 (alias spec-471)
 (action (diff spec-471.html spec-471.html.new)))
(rule
 (action
  (with-stdout-to spec-472.html.new (run ./omd.exe %{dep:spec-472.md}))))
(rule
 (alias spec-472)
 (action (diff spec-472.html spec-472.html.new)))
(rule
 (action
  (with-stdout-to spec-473.html.new (run ./omd.exe %{dep:spec-473.md}))))
(rule
 (alias spec-473)
 (action (diff spec-473.html spec-473.html.new)))
(rule
 (action
  (with-stdout-to spec-474.html.new (run ./omd.exe %{dep:spec-474.md}))))
(rule
 (alias spec-474)
 (action (diff spec-474.html spec-474.html.new)))
(rule
 (action
  (with-stdout-to spec-475.html.new (run ./omd.exe %{dep:spec-475.md}))))
(rule
 (alias spec-475)
 (action (diff spec-475.html spec-475.html.new)))
(rule
 (action
  (with-stdout-to spec-476.html.new (run ./omd.exe %{dep:spec-476.md}))))
(rule
 (alias spec-476)
 (action (diff spec-476.html spec-476.html.new)))
(rule
 (action
  (with-stdout-to spec-477.html.new (run ./omd.exe %{dep:spec-477.md}))))
(rule
 (alias spec-477)
 (action (diff spec-477.html spec-477.html.new)))
(rule
 (action
  (with-stdout-to spec-478.html.new (run ./omd.exe %{dep:spec-478.md}))))
(rule
 (alias spec-478)
 (action (diff spec-478.html spec-478.html.new)))
(rule
 (action
  (with-stdout-to spec-479.html.new (run ./omd.exe %{dep:spec-479.md}))))
(rule
 (alias spec-479)
 (action (diff spec-479.html spec-479.html.new)))
(rule
 (action
  (with-stdout-to spec-480.html.new (run ./omd.exe %{dep:spec-480.md}))))
(rule
 (alias spec-480)
 (action (diff spec-480.html spec-480.html.new)))
(rule
 (action
  (with-stdout-to spec-481.html.new (run ./omd.exe %{dep:spec-481.md}))))
(rule
 (alias spec-481)
 (action (diff spec-481.html spec-481.html.new)))
(rule
 (action
  (with-stdout-to spec-482.html.new (run ./omd.exe %{dep:spec-482.md}))))
(rule
 (alias spec-482)
 (action (diff spec-482.html spec-482.html.new)))
(rule
 (action
  (with-stdout-to spec-483.html.new (run ./omd.exe %{dep:spec-483.md}))))
(rule
 (alias spec-483)
 (action (diff spec-483.html spec-483.html.new)))
(rule
 (action
  (with-stdout-to spec-484.html.new (run ./omd.exe %{dep:spec-484.md}))))
(rule
 (alias spec-484)
 (action (diff spec-484.html spec-484.html.new)))
(rule
 (action
  (with-stdout-to spec-485.html.new (run ./omd.exe %{dep:spec-485.md}))))
(rule
 (alias spec-485)
 (action (diff spec-485.html spec-485.html.new)))
(rule
 (action
  (with-stdout-to spec-486.html.new (run ./omd.exe %{dep:spec-486.md}))))
(rule
 (alias spec-486)
 (action (diff spec-486.html spec-486.html.new)))
(rule
 (action
  (with-stdout-to spec-487.html.new (run ./omd.exe %{dep:spec-487.md}))))
(rule
 (alias spec-487)
 (action (diff spec-487.html spec-487.html.new)))
(rule
 (action
  (with-stdout-to spec-488.html.new (run ./omd.exe %{dep:spec-488.md}))))
(rule
 (alias spec-488)
 (action (diff spec-488.html spec-488.html.new)))
(rule
 (action
  (with-stdout-to spec-489.html.new (run ./omd.exe %{dep:spec-489.md}))))
(rule
 (alias spec-489)
 (action (diff spec-489.html spec-489.html.new)))
(rule
 (action
  (with-stdout-to spec-490.html.new (run ./omd.exe %{dep:spec-490.md}))))
(rule
 (alias spec-490)
 (action (diff spec-490.html spec-490.html.new)))
(rule
 (action
  (with-stdout-to spec-491.html.new (run ./omd.exe %{dep:spec-491.md}))))
(rule
 (alias spec-491)
 (action (diff spec-491.html spec-491.html.new)))
(rule
 (action
  (with-stdout-to spec-492.html.new (run ./omd.exe %{dep:spec-492.md}))))
(rule
 (alias spec-492)
 (action (diff spec-492.html spec-492.html.new)))
(rule
 (action
  (with-stdout-to spec-493.html.new (run ./omd.exe %{dep:spec-493.md}))))
(rule
 (alias spec-493)
 (action (diff spec-493.html spec-493.html.new)))
(rule
 (action
  (with-stdout-to spec-494.html.new (run ./omd.exe %{dep:spec-494.md}))))
(rule
 (alias spec-494)
 (action (diff spec-494.html spec-494.html.new)))
(rule
 (action
  (with-stdout-to spec-495.html.new (run ./omd.exe %{dep:spec-495.md}))))
(rule
 (alias spec-495)
 (action (diff spec-495.html spec-495.html.new)))
(rule
 (action
  (with-stdout-to spec-496.html.new (run ./omd.exe %{dep:spec-496.md}))))
(rule
 (alias spec-496)
 (action (diff spec-496.html spec-496.html.new)))
(rule
 (action
  (with-stdout-to spec-497.html.new (run ./omd.exe %{dep:spec-497.md}))))
(rule
 (alias spec-497)
 (action (diff spec-497.html spec-497.html.new)))
(rule
 (action
  (with-stdout-to spec-498.html.new (run ./omd.exe %{dep:spec-498.md}))))
(rule
 (alias spec-498)
 (action (diff spec-498.html spec-498.html.new)))
(rule
 (action
  (with-stdout-to spec-499.html.new (run ./omd.exe %{dep:spec-499.md}))))
(rule
 (alias spec-499)
 (action (diff spec-499.html spec-499.html.new)))
(rule
 (action
  (with-stdout-to spec-500.html.new (run ./omd.exe %{dep:spec-500.md}))))
(rule
 (alias spec-500)
 (action (diff spec-500.html spec-500.html.new)))
(rule
 (action
  (with-stdout-to spec-501.html.new (run ./omd.exe %{dep:spec-501.md}))))
(rule
 (alias spec-501)
 (action (diff spec-501.html spec-501.html.new)))
(rule
 (action
  (with-stdout-to spec-502.html.new (run ./omd.exe %{dep:spec-502.md}))))
(rule
 (alias spec-502)
 (action (diff spec-502.html spec-502.html.new)))
(rule
 (action
  (with-stdout-to spec-503.html.new (run ./omd.exe %{dep:spec-503.md}))))
(rule
 (alias spec-503)
 (action (diff spec-503.html spec-503.html.new)))
(rule
 (action
  (with-stdout-to spec-504.html.new (run ./omd.exe %{dep:spec-504.md}))))
(rule
 (alias spec-504)
 (action (diff spec-504.html spec-504.html.new)))
(rule
 (action
  (with-stdout-to spec-505.html.new (run ./omd.exe %{dep:spec-505.md}))))
(rule
 (alias spec-505)
 (action (diff spec-505.html spec-505.html.new)))
(rule
 (action
  (with-stdout-to spec-506.html.new (run ./omd.exe %{dep:spec-506.md}))))
(rule
 (alias spec-506)
 (action (diff spec-506.html spec-506.html.new)))
(rule
 (action
  (with-stdout-to spec-507.html.new (run ./omd.exe %{dep:spec-507.md}))))
(rule
 (alias spec-507)
 (action (diff spec-507.html spec-507.html.new)))
(rule
 (action
  (with-stdout-to spec-508.html.new (run ./omd.exe %{dep:spec-508.md}))))
(rule
 (alias spec-508)
 (action (diff spec-508.html spec-508.html.new)))
(rule
 (action
  (with-stdout-to spec-509.html.new (run ./omd.exe %{dep:spec-509.md}))))
(rule
 (alias spec-509)
 (action (diff spec-509.html spec-509.html.new)))
(rule
 (action
  (with-stdout-to spec-510.html.new (run ./omd.exe %{dep:spec-510.md}))))
(rule
 (alias spec-510)
 (action (diff spec-510.html spec-510.html.new)))
(rule
 (action
  (with-stdout-to spec-511.html.new (run ./omd.exe %{dep:spec-511.md}))))
(rule
 (alias spec-511)
 (action (diff spec-511.html spec-511.html.new)))
(rule
 (action
  (with-stdout-to spec-512.html.new (run ./omd.exe %{dep:spec-512.md}))))
(rule
 (alias spec-512)
 (action (diff spec-512.html spec-512.html.new)))
(rule
 (action
  (with-stdout-to spec-513.html.new (run ./omd.exe %{dep:spec-513.md}))))
(rule
 (alias spec-513)
 (action (diff spec-513.html spec-513.html.new)))
(rule
 (action
  (with-stdout-to spec-514.html.new (run ./omd.exe %{dep:spec-514.md}))))
(rule
 (alias spec-514)
 (action (diff spec-514.html spec-514.html.new)))
(rule
 (action
  (with-stdout-to spec-515.html.new (run ./omd.exe %{dep:spec-515.md}))))
(rule
 (alias spec-515)
 (action (diff spec-515.html spec-515.html.new)))
(rule
 (action
  (with-stdout-to spec-516.html.new (run ./omd.exe %{dep:spec-516.md}))))
(rule
 (alias spec-516)
 (action (diff spec-516.html spec-516.html.new)))
(rule
 (action
  (with-stdout-to spec-517.html.new (run ./omd.exe %{dep:spec-517.md}))))
(rule
 (alias spec-517)
 (action (diff spec-517.html spec-517.html.new)))
(rule
 (action
  (with-stdout-to spec-518.html.new (run ./omd.exe %{dep:spec-518.md}))))
(rule
 (alias spec-518)
 (action (diff spec-518.html spec-518.html.new)))
(rule
 (action
  (with-stdout-to spec-519.html.new (run ./omd.exe %{dep:spec-519.md}))))
(rule
 (alias spec-519)
 (action (diff spec-519.html spec-519.html.new)))
(rule
 (action
  (with-stdout-to spec-520.html.new (run ./omd.exe %{dep:spec-520.md}))))
(rule
 (alias spec-520)
 (action (diff spec-520.html spec-520.html.new)))
(rule
 (action
  (with-stdout-to spec-521.html.new (run ./omd.exe %{dep:spec-521.md}))))
(rule
 (alias spec-521)
 (action (diff spec-521.html spec-521.html.new)))
(rule
 (action
  (with-stdout-to spec-522.html.new (run ./omd.exe %{dep:spec-522.md}))))
(rule
 (alias spec-522)
 (action (diff spec-522.html spec-522.html.new)))
(rule
 (action
  (with-stdout-to spec-523.html.new (run ./omd.exe %{dep:spec-523.md}))))
(rule
 (alias spec-523)
 (action (diff spec-523.html spec-523.html.new)))
(rule
 (action
  (with-stdout-to spec-524.html.new (run ./omd.exe %{dep:spec-524.md}))))
(rule
 (alias spec-524)
 (action (diff spec-524.html spec-524.html.new)))
(rule
 (action
  (with-stdout-to spec-525.html.new (run ./omd.exe %{dep:spec-525.md}))))
(rule
 (alias spec-525)
 (action (diff spec-525.html spec-525.html.new)))
(rule
 (action
  (with-stdout-to spec-526.html.new (run ./omd.exe %{dep:spec-526.md}))))
(rule
 (alias spec-526)
 (action (diff spec-526.html spec-526.html.new)))
(rule
 (action
  (with-stdout-to spec-527.html.new (run ./omd.exe %{dep:spec-527.md}))))
(rule
 (alias spec-527)
 (action (diff spec-527.html spec-527.html.new)))
(rule
 (action
  (with-stdout-to spec-528.html.new (run ./omd.exe %{dep:spec-528.md}))))
(rule
 (alias spec-528)
 (action (diff spec-528.html spec-528.html.new)))
(rule
 (action
  (with-stdout-to spec-529.html.new (run ./omd.exe %{dep:spec-529.md}))))
(rule
 (alias spec-529)
 (action (diff spec-529.html spec-529.html.new)))
(rule
 (action
  (with-stdout-to spec-530.html.new (run ./omd.exe %{dep:spec-530.md}))))
(rule
 (alias spec-530)
 (action (diff spec-530.html spec-530.html.new)))
(rule
 (action
  (with-stdout-to spec-531.html.new (run ./omd.exe %{dep:spec-531.md}))))
(rule
 (alias spec-531)
 (action (diff spec-531.html spec-531.html.new)))
(rule
 (action
  (with-stdout-to spec-532.html.new (run ./omd.exe %{dep:spec-532.md}))))
(rule
 (alias spec-532)
 (action (diff spec-532.html spec-532.html.new)))
(rule
 (action
  (with-stdout-to spec-533.html.new (run ./omd.exe %{dep:spec-533.md}))))
(rule
 (alias spec-533)
 (action (diff spec-533.html spec-533.html.new)))
(rule
 (action
  (with-stdout-to spec-534.html.new (run ./omd.exe %{dep:spec-534.md}))))
(rule
 (alias spec-534)
 (action (diff spec-534.html spec-534.html.new)))
(rule
 (action
  (with-stdout-to spec-535.html.new (run ./omd.exe %{dep:spec-535.md}))))
(rule
 (alias spec-535)
 (action (diff spec-535.html spec-535.html.new)))
(rule
 (action
  (with-stdout-to spec-536.html.new (run ./omd.exe %{dep:spec-536.md}))))
(rule
 (alias spec-536)
 (action (diff spec-536.html spec-536.html.new)))
(rule
 (action
  (with-stdout-to spec-537.html.new (run ./omd.exe %{dep:spec-537.md}))))
(rule
 (alias spec-537)
 (action (diff spec-537.html spec-537.html.new)))
(rule
 (action
  (with-stdout-to spec-538.html.new (run ./omd.exe %{dep:spec-538.md}))))
(rule
 (alias spec-538)
 (action (diff spec-538.html spec-538.html.new)))
(rule
 (action
  (with-stdout-to spec-539.html.new (run ./omd.exe %{dep:spec-539.md}))))
(rule
 (alias spec-539)
 (action (diff spec-539.html spec-539.html.new)))
(rule
 (action
  (with-stdout-to spec-540.html.new (run ./omd.exe %{dep:spec-540.md}))))
(rule
 (alias spec-540)
 (action (diff spec-540.html spec-540.html.new)))
(rule
 (action
  (with-stdout-to spec-541.html.new (run ./omd.exe %{dep:spec-541.md}))))
(rule
 (alias spec-541)
 (action (diff spec-541.html spec-541.html.new)))
(rule
 (action
  (with-stdout-to spec-542.html.new (run ./omd.exe %{dep:spec-542.md}))))
(rule
 (alias spec-542)
 (action (diff spec-542.html spec-542.html.new)))
(rule
 (action
  (with-stdout-to spec-543.html.new (run ./omd.exe %{dep:spec-543.md}))))
(rule
 (alias spec-543)
 (action (diff spec-543.html spec-543.html.new)))
(rule
 (action
  (with-stdout-to spec-544.html.new (run ./omd.exe %{dep:spec-544.md}))))
(rule
 (alias spec-544)
 (action (diff spec-544.html spec-544.html.new)))
(rule
 (action
  (with-stdout-to spec-545.html.new (run ./omd.exe %{dep:spec-545.md}))))
(rule
 (alias spec-545)
 (action (diff spec-545.html spec-545.html.new)))
(rule
 (action
  (with-stdout-to spec-546.html.new (run ./omd.exe %{dep:spec-546.md}))))
(rule
 (alias spec-546)
 (action (diff spec-546.html spec-546.html.new)))
(rule
 (action
  (with-stdout-to spec-547.html.new (run ./omd.exe %{dep:spec-547.md}))))
(rule
 (alias spec-547)
 (action (diff spec-547.html spec-547.html.new)))
(rule
 (action
  (with-stdout-to spec-548.html.new (run ./omd.exe %{dep:spec-548.md}))))
(rule
 (alias spec-548)
 (action (diff spec-548.html spec-548.html.new)))
(rule
 (action
  (with-stdout-to spec-549.html.new (run ./omd.exe %{dep:spec-549.md}))))
(rule
 (alias spec-549)
 (action (diff spec-549.html spec-549.html.new)))
(rule
 (action
  (with-stdout-to spec-550.html.new (run ./omd.exe %{dep:spec-550.md}))))
(rule
 (alias spec-550)
 (action (diff spec-550.html spec-550.html.new)))
(rule
 (action
  (with-stdout-to spec-551.html.new (run ./omd.exe %{dep:spec-551.md}))))
(rule
 (alias spec-551)
 (action (diff spec-551.html spec-551.html.new)))
(rule
 (action
  (with-stdout-to spec-552.html.new (run ./omd.exe %{dep:spec-552.md}))))
(rule
 (alias spec-552)
 (action (diff spec-552.html spec-552.html.new)))
(rule
 (action
  (with-stdout-to spec-553.html.new (run ./omd.exe %{dep:spec-553.md}))))
(rule
 (alias spec-553)
 (action (diff spec-553.html spec-553.html.new)))
(rule
 (action
  (with-stdout-to spec-554.html.new (run ./omd.exe %{dep:spec-554.md}))))
(rule
 (alias spec-554)
 (action (diff spec-554.html spec-554.html.new)))
(rule
 (action
  (with-stdout-to spec-555.html.new (run ./omd.exe %{dep:spec-555.md}))))
(rule
 (alias spec-555)
 (action (diff spec-555.html spec-555.html.new)))
(rule
 (action
  (with-stdout-to spec-556.html.new (run ./omd.exe %{dep:spec-556.md}))))
(rule
 (alias spec-556)
 (action (diff spec-556.html spec-556.html.new)))
(rule
 (action
  (with-stdout-to spec-557.html.new (run ./omd.exe %{dep:spec-557.md}))))
(rule
 (alias spec-557)
 (action (diff spec-557.html spec-557.html.new)))
(rule
 (action
  (with-stdout-to spec-558.html.new (run ./omd.exe %{dep:spec-558.md}))))
(rule
 (alias spec-558)
 (action (diff spec-558.html spec-558.html.new)))
(rule
 (action
  (with-stdout-to spec-559.html.new (run ./omd.exe %{dep:spec-559.md}))))
(rule
 (alias spec-559)
 (action (diff spec-559.html spec-559.html.new)))
(rule
 (action
  (with-stdout-to spec-560.html.new (run ./omd.exe %{dep:spec-560.md}))))
(rule
 (alias spec-560)
 (action (diff spec-560.html spec-560.html.new)))
(rule
 (action
  (with-stdout-to spec-561.html.new (run ./omd.exe %{dep:spec-561.md}))))
(rule
 (alias spec-561)
 (action (diff spec-561.html spec-561.html.new)))
(rule
 (action
  (with-stdout-to spec-562.html.new (run ./omd.exe %{dep:spec-562.md}))))
(rule
 (alias spec-562)
 (action (diff spec-562.html spec-562.html.new)))
(rule
 (action
  (with-stdout-to spec-563.html.new (run ./omd.exe %{dep:spec-563.md}))))
(rule
 (alias spec-563)
 (action (diff spec-563.html spec-563.html.new)))
(rule
 (action
  (with-stdout-to spec-564.html.new (run ./omd.exe %{dep:spec-564.md}))))
(rule
 (alias spec-564)
 (action (diff spec-564.html spec-564.html.new)))
(rule
 (action
  (with-stdout-to spec-565.html.new (run ./omd.exe %{dep:spec-565.md}))))
(rule
 (alias spec-565)
 (action (diff spec-565.html spec-565.html.new)))
(rule
 (action
  (with-stdout-to spec-566.html.new (run ./omd.exe %{dep:spec-566.md}))))
(rule
 (alias spec-566)
 (action (diff spec-566.html spec-566.html.new)))
(rule
 (action
  (with-stdout-to spec-567.html.new (run ./omd.exe %{dep:spec-567.md}))))
(rule
 (alias spec-567)
 (action (diff spec-567.html spec-567.html.new)))
(rule
 (action
  (with-stdout-to spec-568.html.new (run ./omd.exe %{dep:spec-568.md}))))
(rule
 (alias spec-568)
 (action (diff spec-568.html spec-568.html.new)))
(rule
 (action
  (with-stdout-to spec-569.html.new (run ./omd.exe %{dep:spec-569.md}))))
(rule
 (alias spec-569)
 (action (diff spec-569.html spec-569.html.new)))
(rule
 (action
  (with-stdout-to spec-570.html.new (run ./omd.exe %{dep:spec-570.md}))))
(rule
 (alias spec-570)
 (action (diff spec-570.html spec-570.html.new)))
(rule
 (action
  (with-stdout-to spec-571.html.new (run ./omd.exe %{dep:spec-571.md}))))
(rule
 (alias spec-571)
 (action (diff spec-571.html spec-571.html.new)))
(rule
 (action
  (with-stdout-to spec-572.html.new (run ./omd.exe %{dep:spec-572.md}))))
(rule
 (alias spec-572)
 (action (diff spec-572.html spec-572.html.new)))
(rule
 (action
  (with-stdout-to spec-573.html.new (run ./omd.exe %{dep:spec-573.md}))))
(rule
 (alias spec-573)
 (action (diff spec-573.html spec-573.html.new)))
(rule
 (action
  (with-stdout-to spec-574.html.new (run ./omd.exe %{dep:spec-574.md}))))
(rule
 (alias spec-574)
 (action (diff spec-574.html spec-574.html.new)))
(rule
 (action
  (with-stdout-to spec-575.html.new (run ./omd.exe %{dep:spec-575.md}))))
(rule
 (alias spec-575)
 (action (diff spec-575.html spec-575.html.new)))
(rule
 (action
  (with-stdout-to spec-576.html.new (run ./omd.exe %{dep:spec-576.md}))))
(rule
 (alias spec-576)
 (action (diff spec-576.html spec-576.html.new)))
(rule
 (action
  (with-stdout-to spec-577.html.new (run ./omd.exe %{dep:spec-577.md}))))
(rule
 (alias spec-577)
 (action (diff spec-577.html spec-577.html.new)))
(rule
 (action
  (with-stdout-to spec-578.html.new (run ./omd.exe %{dep:spec-578.md}))))
(rule
 (alias spec-578)
 (action (diff spec-578.html spec-578.html.new)))
(rule
 (action
  (with-stdout-to spec-579.html.new (run ./omd.exe %{dep:spec-579.md}))))
(rule
 (alias spec-579)
 (action (diff spec-579.html spec-579.html.new)))
(rule
 (action
  (with-stdout-to spec-580.html.new (run ./omd.exe %{dep:spec-580.md}))))
(rule
 (alias spec-580)
 (action (diff spec-580.html spec-580.html.new)))
(rule
 (action
  (with-stdout-to spec-581.html.new (run ./omd.exe %{dep:spec-581.md}))))
(rule
 (alias spec-581)
 (action (diff spec-581.html spec-581.html.new)))
(rule
 (action
  (with-stdout-to spec-582.html.new (run ./omd.exe %{dep:spec-582.md}))))
(rule
 (alias spec-582)
 (action (diff spec-582.html spec-582.html.new)))
(rule
 (action
  (with-stdout-to spec-583.html.new (run ./omd.exe %{dep:spec-583.md}))))
(rule
 (alias spec-583)
 (action (diff spec-583.html spec-583.html.new)))
(rule
 (action
  (with-stdout-to spec-584.html.new (run ./omd.exe %{dep:spec-584.md}))))
(rule
 (alias spec-584)
 (action (diff spec-584.html spec-584.html.new)))
(rule
 (action
  (with-stdout-to spec-585.html.new (run ./omd.exe %{dep:spec-585.md}))))
(rule
 (alias spec-585)
 (action (diff spec-585.html spec-585.html.new)))
(rule
 (action
  (with-stdout-to spec-586.html.new (run ./omd.exe %{dep:spec-586.md}))))
(rule
 (alias spec-586)
 (action (diff spec-586.html spec-586.html.new)))
(rule
 (action
  (with-stdout-to spec-587.html.new (run ./omd.exe %{dep:spec-587.md}))))
(rule
 (alias spec-587)
 (action (diff spec-587.html spec-587.html.new)))
(rule
 (action
  (with-stdout-to spec-588.html.new (run ./omd.exe %{dep:spec-588.md}))))
(rule
 (alias spec-588)
 (action (diff spec-588.html spec-588.html.new)))
(rule
 (action
  (with-stdout-to spec-589.html.new (run ./omd.exe %{dep:spec-589.md}))))
(rule
 (alias spec-589)
 (action (diff spec-589.html spec-589.html.new)))
(rule
 (action
  (with-stdout-to spec-590.html.new (run ./omd.exe %{dep:spec-590.md}))))
(rule
 (alias spec-590)
 (action (diff spec-590.html spec-590.html.new)))
(rule
 (action
  (with-stdout-to spec-591.html.new (run ./omd.exe %{dep:spec-591.md}))))
(rule
 (alias spec-591)
 (action (diff spec-591.html spec-591.html.new)))
(rule
 (action
  (with-stdout-to spec-592.html.new (run ./omd.exe %{dep:spec-592.md}))))
(rule
 (alias spec-592)
 (action (diff spec-592.html spec-592.html.new)))
(rule
 (action
  (with-stdout-to spec-593.html.new (run ./omd.exe %{dep:spec-593.md}))))
(rule
 (alias spec-593)
 (action (diff spec-593.html spec-593.html.new)))
(rule
 (action
  (with-stdout-to spec-594.html.new (run ./omd.exe %{dep:spec-594.md}))))
(rule
 (alias spec-594)
 (action (diff spec-594.html spec-594.html.new)))
(rule
 (action
  (with-stdout-to spec-595.html.new (run ./omd.exe %{dep:spec-595.md}))))
(rule
 (alias spec-595)
 (action (diff spec-595.html spec-595.html.new)))
(rule
 (action
  (with-stdout-to spec-596.html.new (run ./omd.exe %{dep:spec-596.md}))))
(rule
 (alias spec-596)
 (action (diff spec-596.html spec-596.html.new)))
(rule
 (action
  (with-stdout-to spec-597.html.new (run ./omd.exe %{dep:spec-597.md}))))
(rule
 (alias spec-597)
 (action (diff spec-597.html spec-597.html.new)))
(rule
 (action
  (with-stdout-to spec-598.html.new (run ./omd.exe %{dep:spec-598.md}))))
(rule
 (alias spec-598)
 (action (diff spec-598.html spec-598.html.new)))
(rule
 (action
  (with-stdout-to spec-599.html.new (run ./omd.exe %{dep:spec-599.md}))))
(rule
 (alias spec-599)
 (action (diff spec-599.html spec-599.html.new)))
(rule
 (action
  (with-stdout-to spec-600.html.new (run ./omd.exe %{dep:spec-600.md}))))
(rule
 (alias spec-600)
 (action (diff spec-600.html spec-600.html.new)))
(rule
 (action
  (with-stdout-to spec-601.html.new (run ./omd.exe %{dep:spec-601.md}))))
(rule
 (alias spec-601)
 (action (diff spec-601.html spec-601.html.new)))
(rule
 (action
  (with-stdout-to spec-602.html.new (run ./omd.exe %{dep:spec-602.md}))))
(rule
 (alias spec-602)
 (action (diff spec-602.html spec-602.html.new)))
(rule
 (action
  (with-stdout-to spec-603.html.new (run ./omd.exe %{dep:spec-603.md}))))
(rule
 (alias spec-603)
 (action (diff spec-603.html spec-603.html.new)))
(rule
 (action
  (with-stdout-to spec-604.html.new (run ./omd.exe %{dep:spec-604.md}))))
(rule
 (alias spec-604)
 (action (diff spec-604.html spec-604.html.new)))
(rule
 (action
  (with-stdout-to spec-605.html.new (run ./omd.exe %{dep:spec-605.md}))))
(rule
 (alias spec-605)
 (action (diff spec-605.html spec-605.html.new)))
(rule
 (action
  (with-stdout-to spec-606.html.new (run ./omd.exe %{dep:spec-606.md}))))
(rule
 (alias spec-606)
 (action (diff spec-606.html spec-606.html.new)))
(rule
 (action
  (with-stdout-to spec-607.html.new (run ./omd.exe %{dep:spec-607.md}))))
(rule
 (alias spec-607)
 (action (diff spec-607.html spec-607.html.new)))
(rule
 (action
  (with-stdout-to spec-608.html.new (run ./omd.exe %{dep:spec-608.md}))))
(rule
 (alias spec-608)
 (action (diff spec-608.html spec-608.html.new)))
(rule
 (action
  (with-stdout-to spec-609.html.new (run ./omd.exe %{dep:spec-609.md}))))
(rule
 (alias spec-609)
 (action (diff spec-609.html spec-609.html.new)))
(rule
 (action
  (with-stdout-to spec-610.html.new (run ./omd.exe %{dep:spec-610.md}))))
(rule
 (alias spec-610)
 (action (diff spec-610.html spec-610.html.new)))
(rule
 (action
  (with-stdout-to spec-611.html.new (run ./omd.exe %{dep:spec-611.md}))))
(rule
 (alias spec-611)
 (action (diff spec-611.html spec-611.html.new)))
(rule
 (action
  (with-stdout-to spec-612.html.new (run ./omd.exe %{dep:spec-612.md}))))
(rule
 (alias spec-612)
 (action (diff spec-612.html spec-612.html.new)))
(rule
 (action
  (with-stdout-to spec-613.html.new (run ./omd.exe %{dep:spec-613.md}))))
(rule
 (alias spec-613)
 (action (diff spec-613.html spec-613.html.new)))
(rule
 (action
  (with-stdout-to spec-614.html.new (run ./omd.exe %{dep:spec-614.md}))))
(rule
 (alias spec-614)
 (action (diff spec-614.html spec-614.html.new)))
(rule
 (action
  (with-stdout-to spec-615.html.new (run ./omd.exe %{dep:spec-615.md}))))
(rule
 (alias spec-615)
 (action (diff spec-615.html spec-615.html.new)))
(rule
 (action
  (with-stdout-to spec-616.html.new (run ./omd.exe %{dep:spec-616.md}))))
(rule
 (alias spec-616)
 (action (diff spec-616.html spec-616.html.new)))
(rule
 (action
  (with-stdout-to spec-617.html.new (run ./omd.exe %{dep:spec-617.md}))))
(rule
 (alias spec-617)
 (action (diff spec-617.html spec-617.html.new)))
(rule
 (action
  (with-stdout-to spec-618.html.new (run ./omd.exe %{dep:spec-618.md}))))
(rule
 (alias spec-618)
 (action (diff spec-618.html spec-618.html.new)))
(rule
 (action
  (with-stdout-to spec-619.html.new (run ./omd.exe %{dep:spec-619.md}))))
(rule
 (alias spec-619)
 (action (diff spec-619.html spec-619.html.new)))
(rule
 (action
  (with-stdout-to spec-620.html.new (run ./omd.exe %{dep:spec-620.md}))))
(rule
 (alias spec-620)
 (action (diff spec-620.html spec-620.html.new)))
(rule
 (action
  (with-stdout-to spec-621.html.new (run ./omd.exe %{dep:spec-621.md}))))
(rule
 (alias spec-621)
 (action (diff spec-621.html spec-621.html.new)))
(rule
 (action
  (with-stdout-to spec-622.html.new (run ./omd.exe %{dep:spec-622.md}))))
(rule
 (alias spec-622)
 (action (diff spec-622.html spec-622.html.new)))
(rule
 (action
  (with-stdout-to spec-623.html.new (run ./omd.exe %{dep:spec-623.md}))))
(rule
 (alias spec-623)
 (action (diff spec-623.html spec-623.html.new)))
(rule
 (action
  (with-stdout-to spec-624.html.new (run ./omd.exe %{dep:spec-624.md}))))
(rule
 (alias spec-624)
 (action (diff spec-624.html spec-624.html.new)))
(rule
 (action
  (with-stdout-to spec-625.html.new (run ./omd.exe %{dep:spec-625.md}))))
(rule
 (alias spec-625)
 (action (diff spec-625.html spec-625.html.new)))
(rule
 (action
  (with-stdout-to spec-626.html.new (run ./omd.exe %{dep:spec-626.md}))))
(rule
 (alias spec-626)
 (action (diff spec-626.html spec-626.html.new)))
(rule
 (action
  (with-stdout-to spec-627.html.new (run ./omd.exe %{dep:spec-627.md}))))
(rule
 (alias spec-627)
 (action (diff spec-627.html spec-627.html.new)))
(rule
 (action
  (with-stdout-to spec-628.html.new (run ./omd.exe %{dep:spec-628.md}))))
(rule
 (alias spec-628)
 (action (diff spec-628.html spec-628.html.new)))
(rule
 (action
  (with-stdout-to spec-629.html.new (run ./omd.exe %{dep:spec-629.md}))))
(rule
 (alias spec-629)
 (action (diff spec-629.html spec-629.html.new)))
(rule
 (action
  (with-stdout-to spec-630.html.new (run ./omd.exe %{dep:spec-630.md}))))
(rule
 (alias spec-630)
 (action (diff spec-630.html spec-630.html.new)))
(rule
 (action
  (with-stdout-to spec-631.html.new (run ./omd.exe %{dep:spec-631.md}))))
(rule
 (alias spec-631)
 (action (diff spec-631.html spec-631.html.new)))
(rule
 (action
  (with-stdout-to spec-632.html.new (run ./omd.exe %{dep:spec-632.md}))))
(rule
 (alias spec-632)
 (action (diff spec-632.html spec-632.html.new)))
(rule
 (action
  (with-stdout-to spec-633.html.new (run ./omd.exe %{dep:spec-633.md}))))
(rule
 (alias spec-633)
 (action (diff spec-633.html spec-633.html.new)))
(rule
 (action
  (with-stdout-to spec-634.html.new (run ./omd.exe %{dep:spec-634.md}))))
(rule
 (alias spec-634)
 (action (diff spec-634.html spec-634.html.new)))
(rule
 (action
  (with-stdout-to spec-635.html.new (run ./omd.exe %{dep:spec-635.md}))))
(rule
 (alias spec-635)
 (action (diff spec-635.html spec-635.html.new)))
(rule
 (action
  (with-stdout-to spec-636.html.new (run ./omd.exe %{dep:spec-636.md}))))
(rule
 (alias spec-636)
 (action (diff spec-636.html spec-636.html.new)))
(rule
 (action
  (with-stdout-to spec-637.html.new (run ./omd.exe %{dep:spec-637.md}))))
(rule
 (alias spec-637)
 (action (diff spec-637.html spec-637.html.new)))
(rule
 (action
  (with-stdout-to spec-638.html.new (run ./omd.exe %{dep:spec-638.md}))))
(rule
 (alias spec-638)
 (action (diff spec-638.html spec-638.html.new)))
(rule
 (action
  (with-stdout-to spec-639.html.new (run ./omd.exe %{dep:spec-639.md}))))
(rule
 (alias spec-639)
 (action (diff spec-639.html spec-639.html.new)))
(rule
 (action
  (with-stdout-to spec-640.html.new (run ./omd.exe %{dep:spec-640.md}))))
(rule
 (alias spec-640)
 (action (diff spec-640.html spec-640.html.new)))
(rule
 (action
  (with-stdout-to spec-641.html.new (run ./omd.exe %{dep:spec-641.md}))))
(rule
 (alias spec-641)
 (action (diff spec-641.html spec-641.html.new)))
(rule
 (action
  (with-stdout-to spec-642.html.new (run ./omd.exe %{dep:spec-642.md}))))
(rule
 (alias spec-642)
 (action (diff spec-642.html spec-642.html.new)))
(rule
 (action
  (with-stdout-to spec-643.html.new (run ./omd.exe %{dep:spec-643.md}))))
(rule
 (alias spec-643)
 (action (diff spec-643.html spec-643.html.new)))
(rule
 (action
  (with-stdout-to spec-644.html.new (run ./omd.exe %{dep:spec-644.md}))))
(rule
 (alias spec-644)
 (action (diff spec-644.html spec-644.html.new)))
(rule
 (action
  (with-stdout-to spec-645.html.new (run ./omd.exe %{dep:spec-645.md}))))
(rule
 (alias spec-645)
 (action (diff spec-645.html spec-645.html.new)))
(rule
 (action
  (with-stdout-to spec-646.html.new (run ./omd.exe %{dep:spec-646.md}))))
(rule
 (alias spec-646)
 (action (diff spec-646.html spec-646.html.new)))
(rule
 (action
  (with-stdout-to spec-647.html.new (run ./omd.exe %{dep:spec-647.md}))))
(rule
 (alias spec-647)
 (action (diff spec-647.html spec-647.html.new)))
(rule
 (action
  (with-stdout-to spec-648.html.new (run ./omd.exe %{dep:spec-648.md}))))
(rule
 (alias spec-648)
 (action (diff spec-648.html spec-648.html.new)))
(rule
 (action
  (with-stdout-to spec-649.html.new (run ./omd.exe %{dep:spec-649.md}))))
(rule
 (alias spec-649)
 (action (diff spec-649.html spec-649.html.new)))
(rule
 (action
  (with-stdout-to spec-650.html.new (run ./omd.exe %{dep:spec-650.md}))))
(rule
 (alias spec-650)
 (action (diff spec-650.html spec-650.html.new)))
(rule
 (action
  (with-stdout-to spec-651.html.new (run ./omd.exe %{dep:spec-651.md}))))
(rule
 (alias spec-651)
 (action (diff spec-651.html spec-651.html.new)))
(rule
 (action
  (with-stdout-to spec-652.html.new (run ./omd.exe %{dep:spec-652.md}))))
(rule
 (alias spec-652)
 (action (diff spec-652.html spec-652.html.new)))
(rule
 (action
  (with-stdout-to attributes-001.html.new
   (run ./omd.exe %{dep:attributes-001.md}))))
(rule
 (alias attributes-001)
 (action (diff attributes-001.html attributes-001.html.new)))
(rule
 (action
  (with-stdout-to attributes-002.html.new
   (run ./omd.exe %{dep:attributes-002.md}))))
(rule
 (alias attributes-002)
 (action (diff attributes-002.html attributes-002.html.new)))
(rule
 (action
  (with-stdout-to attributes-003.html.new
   (run ./omd.exe %{dep:attributes-003.md}))))
(rule
 (alias attributes-003)
 (action (diff attributes-003.html attributes-003.html.new)))
(rule
 (action
  (with-stdout-to attributes-004.html.new
   (run ./omd.exe %{dep:attributes-004.md}))))
(rule
 (alias attributes-004)
 (action (diff attributes-004.html attributes-004.html.new)))
(rule
 (action
  (with-stdout-to attributes-005.html.new
   (run ./omd.exe %{dep:attributes-005.md}))))
(rule
 (alias attributes-005)
 (action (diff attributes-005.html attributes-005.html.new)))
(rule
 (action
  (with-stdout-to attributes-006.html.new
   (run ./omd.exe %{dep:attributes-006.md}))))
(rule
 (alias attributes-006)
 (action (diff attributes-006.html attributes-006.html.new)))
(rule
 (action
  (with-stdout-to attributes-007.html.new
   (run ./omd.exe %{dep:attributes-007.md}))))
(rule
 (alias attributes-007)
 (action (diff attributes-007.html attributes-007.html.new)))
(rule
 (action
  (with-stdout-to attributes-008.html.new
   (run ./omd.exe %{dep:attributes-008.md}))))
(rule
 (alias attributes-008)
 (action (diff attributes-008.html attributes-008.html.new)))
(rule
 (action
  (with-stdout-to attributes-009.html.new
   (run ./omd.exe %{dep:attributes-009.md}))))
(rule
 (alias attributes-009)
 (action (diff attributes-009.html attributes-009.html.new)))
(rule
 (action
  (with-stdout-to attributes-010.html.new
   (run ./omd.exe %{dep:attributes-010.md}))))
(rule
 (alias attributes-010)
 (action (diff attributes-010.html attributes-010.html.new)))
(rule
 (action
  (with-stdout-to attributes-011.html.new
   (run ./omd.exe %{dep:attributes-011.md}))))
(rule
 (alias attributes-011)
 (action (diff attributes-011.html attributes-011.html.new)))
(rule
 (action
  (with-stdout-to attributes-012.html.new
   (run ./omd.exe %{dep:attributes-012.md}))))
(rule
 (alias attributes-012)
 (action (diff attributes-012.html attributes-012.html.new)))
(rule
 (action
  (with-stdout-to attributes-013.html.new
   (run ./omd.exe %{dep:attributes-013.md}))))
(rule
 (alias attributes-013)
 (action (diff attributes-013.html attributes-013.html.new)))
(rule
 (action
  (with-stdout-to attributes-014.html.new
   (run ./omd.exe %{dep:attributes-014.md}))))
(rule
 (alias attributes-014)
 (action (diff attributes-014.html attributes-014.html.new)))
(rule
 (action
  (with-stdout-to attributes-015.html.new
   (run ./omd.exe %{dep:attributes-015.md}))))
(rule
 (alias attributes-015)
 (action (diff attributes-015.html attributes-015.html.new)))
(rule
 (action
  (with-stdout-to def_list-001.html.new
   (run ./omd.exe %{dep:def_list-001.md}))))
(rule
 (alias def_list-001)
 (action (diff def_list-001.html def_list-001.html.new)))
(alias
 (name runtest)
 (deps
  (alias spec-001)
  (alias spec-002)
  (alias spec-003)
  (alias spec-004)
  (alias spec-005)
  (alias spec-006)
  (alias spec-007)
  (alias spec-008)
  (alias spec-009)
  (alias spec-010)
  (alias spec-011)
  (alias spec-012)
  (alias spec-013)
  (alias spec-014)
  (alias spec-015)
  (alias spec-016)
  (alias spec-017)
  (alias spec-018)
  (alias spec-019)
  (alias spec-020)
  (alias spec-021)
  (alias spec-022)
  (alias spec-023)
  (alias spec-024)
  (alias spec-025)
  (alias spec-026)
  (alias spec-027)
  (alias spec-028)
  (alias spec-029)
  (alias spec-030)
  (alias spec-031)
  (alias spec-032)
  (alias spec-033)
  (alias spec-034)
  (alias spec-035)
  (alias spec-036)
  (alias spec-037)
  (alias spec-038)
  (alias spec-039)
  (alias spec-040)
  (alias spec-041)
  (alias spec-042)
  (alias spec-043)
  (alias spec-044)
  (alias spec-045)
  (alias spec-046)
  (alias spec-047)
  (alias spec-048)
  (alias spec-049)
  (alias spec-050)
  (alias spec-051)
  (alias spec-052)
  (alias spec-053)
  (alias spec-054)
  (alias spec-055)
  (alias spec-056)
  (alias spec-057)
  (alias spec-058)
  (alias spec-059)
  (alias spec-060)
  (alias spec-061)
  (alias spec-062)
  (alias spec-063)
  (alias spec-064)
  (alias spec-065)
  (alias spec-066)
  (alias spec-067)
  (alias spec-068)
  (alias spec-069)
  (alias spec-070)
  (alias spec-071)
  (alias spec-072)
  (alias spec-073)
  (alias spec-074)
  (alias spec-075)
  (alias spec-076)
  (alias spec-077)
  (alias spec-078)
  (alias spec-079)
  (alias spec-080)
  (alias spec-081)
  (alias spec-082)
  (alias spec-083)
  (alias spec-084)
  (alias spec-085)
  (alias spec-086)
  (alias spec-087)
  (alias spec-088)
  (alias spec-089)
  (alias spec-090)
  (alias spec-091)
  (alias spec-092)
  (alias spec-093)
  (alias spec-094)
  (alias spec-095)
  (alias spec-096)
  (alias spec-097)
  (alias spec-098)
  (alias spec-099)
  (alias spec-100)
  (alias spec-101)
  (alias spec-102)
  (alias spec-103)
  (alias spec-104)
  (alias spec-105)
  (alias spec-106)
  (alias spec-107)
  (alias spec-108)
  (alias spec-109)
  (alias spec-110)
  (alias spec-111)
  (alias spec-112)
  (alias spec-113)
  (alias spec-114)
  (alias spec-115)
  (alias spec-116)
  (alias spec-117)
  (alias spec-118)
  (alias spec-119)
  (alias spec-120)
  (alias spec-121)
  (alias spec-122)
  (alias spec-123)
  (alias spec-124)
  (alias spec-125)
  (alias spec-126)
  (alias spec-127)
  (alias spec-128)
  (alias spec-129)
  (alias spec-130)
  (alias spec-131)
  (alias spec-132)
  (alias spec-133)
  (alias spec-134)
  (alias spec-135)
  (alias spec-136)
  (alias spec-137)
  (alias spec-138)
  (alias spec-139)
  (alias spec-140)
  (alias spec-141)
  (alias spec-142)
  (alias spec-143)
  (alias spec-144)
  (alias spec-145)
  (alias spec-146)
  (alias spec-147)
  (alias spec-148)
  (alias spec-149)
  (alias spec-150)
  (alias spec-151)
  (alias spec-152)
  (alias spec-153)
  (alias spec-154)
  (alias spec-155)
  (alias spec-156)
  (alias spec-157)
  (alias spec-158)
  (alias spec-159)
  (alias spec-160)
  (alias spec-161)
  (alias spec-162)
  (alias spec-163)
  (alias spec-164)
  (alias spec-165)
  (alias spec-166)
  (alias spec-167)
  (alias spec-168)
  (alias spec-169)
  (alias spec-170)
  (alias spec-171)
  (alias spec-172)
  (alias spec-173)
  (alias spec-174)
  (alias spec-175)
  (alias spec-176)
  (alias spec-177)
  (alias spec-178)
  (alias spec-179)
  (alias spec-180)
  (alias spec-181)
  (alias spec-182)
  (alias spec-183)
  (alias spec-184)
  (alias spec-185)
  (alias spec-186)
  (alias spec-187)
  (alias spec-188)
  (alias spec-189)
  (alias spec-190)
  (alias spec-191)
  (alias spec-192)
  (alias spec-193)
  (alias spec-194)
  (alias spec-195)
  (alias spec-196)
  (alias spec-197)
  (alias spec-198)
  (alias spec-199)
  (alias spec-200)
  (alias spec-201)
  (alias spec-202)
  (alias spec-203)
  (alias spec-204)
  (alias spec-205)
  (alias spec-207)
  (alias spec-208)
  (alias spec-209)
  (alias spec-210)
  (alias spec-211)
  (alias spec-212)
  (alias spec-213)
  (alias spec-214)
  (alias spec-217)
  (alias spec-218)
  (alias spec-219)
  (alias spec-220)
  (alias spec-221)
  (alias spec-222)
  (alias spec-223)
  (alias spec-224)
  (alias spec-225)
  (alias spec-226)
  (alias spec-227)
  (alias spec-228)
  (alias spec-229)
  (alias spec-230)
  (alias spec-231)
  (alias spec-232)
  (alias spec-233)
  (alias spec-234)
  (alias spec-235)
  (alias spec-236)
  (alias spec-237)
  (alias spec-238)
  (alias spec-239)
  (alias spec-240)
  (alias spec-241)
  (alias spec-242)
  (alias spec-243)
  (alias spec-244)
  (alias spec-245)
  (alias spec-246)
  (alias spec-247)
  (alias spec-248)
  (alias spec-249)
  (alias spec-250)
  (alias spec-251)
  (alias spec-252)
  (alias spec-253)
  (alias spec-254)
  (alias spec-255)
  (alias spec-256)
  (alias spec-257)
  (alias spec-258)
  (alias spec-259)
  (alias spec-260)
  (alias spec-261)
  (alias spec-262)
  (alias spec-263)
  (alias spec-264)
  (alias spec-265)
  (alias spec-266)
  (alias spec-267)
  (alias spec-268)
  (alias spec-269)
  (alias spec-270)
  (alias spec-271)
  (alias spec-272)
  (alias spec-273)
  (alias spec-274)
  (alias spec-275)
  (alias spec-276)
  (alias spec-277)
  (alias spec-278)
  (alias spec-279)
  (alias spec-280)
  (alias spec-281)
  (alias spec-282)
  (alias spec-283)
  (alias spec-284)
  (alias spec-285)
  (alias spec-286)
  (alias spec-287)
  (alias spec-288)
  (alias spec-289)
  (alias spec-290)
  (alias spec-291)
  (alias spec-292)
  (alias spec-293)
  (alias spec-294)
  (alias spec-295)
  (alias spec-296)
  (alias spec-297)
  (alias spec-298)
  (alias spec-299)
  (alias spec-300)
  (alias spec-301)
  (alias spec-302)
  (alias spec-303)
  (alias spec-304)
  (alias spec-305)
  (alias spec-306)
  (alias spec-307)
  (alias spec-308)
  (alias spec-309)
  (alias spec-310)
  (alias spec-311)
  (alias spec-312)
  (alias spec-313)
  (alias spec-314)
  (alias spec-315)
  (alias spec-316)
  (alias spec-317)
  (alias spec-318)
  (alias spec-319)
  (alias spec-320)
  (alias spec-321)
  (alias spec-322)
  (alias spec-323)
  (alias spec-324)
  (alias spec-325)
  (alias spec-326)
  (alias spec-327)
  (alias spec-328)
  (alias spec-329)
  (alias spec-330)
  (alias spec-331)
  (alias spec-332)
  (alias spec-333)
  (alias spec-334)
  (alias spec-335)
  (alias spec-336)
  (alias spec-337)
  (alias spec-338)
  (alias spec-339)
  (alias spec-340)
  (alias spec-341)
  (alias spec-342)
  (alias spec-343)
  (alias spec-344)
  (alias spec-345)
  (alias spec-346)
  (alias spec-347)
  (alias spec-348)
  (alias spec-349)
  (alias spec-350)
  (alias spec-351)
  (alias spec-352)
  (alias spec-353)
  (alias spec-354)
  (alias spec-355)
  (alias spec-356)
  (alias spec-357)
  (alias spec-358)
  (alias spec-359)
  (alias spec-360)
  (alias spec-361)
  (alias spec-362)
  (alias spec-363)
  (alias spec-364)
  (alias spec-365)
  (alias spec-366)
  (alias spec-367)
  (alias spec-368)
  (alias spec-369)
  (alias spec-370)
  (alias spec-371)
  (alias spec-372)
  (alias spec-373)
  (alias spec-374)
  (alias spec-375)
  (alias spec-376)
  (alias spec-377)
  (alias spec-378)
  (alias spec-379)
  (alias spec-380)
  (alias spec-381)
  (alias spec-382)
  (alias spec-383)
  (alias spec-384)
  (alias spec-385)
  (alias spec-386)
  (alias spec-387)
  (alias spec-388)
  (alias spec-389)
  (alias spec-390)
  (alias spec-391)
  (alias spec-392)
  (alias spec-393)
  (alias spec-394)
  (alias spec-395)
  (alias spec-396)
  (alias spec-397)
  (alias spec-398)
  (alias spec-399)
  (alias spec-400)
  (alias spec-401)
  (alias spec-402)
  (alias spec-403)
  (alias spec-404)
  (alias spec-405)
  (alias spec-406)
  (alias spec-407)
  (alias spec-408)
  (alias spec-409)
  (alias spec-410)
  (alias spec-411)
  (alias spec-412)
  (alias spec-413)
  (alias spec-414)
  (alias spec-415)
  (alias spec-416)
  (alias spec-417)
  (alias spec-418)
  (alias spec-419)
  (alias spec-420)
  (alias spec-421)
  (alias spec-422)
  (alias spec-423)
  (alias spec-424)
  (alias spec-425)
  (alias spec-426)
  (alias spec-427)
  (alias spec-428)
  (alias spec-429)
  (alias spec-430)
  (alias spec-431)
  (alias spec-432)
  (alias spec-433)
  (alias spec-434)
  (alias spec-435)
  (alias spec-436)
  (alias spec-437)
  (alias spec-438)
  (alias spec-439)
  (alias spec-440)
  (alias spec-441)
  (alias spec-442)
  (alias spec-443)
  (alias spec-444)
  (alias spec-445)
  (alias spec-446)
  (alias spec-447)
  (alias spec-448)
  (alias spec-449)
  (alias spec-450)
  (alias spec-451)
  (alias spec-452)
  (alias spec-453)
  (alias spec-454)
  (alias spec-455)
  (alias spec-456)
  (alias spec-457)
  (alias spec-458)
  (alias spec-459)
  (alias spec-460)
  (alias spec-461)
  (alias spec-462)
  (alias spec-463)
  (alias spec-464)
  (alias spec-465)
  (alias spec-466)
  (alias spec-467)
  (alias spec-470)
  (alias spec-471)
  (alias spec-472)
  (alias spec-473)
  (alias spec-474)
  (alias spec-475)
  (alias spec-476)
  (alias spec-477)
  (alias spec-478)
  (alias spec-479)
  (alias spec-480)
  (alias spec-481)
  (alias spec-482)
  (alias spec-483)
  (alias spec-484)
  (alias spec-485)
  (alias spec-486)
  (alias spec-487)
  (alias spec-488)
  (alias spec-489)
  (alias spec-490)
  (alias spec-491)
  (alias spec-492)
  (alias spec-493)
  (alias spec-494)
  (alias spec-495)
  (alias spec-496)
  (alias spec-497)
  (alias spec-498)
  (alias spec-499)
  (alias spec-500)
  (alias spec-501)
  (alias spec-502)
  (alias spec-503)
  (alias spec-504)
  (alias spec-505)
  (alias spec-506)
  (alias spec-507)
  (alias spec-508)
  (alias spec-509)
  (alias spec-510)
  (alias spec-511)
  (alias spec-512)
  (alias spec-513)
  (alias spec-514)
  (alias spec-515)
  (alias spec-516)
  (alias spec-517)
  (alias spec-518)
  (alias spec-520)
  (alias spec-521)
  (alias spec-522)
  (alias spec-523)
  (alias spec-524)
  (alias spec-525)
  (alias spec-526)
  (alias spec-527)
  (alias spec-528)
  (alias spec-529)
  (alias spec-530)
  (alias spec-531)
  (alias spec-532)
  (alias spec-533)
  (alias spec-534)
  (alias spec-535)
  (alias spec-536)
  (alias spec-537)
  (alias spec-538)
  (alias spec-540)
  (alias spec-541)
  (alias spec-542)
  (alias spec-543)
  (alias spec-544)
  (alias spec-545)
  (alias spec-546)
  (alias spec-547)
  (alias spec-548)
  (alias spec-549)
  (alias spec-550)
  (alias spec-551)
  (alias spec-552)
  (alias spec-553)
  (alias spec-554)
  (alias spec-555)
  (alias spec-556)
  (alias spec-557)
  (alias spec-558)
  (alias spec-559)
  (alias spec-560)
  (alias spec-561)
  (alias spec-562)
  (alias spec-563)
  (alias spec-564)
  (alias spec-565)
  (alias spec-566)
  (alias spec-567)
  (alias spec-568)
  (alias spec-569)
  (alias spec-570)
  (alias spec-571)
  (alias spec-572)
  (alias spec-573)
  (alias spec-574)
  (alias spec-575)
  (alias spec-576)
  (alias spec-577)
  (alias spec-578)
  (alias spec-579)
  (alias spec-580)
  (alias spec-581)
  (alias spec-582)
  (alias spec-583)
  (alias spec-584)
  (alias spec-585)
  (alias spec-586)
  (alias spec-587)
  (alias spec-588)
  (alias spec-589)
  (alias spec-590)
  (alias spec-591)
  (alias spec-592)
  (alias spec-593)
  (alias spec-594)
  (alias spec-595)
  (alias spec-596)
  (alias spec-597)
  (alias spec-598)
  (alias spec-599)
  (alias spec-600)
  (alias spec-601)
  (alias spec-602)
  (alias spec-603)
  (alias spec-604)
  (alias spec-605)
  (alias spec-606)
  (alias spec-607)
  (alias spec-608)
  (alias spec-609)
  (alias spec-610)
  (alias spec-611)
  (alias spec-612)
  (alias spec-613)
  (alias spec-614)
  (alias spec-615)
  (alias spec-616)
  (alias spec-617)
  (alias spec-618)
  (alias spec-619)
  (alias spec-620)
  (alias spec-621)
  (alias spec-622)
  (alias spec-623)
  (alias spec-624)
  (alias spec-625)
  (alias spec-626)
  (alias spec-627)
  (alias spec-628)
  (alias spec-629)
  (alias spec-630)
  (alias spec-631)
  (alias spec-632)
  (alias spec-633)
  (alias spec-634)
  (alias spec-635)
  (alias spec-636)
  (alias spec-637)
  (alias spec-638)
  (alias spec-639)
  (alias spec-640)
  (alias spec-641)
  (alias spec-642)
  (alias spec-643)
  (alias spec-644)
  (alias spec-645)
  (alias spec-646)
  (alias spec-647)
  (alias spec-648)
  (alias spec-649)
  (alias spec-650)
  (alias spec-651)
  (alias spec-652)
  (alias attributes-001)
  (alias attributes-002)
  (alias attributes-003)
  (alias attributes-004)
  (alias attributes-005)
  (alias attributes-006)
  (alias attributes-007)
  (alias attributes-008)
  (alias attributes-009)
  (alias attributes-010)
  (alias attributes-011)
  (alias attributes-012)
  (alias attributes-013)
  (alias attributes-014)
  (alias attributes-015)
  (alias def_list-001)))
