(rule
 (targets cmark-001.html.out)
 (deps cmark-001.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-001)
 (action (diff cmark-001.html cmark-001.html.out)))

(rule
 (targets cmark-002.html.out)
 (deps cmark-002.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-002)
 (action (diff cmark-002.html cmark-002.html.out)))

(rule
 (targets cmark-003.html.out)
 (deps cmark-003.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-003)
 (action (diff cmark-003.html cmark-003.html.out)))

(rule
 (targets cmark-004.html.out)
 (deps cmark-004.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-004)
 (action (diff cmark-004.html cmark-004.html.out)))

(rule
 (targets cmark-005.html.out)
 (deps cmark-005.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-005)
 (action (diff cmark-005.html cmark-005.html.out)))

(rule
 (targets cmark-006.html.out)
 (deps cmark-006.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-006)
 (action (diff cmark-006.html cmark-006.html.out)))

(rule
 (targets cmark-007.html.out)
 (deps cmark-007.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-007)
 (action (diff cmark-007.html cmark-007.html.out)))

(rule
 (targets cmark-008.html.out)
 (deps cmark-008.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-008)
 (action (diff cmark-008.html cmark-008.html.out)))

(rule
 (targets cmark-009.html.out)
 (deps cmark-009.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-009)
 (action (diff cmark-009.html cmark-009.html.out)))

(rule
 (targets cmark-010.html.out)
 (deps cmark-010.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-010)
 (action (diff cmark-010.html cmark-010.html.out)))

(rule
 (targets cmark-011.html.out)
 (deps cmark-011.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-011)
 (action (diff cmark-011.html cmark-011.html.out)))

(rule
 (targets cmark-012.html.out)
 (deps cmark-012.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-012)
 (action (diff cmark-012.html cmark-012.html.out)))

(rule
 (targets cmark-013.html.out)
 (deps cmark-013.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-013)
 (action (diff cmark-013.html cmark-013.html.out)))

(rule
 (targets cmark-014.html.out)
 (deps cmark-014.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-014)
 (action (diff cmark-014.html cmark-014.html.out)))

(rule
 (targets cmark-015.html.out)
 (deps cmark-015.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-015)
 (action (diff cmark-015.html cmark-015.html.out)))

(rule
 (targets cmark-016.html.out)
 (deps cmark-016.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-016)
 (action (diff cmark-016.html cmark-016.html.out)))

(rule
 (targets cmark-017.html.out)
 (deps cmark-017.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-017)
 (action (diff cmark-017.html cmark-017.html.out)))

(rule
 (targets cmark-018.html.out)
 (deps cmark-018.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-018)
 (action (diff cmark-018.html cmark-018.html.out)))

(rule
 (targets cmark-019.html.out)
 (deps cmark-019.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-019)
 (action (diff cmark-019.html cmark-019.html.out)))

(rule
 (targets cmark-020.html.out)
 (deps cmark-020.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-020)
 (action (diff cmark-020.html cmark-020.html.out)))

(rule
 (targets cmark-021.html.out)
 (deps cmark-021.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-021)
 (action (diff cmark-021.html cmark-021.html.out)))

(rule
 (targets cmark-022.html.out)
 (deps cmark-022.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-022)
 (action (diff cmark-022.html cmark-022.html.out)))

(rule
 (targets cmark-023.html.out)
 (deps cmark-023.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-023)
 (action (diff cmark-023.html cmark-023.html.out)))

(rule
 (targets cmark-024.html.out)
 (deps cmark-024.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-024)
 (action (diff cmark-024.html cmark-024.html.out)))

(rule
 (targets cmark-025.html.out)
 (deps cmark-025.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-025)
 (action (diff cmark-025.html cmark-025.html.out)))

(rule
 (targets cmark-026.html.out)
 (deps cmark-026.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-026)
 (action (diff cmark-026.html cmark-026.html.out)))

(rule
 (targets cmark-027.html.out)
 (deps cmark-027.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-027)
 (action (diff cmark-027.html cmark-027.html.out)))

(rule
 (targets cmark-028.html.out)
 (deps cmark-028.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-028)
 (action (diff cmark-028.html cmark-028.html.out)))

(rule
 (targets cmark-029.html.out)
 (deps cmark-029.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-029)
 (action (diff cmark-029.html cmark-029.html.out)))

(rule
 (targets cmark-030.html.out)
 (deps cmark-030.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-030)
 (action (diff cmark-030.html cmark-030.html.out)))

(rule
 (targets cmark-031.html.out)
 (deps cmark-031.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-031)
 (action (diff cmark-031.html cmark-031.html.out)))

(rule
 (targets cmark-032.html.out)
 (deps cmark-032.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-032)
 (action (diff cmark-032.html cmark-032.html.out)))

(rule
 (targets cmark-033.html.out)
 (deps cmark-033.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-033)
 (action (diff cmark-033.html cmark-033.html.out)))

(rule
 (targets cmark-034.html.out)
 (deps cmark-034.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-034)
 (action (diff cmark-034.html cmark-034.html.out)))

(rule
 (targets cmark-035.html.out)
 (deps cmark-035.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-035)
 (action (diff cmark-035.html cmark-035.html.out)))

(rule
 (targets cmark-036.html.out)
 (deps cmark-036.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-036)
 (action (diff cmark-036.html cmark-036.html.out)))

(rule
 (targets cmark-037.html.out)
 (deps cmark-037.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-037)
 (action (diff cmark-037.html cmark-037.html.out)))

(rule
 (targets cmark-038.html.out)
 (deps cmark-038.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-038)
 (action (diff cmark-038.html cmark-038.html.out)))

(rule
 (targets cmark-039.html.out)
 (deps cmark-039.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-039)
 (action (diff cmark-039.html cmark-039.html.out)))

(rule
 (targets cmark-040.html.out)
 (deps cmark-040.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-040)
 (action (diff cmark-040.html cmark-040.html.out)))

(rule
 (targets cmark-041.html.out)
 (deps cmark-041.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-041)
 (action (diff cmark-041.html cmark-041.html.out)))

(rule
 (targets cmark-042.html.out)
 (deps cmark-042.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-042)
 (action (diff cmark-042.html cmark-042.html.out)))

(rule
 (targets cmark-043.html.out)
 (deps cmark-043.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-043)
 (action (diff cmark-043.html cmark-043.html.out)))

(rule
 (targets cmark-044.html.out)
 (deps cmark-044.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-044)
 (action (diff cmark-044.html cmark-044.html.out)))

(rule
 (targets cmark-045.html.out)
 (deps cmark-045.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-045)
 (action (diff cmark-045.html cmark-045.html.out)))

(rule
 (targets cmark-046.html.out)
 (deps cmark-046.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-046)
 (action (diff cmark-046.html cmark-046.html.out)))

(rule
 (targets cmark-047.html.out)
 (deps cmark-047.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-047)
 (action (diff cmark-047.html cmark-047.html.out)))

(rule
 (targets cmark-048.html.out)
 (deps cmark-048.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-048)
 (action (diff cmark-048.html cmark-048.html.out)))

(rule
 (targets cmark-049.html.out)
 (deps cmark-049.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-049)
 (action (diff cmark-049.html cmark-049.html.out)))

(rule
 (targets cmark-050.html.out)
 (deps cmark-050.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-050)
 (action (diff cmark-050.html cmark-050.html.out)))

(rule
 (targets cmark-051.html.out)
 (deps cmark-051.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-051)
 (action (diff cmark-051.html cmark-051.html.out)))

(rule
 (targets cmark-052.html.out)
 (deps cmark-052.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-052)
 (action (diff cmark-052.html cmark-052.html.out)))

(rule
 (targets cmark-053.html.out)
 (deps cmark-053.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-053)
 (action (diff cmark-053.html cmark-053.html.out)))

(rule
 (targets cmark-054.html.out)
 (deps cmark-054.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-054)
 (action (diff cmark-054.html cmark-054.html.out)))

(rule
 (targets cmark-055.html.out)
 (deps cmark-055.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-055)
 (action (diff cmark-055.html cmark-055.html.out)))

(rule
 (targets cmark-056.html.out)
 (deps cmark-056.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-056)
 (action (diff cmark-056.html cmark-056.html.out)))

(rule
 (targets cmark-057.html.out)
 (deps cmark-057.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-057)
 (action (diff cmark-057.html cmark-057.html.out)))

(rule
 (targets cmark-058.html.out)
 (deps cmark-058.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-058)
 (action (diff cmark-058.html cmark-058.html.out)))

(rule
 (targets cmark-059.html.out)
 (deps cmark-059.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-059)
 (action (diff cmark-059.html cmark-059.html.out)))

(rule
 (targets cmark-060.html.out)
 (deps cmark-060.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-060)
 (action (diff cmark-060.html cmark-060.html.out)))

(rule
 (targets cmark-061.html.out)
 (deps cmark-061.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-061)
 (action (diff cmark-061.html cmark-061.html.out)))

(rule
 (targets cmark-062.html.out)
 (deps cmark-062.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-062)
 (action (diff cmark-062.html cmark-062.html.out)))

(rule
 (targets cmark-063.html.out)
 (deps cmark-063.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-063)
 (action (diff cmark-063.html cmark-063.html.out)))

(rule
 (targets cmark-064.html.out)
 (deps cmark-064.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-064)
 (action (diff cmark-064.html cmark-064.html.out)))

(rule
 (targets cmark-065.html.out)
 (deps cmark-065.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-065)
 (action (diff cmark-065.html cmark-065.html.out)))

(rule
 (targets cmark-066.html.out)
 (deps cmark-066.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-066)
 (action (diff cmark-066.html cmark-066.html.out)))

(rule
 (targets cmark-067.html.out)
 (deps cmark-067.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-067)
 (action (diff cmark-067.html cmark-067.html.out)))

(rule
 (targets cmark-068.html.out)
 (deps cmark-068.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-068)
 (action (diff cmark-068.html cmark-068.html.out)))

(rule
 (targets cmark-069.html.out)
 (deps cmark-069.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-069)
 (action (diff cmark-069.html cmark-069.html.out)))

(rule
 (targets cmark-070.html.out)
 (deps cmark-070.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-070)
 (action (diff cmark-070.html cmark-070.html.out)))

(rule
 (targets cmark-071.html.out)
 (deps cmark-071.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-071)
 (action (diff cmark-071.html cmark-071.html.out)))

(rule
 (targets cmark-072.html.out)
 (deps cmark-072.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-072)
 (action (diff cmark-072.html cmark-072.html.out)))

(rule
 (targets cmark-073.html.out)
 (deps cmark-073.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-073)
 (action (diff cmark-073.html cmark-073.html.out)))

(rule
 (targets cmark-074.html.out)
 (deps cmark-074.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-074)
 (action (diff cmark-074.html cmark-074.html.out)))

(rule
 (targets cmark-075.html.out)
 (deps cmark-075.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-075)
 (action (diff cmark-075.html cmark-075.html.out)))

(rule
 (targets cmark-076.html.out)
 (deps cmark-076.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-076)
 (action (diff cmark-076.html cmark-076.html.out)))

(rule
 (targets cmark-077.html.out)
 (deps cmark-077.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-077)
 (action (diff cmark-077.html cmark-077.html.out)))

(rule
 (targets cmark-078.html.out)
 (deps cmark-078.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-078)
 (action (diff cmark-078.html cmark-078.html.out)))

(rule
 (targets cmark-079.html.out)
 (deps cmark-079.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-079)
 (action (diff cmark-079.html cmark-079.html.out)))

(rule
 (targets cmark-080.html.out)
 (deps cmark-080.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-080)
 (action (diff cmark-080.html cmark-080.html.out)))

(rule
 (targets cmark-081.html.out)
 (deps cmark-081.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-081)
 (action (diff cmark-081.html cmark-081.html.out)))

(rule
 (targets cmark-082.html.out)
 (deps cmark-082.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-082)
 (action (diff cmark-082.html cmark-082.html.out)))

(rule
 (targets cmark-083.html.out)
 (deps cmark-083.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-083)
 (action (diff cmark-083.html cmark-083.html.out)))

(rule
 (targets cmark-084.html.out)
 (deps cmark-084.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-084)
 (action (diff cmark-084.html cmark-084.html.out)))

(rule
 (targets cmark-085.html.out)
 (deps cmark-085.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-085)
 (action (diff cmark-085.html cmark-085.html.out)))

(rule
 (targets cmark-086.html.out)
 (deps cmark-086.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-086)
 (action (diff cmark-086.html cmark-086.html.out)))

(rule
 (targets cmark-087.html.out)
 (deps cmark-087.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-087)
 (action (diff cmark-087.html cmark-087.html.out)))

(rule
 (targets cmark-088.html.out)
 (deps cmark-088.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-088)
 (action (diff cmark-088.html cmark-088.html.out)))

(rule
 (targets cmark-089.html.out)
 (deps cmark-089.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-089)
 (action (diff cmark-089.html cmark-089.html.out)))

(rule
 (targets cmark-090.html.out)
 (deps cmark-090.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-090)
 (action (diff cmark-090.html cmark-090.html.out)))

(rule
 (targets cmark-091.html.out)
 (deps cmark-091.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-091)
 (action (diff cmark-091.html cmark-091.html.out)))

(rule
 (targets cmark-092.html.out)
 (deps cmark-092.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-092)
 (action (diff cmark-092.html cmark-092.html.out)))

(rule
 (targets cmark-093.html.out)
 (deps cmark-093.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-093)
 (action (diff cmark-093.html cmark-093.html.out)))

(rule
 (targets cmark-094.html.out)
 (deps cmark-094.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-094)
 (action (diff cmark-094.html cmark-094.html.out)))

(rule
 (targets cmark-095.html.out)
 (deps cmark-095.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-095)
 (action (diff cmark-095.html cmark-095.html.out)))

(rule
 (targets cmark-096.html.out)
 (deps cmark-096.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-096)
 (action (diff cmark-096.html cmark-096.html.out)))

(rule
 (targets cmark-097.html.out)
 (deps cmark-097.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-097)
 (action (diff cmark-097.html cmark-097.html.out)))

(rule
 (targets cmark-098.html.out)
 (deps cmark-098.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-098)
 (action (diff cmark-098.html cmark-098.html.out)))

(rule
 (targets cmark-099.html.out)
 (deps cmark-099.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-099)
 (action (diff cmark-099.html cmark-099.html.out)))

(rule
 (targets cmark-100.html.out)
 (deps cmark-100.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-100)
 (action (diff cmark-100.html cmark-100.html.out)))

(rule
 (targets cmark-101.html.out)
 (deps cmark-101.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-101)
 (action (diff cmark-101.html cmark-101.html.out)))

(rule
 (targets cmark-102.html.out)
 (deps cmark-102.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-102)
 (action (diff cmark-102.html cmark-102.html.out)))

(rule
 (targets cmark-103.html.out)
 (deps cmark-103.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-103)
 (action (diff cmark-103.html cmark-103.html.out)))

(rule
 (targets cmark-104.html.out)
 (deps cmark-104.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-104)
 (action (diff cmark-104.html cmark-104.html.out)))

(rule
 (targets cmark-105.html.out)
 (deps cmark-105.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-105)
 (action (diff cmark-105.html cmark-105.html.out)))

(rule
 (targets cmark-106.html.out)
 (deps cmark-106.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-106)
 (action (diff cmark-106.html cmark-106.html.out)))

(rule
 (targets cmark-107.html.out)
 (deps cmark-107.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-107)
 (action (diff cmark-107.html cmark-107.html.out)))

(rule
 (targets cmark-108.html.out)
 (deps cmark-108.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-108)
 (action (diff cmark-108.html cmark-108.html.out)))

(rule
 (targets cmark-109.html.out)
 (deps cmark-109.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-109)
 (action (diff cmark-109.html cmark-109.html.out)))

(rule
 (targets cmark-110.html.out)
 (deps cmark-110.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-110)
 (action (diff cmark-110.html cmark-110.html.out)))

(rule
 (targets cmark-111.html.out)
 (deps cmark-111.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-111)
 (action (diff cmark-111.html cmark-111.html.out)))

(rule
 (targets cmark-112.html.out)
 (deps cmark-112.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-112)
 (action (diff cmark-112.html cmark-112.html.out)))

(rule
 (targets cmark-113.html.out)
 (deps cmark-113.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-113)
 (action (diff cmark-113.html cmark-113.html.out)))

(rule
 (targets cmark-114.html.out)
 (deps cmark-114.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-114)
 (action (diff cmark-114.html cmark-114.html.out)))

(rule
 (targets cmark-115.html.out)
 (deps cmark-115.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-115)
 (action (diff cmark-115.html cmark-115.html.out)))

(rule
 (targets cmark-116.html.out)
 (deps cmark-116.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-116)
 (action (diff cmark-116.html cmark-116.html.out)))

(rule
 (targets cmark-117.html.out)
 (deps cmark-117.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-117)
 (action (diff cmark-117.html cmark-117.html.out)))

(rule
 (targets cmark-118.html.out)
 (deps cmark-118.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-118)
 (action (diff cmark-118.html cmark-118.html.out)))

(rule
 (targets cmark-119.html.out)
 (deps cmark-119.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-119)
 (action (diff cmark-119.html cmark-119.html.out)))

(rule
 (targets cmark-120.html.out)
 (deps cmark-120.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-120)
 (action (diff cmark-120.html cmark-120.html.out)))

(rule
 (targets cmark-121.html.out)
 (deps cmark-121.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-121)
 (action (diff cmark-121.html cmark-121.html.out)))

(rule
 (targets cmark-122.html.out)
 (deps cmark-122.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-122)
 (action (diff cmark-122.html cmark-122.html.out)))

(rule
 (targets cmark-123.html.out)
 (deps cmark-123.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-123)
 (action (diff cmark-123.html cmark-123.html.out)))

(rule
 (targets cmark-124.html.out)
 (deps cmark-124.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-124)
 (action (diff cmark-124.html cmark-124.html.out)))

(rule
 (targets cmark-125.html.out)
 (deps cmark-125.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-125)
 (action (diff cmark-125.html cmark-125.html.out)))

(rule
 (targets cmark-126.html.out)
 (deps cmark-126.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-126)
 (action (diff cmark-126.html cmark-126.html.out)))

(rule
 (targets cmark-127.html.out)
 (deps cmark-127.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-127)
 (action (diff cmark-127.html cmark-127.html.out)))

(rule
 (targets cmark-128.html.out)
 (deps cmark-128.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-128)
 (action (diff cmark-128.html cmark-128.html.out)))

(rule
 (targets cmark-129.html.out)
 (deps cmark-129.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-129)
 (action (diff cmark-129.html cmark-129.html.out)))

(rule
 (targets cmark-130.html.out)
 (deps cmark-130.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-130)
 (action (diff cmark-130.html cmark-130.html.out)))

(rule
 (targets cmark-131.html.out)
 (deps cmark-131.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-131)
 (action (diff cmark-131.html cmark-131.html.out)))

(rule
 (targets cmark-132.html.out)
 (deps cmark-132.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-132)
 (action (diff cmark-132.html cmark-132.html.out)))

(rule
 (targets cmark-133.html.out)
 (deps cmark-133.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-133)
 (action (diff cmark-133.html cmark-133.html.out)))

(rule
 (targets cmark-134.html.out)
 (deps cmark-134.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-134)
 (action (diff cmark-134.html cmark-134.html.out)))

(rule
 (targets cmark-135.html.out)
 (deps cmark-135.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-135)
 (action (diff cmark-135.html cmark-135.html.out)))

(rule
 (targets cmark-136.html.out)
 (deps cmark-136.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-136)
 (action (diff cmark-136.html cmark-136.html.out)))

(rule
 (targets cmark-137.html.out)
 (deps cmark-137.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-137)
 (action (diff cmark-137.html cmark-137.html.out)))

(rule
 (targets cmark-138.html.out)
 (deps cmark-138.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-138)
 (action (diff cmark-138.html cmark-138.html.out)))

(rule
 (targets cmark-139.html.out)
 (deps cmark-139.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-139)
 (action (diff cmark-139.html cmark-139.html.out)))

(rule
 (targets cmark-140.html.out)
 (deps cmark-140.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-140)
 (action (diff cmark-140.html cmark-140.html.out)))

(rule
 (targets cmark-141.html.out)
 (deps cmark-141.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-141)
 (action (diff cmark-141.html cmark-141.html.out)))

(rule
 (targets cmark-142.html.out)
 (deps cmark-142.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-142)
 (action (diff cmark-142.html cmark-142.html.out)))

(rule
 (targets cmark-143.html.out)
 (deps cmark-143.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-143)
 (action (diff cmark-143.html cmark-143.html.out)))

(rule
 (targets cmark-144.html.out)
 (deps cmark-144.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-144)
 (action (diff cmark-144.html cmark-144.html.out)))

(rule
 (targets cmark-145.html.out)
 (deps cmark-145.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-145)
 (action (diff cmark-145.html cmark-145.html.out)))

(rule
 (targets cmark-146.html.out)
 (deps cmark-146.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-146)
 (action (diff cmark-146.html cmark-146.html.out)))

(rule
 (targets cmark-147.html.out)
 (deps cmark-147.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-147)
 (action (diff cmark-147.html cmark-147.html.out)))

(rule
 (targets cmark-148.html.out)
 (deps cmark-148.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-148)
 (action (diff cmark-148.html cmark-148.html.out)))

(rule
 (targets cmark-149.html.out)
 (deps cmark-149.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-149)
 (action (diff cmark-149.html cmark-149.html.out)))

(rule
 (targets cmark-150.html.out)
 (deps cmark-150.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-150)
 (action (diff cmark-150.html cmark-150.html.out)))

(rule
 (targets cmark-151.html.out)
 (deps cmark-151.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-151)
 (action (diff cmark-151.html cmark-151.html.out)))

(rule
 (targets cmark-152.html.out)
 (deps cmark-152.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-152)
 (action (diff cmark-152.html cmark-152.html.out)))

(rule
 (targets cmark-153.html.out)
 (deps cmark-153.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-153)
 (action (diff cmark-153.html cmark-153.html.out)))

(rule
 (targets cmark-154.html.out)
 (deps cmark-154.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-154)
 (action (diff cmark-154.html cmark-154.html.out)))

(rule
 (targets cmark-155.html.out)
 (deps cmark-155.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-155)
 (action (diff cmark-155.html cmark-155.html.out)))

(rule
 (targets cmark-156.html.out)
 (deps cmark-156.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-156)
 (action (diff cmark-156.html cmark-156.html.out)))

(rule
 (targets cmark-157.html.out)
 (deps cmark-157.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-157)
 (action (diff cmark-157.html cmark-157.html.out)))

(rule
 (targets cmark-158.html.out)
 (deps cmark-158.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-158)
 (action (diff cmark-158.html cmark-158.html.out)))

(rule
 (targets cmark-159.html.out)
 (deps cmark-159.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-159)
 (action (diff cmark-159.html cmark-159.html.out)))

(rule
 (targets cmark-160.html.out)
 (deps cmark-160.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-160)
 (action (diff cmark-160.html cmark-160.html.out)))

(rule
 (targets cmark-161.html.out)
 (deps cmark-161.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-161)
 (action (diff cmark-161.html cmark-161.html.out)))

(rule
 (targets cmark-162.html.out)
 (deps cmark-162.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-162)
 (action (diff cmark-162.html cmark-162.html.out)))

(rule
 (targets cmark-163.html.out)
 (deps cmark-163.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-163)
 (action (diff cmark-163.html cmark-163.html.out)))

(rule
 (targets cmark-164.html.out)
 (deps cmark-164.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-164)
 (action (diff cmark-164.html cmark-164.html.out)))

(rule
 (targets cmark-165.html.out)
 (deps cmark-165.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-165)
 (action (diff cmark-165.html cmark-165.html.out)))

(rule
 (targets cmark-166.html.out)
 (deps cmark-166.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-166)
 (action (diff cmark-166.html cmark-166.html.out)))

(rule
 (targets cmark-167.html.out)
 (deps cmark-167.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-167)
 (action (diff cmark-167.html cmark-167.html.out)))

(rule
 (targets cmark-168.html.out)
 (deps cmark-168.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-168)
 (action (diff cmark-168.html cmark-168.html.out)))

(rule
 (targets cmark-169.html.out)
 (deps cmark-169.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-169)
 (action (diff cmark-169.html cmark-169.html.out)))

(rule
 (targets cmark-170.html.out)
 (deps cmark-170.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-170)
 (action (diff cmark-170.html cmark-170.html.out)))

(rule
 (targets cmark-171.html.out)
 (deps cmark-171.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-171)
 (action (diff cmark-171.html cmark-171.html.out)))

(rule
 (targets cmark-172.html.out)
 (deps cmark-172.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-172)
 (action (diff cmark-172.html cmark-172.html.out)))

(rule
 (targets cmark-173.html.out)
 (deps cmark-173.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-173)
 (action (diff cmark-173.html cmark-173.html.out)))

(rule
 (targets cmark-174.html.out)
 (deps cmark-174.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-174)
 (action (diff cmark-174.html cmark-174.html.out)))

(rule
 (targets cmark-175.html.out)
 (deps cmark-175.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-175)
 (action (diff cmark-175.html cmark-175.html.out)))

(rule
 (targets cmark-176.html.out)
 (deps cmark-176.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-176)
 (action (diff cmark-176.html cmark-176.html.out)))

(rule
 (targets cmark-177.html.out)
 (deps cmark-177.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-177)
 (action (diff cmark-177.html cmark-177.html.out)))

(rule
 (targets cmark-178.html.out)
 (deps cmark-178.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-178)
 (action (diff cmark-178.html cmark-178.html.out)))

(rule
 (targets cmark-179.html.out)
 (deps cmark-179.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-179)
 (action (diff cmark-179.html cmark-179.html.out)))

(rule
 (targets cmark-180.html.out)
 (deps cmark-180.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-180)
 (action (diff cmark-180.html cmark-180.html.out)))

(rule
 (targets cmark-181.html.out)
 (deps cmark-181.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-181)
 (action (diff cmark-181.html cmark-181.html.out)))

(rule
 (targets cmark-182.html.out)
 (deps cmark-182.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-182)
 (action (diff cmark-182.html cmark-182.html.out)))

(rule
 (targets cmark-183.html.out)
 (deps cmark-183.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-183)
 (action (diff cmark-183.html cmark-183.html.out)))

(rule
 (targets cmark-184.html.out)
 (deps cmark-184.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-184)
 (action (diff cmark-184.html cmark-184.html.out)))

(rule
 (targets cmark-185.html.out)
 (deps cmark-185.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-185)
 (action (diff cmark-185.html cmark-185.html.out)))

(rule
 (targets cmark-186.html.out)
 (deps cmark-186.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-186)
 (action (diff cmark-186.html cmark-186.html.out)))

(rule
 (targets cmark-187.html.out)
 (deps cmark-187.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-187)
 (action (diff cmark-187.html cmark-187.html.out)))

(rule
 (targets cmark-188.html.out)
 (deps cmark-188.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-188)
 (action (diff cmark-188.html cmark-188.html.out)))

(rule
 (targets cmark-189.html.out)
 (deps cmark-189.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-189)
 (action (diff cmark-189.html cmark-189.html.out)))

(rule
 (targets cmark-190.html.out)
 (deps cmark-190.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-190)
 (action (diff cmark-190.html cmark-190.html.out)))

(rule
 (targets cmark-191.html.out)
 (deps cmark-191.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-191)
 (action (diff cmark-191.html cmark-191.html.out)))

(rule
 (targets cmark-192.html.out)
 (deps cmark-192.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-192)
 (action (diff cmark-192.html cmark-192.html.out)))

(rule
 (targets cmark-193.html.out)
 (deps cmark-193.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-193)
 (action (diff cmark-193.html cmark-193.html.out)))

(rule
 (targets cmark-194.html.out)
 (deps cmark-194.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-194)
 (action (diff cmark-194.html cmark-194.html.out)))

(rule
 (targets cmark-195.html.out)
 (deps cmark-195.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-195)
 (action (diff cmark-195.html cmark-195.html.out)))

(rule
 (targets cmark-196.html.out)
 (deps cmark-196.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-196)
 (action (diff cmark-196.html cmark-196.html.out)))

(rule
 (targets cmark-197.html.out)
 (deps cmark-197.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-197)
 (action (diff cmark-197.html cmark-197.html.out)))

(rule
 (targets cmark-198.html.out)
 (deps cmark-198.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-198)
 (action (diff cmark-198.html cmark-198.html.out)))

(rule
 (targets cmark-199.html.out)
 (deps cmark-199.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-199)
 (action (diff cmark-199.html cmark-199.html.out)))

(rule
 (targets cmark-200.html.out)
 (deps cmark-200.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-200)
 (action (diff cmark-200.html cmark-200.html.out)))

(rule
 (targets cmark-201.html.out)
 (deps cmark-201.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-201)
 (action (diff cmark-201.html cmark-201.html.out)))

(rule
 (targets cmark-202.html.out)
 (deps cmark-202.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-202)
 (action (diff cmark-202.html cmark-202.html.out)))

(rule
 (targets cmark-203.html.out)
 (deps cmark-203.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-203)
 (action (diff cmark-203.html cmark-203.html.out)))

(rule
 (targets cmark-204.html.out)
 (deps cmark-204.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-204)
 (action (diff cmark-204.html cmark-204.html.out)))

(rule
 (targets cmark-205.html.out)
 (deps cmark-205.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-205)
 (action (diff cmark-205.html cmark-205.html.out)))

(rule
 (targets cmark-206.html.out)
 (deps cmark-206.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-206)
 (action (diff cmark-206.html cmark-206.html.out)))

(rule
 (targets cmark-207.html.out)
 (deps cmark-207.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-207)
 (action (diff cmark-207.html cmark-207.html.out)))

(rule
 (targets cmark-208.html.out)
 (deps cmark-208.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-208)
 (action (diff cmark-208.html cmark-208.html.out)))

(rule
 (targets cmark-209.html.out)
 (deps cmark-209.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-209)
 (action (diff cmark-209.html cmark-209.html.out)))

(rule
 (targets cmark-210.html.out)
 (deps cmark-210.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-210)
 (action (diff cmark-210.html cmark-210.html.out)))

(rule
 (targets cmark-211.html.out)
 (deps cmark-211.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-211)
 (action (diff cmark-211.html cmark-211.html.out)))

(rule
 (targets cmark-212.html.out)
 (deps cmark-212.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-212)
 (action (diff cmark-212.html cmark-212.html.out)))

(rule
 (targets cmark-213.html.out)
 (deps cmark-213.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-213)
 (action (diff cmark-213.html cmark-213.html.out)))

(rule
 (targets cmark-214.html.out)
 (deps cmark-214.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-214)
 (action (diff cmark-214.html cmark-214.html.out)))

(rule
 (targets cmark-215.html.out)
 (deps cmark-215.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-215)
 (action (diff cmark-215.html cmark-215.html.out)))

(rule
 (targets cmark-216.html.out)
 (deps cmark-216.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-216)
 (action (diff cmark-216.html cmark-216.html.out)))

(rule
 (targets cmark-217.html.out)
 (deps cmark-217.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-217)
 (action (diff cmark-217.html cmark-217.html.out)))

(rule
 (targets cmark-218.html.out)
 (deps cmark-218.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-218)
 (action (diff cmark-218.html cmark-218.html.out)))

(rule
 (targets cmark-219.html.out)
 (deps cmark-219.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-219)
 (action (diff cmark-219.html cmark-219.html.out)))

(rule
 (targets cmark-220.html.out)
 (deps cmark-220.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-220)
 (action (diff cmark-220.html cmark-220.html.out)))

(rule
 (targets cmark-221.html.out)
 (deps cmark-221.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-221)
 (action (diff cmark-221.html cmark-221.html.out)))

(rule
 (targets cmark-222.html.out)
 (deps cmark-222.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-222)
 (action (diff cmark-222.html cmark-222.html.out)))

(rule
 (targets cmark-223.html.out)
 (deps cmark-223.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-223)
 (action (diff cmark-223.html cmark-223.html.out)))

(rule
 (targets cmark-224.html.out)
 (deps cmark-224.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-224)
 (action (diff cmark-224.html cmark-224.html.out)))

(rule
 (targets cmark-225.html.out)
 (deps cmark-225.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-225)
 (action (diff cmark-225.html cmark-225.html.out)))

(rule
 (targets cmark-226.html.out)
 (deps cmark-226.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-226)
 (action (diff cmark-226.html cmark-226.html.out)))

(rule
 (targets cmark-227.html.out)
 (deps cmark-227.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-227)
 (action (diff cmark-227.html cmark-227.html.out)))

(rule
 (targets cmark-228.html.out)
 (deps cmark-228.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-228)
 (action (diff cmark-228.html cmark-228.html.out)))

(rule
 (targets cmark-229.html.out)
 (deps cmark-229.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-229)
 (action (diff cmark-229.html cmark-229.html.out)))

(rule
 (targets cmark-230.html.out)
 (deps cmark-230.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-230)
 (action (diff cmark-230.html cmark-230.html.out)))

(rule
 (targets cmark-231.html.out)
 (deps cmark-231.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-231)
 (action (diff cmark-231.html cmark-231.html.out)))

(rule
 (targets cmark-232.html.out)
 (deps cmark-232.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-232)
 (action (diff cmark-232.html cmark-232.html.out)))

(rule
 (targets cmark-233.html.out)
 (deps cmark-233.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-233)
 (action (diff cmark-233.html cmark-233.html.out)))

(rule
 (targets cmark-234.html.out)
 (deps cmark-234.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-234)
 (action (diff cmark-234.html cmark-234.html.out)))

(rule
 (targets cmark-235.html.out)
 (deps cmark-235.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-235)
 (action (diff cmark-235.html cmark-235.html.out)))

(rule
 (targets cmark-236.html.out)
 (deps cmark-236.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-236)
 (action (diff cmark-236.html cmark-236.html.out)))

(rule
 (targets cmark-237.html.out)
 (deps cmark-237.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-237)
 (action (diff cmark-237.html cmark-237.html.out)))

(rule
 (targets cmark-238.html.out)
 (deps cmark-238.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-238)
 (action (diff cmark-238.html cmark-238.html.out)))

(rule
 (targets cmark-239.html.out)
 (deps cmark-239.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-239)
 (action (diff cmark-239.html cmark-239.html.out)))

(rule
 (targets cmark-240.html.out)
 (deps cmark-240.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-240)
 (action (diff cmark-240.html cmark-240.html.out)))

(rule
 (targets cmark-241.html.out)
 (deps cmark-241.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-241)
 (action (diff cmark-241.html cmark-241.html.out)))

(rule
 (targets cmark-242.html.out)
 (deps cmark-242.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-242)
 (action (diff cmark-242.html cmark-242.html.out)))

(rule
 (targets cmark-243.html.out)
 (deps cmark-243.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-243)
 (action (diff cmark-243.html cmark-243.html.out)))

(rule
 (targets cmark-244.html.out)
 (deps cmark-244.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-244)
 (action (diff cmark-244.html cmark-244.html.out)))

(rule
 (targets cmark-245.html.out)
 (deps cmark-245.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-245)
 (action (diff cmark-245.html cmark-245.html.out)))

(rule
 (targets cmark-246.html.out)
 (deps cmark-246.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-246)
 (action (diff cmark-246.html cmark-246.html.out)))

(rule
 (targets cmark-247.html.out)
 (deps cmark-247.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-247)
 (action (diff cmark-247.html cmark-247.html.out)))

(rule
 (targets cmark-248.html.out)
 (deps cmark-248.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-248)
 (action (diff cmark-248.html cmark-248.html.out)))

(rule
 (targets cmark-249.html.out)
 (deps cmark-249.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-249)
 (action (diff cmark-249.html cmark-249.html.out)))

(rule
 (targets cmark-250.html.out)
 (deps cmark-250.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-250)
 (action (diff cmark-250.html cmark-250.html.out)))

(rule
 (targets cmark-251.html.out)
 (deps cmark-251.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-251)
 (action (diff cmark-251.html cmark-251.html.out)))

(rule
 (targets cmark-252.html.out)
 (deps cmark-252.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-252)
 (action (diff cmark-252.html cmark-252.html.out)))

(rule
 (targets cmark-253.html.out)
 (deps cmark-253.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-253)
 (action (diff cmark-253.html cmark-253.html.out)))

(rule
 (targets cmark-254.html.out)
 (deps cmark-254.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-254)
 (action (diff cmark-254.html cmark-254.html.out)))

(rule
 (targets cmark-255.html.out)
 (deps cmark-255.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-255)
 (action (diff cmark-255.html cmark-255.html.out)))

(rule
 (targets cmark-256.html.out)
 (deps cmark-256.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-256)
 (action (diff cmark-256.html cmark-256.html.out)))

(rule
 (targets cmark-257.html.out)
 (deps cmark-257.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-257)
 (action (diff cmark-257.html cmark-257.html.out)))

(rule
 (targets cmark-258.html.out)
 (deps cmark-258.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-258)
 (action (diff cmark-258.html cmark-258.html.out)))

(rule
 (targets cmark-259.html.out)
 (deps cmark-259.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-259)
 (action (diff cmark-259.html cmark-259.html.out)))

(rule
 (targets cmark-260.html.out)
 (deps cmark-260.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-260)
 (action (diff cmark-260.html cmark-260.html.out)))

(rule
 (targets cmark-261.html.out)
 (deps cmark-261.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-261)
 (action (diff cmark-261.html cmark-261.html.out)))

(rule
 (targets cmark-262.html.out)
 (deps cmark-262.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-262)
 (action (diff cmark-262.html cmark-262.html.out)))

(rule
 (targets cmark-263.html.out)
 (deps cmark-263.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-263)
 (action (diff cmark-263.html cmark-263.html.out)))

(rule
 (targets cmark-264.html.out)
 (deps cmark-264.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-264)
 (action (diff cmark-264.html cmark-264.html.out)))

(rule
 (targets cmark-265.html.out)
 (deps cmark-265.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-265)
 (action (diff cmark-265.html cmark-265.html.out)))

(rule
 (targets cmark-266.html.out)
 (deps cmark-266.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-266)
 (action (diff cmark-266.html cmark-266.html.out)))

(rule
 (targets cmark-267.html.out)
 (deps cmark-267.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-267)
 (action (diff cmark-267.html cmark-267.html.out)))

(rule
 (targets cmark-268.html.out)
 (deps cmark-268.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-268)
 (action (diff cmark-268.html cmark-268.html.out)))

(rule
 (targets cmark-269.html.out)
 (deps cmark-269.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-269)
 (action (diff cmark-269.html cmark-269.html.out)))

(rule
 (targets cmark-270.html.out)
 (deps cmark-270.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-270)
 (action (diff cmark-270.html cmark-270.html.out)))

(rule
 (targets cmark-271.html.out)
 (deps cmark-271.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-271)
 (action (diff cmark-271.html cmark-271.html.out)))

(rule
 (targets cmark-272.html.out)
 (deps cmark-272.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-272)
 (action (diff cmark-272.html cmark-272.html.out)))

(rule
 (targets cmark-273.html.out)
 (deps cmark-273.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-273)
 (action (diff cmark-273.html cmark-273.html.out)))

(rule
 (targets cmark-274.html.out)
 (deps cmark-274.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-274)
 (action (diff cmark-274.html cmark-274.html.out)))

(rule
 (targets cmark-275.html.out)
 (deps cmark-275.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-275)
 (action (diff cmark-275.html cmark-275.html.out)))

(rule
 (targets cmark-276.html.out)
 (deps cmark-276.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-276)
 (action (diff cmark-276.html cmark-276.html.out)))

(rule
 (targets cmark-277.html.out)
 (deps cmark-277.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-277)
 (action (diff cmark-277.html cmark-277.html.out)))

(rule
 (targets cmark-278.html.out)
 (deps cmark-278.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-278)
 (action (diff cmark-278.html cmark-278.html.out)))

(rule
 (targets cmark-279.html.out)
 (deps cmark-279.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-279)
 (action (diff cmark-279.html cmark-279.html.out)))

(rule
 (targets cmark-280.html.out)
 (deps cmark-280.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-280)
 (action (diff cmark-280.html cmark-280.html.out)))

(rule
 (targets cmark-281.html.out)
 (deps cmark-281.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-281)
 (action (diff cmark-281.html cmark-281.html.out)))

(rule
 (targets cmark-282.html.out)
 (deps cmark-282.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-282)
 (action (diff cmark-282.html cmark-282.html.out)))

(rule
 (targets cmark-283.html.out)
 (deps cmark-283.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-283)
 (action (diff cmark-283.html cmark-283.html.out)))

(rule
 (targets cmark-284.html.out)
 (deps cmark-284.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-284)
 (action (diff cmark-284.html cmark-284.html.out)))

(rule
 (targets cmark-285.html.out)
 (deps cmark-285.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-285)
 (action (diff cmark-285.html cmark-285.html.out)))

(rule
 (targets cmark-286.html.out)
 (deps cmark-286.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-286)
 (action (diff cmark-286.html cmark-286.html.out)))

(rule
 (targets cmark-287.html.out)
 (deps cmark-287.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-287)
 (action (diff cmark-287.html cmark-287.html.out)))

(rule
 (targets cmark-288.html.out)
 (deps cmark-288.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-288)
 (action (diff cmark-288.html cmark-288.html.out)))

(rule
 (targets cmark-289.html.out)
 (deps cmark-289.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-289)
 (action (diff cmark-289.html cmark-289.html.out)))

(rule
 (targets cmark-290.html.out)
 (deps cmark-290.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-290)
 (action (diff cmark-290.html cmark-290.html.out)))

(rule
 (targets cmark-291.html.out)
 (deps cmark-291.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-291)
 (action (diff cmark-291.html cmark-291.html.out)))

(rule
 (targets cmark-292.html.out)
 (deps cmark-292.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-292)
 (action (diff cmark-292.html cmark-292.html.out)))

(rule
 (targets cmark-293.html.out)
 (deps cmark-293.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-293)
 (action (diff cmark-293.html cmark-293.html.out)))

(rule
 (targets cmark-294.html.out)
 (deps cmark-294.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-294)
 (action (diff cmark-294.html cmark-294.html.out)))

(rule
 (targets cmark-295.html.out)
 (deps cmark-295.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-295)
 (action (diff cmark-295.html cmark-295.html.out)))

(rule
 (targets cmark-296.html.out)
 (deps cmark-296.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-296)
 (action (diff cmark-296.html cmark-296.html.out)))

(rule
 (targets cmark-297.html.out)
 (deps cmark-297.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-297)
 (action (diff cmark-297.html cmark-297.html.out)))

(rule
 (targets cmark-298.html.out)
 (deps cmark-298.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-298)
 (action (diff cmark-298.html cmark-298.html.out)))

(rule
 (targets cmark-299.html.out)
 (deps cmark-299.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-299)
 (action (diff cmark-299.html cmark-299.html.out)))

(rule
 (targets cmark-300.html.out)
 (deps cmark-300.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-300)
 (action (diff cmark-300.html cmark-300.html.out)))

(rule
 (targets cmark-301.html.out)
 (deps cmark-301.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-301)
 (action (diff cmark-301.html cmark-301.html.out)))

(rule
 (targets cmark-302.html.out)
 (deps cmark-302.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-302)
 (action (diff cmark-302.html cmark-302.html.out)))

(rule
 (targets cmark-303.html.out)
 (deps cmark-303.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-303)
 (action (diff cmark-303.html cmark-303.html.out)))

(rule
 (targets cmark-304.html.out)
 (deps cmark-304.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-304)
 (action (diff cmark-304.html cmark-304.html.out)))

(rule
 (targets cmark-305.html.out)
 (deps cmark-305.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-305)
 (action (diff cmark-305.html cmark-305.html.out)))

(rule
 (targets cmark-306.html.out)
 (deps cmark-306.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-306)
 (action (diff cmark-306.html cmark-306.html.out)))

(rule
 (targets cmark-307.html.out)
 (deps cmark-307.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-307)
 (action (diff cmark-307.html cmark-307.html.out)))

(rule
 (targets cmark-308.html.out)
 (deps cmark-308.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-308)
 (action (diff cmark-308.html cmark-308.html.out)))

(rule
 (targets cmark-309.html.out)
 (deps cmark-309.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-309)
 (action (diff cmark-309.html cmark-309.html.out)))

(rule
 (targets cmark-310.html.out)
 (deps cmark-310.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-310)
 (action (diff cmark-310.html cmark-310.html.out)))

(rule
 (targets cmark-311.html.out)
 (deps cmark-311.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-311)
 (action (diff cmark-311.html cmark-311.html.out)))

(rule
 (targets cmark-312.html.out)
 (deps cmark-312.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-312)
 (action (diff cmark-312.html cmark-312.html.out)))

(rule
 (targets cmark-313.html.out)
 (deps cmark-313.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-313)
 (action (diff cmark-313.html cmark-313.html.out)))

(rule
 (targets cmark-314.html.out)
 (deps cmark-314.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-314)
 (action (diff cmark-314.html cmark-314.html.out)))

(rule
 (targets cmark-315.html.out)
 (deps cmark-315.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-315)
 (action (diff cmark-315.html cmark-315.html.out)))

(rule
 (targets cmark-316.html.out)
 (deps cmark-316.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-316)
 (action (diff cmark-316.html cmark-316.html.out)))

(rule
 (targets cmark-317.html.out)
 (deps cmark-317.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-317)
 (action (diff cmark-317.html cmark-317.html.out)))

(rule
 (targets cmark-318.html.out)
 (deps cmark-318.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-318)
 (action (diff cmark-318.html cmark-318.html.out)))

(rule
 (targets cmark-319.html.out)
 (deps cmark-319.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-319)
 (action (diff cmark-319.html cmark-319.html.out)))

(rule
 (targets cmark-320.html.out)
 (deps cmark-320.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-320)
 (action (diff cmark-320.html cmark-320.html.out)))

(rule
 (targets cmark-321.html.out)
 (deps cmark-321.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-321)
 (action (diff cmark-321.html cmark-321.html.out)))

(rule
 (targets cmark-322.html.out)
 (deps cmark-322.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-322)
 (action (diff cmark-322.html cmark-322.html.out)))

(rule
 (targets cmark-323.html.out)
 (deps cmark-323.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-323)
 (action (diff cmark-323.html cmark-323.html.out)))

(rule
 (targets cmark-324.html.out)
 (deps cmark-324.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-324)
 (action (diff cmark-324.html cmark-324.html.out)))

(rule
 (targets cmark-325.html.out)
 (deps cmark-325.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-325)
 (action (diff cmark-325.html cmark-325.html.out)))

(rule
 (targets cmark-326.html.out)
 (deps cmark-326.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-326)
 (action (diff cmark-326.html cmark-326.html.out)))

(rule
 (targets cmark-327.html.out)
 (deps cmark-327.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-327)
 (action (diff cmark-327.html cmark-327.html.out)))

(rule
 (targets cmark-328.html.out)
 (deps cmark-328.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-328)
 (action (diff cmark-328.html cmark-328.html.out)))

(rule
 (targets cmark-329.html.out)
 (deps cmark-329.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-329)
 (action (diff cmark-329.html cmark-329.html.out)))

(rule
 (targets cmark-330.html.out)
 (deps cmark-330.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-330)
 (action (diff cmark-330.html cmark-330.html.out)))

(rule
 (targets cmark-331.html.out)
 (deps cmark-331.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-331)
 (action (diff cmark-331.html cmark-331.html.out)))

(rule
 (targets cmark-332.html.out)
 (deps cmark-332.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-332)
 (action (diff cmark-332.html cmark-332.html.out)))

(rule
 (targets cmark-333.html.out)
 (deps cmark-333.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-333)
 (action (diff cmark-333.html cmark-333.html.out)))

(rule
 (targets cmark-334.html.out)
 (deps cmark-334.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-334)
 (action (diff cmark-334.html cmark-334.html.out)))

(rule
 (targets cmark-335.html.out)
 (deps cmark-335.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-335)
 (action (diff cmark-335.html cmark-335.html.out)))

(rule
 (targets cmark-336.html.out)
 (deps cmark-336.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-336)
 (action (diff cmark-336.html cmark-336.html.out)))

(rule
 (targets cmark-337.html.out)
 (deps cmark-337.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-337)
 (action (diff cmark-337.html cmark-337.html.out)))

(rule
 (targets cmark-338.html.out)
 (deps cmark-338.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-338)
 (action (diff cmark-338.html cmark-338.html.out)))

(rule
 (targets cmark-339.html.out)
 (deps cmark-339.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-339)
 (action (diff cmark-339.html cmark-339.html.out)))

(rule
 (targets cmark-340.html.out)
 (deps cmark-340.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-340)
 (action (diff cmark-340.html cmark-340.html.out)))

(rule
 (targets cmark-341.html.out)
 (deps cmark-341.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-341)
 (action (diff cmark-341.html cmark-341.html.out)))

(rule
 (targets cmark-342.html.out)
 (deps cmark-342.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-342)
 (action (diff cmark-342.html cmark-342.html.out)))

(rule
 (targets cmark-343.html.out)
 (deps cmark-343.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-343)
 (action (diff cmark-343.html cmark-343.html.out)))

(rule
 (targets cmark-344.html.out)
 (deps cmark-344.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-344)
 (action (diff cmark-344.html cmark-344.html.out)))

(rule
 (targets cmark-345.html.out)
 (deps cmark-345.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-345)
 (action (diff cmark-345.html cmark-345.html.out)))

(rule
 (targets cmark-346.html.out)
 (deps cmark-346.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-346)
 (action (diff cmark-346.html cmark-346.html.out)))

(rule
 (targets cmark-347.html.out)
 (deps cmark-347.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-347)
 (action (diff cmark-347.html cmark-347.html.out)))

(rule
 (targets cmark-348.html.out)
 (deps cmark-348.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-348)
 (action (diff cmark-348.html cmark-348.html.out)))

(rule
 (targets cmark-349.html.out)
 (deps cmark-349.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-349)
 (action (diff cmark-349.html cmark-349.html.out)))

(rule
 (targets cmark-350.html.out)
 (deps cmark-350.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-350)
 (action (diff cmark-350.html cmark-350.html.out)))

(rule
 (targets cmark-351.html.out)
 (deps cmark-351.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-351)
 (action (diff cmark-351.html cmark-351.html.out)))

(rule
 (targets cmark-352.html.out)
 (deps cmark-352.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-352)
 (action (diff cmark-352.html cmark-352.html.out)))

(rule
 (targets cmark-353.html.out)
 (deps cmark-353.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-353)
 (action (diff cmark-353.html cmark-353.html.out)))

(rule
 (targets cmark-354.html.out)
 (deps cmark-354.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-354)
 (action (diff cmark-354.html cmark-354.html.out)))

(rule
 (targets cmark-355.html.out)
 (deps cmark-355.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-355)
 (action (diff cmark-355.html cmark-355.html.out)))

(rule
 (targets cmark-356.html.out)
 (deps cmark-356.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-356)
 (action (diff cmark-356.html cmark-356.html.out)))

(rule
 (targets cmark-357.html.out)
 (deps cmark-357.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-357)
 (action (diff cmark-357.html cmark-357.html.out)))

(rule
 (targets cmark-358.html.out)
 (deps cmark-358.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-358)
 (action (diff cmark-358.html cmark-358.html.out)))

(rule
 (targets cmark-359.html.out)
 (deps cmark-359.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-359)
 (action (diff cmark-359.html cmark-359.html.out)))

(rule
 (targets cmark-360.html.out)
 (deps cmark-360.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-360)
 (action (diff cmark-360.html cmark-360.html.out)))

(rule
 (targets cmark-361.html.out)
 (deps cmark-361.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-361)
 (action (diff cmark-361.html cmark-361.html.out)))

(rule
 (targets cmark-362.html.out)
 (deps cmark-362.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-362)
 (action (diff cmark-362.html cmark-362.html.out)))

(rule
 (targets cmark-363.html.out)
 (deps cmark-363.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-363)
 (action (diff cmark-363.html cmark-363.html.out)))

(rule
 (targets cmark-364.html.out)
 (deps cmark-364.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-364)
 (action (diff cmark-364.html cmark-364.html.out)))

(rule
 (targets cmark-365.html.out)
 (deps cmark-365.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-365)
 (action (diff cmark-365.html cmark-365.html.out)))

(rule
 (targets cmark-366.html.out)
 (deps cmark-366.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-366)
 (action (diff cmark-366.html cmark-366.html.out)))

(rule
 (targets cmark-367.html.out)
 (deps cmark-367.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-367)
 (action (diff cmark-367.html cmark-367.html.out)))

(rule
 (targets cmark-368.html.out)
 (deps cmark-368.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-368)
 (action (diff cmark-368.html cmark-368.html.out)))

(rule
 (targets cmark-369.html.out)
 (deps cmark-369.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-369)
 (action (diff cmark-369.html cmark-369.html.out)))

(rule
 (targets cmark-370.html.out)
 (deps cmark-370.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-370)
 (action (diff cmark-370.html cmark-370.html.out)))

(rule
 (targets cmark-371.html.out)
 (deps cmark-371.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-371)
 (action (diff cmark-371.html cmark-371.html.out)))

(rule
 (targets cmark-372.html.out)
 (deps cmark-372.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-372)
 (action (diff cmark-372.html cmark-372.html.out)))

(rule
 (targets cmark-373.html.out)
 (deps cmark-373.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-373)
 (action (diff cmark-373.html cmark-373.html.out)))

(rule
 (targets cmark-374.html.out)
 (deps cmark-374.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-374)
 (action (diff cmark-374.html cmark-374.html.out)))

(rule
 (targets cmark-375.html.out)
 (deps cmark-375.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-375)
 (action (diff cmark-375.html cmark-375.html.out)))

(rule
 (targets cmark-376.html.out)
 (deps cmark-376.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-376)
 (action (diff cmark-376.html cmark-376.html.out)))

(rule
 (targets cmark-377.html.out)
 (deps cmark-377.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-377)
 (action (diff cmark-377.html cmark-377.html.out)))

(rule
 (targets cmark-378.html.out)
 (deps cmark-378.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-378)
 (action (diff cmark-378.html cmark-378.html.out)))

(rule
 (targets cmark-379.html.out)
 (deps cmark-379.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-379)
 (action (diff cmark-379.html cmark-379.html.out)))

(rule
 (targets cmark-380.html.out)
 (deps cmark-380.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-380)
 (action (diff cmark-380.html cmark-380.html.out)))

(rule
 (targets cmark-381.html.out)
 (deps cmark-381.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-381)
 (action (diff cmark-381.html cmark-381.html.out)))

(rule
 (targets cmark-382.html.out)
 (deps cmark-382.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-382)
 (action (diff cmark-382.html cmark-382.html.out)))

(rule
 (targets cmark-383.html.out)
 (deps cmark-383.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-383)
 (action (diff cmark-383.html cmark-383.html.out)))

(rule
 (targets cmark-384.html.out)
 (deps cmark-384.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-384)
 (action (diff cmark-384.html cmark-384.html.out)))

(rule
 (targets cmark-385.html.out)
 (deps cmark-385.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-385)
 (action (diff cmark-385.html cmark-385.html.out)))

(rule
 (targets cmark-386.html.out)
 (deps cmark-386.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-386)
 (action (diff cmark-386.html cmark-386.html.out)))

(rule
 (targets cmark-387.html.out)
 (deps cmark-387.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-387)
 (action (diff cmark-387.html cmark-387.html.out)))

(rule
 (targets cmark-388.html.out)
 (deps cmark-388.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-388)
 (action (diff cmark-388.html cmark-388.html.out)))

(rule
 (targets cmark-389.html.out)
 (deps cmark-389.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-389)
 (action (diff cmark-389.html cmark-389.html.out)))

(rule
 (targets cmark-390.html.out)
 (deps cmark-390.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-390)
 (action (diff cmark-390.html cmark-390.html.out)))

(rule
 (targets cmark-391.html.out)
 (deps cmark-391.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-391)
 (action (diff cmark-391.html cmark-391.html.out)))

(rule
 (targets cmark-392.html.out)
 (deps cmark-392.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-392)
 (action (diff cmark-392.html cmark-392.html.out)))

(rule
 (targets cmark-393.html.out)
 (deps cmark-393.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-393)
 (action (diff cmark-393.html cmark-393.html.out)))

(rule
 (targets cmark-394.html.out)
 (deps cmark-394.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-394)
 (action (diff cmark-394.html cmark-394.html.out)))

(rule
 (targets cmark-395.html.out)
 (deps cmark-395.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-395)
 (action (diff cmark-395.html cmark-395.html.out)))

(rule
 (targets cmark-396.html.out)
 (deps cmark-396.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-396)
 (action (diff cmark-396.html cmark-396.html.out)))

(rule
 (targets cmark-397.html.out)
 (deps cmark-397.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-397)
 (action (diff cmark-397.html cmark-397.html.out)))

(rule
 (targets cmark-398.html.out)
 (deps cmark-398.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-398)
 (action (diff cmark-398.html cmark-398.html.out)))

(rule
 (targets cmark-399.html.out)
 (deps cmark-399.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-399)
 (action (diff cmark-399.html cmark-399.html.out)))

(rule
 (targets cmark-400.html.out)
 (deps cmark-400.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-400)
 (action (diff cmark-400.html cmark-400.html.out)))

(rule
 (targets cmark-401.html.out)
 (deps cmark-401.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-401)
 (action (diff cmark-401.html cmark-401.html.out)))

(rule
 (targets cmark-402.html.out)
 (deps cmark-402.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-402)
 (action (diff cmark-402.html cmark-402.html.out)))

(rule
 (targets cmark-403.html.out)
 (deps cmark-403.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-403)
 (action (diff cmark-403.html cmark-403.html.out)))

(rule
 (targets cmark-404.html.out)
 (deps cmark-404.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-404)
 (action (diff cmark-404.html cmark-404.html.out)))

(rule
 (targets cmark-405.html.out)
 (deps cmark-405.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-405)
 (action (diff cmark-405.html cmark-405.html.out)))

(rule
 (targets cmark-406.html.out)
 (deps cmark-406.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-406)
 (action (diff cmark-406.html cmark-406.html.out)))

(rule
 (targets cmark-407.html.out)
 (deps cmark-407.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-407)
 (action (diff cmark-407.html cmark-407.html.out)))

(rule
 (targets cmark-408.html.out)
 (deps cmark-408.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-408)
 (action (diff cmark-408.html cmark-408.html.out)))

(rule
 (targets cmark-409.html.out)
 (deps cmark-409.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-409)
 (action (diff cmark-409.html cmark-409.html.out)))

(rule
 (targets cmark-410.html.out)
 (deps cmark-410.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-410)
 (action (diff cmark-410.html cmark-410.html.out)))

(rule
 (targets cmark-411.html.out)
 (deps cmark-411.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-411)
 (action (diff cmark-411.html cmark-411.html.out)))

(rule
 (targets cmark-412.html.out)
 (deps cmark-412.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-412)
 (action (diff cmark-412.html cmark-412.html.out)))

(rule
 (targets cmark-413.html.out)
 (deps cmark-413.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-413)
 (action (diff cmark-413.html cmark-413.html.out)))

(rule
 (targets cmark-414.html.out)
 (deps cmark-414.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-414)
 (action (diff cmark-414.html cmark-414.html.out)))

(rule
 (targets cmark-415.html.out)
 (deps cmark-415.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-415)
 (action (diff cmark-415.html cmark-415.html.out)))

(rule
 (targets cmark-416.html.out)
 (deps cmark-416.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-416)
 (action (diff cmark-416.html cmark-416.html.out)))

(rule
 (targets cmark-417.html.out)
 (deps cmark-417.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-417)
 (action (diff cmark-417.html cmark-417.html.out)))

(rule
 (targets cmark-418.html.out)
 (deps cmark-418.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-418)
 (action (diff cmark-418.html cmark-418.html.out)))

(rule
 (targets cmark-419.html.out)
 (deps cmark-419.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-419)
 (action (diff cmark-419.html cmark-419.html.out)))

(rule
 (targets cmark-420.html.out)
 (deps cmark-420.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-420)
 (action (diff cmark-420.html cmark-420.html.out)))

(rule
 (targets cmark-421.html.out)
 (deps cmark-421.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-421)
 (action (diff cmark-421.html cmark-421.html.out)))

(rule
 (targets cmark-422.html.out)
 (deps cmark-422.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-422)
 (action (diff cmark-422.html cmark-422.html.out)))

(rule
 (targets cmark-423.html.out)
 (deps cmark-423.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-423)
 (action (diff cmark-423.html cmark-423.html.out)))

(rule
 (targets cmark-424.html.out)
 (deps cmark-424.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-424)
 (action (diff cmark-424.html cmark-424.html.out)))

(rule
 (targets cmark-425.html.out)
 (deps cmark-425.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-425)
 (action (diff cmark-425.html cmark-425.html.out)))

(rule
 (targets cmark-426.html.out)
 (deps cmark-426.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-426)
 (action (diff cmark-426.html cmark-426.html.out)))

(rule
 (targets cmark-427.html.out)
 (deps cmark-427.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-427)
 (action (diff cmark-427.html cmark-427.html.out)))

(rule
 (targets cmark-428.html.out)
 (deps cmark-428.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-428)
 (action (diff cmark-428.html cmark-428.html.out)))

(rule
 (targets cmark-429.html.out)
 (deps cmark-429.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-429)
 (action (diff cmark-429.html cmark-429.html.out)))

(rule
 (targets cmark-430.html.out)
 (deps cmark-430.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-430)
 (action (diff cmark-430.html cmark-430.html.out)))

(rule
 (targets cmark-431.html.out)
 (deps cmark-431.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-431)
 (action (diff cmark-431.html cmark-431.html.out)))

(rule
 (targets cmark-432.html.out)
 (deps cmark-432.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-432)
 (action (diff cmark-432.html cmark-432.html.out)))

(rule
 (targets cmark-433.html.out)
 (deps cmark-433.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-433)
 (action (diff cmark-433.html cmark-433.html.out)))

(rule
 (targets cmark-434.html.out)
 (deps cmark-434.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-434)
 (action (diff cmark-434.html cmark-434.html.out)))

(rule
 (targets cmark-435.html.out)
 (deps cmark-435.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-435)
 (action (diff cmark-435.html cmark-435.html.out)))

(rule
 (targets cmark-436.html.out)
 (deps cmark-436.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-436)
 (action (diff cmark-436.html cmark-436.html.out)))

(rule
 (targets cmark-437.html.out)
 (deps cmark-437.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-437)
 (action (diff cmark-437.html cmark-437.html.out)))

(rule
 (targets cmark-438.html.out)
 (deps cmark-438.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-438)
 (action (diff cmark-438.html cmark-438.html.out)))

(rule
 (targets cmark-439.html.out)
 (deps cmark-439.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-439)
 (action (diff cmark-439.html cmark-439.html.out)))

(rule
 (targets cmark-440.html.out)
 (deps cmark-440.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-440)
 (action (diff cmark-440.html cmark-440.html.out)))

(rule
 (targets cmark-441.html.out)
 (deps cmark-441.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-441)
 (action (diff cmark-441.html cmark-441.html.out)))

(rule
 (targets cmark-442.html.out)
 (deps cmark-442.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-442)
 (action (diff cmark-442.html cmark-442.html.out)))

(rule
 (targets cmark-443.html.out)
 (deps cmark-443.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-443)
 (action (diff cmark-443.html cmark-443.html.out)))

(rule
 (targets cmark-444.html.out)
 (deps cmark-444.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-444)
 (action (diff cmark-444.html cmark-444.html.out)))

(rule
 (targets cmark-445.html.out)
 (deps cmark-445.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-445)
 (action (diff cmark-445.html cmark-445.html.out)))

(rule
 (targets cmark-446.html.out)
 (deps cmark-446.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-446)
 (action (diff cmark-446.html cmark-446.html.out)))

(rule
 (targets cmark-447.html.out)
 (deps cmark-447.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-447)
 (action (diff cmark-447.html cmark-447.html.out)))

(rule
 (targets cmark-448.html.out)
 (deps cmark-448.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-448)
 (action (diff cmark-448.html cmark-448.html.out)))

(rule
 (targets cmark-449.html.out)
 (deps cmark-449.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-449)
 (action (diff cmark-449.html cmark-449.html.out)))

(rule
 (targets cmark-450.html.out)
 (deps cmark-450.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-450)
 (action (diff cmark-450.html cmark-450.html.out)))

(rule
 (targets cmark-451.html.out)
 (deps cmark-451.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-451)
 (action (diff cmark-451.html cmark-451.html.out)))

(rule
 (targets cmark-452.html.out)
 (deps cmark-452.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-452)
 (action (diff cmark-452.html cmark-452.html.out)))

(rule
 (targets cmark-453.html.out)
 (deps cmark-453.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-453)
 (action (diff cmark-453.html cmark-453.html.out)))

(rule
 (targets cmark-454.html.out)
 (deps cmark-454.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-454)
 (action (diff cmark-454.html cmark-454.html.out)))

(rule
 (targets cmark-455.html.out)
 (deps cmark-455.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-455)
 (action (diff cmark-455.html cmark-455.html.out)))

(rule
 (targets cmark-456.html.out)
 (deps cmark-456.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-456)
 (action (diff cmark-456.html cmark-456.html.out)))

(rule
 (targets cmark-457.html.out)
 (deps cmark-457.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-457)
 (action (diff cmark-457.html cmark-457.html.out)))

(rule
 (targets cmark-458.html.out)
 (deps cmark-458.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-458)
 (action (diff cmark-458.html cmark-458.html.out)))

(rule
 (targets cmark-459.html.out)
 (deps cmark-459.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-459)
 (action (diff cmark-459.html cmark-459.html.out)))

(rule
 (targets cmark-460.html.out)
 (deps cmark-460.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-460)
 (action (diff cmark-460.html cmark-460.html.out)))

(rule
 (targets cmark-461.html.out)
 (deps cmark-461.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-461)
 (action (diff cmark-461.html cmark-461.html.out)))

(rule
 (targets cmark-462.html.out)
 (deps cmark-462.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-462)
 (action (diff cmark-462.html cmark-462.html.out)))

(rule
 (targets cmark-463.html.out)
 (deps cmark-463.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-463)
 (action (diff cmark-463.html cmark-463.html.out)))

(rule
 (targets cmark-464.html.out)
 (deps cmark-464.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-464)
 (action (diff cmark-464.html cmark-464.html.out)))

(rule
 (targets cmark-465.html.out)
 (deps cmark-465.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-465)
 (action (diff cmark-465.html cmark-465.html.out)))

(rule
 (targets cmark-466.html.out)
 (deps cmark-466.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-466)
 (action (diff cmark-466.html cmark-466.html.out)))

(rule
 (targets cmark-467.html.out)
 (deps cmark-467.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-467)
 (action (diff cmark-467.html cmark-467.html.out)))

(rule
 (targets cmark-468.html.out)
 (deps cmark-468.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-468)
 (action (diff cmark-468.html cmark-468.html.out)))

(rule
 (targets cmark-469.html.out)
 (deps cmark-469.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-469)
 (action (diff cmark-469.html cmark-469.html.out)))

(rule
 (targets cmark-470.html.out)
 (deps cmark-470.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-470)
 (action (diff cmark-470.html cmark-470.html.out)))

(rule
 (targets cmark-471.html.out)
 (deps cmark-471.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-471)
 (action (diff cmark-471.html cmark-471.html.out)))

(rule
 (targets cmark-472.html.out)
 (deps cmark-472.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-472)
 (action (diff cmark-472.html cmark-472.html.out)))

(rule
 (targets cmark-473.html.out)
 (deps cmark-473.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-473)
 (action (diff cmark-473.html cmark-473.html.out)))

(rule
 (targets cmark-474.html.out)
 (deps cmark-474.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-474)
 (action (diff cmark-474.html cmark-474.html.out)))

(rule
 (targets cmark-475.html.out)
 (deps cmark-475.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-475)
 (action (diff cmark-475.html cmark-475.html.out)))

(rule
 (targets cmark-476.html.out)
 (deps cmark-476.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-476)
 (action (diff cmark-476.html cmark-476.html.out)))

(rule
 (targets cmark-477.html.out)
 (deps cmark-477.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-477)
 (action (diff cmark-477.html cmark-477.html.out)))

(rule
 (targets cmark-478.html.out)
 (deps cmark-478.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-478)
 (action (diff cmark-478.html cmark-478.html.out)))

(rule
 (targets cmark-479.html.out)
 (deps cmark-479.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-479)
 (action (diff cmark-479.html cmark-479.html.out)))

(rule
 (targets cmark-480.html.out)
 (deps cmark-480.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-480)
 (action (diff cmark-480.html cmark-480.html.out)))

(rule
 (targets cmark-481.html.out)
 (deps cmark-481.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-481)
 (action (diff cmark-481.html cmark-481.html.out)))

(rule
 (targets cmark-482.html.out)
 (deps cmark-482.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-482)
 (action (diff cmark-482.html cmark-482.html.out)))

(rule
 (targets cmark-483.html.out)
 (deps cmark-483.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-483)
 (action (diff cmark-483.html cmark-483.html.out)))

(rule
 (targets cmark-484.html.out)
 (deps cmark-484.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-484)
 (action (diff cmark-484.html cmark-484.html.out)))

(rule
 (targets cmark-485.html.out)
 (deps cmark-485.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-485)
 (action (diff cmark-485.html cmark-485.html.out)))

(rule
 (targets cmark-486.html.out)
 (deps cmark-486.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-486)
 (action (diff cmark-486.html cmark-486.html.out)))

(rule
 (targets cmark-487.html.out)
 (deps cmark-487.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-487)
 (action (diff cmark-487.html cmark-487.html.out)))

(rule
 (targets cmark-488.html.out)
 (deps cmark-488.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-488)
 (action (diff cmark-488.html cmark-488.html.out)))

(rule
 (targets cmark-489.html.out)
 (deps cmark-489.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-489)
 (action (diff cmark-489.html cmark-489.html.out)))

(rule
 (targets cmark-490.html.out)
 (deps cmark-490.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-490)
 (action (diff cmark-490.html cmark-490.html.out)))

(rule
 (targets cmark-491.html.out)
 (deps cmark-491.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-491)
 (action (diff cmark-491.html cmark-491.html.out)))

(rule
 (targets cmark-492.html.out)
 (deps cmark-492.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-492)
 (action (diff cmark-492.html cmark-492.html.out)))

(rule
 (targets cmark-493.html.out)
 (deps cmark-493.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-493)
 (action (diff cmark-493.html cmark-493.html.out)))

(rule
 (targets cmark-494.html.out)
 (deps cmark-494.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-494)
 (action (diff cmark-494.html cmark-494.html.out)))

(rule
 (targets cmark-495.html.out)
 (deps cmark-495.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-495)
 (action (diff cmark-495.html cmark-495.html.out)))

(rule
 (targets cmark-496.html.out)
 (deps cmark-496.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-496)
 (action (diff cmark-496.html cmark-496.html.out)))

(rule
 (targets cmark-497.html.out)
 (deps cmark-497.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-497)
 (action (diff cmark-497.html cmark-497.html.out)))

(rule
 (targets cmark-498.html.out)
 (deps cmark-498.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-498)
 (action (diff cmark-498.html cmark-498.html.out)))

(rule
 (targets cmark-499.html.out)
 (deps cmark-499.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-499)
 (action (diff cmark-499.html cmark-499.html.out)))

(rule
 (targets cmark-500.html.out)
 (deps cmark-500.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-500)
 (action (diff cmark-500.html cmark-500.html.out)))

(rule
 (targets cmark-501.html.out)
 (deps cmark-501.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-501)
 (action (diff cmark-501.html cmark-501.html.out)))

(rule
 (targets cmark-502.html.out)
 (deps cmark-502.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-502)
 (action (diff cmark-502.html cmark-502.html.out)))

(rule
 (targets cmark-503.html.out)
 (deps cmark-503.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-503)
 (action (diff cmark-503.html cmark-503.html.out)))

(rule
 (targets cmark-504.html.out)
 (deps cmark-504.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-504)
 (action (diff cmark-504.html cmark-504.html.out)))

(rule
 (targets cmark-505.html.out)
 (deps cmark-505.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-505)
 (action (diff cmark-505.html cmark-505.html.out)))

(rule
 (targets cmark-506.html.out)
 (deps cmark-506.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-506)
 (action (diff cmark-506.html cmark-506.html.out)))

(rule
 (targets cmark-507.html.out)
 (deps cmark-507.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-507)
 (action (diff cmark-507.html cmark-507.html.out)))

(rule
 (targets cmark-508.html.out)
 (deps cmark-508.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-508)
 (action (diff cmark-508.html cmark-508.html.out)))

(rule
 (targets cmark-509.html.out)
 (deps cmark-509.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-509)
 (action (diff cmark-509.html cmark-509.html.out)))

(rule
 (targets cmark-510.html.out)
 (deps cmark-510.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-510)
 (action (diff cmark-510.html cmark-510.html.out)))

(rule
 (targets cmark-511.html.out)
 (deps cmark-511.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-511)
 (action (diff cmark-511.html cmark-511.html.out)))

(rule
 (targets cmark-512.html.out)
 (deps cmark-512.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-512)
 (action (diff cmark-512.html cmark-512.html.out)))

(rule
 (targets cmark-513.html.out)
 (deps cmark-513.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-513)
 (action (diff cmark-513.html cmark-513.html.out)))

(rule
 (targets cmark-514.html.out)
 (deps cmark-514.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-514)
 (action (diff cmark-514.html cmark-514.html.out)))

(rule
 (targets cmark-515.html.out)
 (deps cmark-515.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-515)
 (action (diff cmark-515.html cmark-515.html.out)))

(rule
 (targets cmark-516.html.out)
 (deps cmark-516.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-516)
 (action (diff cmark-516.html cmark-516.html.out)))

(rule
 (targets cmark-517.html.out)
 (deps cmark-517.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-517)
 (action (diff cmark-517.html cmark-517.html.out)))

(rule
 (targets cmark-518.html.out)
 (deps cmark-518.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-518)
 (action (diff cmark-518.html cmark-518.html.out)))

(rule
 (targets cmark-519.html.out)
 (deps cmark-519.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-519)
 (action (diff cmark-519.html cmark-519.html.out)))

(rule
 (targets cmark-520.html.out)
 (deps cmark-520.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-520)
 (action (diff cmark-520.html cmark-520.html.out)))

(rule
 (targets cmark-521.html.out)
 (deps cmark-521.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-521)
 (action (diff cmark-521.html cmark-521.html.out)))

(rule
 (targets cmark-522.html.out)
 (deps cmark-522.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-522)
 (action (diff cmark-522.html cmark-522.html.out)))

(rule
 (targets cmark-523.html.out)
 (deps cmark-523.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-523)
 (action (diff cmark-523.html cmark-523.html.out)))

(rule
 (targets cmark-524.html.out)
 (deps cmark-524.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-524)
 (action (diff cmark-524.html cmark-524.html.out)))

(rule
 (targets cmark-525.html.out)
 (deps cmark-525.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-525)
 (action (diff cmark-525.html cmark-525.html.out)))

(rule
 (targets cmark-526.html.out)
 (deps cmark-526.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-526)
 (action (diff cmark-526.html cmark-526.html.out)))

(rule
 (targets cmark-527.html.out)
 (deps cmark-527.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-527)
 (action (diff cmark-527.html cmark-527.html.out)))

(rule
 (targets cmark-528.html.out)
 (deps cmark-528.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-528)
 (action (diff cmark-528.html cmark-528.html.out)))

(rule
 (targets cmark-529.html.out)
 (deps cmark-529.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-529)
 (action (diff cmark-529.html cmark-529.html.out)))

(rule
 (targets cmark-530.html.out)
 (deps cmark-530.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-530)
 (action (diff cmark-530.html cmark-530.html.out)))

(rule
 (targets cmark-531.html.out)
 (deps cmark-531.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-531)
 (action (diff cmark-531.html cmark-531.html.out)))

(rule
 (targets cmark-532.html.out)
 (deps cmark-532.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-532)
 (action (diff cmark-532.html cmark-532.html.out)))

(rule
 (targets cmark-533.html.out)
 (deps cmark-533.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-533)
 (action (diff cmark-533.html cmark-533.html.out)))

(rule
 (targets cmark-534.html.out)
 (deps cmark-534.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-534)
 (action (diff cmark-534.html cmark-534.html.out)))

(rule
 (targets cmark-535.html.out)
 (deps cmark-535.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-535)
 (action (diff cmark-535.html cmark-535.html.out)))

(rule
 (targets cmark-536.html.out)
 (deps cmark-536.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-536)
 (action (diff cmark-536.html cmark-536.html.out)))

(rule
 (targets cmark-537.html.out)
 (deps cmark-537.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-537)
 (action (diff cmark-537.html cmark-537.html.out)))

(rule
 (targets cmark-538.html.out)
 (deps cmark-538.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-538)
 (action (diff cmark-538.html cmark-538.html.out)))

(rule
 (targets cmark-539.html.out)
 (deps cmark-539.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-539)
 (action (diff cmark-539.html cmark-539.html.out)))

(rule
 (targets cmark-540.html.out)
 (deps cmark-540.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-540)
 (action (diff cmark-540.html cmark-540.html.out)))

(rule
 (targets cmark-541.html.out)
 (deps cmark-541.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-541)
 (action (diff cmark-541.html cmark-541.html.out)))

(rule
 (targets cmark-542.html.out)
 (deps cmark-542.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-542)
 (action (diff cmark-542.html cmark-542.html.out)))

(rule
 (targets cmark-543.html.out)
 (deps cmark-543.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-543)
 (action (diff cmark-543.html cmark-543.html.out)))

(rule
 (targets cmark-544.html.out)
 (deps cmark-544.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-544)
 (action (diff cmark-544.html cmark-544.html.out)))

(rule
 (targets cmark-545.html.out)
 (deps cmark-545.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-545)
 (action (diff cmark-545.html cmark-545.html.out)))

(rule
 (targets cmark-546.html.out)
 (deps cmark-546.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-546)
 (action (diff cmark-546.html cmark-546.html.out)))

(rule
 (targets cmark-547.html.out)
 (deps cmark-547.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-547)
 (action (diff cmark-547.html cmark-547.html.out)))

(rule
 (targets cmark-548.html.out)
 (deps cmark-548.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-548)
 (action (diff cmark-548.html cmark-548.html.out)))

(rule
 (targets cmark-549.html.out)
 (deps cmark-549.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-549)
 (action (diff cmark-549.html cmark-549.html.out)))

(rule
 (targets cmark-550.html.out)
 (deps cmark-550.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-550)
 (action (diff cmark-550.html cmark-550.html.out)))

(rule
 (targets cmark-551.html.out)
 (deps cmark-551.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-551)
 (action (diff cmark-551.html cmark-551.html.out)))

(rule
 (targets cmark-552.html.out)
 (deps cmark-552.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-552)
 (action (diff cmark-552.html cmark-552.html.out)))

(rule
 (targets cmark-553.html.out)
 (deps cmark-553.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-553)
 (action (diff cmark-553.html cmark-553.html.out)))

(rule
 (targets cmark-554.html.out)
 (deps cmark-554.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-554)
 (action (diff cmark-554.html cmark-554.html.out)))

(rule
 (targets cmark-555.html.out)
 (deps cmark-555.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-555)
 (action (diff cmark-555.html cmark-555.html.out)))

(rule
 (targets cmark-556.html.out)
 (deps cmark-556.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-556)
 (action (diff cmark-556.html cmark-556.html.out)))

(rule
 (targets cmark-557.html.out)
 (deps cmark-557.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-557)
 (action (diff cmark-557.html cmark-557.html.out)))

(rule
 (targets cmark-558.html.out)
 (deps cmark-558.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-558)
 (action (diff cmark-558.html cmark-558.html.out)))

(rule
 (targets cmark-559.html.out)
 (deps cmark-559.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-559)
 (action (diff cmark-559.html cmark-559.html.out)))

(rule
 (targets cmark-560.html.out)
 (deps cmark-560.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-560)
 (action (diff cmark-560.html cmark-560.html.out)))

(rule
 (targets cmark-561.html.out)
 (deps cmark-561.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-561)
 (action (diff cmark-561.html cmark-561.html.out)))

(rule
 (targets cmark-562.html.out)
 (deps cmark-562.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-562)
 (action (diff cmark-562.html cmark-562.html.out)))

(rule
 (targets cmark-563.html.out)
 (deps cmark-563.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-563)
 (action (diff cmark-563.html cmark-563.html.out)))

(rule
 (targets cmark-564.html.out)
 (deps cmark-564.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-564)
 (action (diff cmark-564.html cmark-564.html.out)))

(rule
 (targets cmark-565.html.out)
 (deps cmark-565.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-565)
 (action (diff cmark-565.html cmark-565.html.out)))

(rule
 (targets cmark-566.html.out)
 (deps cmark-566.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-566)
 (action (diff cmark-566.html cmark-566.html.out)))

(rule
 (targets cmark-567.html.out)
 (deps cmark-567.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-567)
 (action (diff cmark-567.html cmark-567.html.out)))

(rule
 (targets cmark-568.html.out)
 (deps cmark-568.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-568)
 (action (diff cmark-568.html cmark-568.html.out)))

(rule
 (targets cmark-569.html.out)
 (deps cmark-569.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-569)
 (action (diff cmark-569.html cmark-569.html.out)))

(rule
 (targets cmark-570.html.out)
 (deps cmark-570.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-570)
 (action (diff cmark-570.html cmark-570.html.out)))

(rule
 (targets cmark-571.html.out)
 (deps cmark-571.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-571)
 (action (diff cmark-571.html cmark-571.html.out)))

(rule
 (targets cmark-572.html.out)
 (deps cmark-572.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-572)
 (action (diff cmark-572.html cmark-572.html.out)))

(rule
 (targets cmark-573.html.out)
 (deps cmark-573.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-573)
 (action (diff cmark-573.html cmark-573.html.out)))

(rule
 (targets cmark-574.html.out)
 (deps cmark-574.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-574)
 (action (diff cmark-574.html cmark-574.html.out)))

(rule
 (targets cmark-575.html.out)
 (deps cmark-575.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-575)
 (action (diff cmark-575.html cmark-575.html.out)))

(rule
 (targets cmark-576.html.out)
 (deps cmark-576.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-576)
 (action (diff cmark-576.html cmark-576.html.out)))

(rule
 (targets cmark-577.html.out)
 (deps cmark-577.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-577)
 (action (diff cmark-577.html cmark-577.html.out)))

(rule
 (targets cmark-578.html.out)
 (deps cmark-578.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-578)
 (action (diff cmark-578.html cmark-578.html.out)))

(rule
 (targets cmark-579.html.out)
 (deps cmark-579.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-579)
 (action (diff cmark-579.html cmark-579.html.out)))

(rule
 (targets cmark-580.html.out)
 (deps cmark-580.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-580)
 (action (diff cmark-580.html cmark-580.html.out)))

(rule
 (targets cmark-581.html.out)
 (deps cmark-581.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-581)
 (action (diff cmark-581.html cmark-581.html.out)))

(rule
 (targets cmark-582.html.out)
 (deps cmark-582.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-582)
 (action (diff cmark-582.html cmark-582.html.out)))

(rule
 (targets cmark-583.html.out)
 (deps cmark-583.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-583)
 (action (diff cmark-583.html cmark-583.html.out)))

(rule
 (targets cmark-584.html.out)
 (deps cmark-584.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-584)
 (action (diff cmark-584.html cmark-584.html.out)))

(rule
 (targets cmark-585.html.out)
 (deps cmark-585.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-585)
 (action (diff cmark-585.html cmark-585.html.out)))

(rule
 (targets cmark-586.html.out)
 (deps cmark-586.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-586)
 (action (diff cmark-586.html cmark-586.html.out)))

(rule
 (targets cmark-587.html.out)
 (deps cmark-587.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-587)
 (action (diff cmark-587.html cmark-587.html.out)))

(rule
 (targets cmark-588.html.out)
 (deps cmark-588.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-588)
 (action (diff cmark-588.html cmark-588.html.out)))

(rule
 (targets cmark-589.html.out)
 (deps cmark-589.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-589)
 (action (diff cmark-589.html cmark-589.html.out)))

(rule
 (targets cmark-590.html.out)
 (deps cmark-590.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-590)
 (action (diff cmark-590.html cmark-590.html.out)))

(rule
 (targets cmark-591.html.out)
 (deps cmark-591.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-591)
 (action (diff cmark-591.html cmark-591.html.out)))

(rule
 (targets cmark-592.html.out)
 (deps cmark-592.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-592)
 (action (diff cmark-592.html cmark-592.html.out)))

(rule
 (targets cmark-593.html.out)
 (deps cmark-593.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-593)
 (action (diff cmark-593.html cmark-593.html.out)))

(rule
 (targets cmark-594.html.out)
 (deps cmark-594.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-594)
 (action (diff cmark-594.html cmark-594.html.out)))

(rule
 (targets cmark-595.html.out)
 (deps cmark-595.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-595)
 (action (diff cmark-595.html cmark-595.html.out)))

(rule
 (targets cmark-596.html.out)
 (deps cmark-596.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-596)
 (action (diff cmark-596.html cmark-596.html.out)))

(rule
 (targets cmark-597.html.out)
 (deps cmark-597.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-597)
 (action (diff cmark-597.html cmark-597.html.out)))

(rule
 (targets cmark-598.html.out)
 (deps cmark-598.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-598)
 (action (diff cmark-598.html cmark-598.html.out)))

(rule
 (targets cmark-599.html.out)
 (deps cmark-599.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-599)
 (action (diff cmark-599.html cmark-599.html.out)))

(rule
 (targets cmark-600.html.out)
 (deps cmark-600.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-600)
 (action (diff cmark-600.html cmark-600.html.out)))

(rule
 (targets cmark-601.html.out)
 (deps cmark-601.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-601)
 (action (diff cmark-601.html cmark-601.html.out)))

(rule
 (targets cmark-602.html.out)
 (deps cmark-602.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-602)
 (action (diff cmark-602.html cmark-602.html.out)))

(rule
 (targets cmark-603.html.out)
 (deps cmark-603.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-603)
 (action (diff cmark-603.html cmark-603.html.out)))

(rule
 (targets cmark-604.html.out)
 (deps cmark-604.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-604)
 (action (diff cmark-604.html cmark-604.html.out)))

(rule
 (targets cmark-605.html.out)
 (deps cmark-605.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-605)
 (action (diff cmark-605.html cmark-605.html.out)))

(rule
 (targets cmark-606.html.out)
 (deps cmark-606.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-606)
 (action (diff cmark-606.html cmark-606.html.out)))

(rule
 (targets cmark-607.html.out)
 (deps cmark-607.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-607)
 (action (diff cmark-607.html cmark-607.html.out)))

(rule
 (targets cmark-608.html.out)
 (deps cmark-608.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-608)
 (action (diff cmark-608.html cmark-608.html.out)))

(rule
 (targets cmark-609.html.out)
 (deps cmark-609.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-609)
 (action (diff cmark-609.html cmark-609.html.out)))

(rule
 (targets cmark-610.html.out)
 (deps cmark-610.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-610)
 (action (diff cmark-610.html cmark-610.html.out)))

(rule
 (targets cmark-611.html.out)
 (deps cmark-611.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-611)
 (action (diff cmark-611.html cmark-611.html.out)))

(rule
 (targets cmark-612.html.out)
 (deps cmark-612.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-612)
 (action (diff cmark-612.html cmark-612.html.out)))

(rule
 (targets cmark-613.html.out)
 (deps cmark-613.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-613)
 (action (diff cmark-613.html cmark-613.html.out)))

(rule
 (targets cmark-614.html.out)
 (deps cmark-614.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-614)
 (action (diff cmark-614.html cmark-614.html.out)))

(rule
 (targets cmark-615.html.out)
 (deps cmark-615.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-615)
 (action (diff cmark-615.html cmark-615.html.out)))

(rule
 (targets cmark-616.html.out)
 (deps cmark-616.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-616)
 (action (diff cmark-616.html cmark-616.html.out)))

(rule
 (targets cmark-617.html.out)
 (deps cmark-617.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-617)
 (action (diff cmark-617.html cmark-617.html.out)))

(rule
 (targets cmark-618.html.out)
 (deps cmark-618.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-618)
 (action (diff cmark-618.html cmark-618.html.out)))

(rule
 (targets cmark-619.html.out)
 (deps cmark-619.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-619)
 (action (diff cmark-619.html cmark-619.html.out)))

(rule
 (targets cmark-620.html.out)
 (deps cmark-620.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-620)
 (action (diff cmark-620.html cmark-620.html.out)))

(rule
 (targets cmark-621.html.out)
 (deps cmark-621.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-621)
 (action (diff cmark-621.html cmark-621.html.out)))

(rule
 (targets cmark-622.html.out)
 (deps cmark-622.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-622)
 (action (diff cmark-622.html cmark-622.html.out)))

(rule
 (targets cmark-623.html.out)
 (deps cmark-623.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-623)
 (action (diff cmark-623.html cmark-623.html.out)))

(rule
 (targets cmark-624.html.out)
 (deps cmark-624.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-624)
 (action (diff cmark-624.html cmark-624.html.out)))

(rule
 (targets cmark-625.html.out)
 (deps cmark-625.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-625)
 (action (diff cmark-625.html cmark-625.html.out)))

(rule
 (targets cmark-626.html.out)
 (deps cmark-626.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-626)
 (action (diff cmark-626.html cmark-626.html.out)))

(rule
 (targets cmark-627.html.out)
 (deps cmark-627.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-627)
 (action (diff cmark-627.html cmark-627.html.out)))

(rule
 (targets cmark-628.html.out)
 (deps cmark-628.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-628)
 (action (diff cmark-628.html cmark-628.html.out)))

(rule
 (targets cmark-629.html.out)
 (deps cmark-629.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-629)
 (action (diff cmark-629.html cmark-629.html.out)))

(rule
 (targets cmark-630.html.out)
 (deps cmark-630.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-630)
 (action (diff cmark-630.html cmark-630.html.out)))

(rule
 (targets cmark-631.html.out)
 (deps cmark-631.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-631)
 (action (diff cmark-631.html cmark-631.html.out)))

(rule
 (targets cmark-632.html.out)
 (deps cmark-632.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-632)
 (action (diff cmark-632.html cmark-632.html.out)))

(rule
 (targets cmark-633.html.out)
 (deps cmark-633.md)
 (action (with-stdout-to %{targets} (run omd %{deps}))))

(alias
 (name cmark-633)
 (action (diff cmark-633.html cmark-633.html.out)))

(alias
 (name runtest)
 (deps (alias cmark-001)
       (alias cmark-002)
       (alias cmark-003)
       (alias cmark-004)
       (alias cmark-005)
       (alias cmark-006)
       (alias cmark-007)
       (alias cmark-008)
       (alias cmark-009)
       (alias cmark-010)
       (alias cmark-011)
       (alias cmark-012)
       (alias cmark-013)
       (alias cmark-014)
       (alias cmark-015)
       (alias cmark-016)
       (alias cmark-017)
       (alias cmark-018)
       (alias cmark-019)
       (alias cmark-020)
       (alias cmark-021)
       (alias cmark-022)
       (alias cmark-023)
       (alias cmark-024)
       (alias cmark-025)
       (alias cmark-026)
       (alias cmark-027)
       (alias cmark-028)
       (alias cmark-029)
       (alias cmark-030)
       (alias cmark-031)
       (alias cmark-032)
       (alias cmark-033)
       (alias cmark-034)
       (alias cmark-035)
       (alias cmark-036)
       (alias cmark-037)
       (alias cmark-038)
       (alias cmark-039)
       (alias cmark-040)
       (alias cmark-041)
       (alias cmark-042)
       (alias cmark-043)
       (alias cmark-044)
       (alias cmark-045)
       (alias cmark-046)
       (alias cmark-047)
       (alias cmark-048)
       (alias cmark-049)
       (alias cmark-050)
       (alias cmark-051)
       (alias cmark-052)
       (alias cmark-053)
       (alias cmark-054)
       (alias cmark-055)
       (alias cmark-056)
       (alias cmark-057)
       (alias cmark-058)
       (alias cmark-059)
       (alias cmark-060)
       (alias cmark-061)
       (alias cmark-062)
       (alias cmark-063)
       (alias cmark-064)
       (alias cmark-065)
       (alias cmark-066)
       (alias cmark-067)
       (alias cmark-068)
       (alias cmark-069)
       (alias cmark-070)
       (alias cmark-071)
       (alias cmark-072)
       (alias cmark-073)
       (alias cmark-074)
       (alias cmark-075)
       (alias cmark-076)
       (alias cmark-077)
       (alias cmark-078)
       (alias cmark-079)
       (alias cmark-080)
       (alias cmark-081)
       (alias cmark-082)
       (alias cmark-083)
       (alias cmark-084)
       (alias cmark-085)
       (alias cmark-086)
       (alias cmark-087)
       (alias cmark-088)
       (alias cmark-089)
       (alias cmark-090)
       (alias cmark-091)
       (alias cmark-092)
       (alias cmark-093)
       (alias cmark-094)
       (alias cmark-095)
       (alias cmark-096)
       (alias cmark-097)
       (alias cmark-098)
       (alias cmark-099)
       (alias cmark-100)
       (alias cmark-101)
       (alias cmark-102)
       (alias cmark-103)
       (alias cmark-104)
       (alias cmark-105)
       (alias cmark-106)
       (alias cmark-107)
       (alias cmark-108)
       (alias cmark-109)
       (alias cmark-110)
       (alias cmark-111)
       (alias cmark-112)
       (alias cmark-113)
       (alias cmark-114)
       (alias cmark-115)
       (alias cmark-116)
       (alias cmark-117)
       (alias cmark-118)
       (alias cmark-119)
       (alias cmark-120)
       (alias cmark-121)
       (alias cmark-122)
       (alias cmark-123)
       (alias cmark-124)
       (alias cmark-125)
       (alias cmark-126)
       (alias cmark-127)
       (alias cmark-128)
       (alias cmark-129)
       (alias cmark-130)
       (alias cmark-131)
       (alias cmark-132)
       (alias cmark-133)
       (alias cmark-134)
       (alias cmark-135)
       (alias cmark-136)
       (alias cmark-137)
       (alias cmark-138)
       (alias cmark-139)
       (alias cmark-140)
       (alias cmark-141)
       (alias cmark-142)
       (alias cmark-143)
       (alias cmark-144)
       (alias cmark-145)
       (alias cmark-146)
       (alias cmark-147)
       (alias cmark-148)
       (alias cmark-149)
       (alias cmark-150)
       (alias cmark-151)
       (alias cmark-152)
       (alias cmark-153)
       (alias cmark-154)
       (alias cmark-155)
       (alias cmark-156)
       (alias cmark-157)
       (alias cmark-158)
       (alias cmark-159)
       (alias cmark-160)
       (alias cmark-161)
       (alias cmark-162)
       (alias cmark-163)
       (alias cmark-164)
       (alias cmark-165)
       (alias cmark-166)
       (alias cmark-167)
       (alias cmark-168)
       (alias cmark-169)
       (alias cmark-170)
       ;; (alias cmark-171)
       (alias cmark-172)
       (alias cmark-173)
       (alias cmark-174)
       (alias cmark-175)
       (alias cmark-176)
       (alias cmark-177)
       (alias cmark-178)
       (alias cmark-179)
       (alias cmark-180)
       (alias cmark-181)
       (alias cmark-182)
       (alias cmark-183)
       (alias cmark-184)
       (alias cmark-185)
       (alias cmark-186)
       (alias cmark-187)
       (alias cmark-188)
       (alias cmark-189)
       (alias cmark-190)
       (alias cmark-191)
       (alias cmark-192)
       (alias cmark-193)
       (alias cmark-194)
       (alias cmark-195)
       (alias cmark-196)
       (alias cmark-197)
       (alias cmark-198)
       (alias cmark-199)
       (alias cmark-200)
       (alias cmark-201)
       (alias cmark-202)
       (alias cmark-203)
       (alias cmark-204)
       (alias cmark-205)
       (alias cmark-206)
       (alias cmark-207)
       (alias cmark-208)
       (alias cmark-209)
       (alias cmark-210)
       (alias cmark-211)
       (alias cmark-212)
       (alias cmark-213)
       (alias cmark-214)
       (alias cmark-215)
       (alias cmark-216)
       (alias cmark-217)
       (alias cmark-218)
       (alias cmark-219)
       (alias cmark-220)
       (alias cmark-221)
       (alias cmark-222)
       (alias cmark-223)
       (alias cmark-224)
       (alias cmark-225)
       (alias cmark-226)
       (alias cmark-227)
       (alias cmark-228)
       (alias cmark-229)
       (alias cmark-230)
       (alias cmark-231)
       (alias cmark-232)
       (alias cmark-233)
       (alias cmark-234)
       (alias cmark-235)
       (alias cmark-236)
       (alias cmark-237)
       (alias cmark-238)
       (alias cmark-239)
       (alias cmark-240)
       (alias cmark-241)
       (alias cmark-242)
       (alias cmark-243)
       (alias cmark-244)
       (alias cmark-245)
       (alias cmark-246)
       (alias cmark-247)
       (alias cmark-248)
       (alias cmark-249)
       (alias cmark-250)
       (alias cmark-251)
       (alias cmark-252)
       (alias cmark-253)
       (alias cmark-254)
       (alias cmark-255)
       (alias cmark-256)
       (alias cmark-257)
       (alias cmark-258)
       (alias cmark-259)
       (alias cmark-260)
       (alias cmark-261)
       (alias cmark-262)
       (alias cmark-263)
       (alias cmark-264)
       (alias cmark-265)
       (alias cmark-266)
       (alias cmark-267)
       (alias cmark-268)
       (alias cmark-269)
       (alias cmark-270)
       (alias cmark-271)
       (alias cmark-272)
       ;; (alias cmark-273)
       ;; (alias cmark-274)
       (alias cmark-275)
       (alias cmark-276)
       (alias cmark-277)
       (alias cmark-278)
       (alias cmark-279)
       (alias cmark-280)
       (alias cmark-281)
       (alias cmark-282)
       (alias cmark-283)
       (alias cmark-284)
       (alias cmark-285)
       (alias cmark-286)
       (alias cmark-287)
       (alias cmark-288)
       (alias cmark-289)
       (alias cmark-290)
       (alias cmark-291)
       (alias cmark-292)
       (alias cmark-293)
       (alias cmark-294)
       (alias cmark-295)
       (alias cmark-296)
       (alias cmark-297)
       (alias cmark-298)
       (alias cmark-299)
       (alias cmark-300)
       (alias cmark-301)
       (alias cmark-302)
       (alias cmark-303)
       (alias cmark-304)
       (alias cmark-305)
       (alias cmark-306)
       (alias cmark-307)
       (alias cmark-308)
       (alias cmark-309)
       (alias cmark-310)
       (alias cmark-311)
       (alias cmark-312)
       (alias cmark-313)
       (alias cmark-314)
       (alias cmark-315)
       (alias cmark-316)
       (alias cmark-317)
       (alias cmark-318)
       (alias cmark-319)
       (alias cmark-320)
       (alias cmark-321)
       (alias cmark-322)
       (alias cmark-323)
       (alias cmark-324)
       (alias cmark-325)
       (alias cmark-326)
       (alias cmark-327)
       (alias cmark-328)
       (alias cmark-329)
       (alias cmark-330)
       (alias cmark-331)
       (alias cmark-332)
       (alias cmark-333)
       ;; (alias cmark-334)
       (alias cmark-335)
       (alias cmark-336)
       (alias cmark-337)
       (alias cmark-338)
       (alias cmark-339)
       (alias cmark-340)
       (alias cmark-341)
       (alias cmark-342)
       (alias cmark-343)
       (alias cmark-344)
       (alias cmark-345)
       (alias cmark-346)
       (alias cmark-347)
       (alias cmark-348)
       (alias cmark-349)
       (alias cmark-350)
       (alias cmark-351)
       (alias cmark-352)
       (alias cmark-353)
       (alias cmark-354)
       (alias cmark-355)
       (alias cmark-356)
       (alias cmark-357)
       (alias cmark-358)
       (alias cmark-359)
       (alias cmark-360)
       (alias cmark-361)
       (alias cmark-362)
       (alias cmark-363)
       (alias cmark-364)
       (alias cmark-365)
       (alias cmark-366)
       (alias cmark-367)
       (alias cmark-368)
       (alias cmark-369)
       (alias cmark-370)
       (alias cmark-371)
       (alias cmark-372)
       (alias cmark-373)
       (alias cmark-374)
       (alias cmark-375)
       (alias cmark-376)
       (alias cmark-377)
       (alias cmark-378)
       (alias cmark-379)
       (alias cmark-380)
       (alias cmark-381)
       (alias cmark-382)
       (alias cmark-383)
       (alias cmark-384)
       (alias cmark-385)
       (alias cmark-386)
       (alias cmark-387)
       (alias cmark-388)
       (alias cmark-389)
       (alias cmark-390)
       ;; (alias cmark-391)
       (alias cmark-392)
       (alias cmark-393)
       ;; (alias cmark-394)
       (alias cmark-395)
       (alias cmark-396)
       (alias cmark-397)
       (alias cmark-398)
       (alias cmark-399)
       (alias cmark-400)
       (alias cmark-401)
       (alias cmark-402)
       (alias cmark-403)
       (alias cmark-404)
       (alias cmark-405)
       ;; (alias cmark-406)
       (alias cmark-407)
       (alias cmark-408)
       (alias cmark-409)
       (alias cmark-410)
       (alias cmark-411)
       (alias cmark-412)
       (alias cmark-413)
       (alias cmark-414)
       (alias cmark-415)
       (alias cmark-416)
       (alias cmark-417)
       (alias cmark-418)
       (alias cmark-419)
       (alias cmark-420)
       (alias cmark-421)
       (alias cmark-422)
       (alias cmark-423)
       (alias cmark-424)
       (alias cmark-425)
       (alias cmark-426)
       (alias cmark-427)
       (alias cmark-428)
       (alias cmark-429)
       (alias cmark-430)
       (alias cmark-431)
       (alias cmark-432)
       (alias cmark-433)
       (alias cmark-434)
       (alias cmark-435)
       (alias cmark-436)
       (alias cmark-437)
       (alias cmark-438)
       (alias cmark-439)
       (alias cmark-440)
       (alias cmark-441)
       (alias cmark-442)
       (alias cmark-443)
       (alias cmark-444)
       (alias cmark-445)
       ;; (alias cmark-446)
       ;; (alias cmark-447)
       (alias cmark-448)
       (alias cmark-449)
       (alias cmark-450)
       (alias cmark-451)
       (alias cmark-452)
       (alias cmark-453)
       (alias cmark-454)
       (alias cmark-455)
       (alias cmark-456)
       (alias cmark-457)
       (alias cmark-458)
       (alias cmark-459)
       (alias cmark-460)
       (alias cmark-461)
       (alias cmark-462)
       (alias cmark-463)
       (alias cmark-464)
       (alias cmark-465)
       (alias cmark-466)
       (alias cmark-467)
       (alias cmark-468)
       (alias cmark-469)
       (alias cmark-470)
       (alias cmark-471)
       (alias cmark-472)
       (alias cmark-473)
       (alias cmark-474)
       (alias cmark-475)
       (alias cmark-476)
       (alias cmark-477)
       (alias cmark-478)
       (alias cmark-479)
       (alias cmark-480)
       (alias cmark-481)
       (alias cmark-482)
       (alias cmark-483)
       (alias cmark-484)
       (alias cmark-485)
       (alias cmark-486)
       (alias cmark-487)
       (alias cmark-488)
       (alias cmark-489)
       (alias cmark-490)
       ;; (alias cmark-491)
       (alias cmark-492)
       (alias cmark-493)
       ;; (alias cmark-494)
       (alias cmark-495)
       (alias cmark-496)
       (alias cmark-497)
       (alias cmark-498)
       (alias cmark-499)
       (alias cmark-500)
       (alias cmark-501)
       (alias cmark-502)
       (alias cmark-503)
       (alias cmark-504)
       (alias cmark-505)
       (alias cmark-506)
       (alias cmark-507)
       (alias cmark-508)
       (alias cmark-509)
       (alias cmark-510)
       ;; (alias cmark-511)
       (alias cmark-512)
       (alias cmark-513)
       (alias cmark-514)
       (alias cmark-515)
       (alias cmark-516)
       (alias cmark-517)
       (alias cmark-518)
       (alias cmark-519)
       (alias cmark-520)
       (alias cmark-521)
       (alias cmark-522)
       (alias cmark-523)
       (alias cmark-524)
       (alias cmark-525)
       (alias cmark-526)
       (alias cmark-527)
       (alias cmark-528)
       (alias cmark-529)
       (alias cmark-530)
       (alias cmark-531)
       (alias cmark-532)
       (alias cmark-533)
       (alias cmark-534)
       (alias cmark-535)
       (alias cmark-536)
       (alias cmark-537)
       (alias cmark-538)
       (alias cmark-539)
       (alias cmark-540)
       (alias cmark-541)
       (alias cmark-542)
       (alias cmark-543)
       (alias cmark-544)
       (alias cmark-545)
       (alias cmark-546)
       (alias cmark-547)
       (alias cmark-548)
       (alias cmark-549)
       (alias cmark-550)
       (alias cmark-551)
       (alias cmark-552)
       (alias cmark-553)
       (alias cmark-554)
       (alias cmark-555)
       (alias cmark-556)
       (alias cmark-557)
       (alias cmark-558)
       (alias cmark-559)
       (alias cmark-560)
       (alias cmark-561)
       (alias cmark-562)
       (alias cmark-563)
       (alias cmark-564)
       (alias cmark-565)
       (alias cmark-566)
       (alias cmark-567)
       (alias cmark-568)
       (alias cmark-569)
       (alias cmark-570)
       (alias cmark-571)
       (alias cmark-572)
       (alias cmark-573)
       (alias cmark-574)
       (alias cmark-575)
       (alias cmark-576)
       (alias cmark-577)
       (alias cmark-578)
       (alias cmark-579)
       (alias cmark-580)
       (alias cmark-581)
       (alias cmark-582)
       (alias cmark-583)
       (alias cmark-584)
       (alias cmark-585)
       (alias cmark-586)
       (alias cmark-587)
       (alias cmark-588)
       (alias cmark-589)
       (alias cmark-590)
       (alias cmark-591)
       (alias cmark-592)
       (alias cmark-593)
       (alias cmark-594)
       (alias cmark-595)
       (alias cmark-596)
       (alias cmark-597)
       (alias cmark-598)
       (alias cmark-599)
       (alias cmark-600)
       (alias cmark-601)
       (alias cmark-602)
       (alias cmark-603)
       (alias cmark-604)
       (alias cmark-605)
       (alias cmark-606)
       (alias cmark-607)
       (alias cmark-608)
       (alias cmark-609)
       (alias cmark-610)
       (alias cmark-611)
       (alias cmark-612)
       (alias cmark-613)
       (alias cmark-614)
       (alias cmark-615)
       (alias cmark-616)
       (alias cmark-617)
       (alias cmark-618)
       (alias cmark-619)
       (alias cmark-620)
       (alias cmark-621)
       (alias cmark-622)
       (alias cmark-623)
       (alias cmark-624)))

(alias
 (name runtest_all)
 (deps (alias runtest)
       (alias cmark-171)
       (alias cmark-273)
       (alias cmark-274)
       (alias cmark-334)
       (alias cmark-391)
       (alias cmark-394)
       (alias cmark-406)
       (alias cmark-446)
       (alias cmark-447)
       (alias cmark-491)
       (alias cmark-494)
       (alias cmark-511)))
